### ISSUE TITLE
Adding Bump and Specular maps to texture changer

### ISSUE THREAD

**Issue by Catspawgat** [OpenCollarTeam/OpenCollar#100]
What version of OpenCollar are you using?
NA
What behavior did you expect?
NA
What behavior did you see instead?
NA
What steps does someone need to take to reproduce the problem?
NA
As a creator, I'd like to add several different textures to each my collars rather than the default stuff
However a good mesh texture requires the Texture, Bump and Specular maps
Currently this is not an option in OC and if I add several textures, the only way it could work is if the wearer is constantly updating the maps
This is both difficult for some, annoying to others and infuriating to creators (winks)

I think this feature is beneficial to all creators and especially good for end users. One collar can be made to fit all outfits rather than have to change collars or forced to wear a color of color that totally does not match an outfit

Personally, I hope this gets bumped to the top of the features list (hint hint)

**Comment by nirea** [comment]
This would be fairly easy to add to the oc_meshthemes script.  Are your creations just one mesh with a bunch of faces, or is it a bunch of meshes linked together?  (oc_meshthemes only works with the former.)

**Comment by nirea** [comment]
The .meshthemes notecard for configuring the oc_meshthemes script looks like this:

    Modern
    -1|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<1,1,1>|1|2|0  
    1|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<1,1,1>|1|1|0                 
    2|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<0.1,0.1,0.1>|1|2|0
    5|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<0.8,0.8,0.8>|1|2|0
    4|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<0.2,0.2,0.2>|1|2|0
    7|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<0.3,0.3,0.3>|1|3|0
    0|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<1,1,1>|1|3|0
    Ancient
    -1|fe5e04a3-3fc0-86e6-1db1-0f32ae925176|<1,1,1>|1|1|2
    7|fe5e04a3-3fc0-86e6-1db1-0f32ae925176|<.5,.5,.5>|1|1|2
    0|fe5e04a3-3fc0-86e6-1db1-0f32ae925176|<.5,.5,.5>|1|1|2
    2|fe5e04a3-3fc0-86e6-1db1-0f32ae925176|<.5,.5,.5>|1|1|2
    1|fe5e04a3-3fc0-86e6-1db1-0f32ae925176|<.82,.69,.51>|1|0|2
    4|fe5e04a3-3fc0-86e6-1db1-0f32ae925176|<.3,.3,.3>|1|1|2
    Tron
    -1|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<.44,.27,.7>|0.7|2|0|.15
    7|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<1,1,1>|1|3|0|.1
    0|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<1,1,1>|1|3|0|.1
    1|3cb9b0d6-febc-2c6f-94f0-fb2ad88ec973|<1,1,1>|.8|1|0|.1

Each line sets parameters on a different face.  On a given line, the parameters are:

- face
- texture
- color
- alpha
- shine
- bump mode
- glow

It would be very easy to tack additional bump map and specular map parameters at the end of each line.  Maybe you want to try tweaking the script?  It's at https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/collar/oc_meshthemes.lsl.  You'd be adding a few lines after line 45 to pull out the bump and specular map parameters, and then feed them into the llSetLinkPrimitiveParamsFast call.  We might need an if/then in there in case the values are omitted, or some default values (NULL_KEY) that get ignored by SL.  Would take some testing.

**Comment by RestlessSwords** [comment]
It would also be trivial to add into the current oc_themes to read from .themes notecard
see pull-request #135  where I added optional support for "face=n" in .themes
example:
```
[ White+Red ]
Band~TextureWhite~<0.99, 0.99, 0.99>
Band~face=3~TextureRed~<0.99, 0.99, 0.99>
```
The above is mostly the OLD format.  The NEW format allows "texture"=TextureName etc
So similar to my OPTIONAL "face=n" enhancement, could certainly add OPTIONAL "bump=Texture" and or "secular=Texture".

I will wait and see if my "face=n" oc_themes pull-request is accepted.  if it is, I can also add bump & secular enhancements.

**Comment by DoggyCore** [comment]
I'd very much like (or beg for) PRIM_NORMAL and PRIM_SPECULAR to be usable in themes. the level of detail/"realism" can be increased massively by using normal and specular maps, often the exact same texture as the Diffuse (if designed with this in mind) so no extra textures to download or display.

**Comment by RestlessSwords** [comment]
hmmm, I know and have created and used bump-maps but they are blue-purplish (not the same texture as the Diffuse) ??  and I thought secular-maps were also unique textures.

In any case, the syntax would require *ANY* texture-name or UUID (whether it/they happens to be the same as the Diffuse texture or different) for both "bump=xxxxx" and "secular=yyyyy" new optional parameters

I am assuming that you are referring to "Normal" maps as just being another name for "Bump" maps

**Comment by zontreck** [comment]
It would appear that a pull request has implemented this functionality into the master branch. Closing this issue.
