### ISSUE TITLE
oc_bookmarks issue

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#1026]
Sims with a space in the name cause problems, llEscapeURL required! Spotted by Nyxen Starlight, reported in world

**Comment by Omnia2021** [comment]
I tested this using normal language such as Home Sweet Home and it worked fine, I think the answer is to change the URL with spaces into plain language inputs to avoid the conflict. Just a thought.

**Comment by Medea-Destiny** [comment]
fix in #1068
