### ISSUE TITLE
Owner should not be able to unset OwnSelf

### ISSUE THREAD

**Issue by ExecuterMagic** [OpenCollarTeam/OpenCollar#103]
What version of OpenCollar are you using?
7.0 to 7.0 dev 4

What behavior did you expect?  
OwnSelf not override able by Owner

What behavior did you see instead?
Owner can uncheck it , wearer is unable to recheck it then

What steps does someone need to take to reproduce the problem? 
Set OwnSelf , add owner , and let owner uncheck OwnSelf

Found out that an owner is able to uncheck the OwnSelf setting again , and the collar wearer is unable to recheck . 

I think that is a huge flaw personally , since " OwnSelf " kinda represents a " hard limit " for many collar wearers , so don't think that anyone should be able to undo that ,also blacklisting/blocking of the wearer and such should be not possible when OwnSelf is checked . 

Specially for new users that is a huge flaw IMHO , since they " trust " when setting it that they always have the " final control " , what they like this don't have unless they " runaway " , and like that also remove possible other owners all along . 
 
On that thought , i think it would be good if when OwnSelf is checked , only the wearer can remove other owners , but not an Owner being able to remove other set owners of the collar them self .

**Comment by hmaw** [comment]
What was the previous release version 7.0 actions when you attempted to duplicate this?  Is it different   (   Is this is different than the previous release version was handled?  Then yes, this is a giant bug as it was not discussed or was part of the way things were being done and I will not change something like that as it would cause major issues with the customer base to change our known behavior without any reason given.     If it is, then this may be a bug in the code that prevented the last I knew code where only ownself was able to remove ownself?  Was this left out in the name change issue previously?   )

**Comment by nirea** [comment]
Looks like this is intended behavior.
