### ISSUE TITLE
oc_dialog stack heap on sit command.

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#1033]
What version of OpenCollar are you using?
8.2.3

What behavior did you expect?
tmsit or *sit to present my owner with a list of objects

What behavior did you see instead?
stack heap collision every time and likely no or incomplete menu of items

What steps does someone need to take to reproduce the problem?
use sit command or menu in a location with more than 16 items.

**Comment by Medea-Destiny** [comment]
LL just upped the response from llSensor from 16 to 32 items, thus potentially doubling the size of the list we're trying to create.
