### ISSUE TITLE
Feature Request - Force TP with leash

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#1035]
Sorry if I missed this one being discussed. I swear it has been, but I'm looking right over it if it's there.

I know what you're thinking; "isn't this already the case?" Well, yes and no.

True, you can set owners and trusted to be able to force TP you. What I'm looking for is adding in the functionality (option set by owner?) where the current leash holder can force TP you, but if they're not holding your leash, then it's not a force TP. This would also be removed if the leash is anchored to something.

"Why would you want that?" So that people on your trusted list (and maybe even owners, though that would be VERY rare) can send TP's just in a friendly way (I.E. "hey, come to this club") without it being a force, but when they grab your leash, then it's a force. Alternately, could allow for public leashers to have this ability if desired. The coding for the option itself is easy enough, though I know the implementation of it may not be. Especially since you don't want to wipe away the other exceptions set when you remove ones set by the leash. It CAN be done, but it would take some coding to do it.

Even so, just tossing the idea out there. Take it or leave it.

**Comment by cilledyr** [comment]
Actually to add to this; it would be pretty awesome, if you could make a leash handle for the owner, which, will AUTO-TP the sub to the owner, if the submissive is leashed and the leash holder teleports. ((since i realize some teleporters don't actually teleport you, it could also work if the owner is suddenly (far) out of range.. ))
