### ISSUE TITLE
Feature Request : WEARER HUD

### ISSUE THREAD

**Issue by Ai-Dunno** [OpenCollarTeam/OpenCollar#104]
The very simple concept of ease and simplicity
Ideally the wearer can use a non obtrusive HUD to 
1) access OC Main Menu/specific panels
2) easily access some feature (list owners/list grabbing objects/Collar version number /etc
3) keep a status display of the relay (something simple visible on the compact form of the HUD like no light for Off/green for auto/red/orange/etc (I would like to see it clearly visible if it's group only and so on.
4) an emergency zone with a) yellow button "clear RLV restrictions". b) Red button: "Run away" that zone should not be too easy access and be obviously marked to avoid misunderstandings.
5) ability to toggle a verbose option on the collar at the touch of a button to understand a weird behavior (that option could need to be checked before displaying)

the settings of the HUD could be done either by the HUD or by a panel inside the collar itself. so any new HUD could take its settings from the collar of his own wearer and no one else.

Details of the exact features should be ironed out with a clear idea of  the possibilities and the opportunity to implement them. 
Too it could be conjoined with the simple idea that even though a wearer could be taken off his/her collar by an owner... some functions should be still available to them and the corresponding buttons appear on the HUD. Like styling (colors to match a different outfit), stealth to avoid seeking complicated outfits to hide your collar when you are expected to show up in a place where it would be rude to sport one. List owners/trusted/handlers/whatever just to know who the sub is supposed to lend an ear too. (yes some owners like surprises but the information should be available at some point)

All of this might sound a bit complicated but the end result should be a compact button on a screen, able to deploy a small panel of buttons each referring to an available (situational) obvious feature.

**Comment by zontreck** [comment]
This does not appear to be something that would be implemented in core OC. This request appears to contain some development concepts as well for enabling verbose, etc. Most of the actions which you are requesting can be performed by chat command. This idea may be visited after v8 gets released and a solid external attachment API is implemented. But for now this is not something we could do. I am going to close this issue for 2 reasons.

1. No action on this ticket for nearly 2 years
2. Currently not in scope of possibilities offered by the code set.
