### ISSUE TITLE
Outfits `Lock Core` allows attaching from within the folder

### ISSUE THREAD

**Issue by PortaSL** [OpenCollarTeam/OpenCollar#1044]
What version of OpenCollar are you using?
8.2.3

What behavior did you expect?
When using `lock core` you can still attach items from the core folder, just not detach them

What behavior did you see instead?
In my mind it would make sense to have attachments also be restrictied. If you are using multiple subfolders for different variants in the core folder such as the following strucutre. 

![image](https://github.com/OpenCollarTeam/OpenCollar/assets/118939705/e0e5b667-aee0-49e2-8d76-186f227f34f9)
You could have `core1` attached and then lock the folder, the wearer could then attach the items from `core2` but not be able to detach them. 

What steps does someone need to take to reproduce the problem?
Create the above folder structure, with no items attached. 
Enable `Lock Core` 
Attempt to attach item. 

Currently the `Lock Core` uses the `detachallthis` but potentially it should also be using `attachallthis` in tandem.

**Comment by tayaphidoux** [comment]
the core as far as i am aware has no way to difrentiate from core 1 and core 2 so when it applies nude it will attach both, aside from that it is a logical assumption that when the formentioned situation is not going which temporarily unlocks the folders you should not be allowed to attach any thing, however it would defeat the purpose and posibly break if you log in and sl forgets to attach some components which you would then have to manualy attach scine core is the base avatar setup for the strip function to work.

**Comment by Medea-Destiny** [comment]
Out of scope for the way Outfits currently works, but there will be future reconsideration
