### ISSUE TITLE
Request for new menu toggle button 'LeashTurn".

### ISSUE THREAD

**Issue by PonySorrowsong** [OpenCollarTeam/OpenCollar#1045]
What version of OpenCollar are you using?
8.2.3

What behavior did you expect?
When I am facing a different direction than at my leash holder or anchor, I expect my direction to change to facing them when my leash holder starts walking, or where the anchor is. If the chain is linked to the front of the collar, pulling it or yanking it would turn me around in real life. It is not real looking for me to be dragged walking sideways or backwards with the chain extruding from the front of the collar into my neck and out the back of my neck. If I try to walk away from my anchor or leash holder, the same thing would happen in real life, the chain attached to the front of my neck would pull me around. 

What behavior did you see instead?
I see myself walking backwards and not being turned to face the direction the leash is pulling my neck.

What steps does someone need to take to reproduce the problem?
It is easy to reproduce.

To "fix" the problem, I request a toggle button be added to the menu on open collar that would have some intuitive name like "LeashTurn" where if it is not on, things would be as they are now, but if you turn it on, then you can at least have a choice of turning around when the leash is tugged or you try to walk away from your leash holder or anchor.

**Comment by Pingout** [comment]
In the Leash/Configure menu there is a checkbox for Turn, which will make the sub face the direction of the Owner. Is this the feature you are looking for?

**Comment by SilkieSabra** [comment]
Also, the leash rotation requires RLV on in the viewer to work, check that.

**Comment by PonySorrowsong** [comment]
Yes that is the feature I was looking for. I did not know it was there. Would you happen to know if there is a toggle to notify you when your primary and secondary owners log in and out? That would also be helpful.

**Comment by Pingout** [comment]
There is an App, in github, which will set up notification when a Collar Owner logs in. Copy the script into your inventory, then drop the new script into your collar.
https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/Apps/oc_OwnerOnlineCheck.lsl

**Comment by PonySorrowsong** [comment]
Ok Thanks!
