### ISSUE TITLE
Feature Request collar addon aproval

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#1048]
What version of OpenCollar are you using?
8.2.3

What behavior did you expect?
aproval process to be targeted to prevent cross contamination of startup process of addons

What behavior did you see instead?
i have two or more addons thinking they are connected when another one connects.
[09:56:15 AM PDT]  A.R.C Nanny McFeedoux: [Recived approved]TE - Paws Collar Safra's Pony - chest - test (neck):{"addon_name":"OpenCollar","pkt_type":"approved","iNum":0,"sMsg":"","kID":""}

What steps does someone need to take to reproduce the problem?
should include the addon key and/or name that sent the request since the sMsg and kID fields are blank those are perfect spots.

**Comment by tayaphidoux** [comment]
just applied this to my own collar and it seems to be working [11:07:36 AM PDT]  A.R.C Nanny McFeedoux: [Recived approved]TE - Paws Collar Safra's Pony - chest - test (neck):{"addon_name":"OpenCollar","pkt_type":"approved","iNum":0,"sMsg":"Nanny","kID":"6b024578-e705-1634-5044-374f2c79f66f"}

**Comment by SilkieSabra** [comment]
Please do test it *before* you make the pr or else open it as an issue and include the fix you made there, then test it yourself, and on at least one other person, then make the pr when you're sure to the best of your ability it works.  Please.  For future reference.

**Comment by tayaphidoux** [comment]
thats what this is is an open issue/feature request and i applied the consept jus now to test it.

**Comment by tayaphidoux** [comment]
after i can get some relogs if there is no pr's for it yet i may make one.

**Comment by SilkieSabra** [comment]
Oops sorry.. I was too hasty, I'll remove this section of the thread

**Comment by SilkieSabra** [comment]
Amended---yes please do once you've tested it thoroughly.

**Comment by tayaphidoux** [comment]
oc_addon uses llRegionSayTo and i am being silly thinking it could cross talk.
