### ISSUE TITLE
/1 <prefix> NAME displaying incorrectly when set

### ISSUE THREAD

**Issue by mistressohm** [OpenCollarTeam/OpenCollar#1053]
**What version of OpenCollar are you using?**
8.2.3000 (Hotfix oc_dialog)

**What behavior did you expect?**
When using /1 _prefix_ Name _New Name_ the response would list _New Name_ in confirmation

**What behavior did you see instead?**

/1 _prefix_ Name _New Name_ responds with 

[device name]: The wearer's name is now set to _Previous Name_

**What steps does someone need to take to reproduce the problem?**

Wear (or have an owned submissive wear) a version 8.2.3000 (Hotfix oc_dialog) OpenCollar

Use the Name chat command:  /1 _prefix_ Name _new name here_

Instead of seeing the new name, you will instead see the prior name in the confirmation.  However, if you grab the wearer's leash, you will see the new name displayed.

To verify, type: 

/1 _prefix_ Name
and you should see the new name, and not the previous name.

I suspect that there is a statement to print the name to local chat as a confirmation, that is getting called BEFORE the routine to actually change the name value, instead of AFTER that value has been changed.

**Comment by Medea-Destiny** [comment]
The link message to trigger the notification was done immediately after the link message to update the name, and was arriving before that was processed. We already have a delay to avoid this in setting device name, but it was missing in name. Have added in the delay and put some clarification into the notification for changing both name and device name in case of lag.

@mistressohm Thanks for the report, small thing but we really do rely on people spotting these small things and letting us know!
