### ISSUE TITLE
Feature request: let collar connect to remote

### ISSUE THREAD

**Issue by Slanador** [OpenCollarTeam/OpenCollar#1072]
OpenCollar 8.2.x.

Currently a remote connects with nearby collars. 

Suggestion: to let the collar give explicit access to a nearby remote.

**Comment by Medea-Destiny** [comment]
@Slanador can you explain this a bit further? What's the idea behind doing this, what would you like it to achieve?

**Comment by Slanador** [comment]
This came out of a conversation on the Group channel. To be honest, I was more interested in letting someone easily grab a remote HUD from the collar, and then connect to the collar. In the conversation, someone suggested letting the collar connect to a closeby remote. Since I was adding the other issues anyway, might as well add this one to the table in case someone is interested.

**Comment by Medea-Destiny** [comment]
@Slanador Future versions of the remote will allow the owner of the remote to pick a collar to target without having to connect to that collar so this won't be needed, but thanks for going to the effort of posting a suggestion raised in the group to here, appreciated!
