### ISSUE TITLE
wrong leash length setting name in oc_particle

### ISSUE THREAD

**Issue by NikkiLacrima** [OpenCollarTeam/OpenCollar#1089]
oc_leash stores the length setting as **leash_leashlength** while oc_particle looks for the setting **leash_length**

** Edit **
To replicate the issue you need an item that connects a chain from a distance, longer than 2 meters.
Like a clickable box.

Stand less than 2 meters away and click to se chains appear.
Move away to 4 meters and click, no chains should appear.
Set leash length to 10m and click now the chains should connect but they dont.

** Edit **
See PR #1091

**Comment by SilkieSabra** [comment]
Addressed in #1091
