### ISSUE TITLE
"Unkown LockGuard Command" message on locking RR cuffs from others.

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#1090]
So with the new release version, when someone near me changed the poses on RR Vixen cuffs worn by someone else, these messages popped up:

whispers: Unknown LockGuard command: a5a2c14f-f056-3dba-7290-92af6cd4c52c

whispers: Unknown LockGuard command: fe41c8bf-fe35-6e55-dd1d-be53da9f0040

This was repeated with Vixen cuffs on another different person.

whispers: Unknown LockGuard command: 0989741e-f276-b8bc-1050-f91d4333855e

Oddly, when they grabbed the leash on the Vixen collar, it DIDN'T pop up.

Also, when RR Serious Shackle cuffs were locked on ME, again, nothing.

**Comment by NikkiLacrima** [comment]
Should be fixed by #1088, but its good to know that vixen cuffs can be used for testing.

**Comment by SilkieSabra** [comment]
Closing this, addressed by #1088
