### ISSUE TITLE
Leash restrictions remain without leasher

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#1100]
On the newest release candidate, a couple of times now, when someone had been holding my leash and logged off without dropping it, when I logged on the next day, the restrictions remained. This wasn't the case on previous versions. When the leasher logged off, the restrictions were dropped. This has happened the last two times.

Will add more data as I get any.

**Comment by SilkieSabra** [comment]
Actually it has always been the case, or at least for a very long time, that if the leash is engaged when the leasher logs off it's still active.  You can test this two ways, one, if the leasher has owner authority, no one with a lower level of access can call the leash after they've logged off without unleashing; two, if the leasher logs on to the other side of a wall from the wearer the wearer gets their head bopped on the wall.

**Comment by Surssin** [comment]
Oh THAT still works.
I'm talking about the RLV TP blocks that come with strict leashing. Previously, those would drop if the leasher logged off or TPed away. Now it's not doing that.

**Comment by NikkiLacrima** [comment]
I have done some testing with strict leashing, so far everytime the collar has released the strict leasing rlv restrictions after 60 seconds of having the leasher absent.  
On a relog of the wearer, the collar remembers the strict leash condition, and reactivates the rlv restrictions and starts to scan for the leasher. When the leasher is not found the restrictions are removed (after 60 seconds).

**Comment by Surssin** [comment]
I will keep an eye on it and try to note any consistent behavior that may lead to reliable reproducing of the error.

**Comment by SilkieSabra** [comment]
Let's reopen this if it comes up again and is reproducible.
