### ISSUE TITLE
Feature Request: Sync settings across multiple collars via a wearable object

### ISSUE THREAD

**Issue by rocketroo** [OpenCollarTeam/OpenCollar#118]
What version of OpenCollar are you using? OC7

What behavior did you expect? I would like to be able to change between multiple collars depending on outfit/avatars by being able to wear a clickable 'back up' prim. Click it to read all settings in current collar. Change collars, and click the prim again to transfer all settings into a new collar. This will allow multiple collars/harnesses/rings/etc to be used depending on outfit/desire without having to use a database or having to manually re-invite all owners, change all setting or having to copy the settings card manually from one collar to the next. The advantages of this would make collars more attractive as an accessory that can be changed between outfits without hassle. This would avoid the need of an on-line database. This also would keep a back-up to easily fix any collar whose settings got 'glitched' as the back-up would have the last settings in it.

What behavior did you see instead? Owners List and settings have to be redone for each collar manually

What steps does someone need to take to reproduce the problem?

**Comment by NorthGlenwalker** [comment]
This could be done on a similar line to how I get the information to sync the cuffs. This would also make it a lot easier for me to sync the cuffs settings from the collar if it was a built in function. I would suspect this would be better to be controlled by the oc_settings script, as for the cuffs to update it's settings at present it has to interrogate the oc_settings script. by storing these settings in an off-collar prim.

**Comment by SilkieSabra** [comment]
Using a web text file from which to load a url is already functional in the collar.
