### ISSUE TITLE
Easy UI for locking on mesh body parts

### ISSUE THREAD

**Issue by MeredithC** [OpenCollarTeam/OpenCollar#119]
Is there a way to lock on mesh body parts without a lot of fooling around with folders or coding the folders? Thinking of how to lock on mesh heads, hands, feet and bodies so when other things are removed, they remain on.

**Comment by nirea** [comment]
@SatomiAhn and I have discussed how this could be done using similar functionality to the recently-added Detach menu.  I think we needed a new RLVa function to be added to the viewer ("@remattach:<uuid>=n" or something like that).  Any update on that Satomi?

**Comment by Davros-and-Babble** [comment]
I just came around to this.  From the description, Isn't nostrip the solution for keeping body parts on?  I've grouped the two in my mind:  

1) Nostrip, to keep things from being stripped by RLV, such has the body, hands, feet, mesh heads etc, but the collar wearer can still access and remove/swap the items
2) Locking, to keep things forced on the wearerer, such as cuffs, blindfolds, gags, etc, and cannot be taken off by the collar wearer, unless unlocked by RLV (usually a role that has authorization to do so, such as the master/owner).  In which case these would want to be accessed through RLV folders.

If anyone has a different view on this, please chime in!

**Comment by SatomiAhn** [comment]
@Davros-and-Babble: both your suggestions require some preliminary setup. If we had a command for locking by UUID, it would be possible to target a specific worn attachment for locking, even if it wasn't put in some #RLV subfolder.

Of course, folder based techniques allow for very subtle control and they are definitely the way to go... only provided the user who wears the stuff has both time and technical skill to set up the folders correctly.

**Comment by Medea-Destiny** [comment]
One relatively easy change to do here is to limit items that appear in the detach menu by filtering. We could do this with a notecard that simply has a list of attachment names, one per line, that are parsed out of the llGetAttached() list. I would suggest also hardcoding the Maitreya, Belleza, Slink & Kemono body parts into the filter list.  We might also consider having an optional exclude by attach point -- it's rare anyone will want something attached to skull to be detachable, for example.

**Comment by Davros-and-Babble** [comment]
@Medea-Destiny See https://github.com/OpenCollarTeam/OpenCollar/issues/89.  I totally agree with the filtering idea.  I love the detach menu, but seeing a long list makes me a little sad so I hard coded some filters/jury-rigged my own collar.  If I knew more about entire structure of OC, I'd try my hand at updating the code, but I pasted what I had on issue 89.

**Comment by zontreck** [comment]
Outfits has a interface that can be used for this, even if you never use the outfits feature. The function is: Lock Core, so anything inside of 
`.outfits/.core` will be locked, and every 120 seconds, it will lock any newly added items. 

While the original poster @MeredithC  specifically asked for no folder setup, i do believe this is a rather simple folder to set up. I'll close this ticket in about a week if no reply is received.

**Comment by zontreck** [comment]
No reply received since Dec 7 2019. This is a dead ticket. Closing
