### ISSUE TITLE
Collar "Fix" menu not working for owner

### ISSUE THREAD

**Issue by Catspawgat** [OpenCollarTeam/OpenCollar#121]
What version of OpenCollar are you using?
7.0
What behavior did you expect?
Menu Item to fix Collar
What behavior did you see instead?
Access Denied
What steps does someone need to take to reproduce the problem?
As Owner, Access collar menu, Settings, Fix, 
When chosen by collar Owner, you get Access Denied
As wearer, this option works

This should be available to owner as well

**Comment by nirea** [comment]
Owners are often more tech savvy than subs.  If the owner's using the menu and things don't look right, I think it's good for them to be able to click Fix.

**Comment by zontreck** [comment]
This was fixed in a previous pull request but the issue was never closed. Should the issue resurface please open a new issue.
