### ISSUE TITLE
[request] Camera Sync in collar and owner hud

### ISSUE THREAD

**Issue by eksynn** [OpenCollarTeam/OpenCollar#123]
What version of OpenCollar are you using?
7.0

What behavior did you expect?
An option to sync my camera to my pet's, and vice versa through her collar and my owner hud, similar to how it used to be.

What behavior did you see instead?
Just the options to 'sticky' the camera to specific angles.

What steps does someone need to take to reproduce the problem?
Apps -> Camera -> Sync Cam To

Related: https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_camera.lsl
Could we have an option added to the oc_camera script to sync one's camera to a specified target, and to request (forcibly or otherwise) their camera to sync to the requestee's?

Thanks in advance!

**Comment by SilkieSabra** [comment]
This is a good idea for a third party app.

**Comment by eksynn** [comment]
although it's set to completed, i can't find this feature anywhere - i also think i remember someone in the group saying this issue'd open again for it not actually being completed. xD
