### ISSUE TITLE
request: add chat commands sending to OC-RLV wear system

### ISSUE THREAD

**Issue by Hyratel** [OpenCollarTeam/OpenCollar#124]
What version of OpenCollar are you using?
7.0
What behavior did you expect?

Feature request not a bug -

add chat-command transmitting to the RLV wear/add/remove system. brainstormed idea would consist of notecard in user inventory with #onattach and #onremove sections. example case would be for bits that are not attached/detached with clothing, such as Psicorp bits, which have an option for a Bulge mode when Hidden. (multiple copies quickly becomes impractical due to the need for syncing every copy after any change)

this would also allow for bypassing the need for multiple attached HUDs for scripted clothing such as Scripted Strip by consolidating an arbitrary number of chat commands into one OC command, "simultaneous" (used loosely) to attach/detaching apparel

+pants
| Item: pants
| Notecard: pants commands

``` pants commands
#onattach
/5 penis hide

#ondetach
/5 penis soft

```

**Comment by zontreck** [comment]
Not possible how it is described.  When you wear a folder using the collar/ or an outfit. The collar has no way to read a notecard in that RLV Shared folder. So you would need a rather massive notecard in the collar detailing each RLV path and a applicable chat command. This would also in turn use a lot of memory.

We can't implement this as it is written.
