### ISSUE TITLE
We revoke our license grant for the following programs:

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollarTeam/OpenCollar#126]
Me and my colleague @GarvinTwine are revoking our license grant for the following programs:

* .aoloader.lsl
* oc_remote_leashpost.lsl

These programs may no longer be published under the General Public License, version 2. They are different applications and do not resemble files that are a part of what you describe as "OpenCollar" in any way.

We kindly ask that our copyrighted material is removed by the legal owner of this git repository upon receiving this notice. If you need to, you can fork it again once we publish it with a new license of our choice.

Thanks!

**Comment by nirea** [comment]
A GPL grant cannot be revoked.
