### ISSUE TITLE
Colour/themes Error

### ISSUE THREAD

**Issue by tammykenzo** [OpenCollarTeam/OpenCollar#127]
What version of OpenCollar are you using?
7.1
What behavior did you expect?
change colours
What behavior did you see instead?
got a bunch of errors
What steps does someone need to take to reproduce the problem?
Through menu. Themes >settings >themes > Green  it gave me
[22:31] llSetPrimitiveParams error running rule #1 (PRIM_TEXTURE): arg #3 (texture repeat) vector expected but string given. 
six times

theme colour changes worked in 7.0

**Comment by Athaliah** [comment]
Was given the information that lines 452-454 on the oc_themes script may of contributed to this behavior.

**Comment by RestlessSwords** [comment]
Athy is correct, the changes to lines 452-454 were in error, only 3 of 4 names were changed,  line 453 needs the 2nd identifier name changed to lPrimParams  (it was incorrectly left as lParams), and *anyone* who uses the standard Settings->Themes->xxxxx to change color or texture will get a pile of script errors, one error for every prim bein changed (and the resulting change is not done correctly)

**Comment by zontreck** [comment]
#135 PR was merged which should have fixed this, closing
