### ISSUE TITLE
Land Owner Trusted by default.  Should be off by default?

### ISSUE THREAD

**Issue by CaraDoulton** [OpenCollarTeam/OpenCollar#129]
What version of OpenCollar are you using?  7.1  (Behavior is also noted in default collar fresh from the OC vendor)

What behavior did you expect?  I would expect that anything that leaves the collar wearer open to being randomly grabbed would be off by default.  Default settings are Ask (on), Public (off), and it can be assumed that is so that the end user has to choose to enable the more risky behaviors.

What behavior did you see instead? By default, on a brand new collar or when updating an existing collar, the Land setting is checked, which according to the manual "When checked, permits restrictions from objects owned by the landowner to be applied without a prior request."  We've seen people being captured by random RLV traps because of this setting being on by default, and then being unable to get out of these traps.  Even when the collar is set to "Ask", even when they have an owner, even when "Ownself" is checked, the RLV traps are grabbing them because of this Land setting being checked, which no one really knows is on or needs to be checked.  Even the collar wearer's owner is unable to get them out of it, or force port them away once captured.

What steps does someone need to take to reproduce the problem?  Put on a brand new collar, change nothing.  Go to a sim where the RLV traps are owned by the landowner.  Also try while owned, while ownself is on, while 'ask' is enabled.  Nothing will prevent these traps from taking over, while that 'Land' option is checked.

I'd think that simply having the 'Land' option OFF by default would save a lot of heartache.  People can enable it if they want to be more risky.

**Comment by nirea** [comment]
Sounds good to me.

**Comment by mailani19** [comment]
Agreed.  I've had it happen many times where someone forgets to turn off their land trust and ends up locked somewhere while exploring.

**Comment by mailani19** [comment]
Just made a pull request to fix this issue <3

**Comment by zontreck** [comment]
This appears to be fixed. Issue was never closed. I'm gonna go ahead and close it now.
