### ISSUE TITLE
No Themes notecard found in any collar prim

### ISSUE THREAD

**Issue by rocketroo** [OpenCollarTeam/OpenCollar#131]
What version of OpenCollar are you using?7.1

What behavior did you expect? That there be a Themes notecard in the collar

What behavior did you see instead? After searching through all the child prims and the base prim after building, no Themes notecard was found in any of them. 

What steps does someone need to take to reproduce the problem? Create a new collar using a new clean moddable base prim and a child prim for FloatText using the oc_collarizer script and the 7.1 version of the updater. Search all created and original prims Contents section.

**Comment by nirea** [comment]
What happens if you put in a blank themes notecard?  I think we chose the current behavior to avoid having users see a Themes button that does nothing, but I'll admit I haven't worked much with the current themes feature since making the alternate oc_meshthemes script for the main release.

**Comment by zontreck** [comment]
#198 is a potential fix. The proposal is to completely redo themes so it would be easier to use and set up. Also a blank notecard won't even be found reliably. There is a bug that has existed in SL for years
