### ISSUE TITLE
Feature Request: Meshthemes improvement

### ISSUE THREAD

**Issue by rocketroo** [OpenCollarTeam/OpenCollar#132]
What version of OpenCollar are you using? 7.1

What behavior did you expect? To be able to define face and links when applying theme. I have collars of multiple mesh links and also need to not have the main collar as the base prim. So the Meshthemes scripting needs to be altered to : 
**Link Number**|Face|TextureUUID|ColorVector|Alpha|Shine|Bump|Glow
with Shine, Bump and Glow being optional inputs
Would also like to see to be able to put in Texture UUID for Shine and Bump as many mesh objects have their own texture for those properties. And in some cases, may have different Bump for different Textures

What behavior did you see instead? Can only apply themes to base link. This is far too restricting and makes many designs unable to use Meshthemes

What steps does someone need to take to reproduce the problem? Is current meshthemes set up

**Comment by zontreck** [comment]
Please see issue #198 as it might resolve this

**Comment by zontreck** [comment]
New theme script
