### ISSUE TITLE
Regression BugFix: Dont keep re-centering titler onto root prim

### ISSUE THREAD

**Issue by RestlessSwords** [OpenCollarTeam/OpenCollar#134]
What version of OpenCollar are you using?
- 7.1

What behavior did you expect?
- collar creator positions 'FloatText' prim and it stays where it is put

What behavior did you see instead?
- anytime color contents is changed, oc_titler does a forced script reset
- script reset MOVES titler prim to be centered on root prim
- titler prim then sticks out and typically blocks touches to collar froot/root
- - - *IF* for some reason OC designers want to force it to move, it should move to collar center
- - - and OC design should *NOT* assume root prim is the center of the collar

What steps does someone need to take to reproduce the problem?
- have a v7.1 collar with a FloatText prim
- reset the oc_titler, or reset all scripts, or edit any file in the collar contents (like themes)

SOLUTION:
- remove (comment out) oc_titler v7.1 line 96-97 (is a 2-line statement)
- or, change it to set position to CENTER of the COLLAR, not center of ROOT

see pull-request #136

**Comment by Ranno** [comment]
This still seems to be an issue as of 2/13/2019

**Comment by zontreck** [comment]
Won't fix. Will change size of the titler prim but this is required for properly positioning the titler text.
