### ISSUE TITLE
Exceptions cleanup / bug fix

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#137]
oc_exceptions is currently (v7.1) very un-optimised. Exceptions are sent as y (unset) regardless of whether they need to be unset, and each exception is sent as a separate command. Currently each of the 7 exceptions will be set individually for each person on owner / secowner / templist. On login, no exceptions are currently set, so setting a Y for these is entirely pointless.

 The routine ought to be concatenating each exception per user into a single command, but because the llOwnerSay is inside the loop rather than outside the loop, this doesn't happen and each command is sent individually. 

Example of how inefficient this is: if you have 4 people on owner/secowner list and blank all the exceptions, the collar will issue 28 separate RLV commands, each of which is supposed to lift a restriction that obviously hasn't been set, as the collar is just being attached. All 28 of these are unnecessary.

Further: the g_lSettings list, for providing exceptions for people who aren't on the list, actually has the llOwnerSay outside the loop, to properly concatenate the command -- except that the list is not comma separated, making this function fail entirely. As there is no longer a function in the Exs menu for "other" users, I don't actually know if this is still used despite the code being present, though Roan points out it may be supported in notecard settings. I haven't looked into this yet. 

Further 2: the clearEx() function loops through all possible exceptions and clears them one after the other. This can be done by dumping the exceptions list as a string with ",clear=" as a separator, which hits the viewer with 7 times fewer individual llOwnerSay RLV calls, and is approximately 4 times as script-efficient to issue. 

Fix: 

See  [here](https://github.com/Medea-Destiny/OpenCollar/blob/master/src/collar/oc_exceptions.lsl) for my corrected version. It should all be fine but a little more testing might be advisable before a pull request. There is a shortcut taken here in clearing all exceptions before setting rather than setting based on requesting and parsing currently set/unset exceptions as this seems to me to be the most efficient method.

Further 3: I notice also that the script currently resets on attach, which seems like an entirely unnecessary burden on the servers. I'm wary of replacing this with a simple 
`changed(integer change) { if(change&CHANGED_OWNER) g_kWearer = llGetOwner(); }` 
which essentially serves the same purpose (as that is the entirety of state_entry() ) without the repeated  resets because I'm a bit suspicious of the on_attach behaviour of the collar and haven't dug into it properly yet. Resetting the script on attach may actually currently serve a rather backwards purpose of causing the script to avoid multiple hits to SetAllExs during on_attach setting behaviour. Ideally script reset on_attach should be avoided as inefficient, but I am not confident enough that I understand the on_attach behaviour of current OC to know if this is safe.

**Comment by nirea** [comment]
Thanks for the pull request!  I'll close this issue here and we can make the changes over there.
