### ISSUE TITLE
#RLV folder access issue

### ISSUE THREAD

**Issue by Mace68** [OpenCollarTeam/OpenCollar#138]
What version of OpenCollar are you using?
7.1

What behavior did you expect?
To be able to access a folder normally.

What behavior did you see instead?
The folder is not being listed at all.

What steps does someone need to take to reproduce the problem?
Folders called Top or Bottom don't appear in the collar's RLV > # Folders menu.

**Comment by SilkieSabra** [comment]
This is a system wide sl issue.  It is about how you name your folders in your inventory, it affects the entire RLV API and is not related to OpenCollar.  The answer to the problem is not to give your folders "legacy" directory names such as "top" and "bottom."
