### ISSUE TITLE
Request: Enhance .core folder behavior

### ISSUE THREAD

**Issue by Mace68** [OpenCollarTeam/OpenCollar#139]
Considering the purpose of the .core folder under .outfits, I think that rather than removing and reattaching everything it contains, the items in the .core folder should instead be treated as locked or nostrip, at least during an outfit change that's initiated via the Outfits feature.

**Comment by Medea-Destiny** [comment]
issuing @detachallthis:#rlv/.outfits/.core=n before the removal process and removing it after the removal process would be a simple way to ensure that the contents of .core aren't actually removed. 

At the same time, I would propose temporarily locking the collar if not currently locked. Attempting to use outfits with an unlocked collar does not end well, as the collar will be removed before it has a chance to attach anything new.

**Comment by Davros-and-Babble** [comment]
I have to say I really like this idea.  One question I would pose, does the #rlv/.outfits/.core=n prevent items in the folder if they were just links?  If so this would be more than amazing.  If not, I still like the idea ♥

**Comment by zontreck** [comment]
see newest oc_outfits!
