### ISSUE TITLE
LinkMessage command numbers duplicated

### ISSUE THREAD

**Issue by starverse** [OpenCollarTeam/OpenCollar#140]
Two of the integer "command" constant values are duplicated.

`ATTACHMENT_RESPONSE` and `AUTH_REPLY` are both assigned the value 601.  I _believe_ that they should have different values.

**Comment by starverse** [comment]
llMessageLinked(LINK_ROOT, ATTACHMENT_RESPONSE,"CollarCommand|"+(string)iAuth+"|ZHAO_MENU|"+(string)kID, g_kWearer); (in oc_anim.lsl)
llMessageLinked(iSender,AUTH_REPLY, "AuthReply|"+(string)kID+"|"+(string)Auth(kID), llGetSubString(sStr,0,35)); (in oc_auth.lsl)

**Comment by zontreck** [comment]
What script is this occurring in?

**Comment by zontreck** [comment]
No reply received recently. Closing issue. Please reopen if this is still a issue.
