### ISSUE TITLE
Rename foot-couples animation emote

### ISSUE THREAD

**Issue by DarkDonja** [OpenCollarTeam/OpenCollar#143]
Hello,

I touched my 7.1. OpenCollar, clicked [Animations] -> [Couples] -> [foot] and chose a victim for a footkiss or whatever "foot" means.

I expected something like .... X kisses Y's foot

I got something like: X noms Y's foot

English is not my native language, but the dictionary told me that "nom" means something like "eat".

Since I guess that at least 95% of Opencollar users are not cannibalistic, I suggest to rename this text in something like "X kisses Y's foot"

I think that can be done easily by changing the foot-line in .couples notecard:

"foot|~nom|~foot|1.1|_SELF_ kisses _PARTNER_'s foot."

Best regards,

Tats and Donja

**Comment by SilkieSabra** [comment]
I agree, it's easy enough for users to do that in the couples notecard but it's not obvious to the average user; the change should be made in the default couples notecard.

**Comment by zontreck** [comment]
This is being changed in 7.2, i gotta talk to roan and medea tomorrow about it though

**Comment by SilkieSabra** [comment]
fixed.
