### ISSUE TITLE
Capture and Trusted settings do not set RLV accepttp properly

### ISSUE THREAD

**Issue by starverse** [OpenCollarTeam/OpenCollar#144]
What version of OpenCollar are you using? 7.1

What behavior did you expect? A capture, or at least a trusted, would also enable forcetp

What behavior did you see instead? forcetp was not being enabled.

What steps does someone need to take to reproduce the problem?
have someone capture you.  They will not be able to forcetp you.
Set someone as trusted.  They will not be able to forcetp you.

Have them go into the RLV terminal and manually add the accepttp setting.  Now they will be able to forcetp you.

**Comment by zontreck** [comment]
Working on it.

**Comment by zontreck** [comment]
Cannot reproduce. I checked the RLV debug settings and it is setting it perfectly fine and auto tp works. More information is required before this can be fixed.
