### ISSUE TITLE
Relay Issues

### ISSUE THREAD

**Issue by Davros-and-Babble** [OpenCollarTeam/OpenCollar#145]
What version of OpenCollar are you using? 7.1
What behavior did you expect?  Dialog request for being captured by furniture.

What behavior did you see instead?  Either not seeing it after saying no, or seeing a previous dialog instead of the new dialog.  In both cases the furniture user/capturer sees "no relays in range".  Also Add/Block Trusted user isnt shown, only Add/Block owner and object.

What steps does someone need to take to reproduce the problem?   Find any piece of AV Sitter furniture with RLV, right click touch to scan for a victim.   Have the wearer Click no or ignore and try again to produce the results.

**Comment by Davros-and-Babble** [comment]
Also if you use the safeword a person can recapture immediately without it asking

**Comment by zontreck** [comment]
I think relay is one thing getting worked on for 7.2. Can you please tell me what the settings were for the relay?

**Comment by zontreck** [comment]
There is presently a pull request to fix how the relay automatically allows owner, trusted, and land if enabled. I will look and see if the fix covers this issue as well. If not might need to be a separate fix. I do know that a few weeks ago a fix was made to allow the relay to go idle for 20 seconds or so after safeword to avoid recapture. But i do not know if it clears said list.

**Comment by zontreck** [comment]
Is this still an issue? (Will close in 48 hours with no reply, and assume it is fixed in 7.3)

**Comment by zontreck** [comment]
Went past 48 hours. Assuming the problem has been resolved. Please open a new issue if this is still a problem
