### ISSUE TITLE
Questionable unsit behavior in safeword function

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#146]
In 7.1 oc_rlvsys script at line 275, the safeword function (also called when clicking CLEAR ALL from the RLV menu) issues an unsit command - llMessageLinked(LINK_THIS,RLV_CMD,"unsit=force","");

This behaviour was brought up in group by Gloria Nubalo, who raised the point that it can break immersion in roleplay if someone wishes to safeword from RLV restrictions without actually standing up. 

I'm not sure what the purpose of doing this unsit is -- any unsit restrictions will be lifted, so people will have their sit button back. It may be an attempt to avoid problems with furniture that attempts to reapply  restrictions? I tend to agree with Gloria that this is an unnecessary and potentially annoying feature, but this is a behavioral  issue rather than a bug. I'd be in favour of removal, personally. 

The fix is quite simple: just delete line 275.

**Comment by mailani19** [comment]
Also a lot of RLV traps/toys actively spam the RLV commands so even if you do clear them they just immediately lock back on again.  some of them do not if you're not sitting on the object.

**Comment by SharieCriss** [comment]
The issue Mailani19 brings up can be resolved by a 30 second "grace period" where the relay would not accept any commands which would allow someone to stand up, TP away , or whatever else is required to get away from a misbehaving toy. Silkie's concern can be addressed by a private chat command to the sub stating that all restrictions were released and that they may stand up.

**Comment by zontreck** [comment]
Many complaints about that line have been seen ever since that line was introduced. The safeword function did not used to perform unsit

**Comment by zontreck** [comment]
Fixed: And added a 30 second grace period as SharieCriss suggested.  The grace period effectively puts the relay on pause for 30 seconds. I'm just testing the patch before compiling a PR

**Comment by zontreck** [comment]
Requested nirea review the fix since it does change the relay's behavior on safeword.  I got rid of the unsit=force line, and added that 30 second grace period, but there was another issue in the relay script. It was not even running Safeword when the collar wearer used their safeword. They would have to open the collar menu, go to relay, and then click safeword there..
