### ISSUE TITLE
VD script oc_pet not deleted by hammer

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#152]
I noticed twice recently that when updating using the hammer script from peanut no.9, the version that comes with oc_pet and one couples animation "petting" , the hammer script does not delete oc_pet and does not load oc_couples although the couples animations load properly.  Result was I had to instruct them to manually delete oc_pet and load oc_couples.

**Comment by zontreck** [comment]
To solve this issue the updater needs to be refactored to allow for inserting the update handler into child prims. At present time this is not how the updater is set up

**Comment by zontreck** [comment]
Can't fix due to compatibility issues with hammering the newer VD collars. Closing this ticket.
