### ISSUE TITLE
Antislide Setting throws an error message when pasted into the Settings notecard

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#154]
In OC V 7.1, AntiSlide Animations with the name structure ~walk_[animname] appear as ANIM=PoseMoveWalk~~walk_[animname]  when the settings are printed.  When copied to the settings notecard, however, it produces an error: "cannot find animation 'walk_[animname]'".

Could this be caused by a conflict between the tilde in the front of the animation name and the tilde separator in the settings parameters? It appears that the settings script cannot "see" the tilde at the start of the animation name and so doesn't find the animation.

To reproduce the error:  Name an antislide walk, drag it to the collar Animator prim, set it as an Antislide option, print the setting and copy it to the settings notecard.

**Comment by zontreck** [comment]
Have you personally tested this with other animations without the tilde? If not i will try it to see if that is the issue. It's a easy fix though

**Comment by zontreck** [comment]
just tested it is the tilde

**Comment by SilkieSabra** [comment]
the tilde is required for the antislide protocol so there has to be a tilde there

**Comment by SilkieSabra** [comment]
easier to change the spelling of the antislide animation than rewrite all the settings
