### ISSUE TITLE
Separating OC system into a master item and slave items (code terminology, not BDSM terminology)

### ISSUE THREAD

**Issue by MikuGit** [OpenCollarTeam/OpenCollar#169]
I was talking to roan on SL and they suggested I posted this as an issue in here as people may be interested in the idea.

The idea is to separate the OC system into a master item, such as a HUD, which retains all the core system scripts for OC, with settings, RLV, owner lists etc etc.

Then you have the slave items, which are lightweight on scripts and communicate with the master item in order to do all the things OC does.

The reason for this is that -a lot- of people use the OC system for a ton of things that aren't collars.
That means that people end up wearing multiple OC systems at the same time a lot of the time. That's a waste of resources.

The downsides of this separation, apart from development efforts, is that items will require chat commands to communicate, which will require handshaking to be lagproof and as such may be slightly slower and may, in the worst case break from heavy lag. With proper message identification, you'll avoid message desynch though. Desynch and loss of messages are probably rather rare though.

The upsides are that you have one core and people can very easily develop collars, cuffs, hoods, gloves, armbinders, boots, what-have-you, that are all using the same core system, the same ownerlists, the same settings. You'll be able to change collar to another design, but all settings will be intact without the use of a web server.
You also get the possibility of a pretty HUD that can show information about RLV, lockstates and whatever you want really. You can have buttons to open certain menus directly.

I'm new to git, so I'll likely not be very active here to respond to comments or questions about the issue, though I may, if I get how it works :p 
I'm however accessible on SL as Himeko (Himechan Resident).

**Comment by pcbeeswing** [comment]
Sounds like a good idea. It's work like most objects that communicate with a HUD.

**Comment by MikuGit** [comment]
It's not up to me to say whether the feeling is important or not.
That's subjective and up to each user.

A collar is a collar.
But for me, not having the scripts in the collar doesn't make the collar less of a collar. 
To me, it super doesn't matter where the scripts are.
To me, having the owner on the system is what matters and it also matters that it's easy and convenient for me to switch out collars to fit with my current outfit and shape. Something which is entirely impossible today, and my collar item is often hidden because it doesn't fit my current outfit, which is quite sad.
When I'm on a latexy avatar, I want a latexy posture collar and when I'm on a more vanilla avatar, I want a more "normal", subtle collar.
MD does this very well with their cuff engines, it's just sad that they are 2 engines instead of one and that they didn't integrate the collar into the engine system.

And this would really be no more complex than it already is from a user standpoint.
Instead of slapping on a collar, you slap on the master system and the collar and then it works exactly the same, with the same menus.
In fact, it would be easier than it is today. Not for collars, which would be no different, but for all other compatible items, both from a user standpoint and a developer standpoint.
I will confess that I haven't checked, but I assume that there still aren't any integrated cuffs for open collar. Something which existed back in the 3.x days and something which "all" other large BDSM chains provide along with their collars.
With the proposed system, you can put a premade slave script into any object and it'll detect the relevant links, provide particles when needed and do a @detach=n and hide/unhide links when the master asks for it.
As a developer you'd need a single script that would need no modification in order to make an OC product. You'd then also have the possibility, when desired, to create your own menus and functionality for the object similarly to how plugins work today, but on a more core level. Everything would be customizable and updatable without anything being lost or broken. While possible, people would have no reason to go fiddling with the core scripts, which some people do today, and render their items not updatable.

But I can respect that it can matter for some people where the scripts are.
Some will care, some won't. Some people don't even know, or care, what scripts are and what they do and OC have users like that as well. Probably a lot of them.
Having the core strictly in the collar makes for a problem though, because that still requires you to have a collar on at all times and it has to be that collar, and not another design that fits your new outfit, or you lose all settings.

However, there may be a best of both worlds.
It could be good to have as an option perhaps, for the people that want to have the same collar on at all times.
It wouldn't matter for compatible items where the core is.
But it does matter that the core is standalone and that the core system is built on the idea of interfacing with other objects. And it does matter that the main Open Collar package comes with said core system as a stand-alone by default and that all developers ship their product with a non-core version.
If they then also want to link a core to another version, that's all fine.
This would only mean that the core can chat with other items both over link messages and chat messages, that's the only difference.
To make the collar specific menus and options, you treat it like any other compatible item, as described above, and make a lightweight script for it for the item-specific settings and functions.
The core would detect that it's not in a hud with buttons because the relevant linked buttons with their names/descriptions aren't found, similarly to how it detects leashpoints and other links today.
Then to developers, you supply the core only inside of a notecard, which states, with clear instructions, how they are meant to use it and link it to their object only as an alternative, and to ship both versions.
For the users, the core is available, of course, and if they want to core an item that isn't shipped with a cored alternative, they can just link it and they have their cored item.

As for the non-centralized model with several stand-alones that communicate.
I don't think that having several stand-alones that talk to eachother and turn on and off cores would be viable. It would be possible to do and really quite nifty of a system. But where should you load the settings from? How can you determine what item is the master system when there are conflicting settings? You'd be required to have a heartbeat call to check for other items all the time, and fast enough as to not cause any interference with usage.
 A centralized system is needed I think. It's not a bad idea though.

**Comment by zontreck** [comment]
@nirea  @Medea-Destiny  @SilkieSabra 
Something we could maybe set as a todo item for v8? Although i do not want to make this mandatory to do. Perhaps something along the lines of.. having a select few core scripts, and everything else could optionally be put into other objects, creating the ability to completely redo the cuff scripts as well under this protocol. I definitely do not want to make this required though. Since if we do that then we create additional attachments people would need to wear.

**Comment by MikuGit** [comment]
Having a core that can be migrated and can stay in the collar (or another item) would be great. So that, indeed, you don't need more than one item.
But you need a way to handle multiple cores being put on at the same time so that it's intuitive and easy to use.
To make it migratable, I assume you only need to make it listen to both linked messages and a chat channel at the same time. Maybe make a tcp/ip-esque handshaking for the chat channel to prevent lost messages and pipe the messages in through that. If external messaging is done in a separate modular script, the item could also be made to work separate of external cores, should you really want it to, by removing said script. And modders could then make it work with cores again, should they really want to, by putting it back again.

Perhaps not the best way of doing it as it requires quite a bit of effort on the users, but maybe the idea might give you other, better ideas:
Maybe it could actually be done by turning off cores as anna above suggested. If they detect a master core, they turn off and only one master core is ever allowed. If multiple are present, it could check creation time of the object and pick the oldest and turn off the rest, or some other way of singling out one.
Primary owners could promote a core to master core and export its settings to other cores as well as "binding" other cores to that master core to prevent them from using any other master cores.
That way you can pick which core you want to use as the settings database.

**Comment by zontreck** [comment]
Won't do. This would be more trouble than it is worth. v8's API would allow for addons and plugins to behave the same, but the core scripts will always need to reside in the same object.
