### ISSUE TITLE
Sub-menus for MeshThemes

### ISSUE THREAD

**Issue by PeeBeeMcMillan** [OpenCollarTeam/OpenCollar#174]
<i>[concerns OC 7 in general]</i>

Greetings!

While trying to "unclutter" the buttons and avoid confusingly abbreviated button names in .meshthemes, I had the impulse to group themes into sub-menus, which apparently isn't possible at this time.

Since I'm a mesh person, my scripting skills are little above the level of "I can make that box change color!", so it's unfortunately out of my league to look into it myself. So, I thought I would put my thoughts out to the collective intelligence of the team.

In OC the syntax is [MyTheme] for the button/theme name, followed by the face setup line(s).
However, let's say we have a mesh collar with 3 faces (band, metals, bow) and each has 3 texture options.
To cover all possible single combinations, we need heavily abbreviated button names, that are incomprehensible for many end-users.

In my mind it would be super nice to have a "parent menu button syntax", to group the parts.
The command line for the faces wouldn't have to change, the challenge is more about how the dialog is being created and structured, I suppose.

Obviously, the easier way is to add a color/texture changer HUD with the collar. The downsides are that more scripts would have to be added  - and more importantly - that the use of such HUD would be limited to the wearer. I would argue that it's more desirable to keep the themes available to Owners as well, within the collar menu.

Thanks for reading and considering my little suggestion essay!

Best, PeeBee

<i><b>hypothetical .meshthemes note card example:</b>
+Band+ // new button syntax, which creates a menu that contains all theme buttons below it
[Color1] //theme button, as is now
face0|....... // command line, as is now
[Color2]
face0|.......
[Color3]
face0|.......

+Metals+
[Color1]
face1|.......
[Color2]
face1|.......
[Color3]
face1|.......

+Bow+
[Color1]
face2|.......
[Color2]
face2|.......
[Color3]
face2|.......
</i>

**Comment by zontreck** [comment]
Please see issue #198 as the proposal i made might actually partially resolve this issue

**Comment by zontreck** [comment]
See the new theme script
