### ISSUE TITLE
Bookmarks does not load from updater unless there is already a bookmarks script in the collar

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#175]
When updating a collar that does not already contain a version of oc_bookmarks, the Updater fails to load it.  I discovered this with a user who had no bookmarks script in her collar after using the collarizer.  I duplicated it, then checked it by deleting bookmarks from a stock collar and running the updater, it did not load.  I then added a comment to an existing bookmarks script in another copy of the stock collar, ran the updater and the script was replaced by the one from the updater.  We have a lot of users who have created their own collars with the collarizer and have no bookmarks.

**Comment by zontreck** [comment]
This is because the current installer's apps bundle has the OPTIONAL flag. and thats how optional works at the moment it doesnt prompt the user for whether they want to install the optional bundle or not.
