### ISSUE TITLE
Unlocked Collar Detaches during Replace Outfits causing Replace to abort

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#179]
If using the Outfits function to replace an outfit while the collar is unlocked, the replace function fails at the point the collar detaches.

Possible Fix:  have the collar detect if the collar is locked initially and add a temp lock if necessary.

**Comment by zontreck** [comment]
@Medea-Destiny this should go in the revise of the Outfits menu.

**Comment by Aeroxia** [comment]
I just tried adding (nostrip) after .core, trying to stop crucial things from being detached from the detach menu, and that didn't work but it did fix this.  .core still seems to be working (to my surprise), and in fact way better than before - it doesn't remove everything and re-add it every time, it just leaves it on. Even the unlocked collar.

Maybe the help should say to call it ".core (nostrip)" instead? I have no idea if this would break anything else, but so far this is way better.

**Comment by zontreck** [comment]
We do not have a .core folder. Please see http://opencollar.cc for information. You are likely not using official open collar scripts @Aeorxia

**Comment by SilkieSabra** [comment]
.core force rewears everything in the folder whenever Outfits is used to replace outfits.  placing (nostrip) after .core might just mean .core is broken but (nostrip) is working.. otherwise if both were working you'd be wearing duplicates.

**Comment by Aeroxia** [comment]
Well, I'm not wearing duplicates. Without (nostrip) it removes and replaces them, and breaks if the collar isn't locked or put back on manually. With (nostrip) everything just stays on, and the rest changes as you'd expect. I don't know what the code says but that's what's happening.
