### ISSUE TITLE
"Add On" no longer always seen in the "Apps" menu as backwards compatibility

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollarTeam/OpenCollar#183]
What version of OpenCollar are you using? V7.1

What behavior did you expect? add a legacy script using Add on as parent menu name to still show up in Apps menu

What behavior did you see instead? sometime the legacy app would show up in the Apps menu and other times it would not. a "Fix" will always clear it from the Apps Menu

What steps does someone need to take to reproduce the problem?
Drop a legacy script into an unlocked collar see if the new menu item is showing up.

I think now maybe as well as any other time to stop using the backwards compatibility of Add on and Apps as parent menu and just use Apps

**Comment by zontreck** [comment]
We shouldn't drop backward compatibility. Too often i see people give up on a feature because it's too much work to fix it. Instead we need to be looking into fixing the "Add On" translation to Apps and simply make it more reliable.

**Comment by zontreck** [comment]
Fixed in pull request. Please open a new issue if this problem persists when using code from a future release or from git master.
