### ISSUE TITLE
Lock prim does not hide when clicking Stealth in menu

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#184]
What version of OpenCollar are you using?
7.1

What behavior did you expect?
When clicking Stealth in the menu, the whole collar should hide.

What behavior did you see instead?
All of the collar is hiding except for the lock (while collar is locked).

What steps does someone need to take to reproduce the problem?
You might need a copy of RealEvil's Simone Heart Collar.  I have a gift card to his shop that someone can use if they're working on this.

If you use the Settings -> Stealth button in the menu, while the collar is locked, then everything hides except the lock.  But the hide/stealth chat commands work.

I tried adding some debug chat output in the loop inside oc_themes where things get hidden, and that fixed the problem.  So that tells me this is probably a race condition where two different scripts are making llSetLinkAlpha calls, and by slowing down the loop in oc_themes I made it lose the race.  Which makes the thing hide.

I see that oc_sys has its own SetLockElementAlpha function to hide/show the lock depending on whether the collar's locked or not.  But it's supposed to have a global g_iHide variable that, if true, makes it skip any changes.  I think that variable is getting out of sync somehow.

**Comment by Medea-Destiny** [comment]
Line 653 of oc_sys has:
 `g_iHide=!(integer)llGetAlpha(ALL_SIDES) ; //check alpha`

From line 599: 
```
else if (sMessage == STEALTH_OFF) {
                         llMessageLinked(LINK_ROOT, iAuth,"hide",kAv);
                         g_iHide = TRUE;
                    } else if (sMessage == STEALTH_ON) {
                        llMessageLinked(LINK_ROOT, iAuth,"show",kAv);
                        g_iHide = FALSE;
                    }
```
I haven't followed this through yet, but that looks to me likely where the variables are getting out of sync. Setting g_iHide in this way doesn't make much sense to me, as it tries to derive current alpha state from root, which isn't handled in the stealth command anyway.
