### ISSUE TITLE
.aolink timerevent attempting to remove lowercased inventory name

### ISSUE THREAD

**Issue by NaomiLocket** [OpenCollarTeam/OpenCollar#186]
### What version of OpenCollar are you using?
specific file, aolink, any version up to two year old archive and to current. (v4.7)

### What behavior did you expect?
No debug window error messages.

### What behavior did you see instead?
Debug error message triggering on not being able to find missing inventory, "ao link"

### What steps does someone need to take to reproduce the problem?
Attempt to use _a script provided in world_ by another group such as Nanite Systems. They provide the script as "**AO Link**" and the settimer event logic doesn't account for this at all. The issue is triggered on first install due to stateentry timerevent call. Probably not obvious for average users as to "what is wrong". Two poweruser workarounds are to _remove_ the timerevent and its trigger completely and recompile, or _rename the script_ to the expected case sensitive "ao link".

_Please review the "auto update" logic for a not-case-sensitive solution._
Obviously won't fix in world distributions that don't update, but can only do so much and stop expanding it to new sources.

**Comment by Medea-Destiny** [comment]
No longer relevant.
