### ISSUE TITLE
blindfold (gag?) plugin

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#187]
Requested by Gem M.M (Aisha  Marshdevil) in world: "any chance we could get an insanely basic blindfold script out that just alters the windlight setting to a permanent configuration whilst blindfold is worn?"

My thoughts -  we could provide a blindfold and gag plugin which provides windlight-based blinding / semi blinding and speech garbling. This could offer menu access to these features, and also via the hudchannel allow ultra - simple blindfolds and gags to request a blindfolding/gagging service of the collar. 

Questions: Do we rely purely on collar auth for this, or should we allow the external device to do its own auth if the device is worn by the collar wearer?

How basic is good enough? For example we could offer a single on/off for vision and a single garble level, or we could get more extreme and offer multiple garble levels and multiple levels of vision obscuring.

Are there any other features that a plugin like this should offer?

**Comment by GeminiMarshdevil** [comment]
Ohai. this is Gem M.M.
Question1: i suggest we rely on which ever method is most efficient as the intention for "stupid simple blindfold" is not to replace full fledged proper scripted blindfolds from third parties but to simply offer a "free" alternative for those who cannot afford it and to replace the junk free alternatives on the market which cause more lag than good.

Question2: Thee Most Basic of on and off, by top level owner and possibly a lock function within the same menu.   
Example of menu:  (Toggle On/Off), (toggle Lock/Unlock). 
as for the "tiers" of blindness, that can be achieved (if even desired) via settings notecard) if it would be cheaper and ultimately desired, to integrate a third button . it would look like this: (Toggle 0%,50%,100%) 0% being RP friendly-vision un-obscured. 100% being vision totally obscured.

the gag is a distant second focus.  right now the goal is to offer and quick, dirty, but efficient solution to "junk laggy blindfolds" but not impede on the potential for third party blindfolds.

Collar menu integration would also allow the possibility for API functionality for third party blindfolds to have a quick easy way to integrate their blindfolds into the collar.

**Comment by Medea-Destiny** [comment]
Extending the collar API for better integration in general is a longer-term project that perhaps goes beyond the scope of this, though if there are specific things that you feel a basic low-lag blindfold etc. could really use, please do mention them.

As for a lock function in the same menu, the blindfold/gag item would issue a command to the collar saying roughly "I've been attached, please gag/blindfold", and it would be trivial to set a lock on the issuing object for the duration of the gag/blindfold function. It's also pretty trivial for the issuing item to llOwnerSay("@detach=n"); just before chatting the command to the collar. Either way seems pretty straightforward, but it might be good to have collar owners able to bypass the device through the collar -  clicking an unblindfold/ungag button would therefore unlock the item as well as stopping the blinding/garbling.

I know that the Blindfold is a more important issue for Gem M.M (and what she specifically requested) but it seems to me that offering both in one package is advantageous, allowing equally "stupid simple" gags. I have garble code I would be happy to contribute to this, so it's not much extra effort.

**Comment by GeminiMarshdevil** [comment]
I can dig API functionality being post 8.0

Lock and Unlock can be directly tied in with "on and off" and can be bypassed entirely from the collar menu by simply making it in-world clickable, but the advantage of the in-menu buttons is for the self-bondage types. inworld clicking of the seperately worn gag/blind is nice and absolutely advantageous for roleplay. but the importance of the in menu on/off cannot be undersold. 

i cant code. im just here to improve your marketability with easy to achieve, low-effort flippable features.
if you're game for the extra gag, Absolutely it would increase your marketability and the overall appeal of OC as a whole. i see no downsides where the will is present.

**Comment by tamakohan** [comment]
For anyone who simply wants a script you can drop in to your collar to gain blindfold functionality you can try [oc_isolation.lsl](https://github.com/tamakohan/OpenCollar/blob/master/src/collar/oc_isolation.lsl) from my fork which should work just fine in plain OC7.x.

The script also contains a deafener and muffler though all parts are optional. It doesn't give you any visuals but it's meant to be used in conjunction with separate, unscripted blindfold (etc.) objects. A lot of it (perhaps not the blindfold part, it's been a while) is based off the old OC3 OpenMuzzle scripts.

Granted the script currently doesn't distinguish between access levels (public/group, trusted and owner are treated equally, one cannot lock a lower rank out of something though wearer never has access unless self-owned of course), and there's no API that could potentially be used by compatible scripted objects, but it does provide the raw functionality.

**Comment by SilkieSabra** [comment]
Thanks.. long belated to tamakohan.  There are also other third parties making blindfolds.
