### ISSUE TITLE
Meta issue: Improve reporting of auth failure

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#189]
There are a number of cases where reporting of insufficient auth for an option selected is not well handled.

Issue #185 refers to this problem. It was pointed out to me in world by Susannah McMinnar that another is with the "CLEAR ALL" button. The clear function is owner only, but access denied is sent only to the wearer. This is a significant problem. Example:
Someone on trusted list selects a restriction. Later, they hit "CLEAR ALL", expecting the restriction to be cleared. The wearer receives "Access Denied", but no notification of what was tried that access was not allowed for. The person clicking the menu gets no feedback at all, and thus is unaware that the restriction they have set has not been cleared. We should be telling the wearer what that Access Denied message actually refers to, and we should be telling the menu operator when access has been denied.

Please use comments to list any further known examples where auth failure in commands is problematically failing to be reported.

**Comment by zontreck** [comment]
Are there other instances of this issue in the scripts not initially reported here? I'll do my best to sort through the scripts when trying to fix and clarify the access denied message, .. though it would help to know approximately what script these issues are occuring in.

**Comment by zontreck** [comment]
Please test the code that has been updated. This issue should now be resolved.

**Comment by zontreck** [comment]
Closing as resolved
