### ISSUE TITLE
Titler Prim moves on its own

### ISSUE THREAD

**Issue by Ranno** [OpenCollarTeam/OpenCollar#194]
What version of OpenCollar are you using?

    * 7.1

What behavior did you expect?

    * collar creator positions 'FloatText' prim and it stays where it is put

What behavior did you see instead?

    * script reset MOVES titler prim to front of collar

    * titler prim then sticks out and typically blocks touches to collar front

    * * * _IF_ for some reason OC designers want to force it to move, it should move to collar center

   

What steps does someone need to take to reproduce the problem?

    Update a version 3.998 collar to 7.1 with a FloatText prim

**There was a similiar issue reported and to my knowledge this was not addressed with a merged request?

**Comment by zontreck** [comment]
Hi yes i closed that pull request because the one who submitted the pull request did not move the script to it's proper location and since that time there has been numerous commits, one i think even caused a merge conflict with the PR. I have been looking into ways to fix this problem though

**Comment by zontreck** [comment]
Potential duplicate #134

**Comment by Ranno** [comment]
I fixed this issue by commenting out two lines of code in the oc-titler script. The prim now stays where the creator intends it to be rather than automatically moving to be centered on the root prim of the collar. IMO this is a preferable default behavior. see line 96-97

**Comment by zontreck** [comment]
Okay awesome, i'll take a look. If you want and know how to you can always create a pull request too though

**Comment by Ranno** [comment]
never done that, thanks for handling it.

**Comment by zontreck** [comment]
Yep no problem

**Comment by zontreck** [comment]
Duplicate issue: #134
