### ISSUE TITLE
Proposal for improvement - RLV outfits

### ISSUE THREAD

**Issue by tenshilove** [OpenCollarTeam/OpenCollar#195]
As a general principle, I like and approve of the way in which the RLV folders section works; however in my personal opinion the function as it is is a bit like a blunt instrument more than a scalpel: A bit "all of nothing" of sorts. It would be interesting (perhaps a challenge)  if it was possible to strip individual components of an RLV outfit, like old school folder detaches.

**Comment by agesly** [comment]
Can you explain how it would differ from the Folders feature that still exists under the RLV menu?

**Comment by zontreck** [comment]
See new oc_outfits.
