### ISSUE TITLE
Capture able to lock/unlock

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#196]
This is mainly a note for myself when i have the time to fix this issue.

**Comment by SilkieSabra** [comment]
Capture should confer temporary Trusted access plus the exception on autoaccept-tp.  In other words Captors cannot make changes to the access settings or lock/unlock the collar , and Captors have trusted rank on the collar and cannot override owners on the normal ranked settings such as leash.

**Comment by zontreck** [comment]
Verified that capture does actually set temporary owner.  I'll make a temporary variable set under the settings for when capture is active, so that it will just disable the ability to change access or even lock status.  Any script that wants to then deny access to capture can listen for that variable being changed.

**Comment by zontreck** [comment]
Implementation ready for testing

**Comment by zontreck** [comment]
Fixed
