### ISSUE TITLE
Themes / Meshthemes are not very easy for users to set up on their own.

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#198]
The current setup for meshthemes and themes, is that it is generally not very user friendly. Not much instructions on how to set it up, even by reading the script, it's a mess. 

There are also some things not supported directly by these scripts which could be.

My proposal is this:

The notecard format needs to be customizable,
The below format could easily be generated and parsed by a script. We need only have a catalog of what notecards to have the themes script read. And while yes this is a bit long even as a sample, it allows for readability, and for the themes system to be 100% customizable by the end user or by the distributor. 

The idea with the ParentMenu value is that: If that section of the themes menu does not exist, then it should automatically generate the menu button and place this theme under in a submenu.

^^ By allowing for users to make a submenu within themes by just a notecard, is something that i have heard requested regarding other scripts. And if users can make their own configurations by simply clicking a save button and out comes the config, we need to seriously consider allowing these submenus otherwise one single menu will get overloaded.

This idea is very much up for discussion, as this is a draft, and is not the end format. If you have ideas, or suggestions, please don't hesitate to comment on this or to contribute via pull request.

As this is a idea, the format we end up using in the end might be very different as we do also need to keep in mind notecard max lengths.

===========

.themes
Sample.item = require

=========

Sample.item
{
  "ParentMenu": "Sizes",
  "isSubmenu": true,
  "MenuItem": {
    "id": "Sample",
    "links": {
      "1": {
        "id": "OpenCollar",
        "scale": "<1,1,1>",
        "position": "<1,1,1>",
        "faces": {
          "0": {
            "color": "<1,1,1>",
            "texture": "UUID",
            "otherPropertiesGoDownHere": "blah"
          },
          "otherFacesGoDownHere": "blah"
        },
        "rotation": "<1,1,1>"
      },
      "otherLinksPropertiesGoDownHere": "blah"
    },
    "applyImmediately": true,
    "allowSubMenu": false
  }
}

**Comment by zontreck** [comment]
The indentation in the sample item got removed, it was easier to read prior to that

**Comment by SilkieSabra** [comment]
themes/meshthemes is very limited what it can do and these days users expect collars to have the kind of texture change ability that lots of mesh clothing does, and confusing to have both themes and meshthemes in the updater except they are not to be both used.  Anything we can do to make customization more user friendly and expand capabilities would be great.

**Comment by nirea** [comment]
I'm good with unifying the two.

What I don't want is all the complexity of the old appearance system that also supported individually coloring/texturing each prim using menus and chat commands.  I think the complexity cost there far exceeds the benefits.  The meshthemes script was created primarily to be a much simpler alternative.

**Comment by agesly** [comment]
I would be reluctant to save prim positioning and rotation on the theme. I think it should be inherent to the model and not the theme/skin of it.
Also I think it should be well defined how the theme will identify each part: should it refer to each prim with number or description (should we support the user linking other stuff to the collar)?

**Comment by zontreck** [comment]
Well, thats why i wanted to put it up for discussion. And yes. The positioning and rotation data would need to be object specific,. And for detecting which link, i'd say in order to save space in the notecard, it would just count the length of description and perhaps place the actual prim name?  I dunno, i personally think that it should have the ability to run through the positions and such for those that want to save their collar position, sizes, etc.

**Comment by agesly** [comment]
Saving position and size seems to me like a different feature. Like wanting to save size/position presets for different avatars the user uses. Themes are just textures and colors IMHO.

**Comment by zontreck** [comment]
I suppose, it may seem like a different feature, but we're looking at entirely implementing a rewrite of themes in order to bring all the customization options people want. There could be menus for apply different parts, but i dont want to exclude something since i've heard people asking for position, scale, and rot to be in themes. Now, granted that its more complicated to do this than people realize, and they usually will group position and rotation in a single word, that being position.

**Comment by agesly** [comment]
What is the use-case would it be trying to cover by adding position/rotation/scaling to the theme system?
Having a different theme change the position of elements attached to the collar (like a led lights or padlocks)?

**Comment by zontreck** [comment]
Use case: Someone accidentally rotates, or scales the object wrong or it is no longer in the right position. The proposed apply button under themes could reset it back to the user's preferences, or to the maker's defaults if the user customized it and wants it back to how it came originally without swapping to a new collar and redoing all their settings.

**Comment by zontreck** [comment]
Incase it wasn't clear.. i'll clarify.. the theme app menu would contain several submenus where the actual themes could be located. When you get to a theme item, and not a submenu containing lists of themes, it should contain buttons along the lines of: ["Size", "Position", "Rotation", "Colors", "Textures", "TextureEffects", "All", etc]., Where each button would apply the contents of that to all linked prims that contain that value. And the json could always be modified to exclude something, and if it's missing entirely from the json, the button list should adjust to only show what is supported by that theme.
