### ISSUE TITLE
Posture button missing

### ISSUE THREAD

**Issue by Ranno** [OpenCollarTeam/OpenCollar#200]
What version of OpenCollar are you using? 

7.1

What behavior did you expect?

open the anims menu and 'posture' button appears along with the other choices

What behavior did you see instead?

no posture button present in the menu

What steps does someone need to take to reproduce the problem?

create a new collar in a new prim using the collarizer and the 7.1 updater

Possible solution:

The 7.1 updater does not contain the ~stiff animation. Adding the ~stiff animation to the animator prim manually resolves this issue.

The updater should be updated to include the ~stiff animation in order to restore full functionality.

**Comment by zontreck** [comment]
We can certainly look into this.

**Comment by zontreck** [comment]
@nirea Can we make this a planned change for the next update?

**Comment by SilkieSabra** [comment]
My memory is that the animation we were using for ~stiff has a flaw that makes a spread hands effect. So we would need a new animation to replace the Posture setting.

**Comment by zontreck** [comment]
I don't remember the hands being spread with the stiff animation.. I'll check an older collar though.

**Comment by zontreck** [comment]
No the old ~stiff animation does not have spread hands, but it is possible that v3.9+ ~stiff did. I tested the stiff anim from 3.501 and below.

**Comment by zontreck** [comment]
Closing issue, with the posture animation being added manually this problem is resolved. Can discuss adding a new posture animation for the next release
