### ISSUE TITLE
Repository is missing many BVH animation files.

### ISSUE THREAD

**Issue by Tynach** [OpenCollarTeam/OpenCollar#203]
This GitHub repository is missing *many* of the .bvh animations from the OpenCollar project. Right now, these are the bvh files which are available here in this repository (not counting the .avm files that accompany many of the .bvh files):

```
cuffs_back.bvh
cuffs_front.bvh
kneel.bvh
lying_on_back.bvh
lying_on_belly.bvh
nadu.bvh
oc_ground01.bvh
oc_ground02.bvh
oc_sit_girl01.bvh
oc_sit_girl02.bvh
oc_stand_boy01.bvh
oc_stand_boy02.bvh
oc_stand_boy03.bvh
oc_stand_girl01.bvh
oc_stand_girl02.bvh
oc_stand_girl03.bvh
shy.bvh
stiff_neck.bvh
submit.bvh
table.bvh
~foot-bottom.bvh
~foot-top.bvh
~hug.bvh
~jump-bottom.bvh
~jump-top.bvh
~run.bvh
~walk_Female.bvh
~walk_Male.bvh
```

On the other hand, these are the animations which are listed within the collar itself:

```
back
beautystand
belly
booty
bop
bracelets
cutie
display
doggie
kneel
nadu
rise
shy
submit
table
tower
~catch
~cling
~foot
~good
~hips
~hug
~kiss
~leap
~nom
~pet
```

And these are also in the collar, if the collar was upgraded from a 6.x or 4.x collar (from before splitting from VirtualDisgrace):

```
~run
~shock
~stiff
~walk_Crawl
~walk_Female
~walk_Male
~walk_Pony
~walk_Worm
```

There are many that are in the collar, that aren't in this repository; and there are quite a few (mostly AO ones) that are are *not* in the collar, but *are* in the repository!

Not only that, but the AO itself contains a different set of animations, most of which are not anywhere else:

```
legacy_crouch
legacy_ground01
legacy_ground02
legacy_ground03
legacy_ground04
legacy_ground05
legacy_ground06
legacy_run
legacy_sit_boy01
legacy_sit_boy02
legacy_sit_boy03
legacy_sit_boy04
legacy_sit_girl01
legacy_sit_girl02
legacy_sit_girl03
legacy_sit_girl04
legacy_sit_girl05
legacy_stand_boy01
legacy_stand_boy02
legacy_stand_boy03
legacy_stand_boy04
legacy_stand_boy05
legacy_stand_boy06
legacy_stand_girl01
legacy_stand_girl02
legacy_stand_girl03
legacy_stand_girl04
legacy_stand_girl05
legacy_stand_girl06
legacy_stand_girl07
legacy_stand_girl08
legacy_stand_girl09
legacy_walk01
legacy_walk02
legacy_walk03
oc_ground01
oc_ground02
oc_ground_marine
oc_run01
oc_run02
oc_sig_girl01
oc_sig_girl02
oc_stand_boy01
oc_stand_boy02
oc_stand_boy03
oc_stand_crawl
oc_stand_girl01
oc_stand_girl02
oc_stand_girl03
oc_stand_marinepony
oc_stand_worm
oc_walk01
oc_walk02
oc_walk_crawl
oc_walk_marainepony
oc_walk_worm
```

I have been unsuccessful in my attempts to find most of these animations in any source code repositories I've looked in. Right now, I'm only able to find the files created by Wendy Starfall and Toy Wylie. I also cannot find them in any earlier commits, even commits from 2015 and 2016.

**Comment by zontreck** [comment]
@nirea can this be looked into or is there a reason why not all animations have the BVH files on the github?

**Comment by Tynach** [comment]
I don't believe there should be a reason to omit the BVH files. The .license file within the AO itself lists that many of the missing ones *should* be under the Creative Commons Attribution-ShareAlike 4.0 International Public License. Other missing ones should 'include attribution' to the author, or are said to be public domain. The entire clause (modified slightly by me in an attempt to preserve formatting):

> 5. Animations:
> 
> > a. To the best of Our knowledge, the animations included in Default OpenCollar and the
> > OpenCollar AO which were created by Damien Fate, Dyonis Blanc, Indika Herbst, Roenik Newell,
> > Solari Hayashida, Darien Caldwell, Whinge Languish, Twitch Misfit and Antoinette Lioncourt are
> > in the Public Domain and may be used without restriction.
> > 
> > b. The animations created by Arcane Gothly, Ilse Mannonen, Marine Kelley, Nadja Gufler, Nandana
> > Singh, Creamy Cooljoke, Stephe Ehrler, Garvin Twine, Madison McHenry must remain FULL PERMS and
> > attribution (e.g. this License Addendum) must be included.
> > 
> > c. The walk motions by Vanish Firecaster must remain FULL PERMS and include attribution to the
> > original Author.  In case modifications were made, these must be stated and noted.
> > 
> > d. The animations created by Wendy Starfall and which are either derivative works of Linda
> > Kellie Henson's resource or original creation, as well as the animations created by Toy Wylie,
> > Vasa Vella, including uploaded animations by those creatores from uploaders MissSpoken and
> > OpenCollar Organiser are licensed under a Creative Commons Attribution-ShareAlike 4.0
> > International Public License (https://creativecommons.org/licenses/by-sa/4.0/legalcode) and must
> > remain FULL PERMS.

**Comment by nirea** [comment]
In the early days, many anims were donated or used from widely-circulated freebie packs purely inworld, without having BVH sources.  That would be pretty much everything in the 5a category from Tynach's quote.

I seem to have lost the BVHs for some of the ones I made as well.  Sorry. :(

**Comment by Tynach** [comment]
Understandable, @nirea. It's been a long time, and files can get lost relatively easily; I know I've had important files (even ones I've backed up in multiple places) slowly disappear without me realizing, it until all copies are gone.

Obviously it would normally be considered bad to even suggest this, but since the licenses are known, would it be possible to extract the files from what is sent to/cached by the viewer? I'm not sure if animations are cached like textures are, but if so perhaps they can be extracted from the cache files?

**Comment by zontreck** [comment]
While it is possible to do so.. Extracting those animation files would break linden tos. That is why legal viewers do not offer the functionality.

**Comment by tenshilove** [comment]
The animations in my fork attempt to be a more static alternative to the ones in the collar especially doggie which is meant more as a puppyplay pose rather than an animation. I know there's some issues with at least one of my animations, I'll work on those and when the issues are solved I'll update the bvhs.
