### ISSUE TITLE
Maximum leash length, increase?

### ISSUE THREAD

**Issue by Neceh** [OpenCollarTeam/OpenCollar#204]
I noticed that the maximum length of a leash is 20 meters, in pony play there are whip circles that require 25 or even 30 meter distance to work properly. So I'm requesting a longer option, or a custom button with a dialog box where you could set the amount of meters in.

**Comment by zontreck** [comment]
Hi! For some reason it does appear that the max leash length even when using the <prefix> length <number> command, is 20 max. I can look at fixing this

**Comment by zontreck** [comment]
Resolved in git master: src/collar/oc_leash.lsl
