### ISSUE TITLE
Missing link from Firestorm to non-extant OpenCollar Attachment Protocol page

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#205]
While trouble-shooting the Firestorm AO for someone using OpenCollar poses, I discovered that the Firestorm wiki has an old link to an OpenCollar Attachment Protocol page from our old wiki that redirects to opencollar.at.  Page is here: https://wiki.phoenixviewer.com/fs_controlling_ao_w_scripts . I can file a JIRA to correct this but would better have a page to replace it.  I found the original here http://code.google.com/p/opencollar/wiki/OpenCollarAttachmentProtocol but it is part of developer documentation that was taken down and has not been replaced.  Can we give them a page? Do we need to replace the entire suite of developer documentation?

**Comment by zontreck** [comment]
Might be a good idea to put new developer documentation up and a jira should be filed with Firestorm to get the link pointing the the right domain

**Comment by zontreck** [comment]
The page was edited by StarWolf2000 to point to OpenCollar.cc, we can write up the attachment protocol docs and put it up on the site there. The issue is closed though since it no longer points to the .at domain
