### ISSUE TITLE
Collar update available message is not specific

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#206]
After checking the scripts for what the update available message is, it appears it does not specify what version is available, nor where to obtain it from. 

Will make a file in the github containing the update_available message so we can customize it.  And will make the oc_sys script pull the message if the version installed does not match the master branch.

**Comment by Medea-Destiny** [comment]
I have a script for reading a page from github to check for updates already if that would help. 

I suggest we have an update_check page on the git which has two lines, the first being current version number, the second in the format MOTD ver num~MOTD. Get the page on rez, check version number compared to current and put an UPDATE AVAILABLE message in main menu if current version is lower. Also check and store MOTD ver num, llOwnerSaying MOTD if MOTD ver num is higher than currently stored (preferably with a short delay so it doesn't get lost during log-in spam) so we can use that as a way to pass on info when needed.

**Comment by zontreck** [comment]
oc_sys already reads from github, i just would need to add a secondary request or change the file formatting

**Comment by zontreck** [comment]
I discovered a bunch of issues when digging through oc_sys pertaining to github data calls, i'm fixing those up before i make a PR and merge.
