### ISSUE TITLE
Fix menu's doesn't do re-menu

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#213]
What version of OpenCollar are you using?
7.1

What behavior did you expect?
Menu dialog re-appearing after selecting Fix from the Settings menu.

What behavior did you see instead?
No menu dialog.

What steps does someone need to take to reproduce the problem?
Attach (clean, new) collar, touch collar, select Settings from menu, select Fix.

Fixing the menus is a neat feature that someone may use just because he/she believes the menus need to be rebuilt, usually because some of the buttons (apps) is not showing. After this fixing, you obviously want to go back to see the button has reappeared and then use it, yet you need to touch the collar first.
As a collar user, I find that confusing and not intuitive.

**Comment by zontreck** [comment]
This is can be reproduced on git master. Will fix.

**Comment by zontreck** [comment]
I should have a fix for this in the next few hours.

**Comment by zontreck** [comment]
Closing this as resolved.
