### ISSUE TITLE
Change Request: Make LINK_* lower/camelCase

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#216]
As an OC (plugin) developer,
I would like to see the global LINK_* integers in lower/camel-case and outside of the Message Map,
So that it is less confusing that those globals are NOT constants and NOT meant to be used as message nums.

For example:
rename LINK_AUTH to g_iLinkAuth

**Comment by zontreck** [comment]
The LINK* values are essentially a constant. After being set at collar boot, they never change.

**Comment by zontreck** [comment]
Besides.. in your own plugins nothing stops you from changing the variable names.

**Comment by Tuco-Solo** [comment]
There might be developers that disagree. For example, in oc_sys, in link_message event, one can read:

       } else if (iNum == LINK_UPDATE) {
            if (sStr == "LINK_AUTH") LINK_AUTH = iSender;
 
Therefore, LINK_AUTH would better not be considered a constant.
Also, it is listed in "Message Map", which can be confusing too. Moving it to something like "Link Number Map" could be more intuitive about it is and how to use it.

I agree that independent scripts like plugins can have their own naming scheme, but one could expect to have all naming be consistent, for maintainability purposes.

The head of the 'issue' reads Change Request, but it's more like a suggestion. As a (new) developer who tries to understand all OC code this is one of the things that other new developers could benefit from, that's all.

**Comment by zontreck** [comment]
I'm aware. That is why i said they are constant after initial boot up. They get assigned once, but never changed again afterwards.

**Comment by zontreck** [comment]
@nirea Your thoughts?

**Comment by nirea** [comment]
I like leaving constants in all caps, but I can see that LINK_AUTH isn't quite a constant.  No strong feelings about how it's capitalized.

**Comment by Medea-Destiny** [comment]
No strong feelings here either, but I see Tuco's logic.

**Comment by zontreck** [comment]
yea i definitely can see the logic, though it does still appear to be a constant. The only reason it gets initialized to a value in link_message() is because the locations of the scripts is not known nor hard coded.  But those locations never change during operation of the scripts. They stay there or else the other scripts will need to be rebooted and have menus fixed.  Reboot would be necessary in order to get the settings all sent back out properly.

**Comment by zontreck** [comment]
This issue can now be safely closed as all the scripts in linked prims have been moved
