### ISSUE TITLE
Change request: Start auth lists with 1

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#217]
As an OC 7.1 user,
I would like to see lists start with 1 when adding and removing residents from auth lists
So that is is more like "this first entry in the list has number 1".

(As a developer: I know, 'we' usually start with 0 when iterating, but an end user that has never scripted, it does not make much sense.)

Just a small thought. ;-)

**Comment by zontreck** [comment]
This is mostly a limitation of LSL and many other programming languages. The language itself starts the list off at 0.  In order for us to start the list at 1, we would have to pad the list with a single garbage entry, and its just not worth the effort, say someone sends back a list to auth then that doesnt include the garbage, then the item in position 0 gets dropped.

**Comment by nirea** [comment]
Is this in a menu or chat output?

If the menu, I think we can consistently just do 1-based numbering there (we might already).
