### ISSUE TITLE
Changes to Relay behaviour

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#219]
The relay respects the collar's owner/trusted/tempower lists. This currently has some somewhat odd side-effects.

1.If you have landowner trusted, should you be vulnerable on your own land? My feeling is not and my proposal is that in this case the collar behaviour should revert to ask mode. This maybe is something that should be switchable though.

2. When in ask mode, the collar will not give you a yes/no dialogue if the relay is used by an owner. Sounds sensible. However, this is currently extended to the owner of an object hitting the relay. Suppose you are self-owned, should you be unable to have ask mode active on your own objects? Clearly not.

3. Extension to above: if the owner of an object is an owner of a collar, should we always trump ask mode? I don't believe so. Someone else using their rezzed item would bypass the ask mode of your collar. I propose that we only bypass based on the owner of the object if that owner is actually in the sim at the time.

Fixes are here:   #218

Any objections?

**Comment by zontreck** [comment]
If no objections are raised in say... 48 hours lets get this pushed into the master branch. This way it could get included in the Beta and thus 7.2 when we release it. No concerns were raised regarding the Alpha yet. I'd still like to ask @nirea though for thoughts also on it, but this could easily get included with 7.2.
