### ISSUE TITLE
Non-owner can promote themselves to owner through Cuffs App

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#223]
What version of OpenCollar are you using?
7.2 RC3

What behavior did you expect?
Non-owner not being able to add themselves as owner

What behavior did you see instead?
After visiting the Cuffs App, got the ability to add owners, including themselves

What steps does someone need to take to reproduce the problem?
Non-owner touches collar, Apps -> Cuffs -> BACK -> Access -> + Owner
This valid for the same dialog session. if dialog times out, or avatar touches collar again, the procedure has to be repeated.

Some debugging info:
Upon selecting Cuffs in the Apps menu, the auth level is is still CMD_EVERYONE. Then, selecting BACK (triggering command "menu Apps") the level is CMD_OWNER.

This test was repeated with the Bell app, which did not seem to have this behavior.

**Comment by SilkieSabra** [comment]
Tuco, you don't say if the non-owner was the wearer or what level of access the "non-owner" had?

**Comment by Tuco-Solo** [comment]
non-owner was completely unknown to collar

**Comment by zontreck** [comment]
OK Adding bug label will look into it later
