### ISSUE TITLE
Feature request: Organisation of Detach menu

### ISSUE THREAD

**Issue by MinesweeperM** [OpenCollarTeam/OpenCollar#226]
Greatings!
Talking about v7.2.
Default order of items in Detach menu, determined by the order in which attachments were put on.
Sometimes this leads to confusion in the menu, as on the first screenshot, and makes it difficult to find the needed attachment.
![Before](https://user-images.githubusercontent.com/11153846/61314987-7c49eb00-a806-11e9-90be-a91f3f4c86f5.jpg)
My first idea was to create virtual folders in menu, to put attachments with similar names in, but it seems to make some difficulties and ugly solutions in coding (or not?), so we can just put a string 
`lButtons = llListSort(lButtons, 1, TRUE);`
between lines 262 and 263 in oc_rlvsuite, and get a prettier list, as on the second screenshot.
![After](https://user-images.githubusercontent.com/11153846/61315396-55d87f80-a807-11e9-9f09-e6c4dda13abd.jpg)

**Comment by zontreck** [comment]
This fix is being tested now

**Comment by zontreck** [comment]
Implemented as of commit 6b5b7fc
