### ISSUE TITLE
oc_capture broken with TRUSTED change

### ISSUE THREAD

**Issue by RayZopf** [OpenCollarTeam/OpenCollar#227]
What version of OpenCollar are you using?
7.2

What behavior did you expect?
'capture release' command working
getting the correct menu with button 'Release'

What behavior did you see instead?
after capturing one still gets a capture yes/no menu
'capture release' silently fails

What steps does someone need to take to reproduce the problem?
capture a wearer and try to release via command and menu

Fix with annotations and further questions attached
[oc_capture.txt](https://github.com/OpenCollarTeam/OpenCollar/files/3414895/oc_capture.txt)

**Comment by SilkieSabra** [comment]
I was able to duplicate this issue with the following steps:

Expected: Using OC 7.2, when capture is active, a non-owner captures the wearer then issues [prefix] capture release as instructed in the capture text.

What happens:  Capture release does not result in release

To duplicate.

1. Wearer sets capture on.
2. User with no other means of access captures wearer.
3.  User types [prefix] capture release
4.  Wearer sees she is still captured.
5.  User attempts to open the capture menu again and gets the capture start menu, not the release menu.  User receives request to capture and this time declines.
6.  Wearer presses Capture again and this time gets the Release button meant for the user.

**Comment by RayZopf** [comment]
after checking again, it is afaik right that the wearer while beeing captured gets the 'Release' button too
the wearer then just is blocked from using the release command

**Comment by zontreck** [comment]
Fixed - Will release a 7.3 update shortly
