### ISSUE TITLE
[Feature request] cmd or .settings cmd to disable outfits but not RLV or relay systems

### ISSUE THREAD

**Issue by GeminiMarshdevil** [OpenCollarTeam/OpenCollar#229]
the ability to disable the entire outfit system, but not the Relay or RLV systems.
a simple cmd or settings config method would suffice. no need to go mucking about in LLdialog or the rest of the systems.  

i did this manually once before with the 7.1release by //commenting out a few sections in different scripts but if i could just enter a .settings line cmd to disable outfits, that would be great ^_^

**Comment by Medea-Destiny** [comment]
Note: I am targeting a major overhaul of outfits for the clothes handling rewrite for 8.0, so it's not worth putting much effort into tweaking stuff until then.

That said, there's a very simple approach to this, which is to have the [oc_rlvsuite ](https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/collar/oc_rlvsuite.lsl)check whether #rlv/.outfits is set up, and only add the outfits button if so.

**Comment by JaynaDover** [comment]
The VD style outfits system is quite non-intuitive, and flat (no subfolders) meaning that at best you can have perhaps 20-30 outfits before it becomes an awkward mess. It also makes it impossible to do stripping properly - it's an all or nothing style system. Can someone please explain why they think Outfits is better than just navigating to an #RLV/outfits folder tree? While the existing #RLV folder browser could certainly use some love to get things modernized, going to a completely unique "incompatible with EVERYTHING else" based system just doesn't seem like a positive move.

**Comment by zontreck** [comment]
This is no longer relevant as both outfits and detach are optional apps.
