### ISSUE TITLE
Capture still broken in 7.3

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#233]
As reported by Linda (Chylin) in group, capture only works when public access is on. 

The problem is that usercommands are only passed when auth equals or exceeds CMD_EVERYONE. When public access is on, strangers will be passed with CMD_GROUP, but when it's off they are passed with CMD_NOACCESS and will not get the capture menu. 

#232 updates by passing CMD_NOACCESS for the appropriate string ("capture Tempowner~[key]") which seems to fix this issue.

Thanks to Linda for the report and helping test.

**Comment by Medea-Destiny** [comment]
Point of discussion: do we need to do another release? People are getting confused with rapid releases, but I think this is a showstopper for capture and propose a 7.3.1 release rather than a 7.4, to let people know it's a small bugfix.

**Comment by Medea-Destiny** [comment]
Okay, apparently this is intentional behaviour and I've missed #228 . It didn't occur to me that this is intentional because I'm mystified about what the point of capture is when public access is on anyway!

**Comment by zontreck** [comment]
Closing as duplicate issue of #228
