### ISSUE TITLE
Load from .settings card only retrieves first three owners listed

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#234]
What version of OpenCollar are you using? 
7.3

What behavior did you expect? 
When loading settings from a notecard, I expected it to load all owners listed in the notecard

What behavior did you see instead? 
The collar loads only the first three owners from the notecard and then skips all others

What steps does someone need to take to reproduce the problem?
Place a .settings notecard in the collar with more than three owners specified, then load settings from within the collar

**Comment by zontreck** [comment]
Hi! What prim did you place .settings in? And did the settings line end up being longer than 255 bytes?

**Comment by boundtight** [comment]
.Settings was in the Settings prim, the line was 218 characters (bytes) long

**Comment by RomkaSwallowtail** [comment]
settings have a limit on the number of owners, trusted and blocked.
max owners = 3 , max trusted = 15 , max blocked = 9 ; all that is more is ignored.
(in settings.lsl lines 232-251)

**Comment by zontreck** [comment]
Yea i just looked at that segment of code... Thats gonna need some rewriting to move that part of the logic into oc_auth, it should be a limit of 28 entries, period, so you should be able to have say, 19 owners, 8 trusted, 1 block. Just as a example.

**Comment by RomkaSwallowtail** [comment]
I don’t understand how many owners of one slave can be?
it seems to me pointless!

**Comment by zontreck** [comment]
Perhaps to some it would seem pointless. But it's not supposed to be a fixed limit on either 3 of the settings. It's supposed to just be a cap of 28.

**Comment by zontreck** [comment]
@nirea your thoughts? 

I know we are redoing settings from virtually the ground up for v8 and so the limit would be drastically increased, but I'm wondering, is this intentional at the moment?

**Comment by RomkaSwallowtail** [comment]
increasing the access limit requires more memory,
maybe it makes sense to move noteсard and URL loading functions from oc_settings script into separate script in the root prim?

**Comment by zontreck** [comment]
I didn't say the current design would allow increasing the access limit. After the rewrite yes the limit will be increased. But at present time no, the limit will remain at 28. What it should be though is 28 total. It shouldn't be specifying how the 28 is divided up

**Comment by zontreck** [comment]
This has been resolved in the latest commits.

New settings token type has been added for advanced configuration

```
AUTH=owner~<uuid>,<uuid>,<uuid>,<uuid>
AUTH+owner~<uuid>,<uuid>,<uuid>,<uuid>
```

This lets you add as many owners as you want without worrying about the notecard line limit. Additionally the strange limitation of 3 owners has been removed.

Also worth noting is the optional toggle to disable automatically adding a comma in the append mode:

```
SETTINGS=nocomma~1
AUTH=owner~<uuid>,<uuid>,<uuid>,<uuid>
AUTH+owner~,<uuid>,<uuid>
```

Note how i manually added a comma in that second example after the tilde. That example had automatic commas disabled.
