### ISSUE TITLE
Settings notecard in root prim is not reread after changing it and is not found when Load is requested.

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#237]
In Version 7.3,

The release notes say:
"Added a .settings notecard relay. Enables placing .settings into root prim instead of only in the Settings prim
As of 7.2 RC3 / Full Release, if the .settings notecard is not changed, reboot not requested, or load not requested from Settings, the .settings will not be relayed if it has already been read- This is to avoid unnecessary link messages."

From this the expected behavior would be that if the .settings notecard is loaded in the root prim, and *is* changed, the notecard will be reread upon a load request, relog, or reboot, or take and rerez.

I loaded a .settings notecard with AUTH=public~1 and other settings, onto a notecard named .settings, and dragged it into the contents of the root prim of a V 7.3 collar.  The settings loaded. But when i deleted the setting AUTH=public~1 and pressed Load in the Settings menu, it returned the message "No .settings to load found."  The changed setting did not load.  I repeated all tests with a collar rezzed on the ground, and while wearing it on my collar test alt.

To reproduce: 

1) Load sample settings printed on a .settings notecard into the root prim of a V 7.3 collar.  The settings will load.  

2) Make a change to the settings and save.  

3) Press Load in the Settings menu.  The collar returns "No .settings to load found" and the settings are not changed.  

4) Repeat steps 1 and 2.  Take and rerez.  Same result.

5) Repeat steps 1 and 2. Relog while collar is worn.  Same result.

6) Repeat steps 1 and 2.  Send reboot command to rezzed collar.  Same result.

**Comment by zontreck** [comment]
Cannot reproduce.  Settings behavior is intentional. Although the no settings notecard line may need to be revised to say: No .settings found in <settings prim name here>
