### ISSUE TITLE
Stack Heap Collision in oc_rlvsuite

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#241]
Issue created by: Silkie Sabra

on two occasions users have reported a stack heap in rlvsuite, most likely happening when the attachment cap on the avatar is reached and there is one item in the queue to be attached, as reported by one of the two users.  Could it also be very long attachment names?  Needs more testing to duplicate the error.

**Comment by SilkieSabra** [comment]
I posted this issue using opencollarangel, it shows under aria's github handle.

**Comment by opencollarangel** [comment]
Comment from Tashia Redrose
 
Yea we should look into this

**Comment by SilkieSabra** [comment]
Another case came up, this time the avatar had 30 out of 38 attachments worn, but several of the names were very long, example:  "GENUS Project - Genus Head - Classic Face W001 - v1.6 - Mocap".  The item can't be renamed.

**Comment by zontreck** [comment]
I believe a new version of rlvsuite is in the works. Once it is completed the issue can be closed
