### ISSUE TITLE
Remove All Trusted searches for Nobody

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#245]
OpenCollar V 73

Remove All Trusted should remove only those listed as Trusted.
Instead it searches for a zero string and returns:  "Nobody" is not in Trust List where "nobody" is the string 00000000-0000-0000-0000-000000000000 .
To reproduce, add more than one avatar to Trust and then select Remove Trust > Remove All

**Comment by Medea-Destiny** [comment]
I hate Auth.

I think this may be failing on line 212 if g_iGrantRemoval = TRUE. This will be the case if self ownership has been explicitly removed. There is no handling for "remove all" command when g_iGrantRemoval=TRUE. Nor is there any good reason I can see for using g_iGrantRemoval at this point. I think it's a clumsy way to try to handle permissions.

**Comment by zontreck** [comment]
Fixing this issue now. Was able to repro it

**Comment by Medea-Destiny** [comment]
Line 496, else if (llToLower(sTmpID) == "remove all")  <- sTmpID will be "Remove" not "Remove All", so it then gets treated as a name in line 502
