### ISSUE TITLE
Suggestion: allow attachments more interaction with OC

### ISSUE THREAD

**Issue by DarkDonja** [OpenCollarTeam/OpenCollar#252]
Hello,

as a collar user and attachment developer,
I would like to use more OC features from other attachments
to reduce the amount of worn collars per avatar.

### My Problem

Some people wear an opencollar (e.g. 9.3) around their necks. Then the dominant comes with a wonderful clit ring and wants the sub to wear (e.g. with an old 3.x opencollar inside) because of the leash functionality. And then another item with another full suite of opencollar scripts. And it gets more and more laggy and more and more different prefixes need to be used and so on... A friend of mine is wearing 3 different complete OCs...

Well, I know that one can use the OC owner system from attachments to authorize users (sending messages with "OpenCollar?" and "AuthRequest" and so on, oc_com lines 441 and 449) and already use it in some of my builds.

As far as I can see, this only supports the handshake and authentication, but nothing else.

### I dream about functionality like:

- an attachment (e.g. nose ring) sends a command to the OC to use the OC's invisible leashing functionality. The collar cares for following the leasher, but doesn't emit chain particles. The chain particles are sent from the nose ring (maybe with settings from oc_particles). So the script inside the nose ring could be rather simple.
- using oc_dialog also from attachments?
- an attachment wants to set some RLV restrictions and could ask the OC to care for them. Ok, one could send the commands to the OC RLV relay, but having a central RLV handler would make it easier.... maybe with a redesign for RLV/Restrictions or the like.
- accessing OC settings (maybe readonly) from attachments, e.g. owners, RLV status, ...

Something like this could reduce the amounts of collars per wearer a lot, especially when there are some template scripts for attachments, e.g. a drop-in leashing-script or whatever.

### Some ideas of how to implement

One would need a little communication protocol between attachments and the collar:

- one way could be to make oc_com more open and versatile, e.g. by adding a big "else-Block" to oc_com (between line 451 and 452 which handles these requests)
- another way could be to create create an OC plugin similar to the one to the cuffs which has an own communication channel.
- or are there other interfaces I am not yet aware of?

But oc_com already cares for communication very well, and in my eyes, all communication should run over this already existing channel.

### Question

I am willing to put effort into implementing this, but before, I would like to ask you for your opinion:

- What do you think about this idea? (I can't be the first that thinks about something like this)
- What are possible ways to develop this?
- Do you know if somebody already implemented this? are there additional interfaces? maybe one could work together?

Thanks for reading.

Best regards

Donja (DarkDonja Resident)

**Comment by zontreck** [comment]
Well your example version i'm a little confused by.. We don't have a 9.3. But, v8 is planned to have a extremely flexible attachment API.

**Comment by zontreck** [comment]
The API for v8 is already being written as we continue to fix bugs in the existing scripts.

**Comment by DarkDonja** [comment]
sorry, 7.3, of course. really cool, zontreck. can I help somehow?

**Comment by zontreck** [comment]
I am still writing up the specs for the API. I've written a few sample scripts for concepts but none have proven to be easy to use nor easy to develop for. So i'm still experimenting at this time. There is not any finished script that can be edited or patched at the moment. Once a final revision of this API exists it'll reside on this github and can be contributed to. 

There are a few requirements for this API as the idea currently stands (The following is subject to be revised at any given time, this is not a final product)

* Be easy for new developers to adopt
* Be backward compatible with older scripts
* Allow OC scripts to reside in any attachment
* Allow plugins or attachments, to "listen" for any menu button path being activated
* Allow plugins or attachments to "listen" for a specific setting being changed by a script
* Allow attachments to save settings to oc_settings, as well as to read said settings

In addition to the above, a goal with the API will be to have a "replace" feature as well.. So for instance- Say you have two relays, then a attachment or plugin can send an API call and redirect the "Relay" button to go to the new destination script. Scripts will have to handle the replace feature independently. So for the relay example, the relay portion of the code will deactivate itself and stop listening for RLV commands. (This is just an example)

All in all- This is going to be both a plugin API and a attachment API all in one. We want it to be easy to use, but also seamless.  All the things you have indicated above with what you'd like to see, we hope to accomplish with this upcoming feature.

**Comment by zontreck** [comment]
See latest code in the attachments folder. Let me know if those solve your issue

**Comment by zontreck** [comment]
This has now been fully resolved with the implementation and upcoming OC version 8.0.

Please see oc_api for the (currently) undocumented Addon API.
