### ISSUE TITLE
Request for community input: Capture Rewrite

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#266]
As was mentioned in the main OpenCollar group inworld earlier, I'm working on a rewrite for capture. 

This ticket will be used to track community input.

Either IM Aria (Tashia Redrose) directly, or post your comments in this ticket.

The specific question being asked of the community is: How should capture work in your eyes?
==========

If you are not familiar with the current capture script, please check out the Capture menu in a current version of OpenCollar. `oc_capture.lsl` must be installed in the collar for this menu to appear!

*This ticket will be closed and capture will be rewritten on/around 12/2/2019*

**Comment by zontreck** [comment]
Community input from yesterday 11/24/2019
===

Total mentioning something along these lines: **2**

A feature that would allow for some type of non-instant capture.


*This could be potentially implemented using two modes, the standard click / chat command to capture with no requirement to be within a certain distance for `x` seconds. The second mode could potentially require the person trying to capture to remain within 5m or so for 10 seconds. These values may be customizable.*

**Comment by lillith-xue** [comment]
My opinion to oc_capture:
Capturing should work when the Collar is not set to public. In public mode, random people already have access to the Collar. 

- There should be a setting to Enable/Disable the dialog asking the wearer on capture.
- A timer to automatically free the wearer after a certain time, for when the captor forgets about it
(if the captor is not in the same region for a certain time free the wearer?)
- disable oc_capture when the collar is set to public, it makes no sense everyone already has access
- disable self owned while captured
- some settings to specify what can be accessed by the captor

**Comment by zontreck** [comment]
Due to a lack of responses, Capture will work as it presently does except that it'll be fixed to work without public enabled.
