### ISSUE TITLE
Suggestion: Remove oc_rlvcmd, oc_rlvstuff and oc_garble

### ISSUE THREAD

**Issue by lillith-xue** [OpenCollarTeam/OpenCollar#282]
oc_rlvcmd and oc_rlvstuff look like doing the same as oc_rlvsuite + oc_rlvextension
a simple garble function is also included in oc_rlvextension

also remove oc_undress?

**Comment by Medea-Destiny** [comment]
oc_undress will be redundant too with the clothing thing I'm doing.
