### ISSUE TITLE
Capture plugin ignores far touch limit

### ISSUE THREAD

**Issue by SharieCriss** [OpenCollarTeam/OpenCollar#295]
What version of OpenCollar are you using? 7.4 RC1

What behavior did you expect? When the toucher is beyond 20m range and the collar is range limited, the toucher should not get ANY menus.

What behavior did you see instead? Toucher was allowed access to the capture menu

**Comment by zontreck** [comment]
Any auth requests should be going through oc_auth. So the range limit should be getting honored for both chat commands and menus. I'll take a look into this. I shouldn't need any more information.
