### ISSUE TITLE
[HELP WANTED] Leash disconnects randomly in high-lag regions

### ISSUE THREAD

**Issue by SharieCriss** [OpenCollarTeam/OpenCollar#296]
What version of OpenCollar are you using? 7.4 RC1

What behavior did you expect? Leash should stay visible and enabled

What behavior did you see instead? In the high lag sim, the leash would randomly disconnect requiring the play partner to re-leash after a few minutes. I suspect the check for nearby leash target is randomly timing out and may need a longer timer.

What steps does someone need to take to reproduce the problem?
Leash someone in a high lag playground such as HBC

**Comment by zontreck** [comment]
Can you provide me some additional information?

1. Approximately how long until the disconnects from leashing begins?
2. Can you give me the name of a example high lag region this is occurring in? (And is this sim public access so i can test to see if i get these errors too)

**Comment by zontreck** [comment]
Hi @SharieCriss : After trying to reproduce this issue; I need to know how to reproduce this. I could not get this to occur. I tested this at the sim: Lochme, as it is known to be high lag at times..

Additionally; while the timer logic did need a little cleaning up, this problem for me did not occur with either the cleaned up version nor the RC1 version.

**Comment by SharieCriss** [comment]
The problem started within a few minutes. Leash, get chatting, notice leash is gone. Leash again.... Chat some more, leash gone again... After the 4th time, moved to another lower lag sim and the problem did not occur. I've never seen this before, it could be the sim itself was misbehaving, but all scripted items were REALLY laggy with long delays to get a manu, region script run times in the single digits. As I mentioned in the original post, it happened at HBC (it comes right up in search, don't have the LM at the moment) which is always super busy loaded with avis with lots of scripted attachments. 

I'm suspecting this is NOT RC related but may be another old issue that is rearing it's head due to the continued poor region performance issues on the grid. This is certainly nothing I would hold up a release over as it really does appear to be lag-caused, but perhaps there is a way to mitigate it in the future.

**Comment by zontreck** [comment]
Help Wanted
======

This cannot be reproduced easily. If repro steps are found, or a patch is produced, please send it in.
