### ISSUE TITLE
[Suggestion] Migrate "tools" like SubAO and Relay into a single HUD

### ISSUE THREAD

**Issue by MikuGit** [OpenCollarTeam/OpenCollar#304]
Ròan didn't allow me to be lazy, so here we go.

Based on people easily reaching the attachment limits, I suggest making a single hud attachment that has all the OC "tools" (for a lack of a better name) in it.
Now you might argue that some people won't want the SubAO and some people won't want the relay and that would bloat them.

But!
That's where llSetScriptState comes in.
You have a master script that toggles the scripts on and off depending on what people want to use.
That means that the scripts won't hog resources or menu space, but you can have all scripts and thus all tools in a single place, making for a single nice and powerful attachment.

A side note is that this technology could be useful in turning features on and off in the collar as well. It's a bit messy to delete all the scripts you don't want, so turning them off and on would be easier. One example being a hood I have that is scripted with OC, where I've removed mostly everything I can apart from the very core things. It would have been neat to just go into a menu and disable everything I don't want instead.

**Comment by zontreck** [comment]
This is a good idea. I'm not sure how the AO would interact with the Relay though as the one we have in mind would conflict with linked messages as it exists.

For the collar part of this suggestion:

I have been contemplating as part of v8 a sort of soft switch, where at boot-up all scripts would start, and inform the "master" script with their script name, and what menu path. This way until that path gets accessed the script would be set to not running.  I'm just unsure if this would work for in real-time being able to start a script and then open the menu up. The question then also becomes how we will determine when to stop the scripts again.
