### ISSUE TITLE
Animations > Posture

### ISSUE THREAD

**Issue by Attitum** [OpenCollarTeam/OpenCollar#305]
What version of OpenCollar are you using?
Beta five
What behavior did you expect?

Animations > Posture
Pressing > [ ] posture button
reponse : 
[17:49:00] OpenCollar: Your neck is locked in place.
[17:49:03] OpenCollar: Your neck is locked in place.

It does not fill in the box on button
it produces a second locked message
2nd press should be unlocked with button refreshing

What behavior did you see instead?
[17:49:00] OpenCollar: Your neck is locked in place.
[17:49:03] OpenCollar: Your neck is locked in place.

What steps does someone need to take to reproduce the problem?
Update collar to beta 5 goto Animations > Posture "press button"

My guess is that the ANIM (if (llGetInventoryType("~stiff") == INVENTORY_ANIMATION))its looking for is not in collar its error'ing out and has no code to deal with this.

**Comment by zontreck** [comment]
Considering the grid issues today. Try this once there isn't massive grid issues.

**Comment by Attitum** [comment]
It's an issue

**Comment by zontreck** [comment]
There is still ongoing grid issues.

**Comment by zontreck** [comment]
Someone else was able to repro. So unlikely to be grid issues. I'll fix this later when I'm able to login

**Comment by SilkieSabra** [comment]
didn't we deprecate the posture animation we had because of issues with spread hands? there shouldn't be a posture button if there's no posture animation

**Comment by zontreck** [comment]
Cannot repro

Here's the results of my test
```
[17:53:38] OpenCollar: Posture override active.
[17:53:39] OpenCollar: Your neck is locked in place.
[17:53:41] OpenCollar: You can move your neck again.
```

**Comment by zontreck** [comment]
The button toggles just fine

**Comment by Attitum** [comment]
The Button works just fine, when you have an animation in the collar, remove the animation, its the same problem with Antislide as well

**Comment by Attitum** [comment]
as stated in my origina issue right here again!

My guess is that the ANIM (if (llGetInventoryType("~stiff") == INVENTORY_ANIMATION))its looking for is not in collar its error'ing out and has no code to deal with this.
