### ISSUE TITLE
Leash and Lock interaction leads to constant pulling (repro possible)

### ISSUE THREAD

**Issue by DogThing** [OpenCollarTeam/OpenCollar#306]
What version of OpenCollar are you using? 
7.4 Beta 5

What behavior did you expect? 
Leash as normal

What behavior did you see instead? 
Leash acts correctly when collar is unlocked. If locked, leash will continue to 'tug' the wearer against the leash holder no matter what length is set. If then unlocked, The constant tugging  (every 2 seconds)  stops.

What steps does someone need to take to reproduce the problem? 
Unlock collar, leash wearer, lock collar.
(I have a slightly odd avatar which seems to be the magic ingredient in this bug. Quadruped human but not wildly out of SL norms for size or posture.)

**Comment by zontreck** [comment]
Cannot reproduce this as is.

**Comment by zontreck** [comment]
As you can see https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/collar/oc_leash.lsl#L694-L719

There's not any use for the locked token anyhow, so i'm not sure how this would be affecting leash. I did try to repro anyway

**Comment by DogThing** [comment]
I have tried to reproduce this with other avatars, an alt in feral dog form, all sort of combinations of size and skeletal deformations but none exhibit the same behavior as reported. Infuriating.
I'm available for testing (Vicky Carfield) if you think it might be worth investigating.
