### ISSUE TITLE
[Request for Community Input] New Feature: Weld

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#311]
[![](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/Yes)](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/Yes/vote)
[![](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/No)](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/No/vote)

A common complaint has been that OpenCollar doesn't have Welding for the Lock. And while this has never been a OpenCollar feature, many third party products do actually have this feature. Someone also told me last night that they would switch to OpenCollar, but that they would want the Weld functionality. 

QUESTION: Should we add in welding functionality to OpenCollar? If so what in your eyes would this feature look like? If not, why shouldn't this be a feature?

**Comment by mistressohm** [comment]
You can put a "Lock" value into the .settings notecard, so that when the
collar is worn (or the wearer logs in) it locks automatically.

If it is offered as a feature, it should be via an update object that the
submissive (not the dominant) needs to rez, agree to, and then type in the
name of the owner authorizing the weld.  That way there's no question of
consent, as the Dominant has no role in the process, and is only verified
as part of it.  If the named Dominant is not the SOLE owner, or is not
owner rank in the collar already, the Weld should fail.  This means that
OwnSelf collars cannot be Welded.

Once the Weld is agreed to, the collar is locked, and the Unlock button is
no longer offered.

**Comment by zontreck** [comment]
Any other thoughts on this?

**Comment by zontreck** [comment]
10 more days until this is a dead topic

**Comment by zontreck** [comment]
POLL
[![](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/Yes)](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/Yes/vote)
[![](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/No)](https://api.gh-polls.com/poll/01E8D4HVQSMCNTJDP0RGFKQ8T9/No/vote)

**Comment by GeminiMarshdevil** [comment]
i see no reason not to include the feature.
caveat id like to see tho is the option during welding to lock the owner into its "welding" or not.

example:  
who ever is welding the collar gets the choice to lock the collar itself on forever, 
OR
lock the collar AND 1 owner such that the collar is forever stuck with that owner.

the welding function should include the removal of safewording.
likewise if the collar has no owner. but the owner is desired to be locked on, then Self Ownership should be what is permanently locked in place.

**Comment by SilkieSabra** [comment]
Words are things, and a private designer came up with the name "weld".  While we can create our own version of the actual operation, we should not use the name.

**Comment by zontreck** [comment]
The concept of welding didn't originate with a private designer..

**Comment by GeminiMarshdevil** [comment]
[14:58:01] Gem H.M. (aisha.marshdevil): so
[14:58:03] Gem H.M. (aisha.marshdevil): guess what.
[14:59:17] Gem H.M. (aisha.marshdevil): this is a welded collar: https://images.homedepot-static.com/productImages/a0293975-a888-4b11-b6c0-43389e0ea8c3/svn/platinum-pets-dog-collars-c183mmbch-64_1000.jpg


its first usage was in the rough 1700's ?  by dog breeders
[15:00:20] Gem H.M. (aisha.marshdevil): the point here being, the word "Weld" is not copyrightable and not even first used by wendy and in fact, is an old as fuck tradition in BDSM ancient as bdsm itself before SL was ever a thing and again used a dozen times before opencollar even existed
[15:00:23] Gem H.M. (aisha.marshdevil): in sl
[15:00:51] Gem H.M. (aisha.marshdevil): any questions? x3

**Comment by zontreck** [comment]
15 yes
17 no

Closing poll and will not implement feature
