### ISSUE TITLE
Remove Kyrah Abattoir's mesh files

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#32]
This user has indicated that she wants to withdraw the mesh design that she contributed a while back (the simple round collar with a ring on the front).  While we could perhaps fight this, it's probably not worth it, so let's figure out which files those are and remove them.

**Comment by kyrahabattoir** [comment]
https://github.com/OpenCollarTeam/OpenCollar/pull/36

**Comment by nirea** [comment]
So to clarify, this means these meshes are no longer being made available under the Creative Commons Attribution-ShareAlike 4.0 International Public License, as specified at https://github.com/VirtualDisgrace/opencollar/blob/master/LICENSE?

**Comment by nirea** [comment]
Further reading:  https://www.plagiarismtoday.com/2014/12/09/revoking-creative-commons-licenses/

We may still do this as a courtesy, but it looks like it's not legally necessary.  I'm going to see what other members of the OpenCollar community think.

**Comment by silentwat** [comment]
Well.. once it is donated to project... too bad...

**Comment by Saraeva** [comment]
Nirea, I would advise against retaining Kyrah Abattoir's mesh files for use in this branch of OpenCollar. If you continue to allow the meshes to be available; your reputation in SecondLife will be most likely be tarnished. Whenever someone made the same request to Wendy, it was always honored.

**Comment by nirea** [comment]
Yeah, I think you're right Saraeva.  We have a new default design in the works.
