### ISSUE TITLE
Feature Request: Chained Avatar Mobility

### ISSUE THREAD

**Issue by spflanze** [OpenCollarTeam/OpenCollar#320]
What version of OpenCollar are you using? 7.5

I notice that if the avatar's ankles are chained together the avatar cannot move. I would like to see several mobility modes determined by how the avatar is chained. similar to how the Mesmerize Dungeon cuffs work, which I can demonstrate on request:

1) If the ankles are chained together by a length of chain that allows them to be somewhat apart, I would like the avatar to be only able walk, and be restricted from running.

2) If the ankles are chained close together:
    
    a) If hands are chained behind the back the avatar can only hop and move a slow speed, such as crouching speed (when C key is held down), or slower.
    
    b) If hands are chained together in front, the avatar can move on hands and knees, but putting hands forward while weight is on the knees, and then drawing the knees up forward together while the weight is on the hands.

    c) If the avatar is in hog tie, I would like for the avatar to be only able to move very slowly as it squirms, and wriggles, while the torso is horizontal..

**Comment by zontreck** [comment]
Added the help wanted tag

**Comment by SilkieSabra** [comment]
This is about what animations are assigned to what poses.  Superseded by AddonCuffs.
