### ISSUE TITLE
Feature Request: Coffle

### ISSUE THREAD

**Issue by spflanze** [OpenCollarTeam/OpenCollar#321]
Make it possible to leash avatars together by collar, or cuff, to make a coffle that can be lead on leash by a captor, or owner.

**Comment by zontreck** [comment]
Anyone else think this could be a good feature to have?

**Comment by SimplyNemz** [comment]
Can't you effectively already do this?

Three people, A, B, C.

A takes leashes for B & C.
A passes leash for C to B.
A is holding B's leash. B is holding C's leash.
If B is not wearing a leash holder, the leash will default to B's collar.

If person A starts walking and drags person B, person B will start to drag person C.

**Comment by zontreck** [comment]
Not with cuffs

**Comment by mistressohm** [comment]
Were you wanting the chain to go from back of A's collar, to B's cuffs, and
then to B's collar?
