### ISSUE TITLE
Freature Request: Reserved Memory Minimization 

### ISSUE THREAD

**Issue by spflanze** [OpenCollarTeam/OpenCollar#322]
Regardless of how much memory a script actually uses, Mono reserves 64k memory for each script. This 64k times the number of scripts the collar is a significant amount of memory that can unnecessarily limit the number of other attachments an avatar may have to play with, such as CODE-5 Real Spankers, and what not. And so I would like to see llSetMemoryLimit() used to reduce unused reserved memory. Code I used to do this si below. It adapts, as much as practical, the amount of memory the script is using.

Defines a global that can be placed in the first few lines of script so the memory margin is easily found and changed:

// The amount of memory needed above that returned by llGetUsedMemory().
// Used in state_entry() to reduce the maximum memory limit to below
// the defautlt 64kB for Mono. This allows more scripts in sims that limit
// script memory.  This value is determined by trial and error. It is increased
// until stack heap collision errors no longer occur.
integer iMaxMemLimMargin = 2048;

To be place at the bottom of the default state's state_entry() event:

        // It can happen that the call to llSetMemoryLimit() will not work first time, even
        // when passed the same value. For reliability try several times. 
        integer i;
        while( i++ < 10 && !llSetMemoryLimit( llGetUsedMemory() + iMaxMemLimMargin ))
        { llSetMemoryLimit(6400);
        }

**Comment by zontreck** [comment]
This is not realistic. It's a nice thought but almost all the scripts are at the maximum memory usage anyhow. I wish i could say we could limit the memory... One thing we are looking at for the next version is to automatically turn scripts off or on depending on need

**Comment by spflanze** [comment]
I have already done it. It was necessary because of the 4 MB limit at the region I need to use them in, and other attachments required for RP.  I offer to pass you a collar, and cuffs, set in which I have done this minimization to the OpenCollar 7.4 cuffs, and 7.5 collar, scripts. The iMaxMemLimMargin values are individually set for each script by trial, and error, during a lot of testing where each script's function was used. After each stack heap collision error I got I increased the value of iMaxMemLimMargin by a generous amount. I do not get the stack heap collision errors anymore, and still have reduced memory usage by a large amount. Not all the scripts will be in these cuffs, and collar, because I removed the ones I do not need.

I understand that as one does things such as add secondary owners. adds to the Access List, memory needs increase. But is should be possible to reserve plenty of memory for such needs, or use llSetMemoryLimit() to increase memory with each addition.

**Comment by zontreck** [comment]
My answer isn't changing on this. 4MB as a limit is ridiculous for any sim to impose. The primary issue would be sim cpu use.

With the 7.5 update we took the step to make 90% of the apps completely optional.

Also i don't understand why you are even setting memory limits in the cuffs. It is 1 script per cuff as of 7.4. 


I understand wanting to stay at a low memory usage. But most collars are going to use quite a bit of memory.

Now that being said. If you wish to pass me a set of scripts I'll do a diff comparison and see if any of the optimizations can be used. But i have to keep the community as a whole in mind. Not just the random sim with a 4MB limitation.

**Comment by zontreck** [comment]
My SL username is Tashia Redrose
