### ISSUE TITLE
Name on chatted text incorrectly using description

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [OpenCollarTeam/OpenCollar#323]
What version of OpenCollar are you using?
7.4.1

What behavior did you expect?
Chatted message to use the object name either:
Given name of the object (prefered)
Generated name such as the already included in chat Displayname (Accountname)'s collar
The first element of the description aka the appearance group name (Undesirable)

What behavior did you see instead?
`Body~notexture~nocolor~noshiny~noglow: WhiteFire (WhiteFire Sondergaard)'s collar has been unlocked.`

What steps does someone need to take to reproduce the problem?
Setup a collar where the scripted prim has a description such as above.

**Comment by zontreck** [comment]
Can you describe what is happening>?

**Comment by zontreck** [comment]
That issue was fixed awhile ago. What is the version of oc_dialog?  When you type: ```<prefix> versions``` what does it say on the oc_dialog line?

**Comment by WhiteFire-Sondergaard** [comment]
oc_dialog SCRIPT VERSION: 7.4
Installed from the "7.5" updater box.

**Comment by zontreck** [comment]
According to default behavior:
https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/collar/oc_dialog.lsl#L513-L515

The script will use the description only initially. 

You would need to change the 'devicename' for that text to change

**Comment by zontreck** [comment]
Command for changing device name:
```
<prefix> device name <newname>
```

**Comment by WhiteFire-Sondergaard** [comment]
This seems like undesirable behavior as a default, compounded by the lack of documentation in the creation howto. If one has to read the source for such a basic function less well equipped designers will find this quite frustrating.

IMHO of course.

**Comment by zontreck** [comment]
Yea understandable. It has to get the devicename from somewhere. Where would you propose we get the devicename from?

**Comment by WhiteFire-Sondergaard** [comment]
The name of the object. Presumably the designer will have that as it's model name. Or in other words: make no change to the name on output by default.

**Comment by zontreck** [comment]
I'll leave this open as a bug and it'll get revisited later.

**Comment by zontreck** [comment]
This issue was resolved in a previous commit.
