### ISSUE TITLE
Feature/App Request: Owner Login Alert

### ISSUE THREAD

**Issue by SimplyNemz** [OpenCollarTeam/OpenCollar#324]
I admit, this is a bit of a silly request. If someone makes it though, it'll hopefully save my noggin from getting hit by a rutabaga so often.

Idea is a simple App addon. When an owner, possibly add option for trusted, connects to SL a HUD would pop up with an audio cue to alert the wearer. Thus alerting them they might soon be summoned or giving them a chance to greet their owner right away. Maybe add additional prompts to the HUD, letting them open an IM window or request teleport.

I know there are a few items on the market that work like this, but it would be a nifty feature to add to the collar itself and save an additional attachment point for some folks. It would also save this poor kitten from being bonked over the head on a regular basis. Think of the kittens!

**Comment by zontreck** [comment]
hm. Ya this would be a good feature to add!

**Comment by WhiteFire-Sondergaard** [comment]
As requested in chat:
app

Matches the request. Is a periodic scanning device and would add script weight and time to the collar. Requires a HUD to handle popup which would limit the number of people who would use it dramatically.

As the Owner list is not a opt-in thing, and this might not be an obvious result even if it is, this could present a privacy risk to people on the Owners list as well. I am not sure how such a device fits into the TOS.

Just IMHO of course. I have all the opinions.

**Comment by zontreck** [comment]
according to the request. tit does not appear a HUD is requested specifically. it sounds like it could be a simple dialog popup.

**Comment by WhiteFire-Sondergaard** [comment]
> according to the request. it does not appear a HUD is requested specifically. it sounds like it could be a simple dialog popup.

> When an owner, possibly add option for trusted, connects to SL a HUD would pop up with an audio cue to alert the wearer.

I am going to have to disagree with you about the nature of the request. However I do agree a (possibly more reasonable) alternate would likely be a notification, or a llDialog() which would allow for the requested buttons.

**Comment by zontreck** [comment]
Reason I say that is due to how it is worded. huds don't pop up. But other elements on the heads up display CAN. Such as a dialog.

**Comment by zontreck** [comment]
Maybe the OP: @SimplyNemz can clarify their meaning later by the word HUD

**Comment by WhiteFire-Sondergaard** [comment]
I was simply assuming the OP was reasonably well acquainted with SL which has a specific meaning that most users interact with for a HUD. In short taking them at face value until told otherwise.

HUDs can pop up, either by being attached at the time they are required or minimizing themselves through position and scale and then restoring on request. I have seen both tactics taken, especially for blind folds.

Regardless I'd still say it's kinda moot as a llDialog() would meet the goals and have a tremendously smaller implementation cost, cause less lag, consume less texture memory, etc.

**Comment by SilkieSabra** [comment]
Setting aside the definition of "HUD", can someone tell me why the SL "X is online" toast when you log in is not enough of a "heads up"?

**Comment by SimplyNemz** [comment]
Yah for poor terminology?

Where in a large HUD popping up in the middle of my screen with fireworks and fanfare would be nifty, it's not needed. Specially if it's going to cause that much extra usage. A dialog window as zontreck mentioned would suffice.

As to privacy, there are a number of online tracking systems on the MP. I picked up a very rudimentary one last night that simply gives a basic text notice in nearby. However, that does raise ANOTHER question, why is there no dialog confirmation required from owners before they are fully as owner by the collar? That sounds like something that should already be in place and not that difficult to include.

Silkie, a couple of reasons! I personally have it set not to give notices when a friend log ons or off. I have a decent list of friends and some of them like to poof regularly. Getting spammed by those notices is frustrating. In addition, if someone is under RLV restrictions, they may not be watching or able to see chat. So they might not see the notice, where as the dialog window would appear irregardless. I also often ignore when 'nearby' flashes when I'm working on something, as I have a few items and groups that like to give text spam on occasion.

**Comment by zontreck** [comment]
Adding to the todo list for 8.0 Alpha 3

**Comment by zontreck** [comment]
As this will be a optional app, removing from 8.0 project queue
