### ISSUE TITLE
[Bug] Any leash RLV commands not properly being executed

### ISSUE THREAD

**Issue by MinesweeperM** [OpenCollarTeam/OpenCollar#325]
What version of OpenCollar are you using?
7.4.1
What behavior did you expect?
When sub is strictly leashed, he must be unable to sit somewhere far.
What behavior did you see instead?
He can sit everywhere
What steps does someone need to take to reproduce the problem?
Just leash collar wearer with "strict" option, and he must try to sit on far furniture.

It seems, directive "sittp=n" missed in string 201 of "oc_leash" script

**Comment by zontreck** [comment]
Confirmed bug

**Comment by zontreck** [comment]
Reason: Leash was not updated to use the newer rlvsuite / rlvsys updates to restrictions.

**Comment by zontreck** [comment]
Sittp will be added to it. But the overall bug is actually larger than just sittp

**Comment by SimplyNemz** [comment]
And you beat me to it!

This is related to the same issues I have had with Strict Leash allowing me to teleport, fly, etc after a while. 

[00:46] This is approx. what the macro would need to be for strict leash: 29360128, 3211264
[00:47]  i'll take a look at fixing that later. I'm focused on the cuffs at the moment
