### ISSUE TITLE
RLV Restrictions not applied after relog 

### ISSUE THREAD

**Issue by anna-glume** [OpenCollarTeam/OpenCollar#326]
What version of OpenCollar are you using?
7.5 (7.41)
What behavior did you expect?
Step 1: Owner applies RLV restrictions. RLV restrictions are effective.
Step 2: I relog.
Step 3: RLV restrictions are reapplied by the collar after coming back online. 

What behavior did you see instead?
Step 1: Owner applies RLV restrictions. RLV restrictions are effective.
Step 2: I relog.
Step 3: RLV restrictions are not applied again.

The restrictions are applied after a reboot of the collar [prefix]reboot.
I had to do reboot twice at least one time to see the restrictions apply again.
I presume it is some kind of race condition in the startup of the collar scripts.

What steps does someone need to take to reproduce the problem?
Maybe try on a slow or laggy sim. Try on our sim, just ask, but have it seen on others too. 
For me the behavior is very consistent, i see it more often not working then working.

**Comment by zontreck** [comment]
This issue was fixed in commit 95c3b2abc139b7e99ecf45dd8efe68020704aa05
