### ISSUE TITLE
UI issue: new macro creation should not be the default option under Restrictions

### ISSUE THREAD

**Issue by LibertineFrostbite** [OpenCollarTeam/OpenCollar#327]
When applying restrictions, users expect to see the familiar menu options, not be dumped into a macro creation process that did not previously exist. Hiding the actual setting of restrictions under the heading "Individual" is not intuitive and confusing to longtime users. As a technical writer it's my job to figure out undocumented interfaces; if *I* couldn't figure it out easily, what chance does your average non-technical person have? We all know hardly anybody reads documentation. Please consider making macro creation the submenu and individual restrictions the default. 

I dread having to explain this interface change to certain dominants so much that I gave up and went back to the previous version.

What version of OpenCollar are you using? 7.5

What behavior did you expect? I expected to be able to apply a restriction.

What behavior did you see instead? I was led into an unfamiliar macro creation process that was hard to understand and did not make it obvious how to simply apply a restriction.

What steps does someone need to take to reproduce the problem? Use the Restrictions menu.

**Comment by zontreck** [comment]
Okay then how would you suggest we handle the individual restriction menu? If its so confusing i want to see some suggestions.

**Comment by SilkieSabra** [comment]
Macros are on the front page of the Restrictions menu since V 4.  It's what's familiar now to most users.

**Comment by LibertineFrostbite** [comment]
> Macros are on the front page of the Restrictions menu since V 4. It's what's familiar now to most users.

Um... no. I'm wearing a 7.3 collar right now and there is no macro feature. That's why I was so confused. 7.4 didn't have them either. I've never seen that macro feature before and I've been using OC for more than ten years.

As for the behaviour I'd expect -- I'd put the restriction categories back where they were and move the macro creation to a Macros menu. That way users who are familiar with the old way can still find what they're looking for easily, and macro creation is clearly labeled as macro creation.

**Comment by zontreck** [comment]
Theres no "Macro" feature in 7.3, because it is the default, you have no individual restrictions with 7.1-7.3. In prior versions this was a feature. Macros were introduced in v6, And they did away with individual restrictions creating the need for a RLV Terminal button in the menu

**Comment by LibertineFrostbite** [comment]
That is very, very confusing to me, because I'm not getting at all the same behaviour from the Restrictions menu in the 7.5 collar that i am from the 7.3. Here's what the Restrictions menu in my collar looks like. I literally used the 7.3 updater to convert it from an earlier version only two days ago. https://i.gyazo.com/fe495fcd791d83f73c8e13370052dc95.png

**Comment by zontreck** [comment]
I'm aware of what the 7.3 menu looks like. It does not change the fact that it used to look very different. Take a look at a 3.x collar and compare to 7.3. 7.3 was missing a lot of features when compared

**Comment by SilkieSabra** [comment]
V4-7.3 grouped commonly used restrictions in suites with names like "rummage", "daze" "Dazzle" and left out all the other restrictions, and then included a "terminal" so you could type in the restriction you wanted.  Those suites are what I was referring to as the "macros" on the front page.  You can now change them with the new Macros feature.  And, all the individual (nongrouped) restrictions are available once again, arranged categorically.  [](https://opencollar.cc/docs/RLV#restrictions) . If you can familiarize yourself with the new layout, you and your dominants will have many more options than before.

**Comment by zontreck** [comment]
This really isn't a bug and there's not enough here to consider it to be a feature request. If you need help figuring out the user interface for 7.4x please ask in the OpenCollar group. I'm going to close this ticket for now. If you have anything you want to add to this ticket, feel free to add another comment.
