### ISSUE TITLE
Unexpected behaviour: wearer cannot change relay mode if relay is active, owners are set, and access is public, even when collar is unlocked. If collar is removed, relay HUD still cannot be removed.

### ISSUE THREAD

**Issue by LibertineFrostbite** [OpenCollarTeam/OpenCollar#328]
In previous versions, the wearer could change their own relay mode by default. Now if the collar has owners and the relay is active, the wearer cannot change the relay mode, even if the collar is unlocked. (At least this is true with access set to public.) Worse yet, the relay cannot be removed even if the collar is removed; IMHO it should automatically detach (or at least unlock) if it can no longer communicate with the collar. I'm uncertain if this is the intended behaviour but I find it problematic. 

If an owner wants to block the wearer's ability to change relay mode they should have the option, but as most of us wear our collars 24/7, this is really inconvenient for those of us who only have owners set for convenience (and only occasional contact with those owners). This new behaviour has essentially made the OC relay unusable for me.

What version of OpenCollar are you using? 7.5

What behavior did you expect? To be able to change my relay mode.

What behavior did you see instead? Message stating that only owners can change relay mode.

What steps does someone need to take to reproduce the problem? Have owners. Have relay turned on. Try to change relay mode with collar unlocked. (Note that Public mode was also enabled, and I was not able to test whether that affected setting the relay because I could not unset Public due to not owning my own collar.)

**Comment by zontreck** [comment]
This is a bug. Not the intended behavior

**Comment by zontreck** [comment]
Regardless, we're doing away with the HUD based relay.

**Comment by zontreck** [comment]
I know this doesn't help overall at the moment. But here is the chat command which will turn off the relay
```
/507 {"type": "mode", "cmd": "set", "value": -1}
```

**Comment by LibertineFrostbite** [comment]
Good to hear!
