### ISSUE TITLE
Request for update of the Help Notecard given in the collar

### ISSUE THREAD

**Issue by avelluna** [OpenCollarTeam/OpenCollar#329]
What version of OpenCollar are you using?
7.5
What behavior did you expect?
Help notecard have the most up to date commands.
What behavior did you see instead?
Help notecard is out of date for some chat commands.
What steps does someone need to take to reproduce the problem?
Press help on menu button and read the notecard. Titler is no longer title on, it is now title show. title off is now title unshow.   title [a fancy title] no longer works (possible bug). outfits command no longer works (possible bug). terminal command no longer exists. 

Probably more to list but those are the ones I have gone through.

**Comment by zontreck** [comment]
What help notecard are you referring to? All documentation is maintained on https://opencollar.cc

**Comment by zontreck** [comment]
This is not a bug though, this could have been asked in the opencollar group inworld.

**Comment by avelluna** [comment]
When you press help on the collar menu, it gives a notecard.

**Comment by zontreck** [comment]
That help button needs to be adjusted to point to the website then.

**Comment by SilkieSabra** [comment]
There is a help notecard, the text is kept in the git, i can update it there
but it will need to be manually updated int the vendor?

**Comment by zontreck** [comment]
@SilkieSabra how do you want to resolve this?

**Comment by SilkieSabra** [comment]
It looks like most of what needs to be updated are old chat commands.

**Comment by SilkieSabra** [comment]
Several chat commands either changed or were dropped with 7.4/5, I've made a few changes, will go through it more thorughly.

**Comment by cruelraremaster** [comment]
Let's close this old issue - if there is still work to do on the current version 8.2.3 notecard, please re-open or create a new issue with details.
