### ISSUE TITLE
Replace VirtualDisgrace-specific update/news code

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#33]
Any inworld scripts checking for new versions or news updates should get them from this repository rather than one owned by VirtualDisgrace.

**Comment by silentwar-resident** [comment]
yep agreed

**Comment by IalaAndromeda** [comment]
Not just update/news, various places refer to opencollar.at for documentation purposes and information.
E.g. oc_ao.lsl, line 341 en 342

**Comment by SilkieSabra** [comment]
Also there is a builtin bookmark to the current VirtualDisgrace Temple; that should be removed but then we will need to replace it with some default location that's stable.
