### ISSUE TITLE
7.5 Safeword cannot be disabled

### ISSUE THREAD

**Issue by sarah-hunt** [OpenCollarTeam/OpenCollar#331]
What version of OpenCollar are you using?
7.5
What behavior did you expect?
i used this comand in the settings nc: GLOBAL=safeword~0 

What behavior did you see instead?
it should have turned of the collars internal safeword, instead it changed the safeword to ' 0 '. if i look in help menu i see safeword is 0.
What steps does someone need to take to reproduce the problem?
no idea, im not a scripter. :)

**Comment by zontreck** [comment]
Marked as a bug- Will look into after the cuffs are finished

**Comment by SilkieSabra** [comment]
This is a high priority for me since it breaks "hardcore" settings that many are interested in. Any chance it's an easy fix?
