### ISSUE TITLE
Leash is not Invisible When I Click Configure .. Invisible

### ISSUE THREAD

**Issue by sethmerrick305** [OpenCollarTeam/OpenCollar#334]
What version of OpenCollar are you using? [Tethered] Collar - Eternity Diamond (2019) 7.4 updated 3.24.20

What behavior did you expect? Expected the leash to go invisible.

What behavior did you see instead? A white rope appearance.  Leash is NOT invisible!@

What steps does someone need to take to reproduce the problem? I have no idea.  New to all this.

**Comment by zontreck** [comment]
Oops. Not fully resolved

**Comment by sethmerrick305** [comment]
For several days the Lease was invisible.  I refreshed and saw that the white glowing rope is showing again.  I'll try refreshing; however, this needs to be fixed please.  Thank you.

**Comment by zontreck** [comment]
Use latest oc_particle from commit 9376e1f. It is fixed
