### ISSUE TITLE
Outfits won't show in Browse menu unless something other than .outfits is a top folder in #RLV

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#335]
OpenCollar 7.5

A member had only .outfits in #RLV, no other folders.  

She had a correctly configured .outfits folder with two folders plus .core inside that.
The folders did not show in the Browse Menu.  We tried Fix Menus and checked a screenshot of her #RLV folders in inventory.  When she added another folder in #RLV next to .outfits, the contents of .outfits showed in the Browse menu.

Is this a bug or is it just part of how #RLV works?  If the latter I'll get it in the documentation.

**Comment by zontreck** [comment]
If this is a bug in RLV, then needs to be reported to either RLVa's maintainer or to Marine for RLV

**Comment by SilkieSabra** [comment]
so is it a bug in the #RLV API or in oc_outfits or oc_rlvsys?

**Comment by zontreck** [comment]
RLV API if you need to have at least one normal toplevel folder in RLV

**Comment by SilkieSabra** [comment]
I'll check with Kitty Barnett (RLVa)

**Comment by zontreck** [comment]
Might as well check with Marine as well (RLV) incase this is also a bug there
