### ISSUE TITLE
poses in collar override accepted invited subhugs/hugs

### ISSUE THREAD

**Issue by floreoresident** [OpenCollarTeam/OpenCollar#336]
What version of OpenCollar are you using? OC 7.5

What behavior did you expect? to not override and let me complete the hug i accepted an invite for while being in a pose of the collar

What behavior did you see instead? the pose in collar takes over and stops the hug i accept an invite of

What steps does someone need to take to reproduce the problem? accept the hug invite and being in a pose of the collar

**Comment by floreoresident** [comment]
What i noticed the couple animation which is being overridden is also an animation playing in the same  collar where also the kneel is from being played

**Comment by zontreck** [comment]
Does the couple animation start from the collar or someone else

**Comment by floreoresident** [comment]
The couple animation starts from the collar.

**Comment by zontreck** [comment]
new master ticket #370
