### ISSUE TITLE
oc_bell is using a changed() event and checking the root prim alpha to update g_iHide

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [OpenCollarTeam/OpenCollar#338]
What version of OpenCollar are you using?
7.4.patch that is calling itself 7.5

What behavior did you expect?
It to listen for the link messages like a good boy.

What behavior did you see instead?
It totally ignored that, and instead never allowing my bell to show because this particular collar has a transparent root prim.

What steps does someone need to take to reproduce the problem?
Make a collar with a root prim set to 100% alpha.

**Comment by zontreck** [comment]
Issue verified. Marking as a bug with help wanted tag

**Comment by zontreck** [comment]
oc_bell is not using LM_SETTINJG_RESPONSE to update the g_iHide flag
