### ISSUE TITLE
Rename vanilla to "Own Self"?

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#34]
I think the term "vanilla" is not very intuitive to describe a configuration where the wearer retains control of the collar's functions.  But maybe I'm weird.  What's the community's take?

**Comment by SerinaG** [comment]
Would agree with your thought nirea. The menu label should describe the function.

**Comment by silentwar-resident** [comment]
I agree.. go for it nirea.

**Comment by SatomiAhn** [comment]
"Own Self" is self-explaining. I think it is a good change.

**Comment by SilkieSabra** [comment]
I am not sure the "vanilla" function does anything useful at all that simply adding oneself to the owner role didn't do.  Is there any reason why we can't get back the ability to press add owner and select one's own name?

**Comment by nirea** [comment]
I don't have strong feelings either way, roan.  But renaming is easier than
ripping the whole feature out at this point.

**Comment by NorthGlenwalker** [comment]
I never liked the name Vanilla as outside of the BDSM community it does not mean anything anyway. I agree to rename it for now but I also agree with Silkie and it should be just select yourself as owner as before (not looked at the code but I assume there is a filter to exclude yourself in the add owner role list building.

**Comment by kisaminclaws** [comment]
The big difference between the so-called "Vanilla" mode and adding yourself as an owner is that if vanilla is checked, then some other owner can NOT remove you from owner privileges.  Thus, it's a way of being "locked out" of your own collar and/or preventing the necessity of having to reset or runaway.

**Comment by silentwar-resident** [comment]
Yeah there good point but some want to go extreme and not let them runaway or use collar at all that’s why Wendy created heartcore….

**Comment by TakatSu1** [comment]
Agreed, SilentWar  But Vanilla is the other direction from that - it prevents you from being removed as an owner.

**Comment by nirea** [comment]
I've implemented the rename.  If we  want to drop the dedicated feature and just support owning yourself as a user, let's make a separate ticket for that.
