### ISSUE TITLE
Updater is failing to remove scripts named OpenCollar - x from versions 3.7 - 3.97

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#340]
Since the V 7.4-5 update I have run into many instances where older collars were duplicating scripts because there was a run of versions (by report, since I did not always have access to these collars to see the version) 3.7, 3.8 and up as far as 3.97.  These collars had scripts named OpenCollar instead of oc.  According to the documentation the updater can update these successfully, but it has stopped overwriting these scripts.  I find it hard to believe it never overwrote them or we would have had this error more often in the last three years.

**Comment by zontreck** [comment]
This is because it is no longer nuking the entire contents, that did not resolve the issues with updating from a non-OC version, so the nuke code was removed. I had forgotten to check clearly if there was code to remove all older script names.
