### ISSUE TITLE
Feature Request - Rework Restrictions For Ease Of Use

### ISSUE THREAD

**Issue by SimplyNemz** [OpenCollarTeam/OpenCollar#341]
What version of OpenCollar are you using?
7.5

What behavior did you expect?
System which shows what restrictions are in place and easily swap restrictions.

What behavior did you see instead?
Impressive system to manage all the different restrictions, but one which is ultimately confusing to manage macros with.

What steps does someone need to take to reproduce the problem?
Wear the collar.

-----

Basically requesting we swap the dialog interface method being used for restriction macros. This is intended to enhance user ease of use.

Currently when you click on Restrictions you are given a list of Macros you can then go into and add, replace, or clear. You are also given an option to go further and individually manage restrictions or save your own macro.

However.. I feel like most people don't know the term macro. There's also no way to easily tell which macros are in use already.

1) Reword the dialog box. Instead of [Macros] use 'Restriction Sets' and add further explanation. Also replace [Manage] button with [Custom Set].

"Restriction Sets

Click to activate or deactivate."

2) Switch from current system, where in you have to click and then add, to the same system being used for the individual settings. Where in the dialog button option has a checkbox.

This does remove the replace feature. However, it also removes the necessity of clicking extra buttons to go in and add or remove restrictions anyways. It will also provide a visible way to see what sets are active and which ones are not. 

3) Perhaps add a link directly to the help page for this section as well? So people can go and see exactly what each set option contains and how the individual settings work as well. https://opencollar.cc/docs/RLV

**Comment by zontreck** [comment]
Work on this has begun in #339 

I started with exceptions, implementing the ability to have custom exceptions as requested in OC Group many times.

Tomorrow I plan on reworking the restrictions menu for ease of use.
