### ISSUE TITLE
Go back to having all scripts in root prim?

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#35]
The move to put groups of scripts into child prims has been the source of much pain for people trying to build OpenCollar into their own designs.  We should ease that pain.  This might be by simplifying the collar design itself to just use the root prim, or might be by providing free tools that automate the install process.  This ticket is the place to discuss the pros and cons of each option.

I understand that the child prim decision was made in an effort to reduce script times.  If anyone has script time measurements from before and after splitting out the scripts, that would be useful information to share here.

**Comment by CaptainDuckman** [comment]
I'm not sure how changing scripts from intra-prim messaging to inter-prim messaging would decrease script time. Seems somewhat counterintuitive in fact.

It's probably smarter to reduce communications between scripts overall, and especially to do away with listeners on channel 0 (and go through other listeners with a fine comb to see if they're really needed) as those have to parse anything being said in local chat.
This would of course be a functional change, as people would no longer be allowed to command the collar through local chat but instead have to use another channel. But it would be a performance improvement.

**Comment by SatomiAhn** [comment]
The theory behind the idea that splitting into several prims might improve efficiency is that, in this case, the filtering is done by the virtual machine itself (native code), and not as the result of interpreting scripts (less efficient).

But as nirea says, the difference might be negligible and not worth the hassle.

However there may be other reasons to consider, for having scripts in several prims:
- historically, there were many properties relative to a prim that could not be set from a different prim. It looks like new LSL functions were added to that purpose. But were all cases actually covered? (I believe they were)
- RLV restrictions are relative to a prim. If we want to be able to set restrictions independently for different plugins (or different relay sources), having several prims may be useful. Up to now, this was simulated by some tedious tracking using lists of sources and lists of lists of restrictions. Doing so does more or less do the job, but
 -- some corner cases of RLV cannot completely be simulated in this way (it did not matter much up to now though)
 -- it uses lot of memory (which isn't good but still ok) in an uncontrollable way (which is bad as it sometimes triggers out of memory errors).

**Comment by nirea** [comment]
To go into a little more detail, having the scripts in separate links lets
you specify one of those numbers instead of LINK_SET when calling
llMessageLinked.  Then only the scripts in that link have to process the
link message, and not all scripts in the collar that have a link_message
event.

But yeah, I'd like to see measurements before deciding.

**Comment by CaptainDuckman** [comment]
Thanks Satomi, that makes sense. 
Lists are indeed pretty slow, and error prone. If it simplifies the scripting, I'm all for reducing dependence on them (especially given the lack of complex data types in LSL, striped lists are even more of a pain) whether it gives a measurable improvement on performance or not, as it makes the code more robust.

**Comment by pixelwork** [comment]
I agree things should be performance tested before deciding for the one or other but if it is close and does not make too much difference i still prefer the multiple prims solution for reasons of clearness, have all the animation stuff in one prim for example so you dont have to deal with all the animation related files in the inventory of the main prim when you are working on it.  Hope you get what i mean.

**Comment by SilkieSabra** [comment]
speaking as a user not a scripter:  I was told that placing the scripts in child prims made the script time much more efficient because all the scripts don't have to listen to every other script in the collar.  I found that building with the child prims, even using dedicated link numbers, was not very difficult once I worked out how to do it and was able to teach others.  Only users with non-existent building skills might be unable to do things like adding animations because they don't know how to use Edit Linked for instance; and dabblers trying to add collar scripts to a favorite necklace might be stumped unless they can read the how-to's we will be putting out.

**Comment by NorthGlenwalker** [comment]
The idea I came up with, not thought through fully yet, to keep multiple prims, which I like for the link messages but not for building as currently they HAVE to be in a set order. Is for each sub scripted prim to locate it's self in the prim set then relay it's link number only once on collar reset, the other prim set scripts then log this prim number and use it on the link number on llMessageLinked. this would open up builders to still have the separate prims but not forced to have them as link 1-5.

**Comment by Saraeva** [comment]
NorthGlenwalker, link order was true for v4.x. Starting with v6.0.0, prims could be linked in arbitrary order.

**Comment by TakatSu1** [comment]
There is definitely going to be a performance drop if we move all the scripts to one prim over a system with scripts distributed (or at least clustered) in several prims IFF the message senders properly direct their link messages to specific prims.

I'm not sure what the latency is for an LSL script to receive a link message, execute a few lines of lsl script to decide it's not for that script, and then exit, but every script will need to do that if we move them all to the same prim.  I'll run some tests tonight and see what the impact is.

**Comment by TakatSu1** [comment]
So I did a bit of testing tonight with using llMessageLinked (LINK_THIS) versus LINK_SET.  Here was the test set up:

two prims in the link set.  The root prim had the main test script.  (more about this one in a moment).  The other had 100 scripts, all with link_message (...) handlers in them that did pretty much nothing other than increment a counter.

the test script sent a link message to LINK_THIS.  It had a link_message handler, so would receive this message.  When received, it used the integer parameter as the counter and would send out another one.  When it reached a certain number of loops, it would then switch over to a new state and run again, this time running with LINK_SET as the destination.

The results were:
   LINK_THIS: 24.895970 seconds
   LINK_SET: 25.501470 seconds

so using grouping scripts into different prims seems to save you about 2.4 percent.  I'm not sure that's enough to worry about on a per user basis.  However, if you multiply that over the number of collars active at any one time, it actually might add up to a significant cpu-second savings across the whole grid.

**Comment by pixelwork** [comment]
yes. 2.4 percent does not sound much but as you say things sum up in the end.

i really like that the root prim keeps quite clean and i dont have to mess with 100 items in the inventory

the only thing that maybe should go back to the root prim is the oc_settings script with the .settings notecard, for the users it would be easier to change that notecard then.

**Comment by nirea** [comment]
From the discussion here I'm getting that there's a moderate preference for keeping the scripts in multiple prims, even if there aren't benefits in script time.  Given that consolidating them together again would be a pile of work, I say let's not do it.

**Comment by nirea** [comment]
And Takat, thank you for the data!

**Comment by TakatSu1** [comment]
You're quite welcome.

**Comment by RestlessSwords** [comment]
I agree with having scripts clustered in several different prims but for a different reason.  In my experience it is not the message transmission that is the time load, it is the scripts receiving the message and then processing it to see if it is for them.  consider 10 prim each with 10 scripts.  If I send a message to the correct prim, only 10 scripts get a message and process it, so 10 units of message transmission and processing  if all 100 scripts are in in same prim. 100 messages go to 100 scripts (one to each) and all have to process their message, so 100 units of message transmission and processing.  I believe the different is very significant, you only want sets of scripts processing messages that are likely for them.
