### ISSUE TITLE
Suggestion for RLV's IMs lock

### ISSUE THREAD

**Issue by EveValentine** [OpenCollarTeam/OpenCollar#351]
Greetings. I've been redriven to this post in order to submit a request / suggestion: adding the ability to whitelist a group. Example: i lock my sub's IM to prevent her to receive IM, but whitelist the family group, so she can still talk on it somehow.

Thanks.

**Comment by zontreck** [comment]
Honestly i am not sure this is possible. I feel like this was asked in group before and given a similar answer.

**Comment by zontreck** [comment]
Not possible

**Comment by zontreck** [comment]
As you can see in this image, it is not possible at all do do what you are asking. I issued the sendIM  = no with OpenCollar's group ID. It did not work.

![FdnICmFsgs](https://user-images.githubusercontent.com/1643882/84594478-59a1c700-ae07-11ea-97a8-8742e62f2b08.png)
