### ISSUE TITLE
two broken remote shortcuts

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#352]
using Remote V 1.6
Detach shortcut broken--does not go to detach app.'
Rez button (the box icon) does not rez inventory.  Rez in the Main remote menu (the Gear icon) does work fine.

**Comment by zontreck** [comment]
I tested all of the buttons, are you positive that this is happening with 1.6?

**Comment by SilkieSabra** [comment]
yes, we can test it again inworld today

**Comment by SilkieSabra** [comment]
Retested on different copy of the remote and different collar.  Detach shortcut works on the second test.  Rez Inventory Object shortcut still not working.  Not a big deal because you can do that from the main remote menu and it works fine.

**Comment by zontreck** [comment]
marking it as a bug because it has to be something in the code causing this.

**Comment by zontreck** [comment]
test

**Comment by zontreck** [comment]
test

**Comment by zontreck** [comment]
This was fixed for the remote (7.5). A new remote is in the works for OC 8. Closing the issue as resolved.
