### ISSUE TITLE
Suggest to add Chat Commands for Apps>Titler

### ISSUE THREAD

**Issue by kaiakrystal** [OpenCollarTeam/OpenCollar#355]
What version of OpenCollar are you using? 7.5

What behavior did you expect? Set titler text; show/hide titler; set titler color

What behavior did you see instead? No response to chat commands found. Reviewed script and could not find reference to sMessage, or what could possibly be chat commands.

What steps does someone need to take to reproduce the problem? [prefix] set Title/Titler; [prefix] set Title/Titler color; [prefix] Title/Titler show/hide

**Comment by zontreck** [comment]
There should be chat commands. I'm checking

**Comment by zontreck** [comment]
Okay just checked

CMD_OWNER is required for using the chat commands:

Commands are: 

```
Commands all begin with: <prefix> titler
title <string>
color <vector RGB>
show
hide
up
down
plain

```

**Comment by kaiakrystal** [comment]
Thank you.

**Comment by zontreck** [comment]
@SilkieSabra assigning this to you to add to the documentation on the opencollar.cc repository

**Comment by SilkieSabra** [comment]
User Documentation updated.
