### ISSUE TITLE
7.5 detach not sorting as expected

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#358]
As resolved in #226, rlvsuite was previously getting the full list of names and uuids. This new script only retrieves the uuids and lets dialog translate to names.

oc_dialog needs a way to sort uuids by the resolved name.
However we make this happen, there needs to be a way to call this feature with and without sorting enabled.

**Comment by MinesweeperM** [comment]
So, i get solution, that works, but not sure it is good. It is still for oc_detach, but i think i can adopt it to oc_dialog, if we really need... Do we?
So, here is it, starting from line 80:
`
// Start sorting list
    integer attlist_lengh = llGetListLength(llGetAttachedList(llGetOwner()));
    list attached;
    while (attlist_lengh --) { //Filling the list with attachements names
        attached += llKey2Name(llList2String(llGetAttachedList(llGetOwner()), attlist_lengh));
        attached += llList2String(llGetAttachedList(llGetOwner()), attlist_lengh);
    }
    
    attached = llListSort(attached, 2, TRUE);
    attlist_lengh = llGetListLength(attached);
    do { //Deleting attachements names from list
        attlist_lengh = attlist_lengh - 2;
        attached = llDeleteSubList(attached, attlist_lengh, attlist_lengh);
    }
    while(attlist_lengh > 0);  
// End sorting list

    attached = llDeleteSubList(attached, llListFindList(attached, [(string)llGetLinkKey(LINK_ROOT)]), llListFindList(attached, [(string)llGetLinkKey(LINK_ROOT)])); // We don't really want to detach collar by itself? Or not?

    
    Dialog(kID, sPrompt, attached,  [UPMENU], 0, iAuth, "Menu~Main");
}
`

**Comment by zontreck** [comment]
Refactor needed for oc_dialog to include sorting of the names themselves from the automatic UUID to name resolution

This can be accomplished in PR #339
