### ISSUE TITLE
cagehome app wrong descripted in the notecards

### ISSUE THREAD

**Issue by JackalHotaling** [OpenCollarTeam/OpenCollar#364]
What version of OpenCollar are you using?
7.5

What behavior did you expect?
Reading the notecard description of the app I expect it could rezz a cage. I read: "Rezzes a cage from the collar contents (you need to have a cage object in there for this to work)"
It is not an app problem. Just is better to change the description in the notecard.

What behavior did you see instead?
The app just force TP to a location setted as cagehome.

What steps does someone need to take to reproduce the problem?

**Comment by SilkieSabra** [comment]
Cagehome is functioning as expected.  You need to supply the cage object.  If you want to use a force tp to a location, use bookmarks.

**Comment by zontreck** [comment]
it does not rez anything

**Comment by zontreck** [comment]
documentation needs to be updated

**Comment by SilkieSabra** [comment]
I'm looking at how this is supposed to work, it's not the app I thought it was.
