### ISSUE TITLE
Cuff scripts do not all apply themes, only one cuff

### ISSUE THREAD

**Issue by KikaLynn** [OpenCollarTeam/OpenCollar#366]
What version of OpenCollar are you using?7.5

What behavior did you expect? the matching cuff themes to update with  the rest

What behavior did you see instead? theme feature is broken, only one cuff responds the the theme menu

What steps does someone need to take to reproduce the problem? no idea, 
possibly a stand alone cuff installer would be nice. so this is more like a combination issue report and feature request. thank you.

**Comment by zontreck** [comment]
cuffs have no theme options to begin with
Closing issue as not-relevant
