### ISSUE TITLE
8.0A2: Lock button in menu does not reflect collar locked state

### ISSUE THREAD

**Issue by chrissy-voir** [OpenCollarTeam/OpenCollar#375]
What version of OpenCollar are you using?
8.0a2

What behavior did you expect?
I would expect that the "Lock" button in the collar menu to be checked when the collar is locked.

What behavior did you see instead?
The "Lock" button remains unchecked even when the collar is locked.

What steps does someone need to take to reproduce the problem?
Wear collar.
Lock collar either by adding GLOBAL=locked\~1 or by selecting "Lock" from the collar menu.
The "Lock" button checkbox will not reflect the locked state of the collar.
Settings->Print can be used to see the collar's locked state as GLOBAL=locked\~1 will appear if the collar is locked.

**Comment by zontreck** [comment]
Attributing this to a font issue. Will change default checkboxes font
