### ISSUE TITLE
8.0A2: Listening on channel 1 is not disabled

### ISSUE THREAD

**Issue by chrissy-voir** [OpenCollarTeam/OpenCollar#377]
What version of OpenCollar are you using?
8.0a2

What behavior did you expect?
I would expect GLOBAL=channel\~2 to disable the listener on channel 1 and enable a listener on channel 2.

What behavior did you see instead?
The listener on channel 1 is active, in addition to a listener on channel 2.  This is the behavior in 7.1 and 7.5.

What steps does someone need to take to reproduce the problem?
Add the following to the .settings notecard:
```
GLOBAL=DeviceName~Chrissy's Collar~prefix~cv~channel~2,FALSE~WearerName~Chrissy Voir~safeword~eggplant~touchNotify~1~eggplant~touchNotify~locked~1
```
Attempt to send a collar command in nearby chat using the command `cvmenu`
The menu will be displayed.

**Comment by zontreck** [comment]
Now investigating
