### ISSUE TITLE
8.0A2: RLV Folders Menus Have Lots of Checkboxes and Strange ASCII Graphical Characters

### ISSUE THREAD

**Issue by chrissy-voir** [OpenCollarTeam/OpenCollar#378]
What version of OpenCollar are you using?
8.0a2

What behavior did you expect?
When I select RLV-># Folders, I expect a usable display of items in the #RLV folder.

What behavior did you see instead?
I saw a confused display of the #RLV folders containing lots of empty check boxes and other graphical ASCII characters.  This was confusing and got in the way of using the #RLV folder system.

What steps does someone need to take to reproduce the problem?
Open collar menu.
Select RLV-># Folders
Traverse the directories

**Comment by zontreck** [comment]
Attributing this to a font issue. Will change default checkboxes font
