### ISSUE TITLE
8.0A2: RLV Relay Settings Checkboxes Do Not Reflect Configuration

### ISSUE THREAD

**Issue by chrissy-voir** [OpenCollarTeam/OpenCollar#379]
What version of OpenCollar are you using?
8.0a2

What behavior did you expect?
I would expect the checkboxes for be checked if a setting is enabled and not if they are not.  All checkboxes seem to always be unchecked.

What behavior did you see instead?
Checkboxes are always unchecked.  Clicking the option does not change the appearance, but messages to Nearby Chat indicate the the value has been changed.

What steps does someone need to take to reproduce the problem?
Open collar menu.
Select RLV->Relay->OFF, Ask, Auto,or Wearer.
Check boxes will not change.
Note: the checkboxes also do not reflect the values configured in .settings.

**Comment by zontreck** [comment]
Attributing this to a font issue. Will change default checkboxes font
