### ISSUE TITLE
Easy free pull requests for use in other SL type grids.

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollarTeam/OpenCollar#38]
After spending the last 4 years supporting the OC project (3.99x code) on most other SL type grids I would like to propose this as an opportunity to also make the latest OC code available to easy forking over for use on other grids.
Main changes would be just under the license part of the script to add the grid specific section of the constants like sound UUID's, textures UUID's etc so these can be easily found and changed for each grid. 
It would also need some minor code changes as some command usage do not exist in the OSSL (OpenSim Script Language) or PHLOX script engines, IE in mono "if ( (key)Kid )" is used to check if the Kid is a valid UUID does not exist on other systems so you have to either check string length or  llParseString2List(Kid, ["-"], []);  and count the list length.
I would be happy to look into this myself to feed back into the main project if excepted

**Comment by nirea** [comment]
It sounds like a good idea to me, though I don't have the bandwidth to lead the effort or experience in OpenSim to test.  If you want to lead the charge, that would be awesome.

Maybe all UUIDs should be in grid-specific text files, and loaded from the repo via HTTP.  Then you could have one file for Agni, one for Aditi, one for each other grid you'd like to support.

**Comment by silentwar-resident** [comment]
How did you “load” textures from repo via http into sl?

I thought it has to be stored in a avi in order to do that…

lol

**Comment by CorwinDavidson** [comment]
Upload assets to specific grid
Record UUID's for each asset
Save UUID info to a text file (or database) for that grid
llHTTPRequest UUID info for current grid

**Comment by silentwar-resident** [comment]
ahh got it :-)

**Comment by lord9** [comment]
I think this is an excellent idea.  In the past, in OpenSim, the grids who adapted OC then protected the adapted code from others being able to use it.

**Comment by silentwar-resident** [comment]
why close the scripts (no mod) leave it open source!

**Comment by SilkieSabra** [comment]
OC is not currently heading any projects for OpenSim.
