### ISSUE TITLE
V8.0A2 cagehome menu is broken 

### ISSUE THREAD

**Issue by tomtenberge** [OpenCollarTeam/OpenCollar#381]
V8.0 A2

expected: a menu for the cagehome plugin

delivered: no menu

reproduction: try to open the cagehome menu

**Comment by tomtenberge** [comment]
OC_cagehome

not initiating when prompted to initiate during typical menu scrolling through main menu, into apps menu, then attempting to launch it from apps menu.

path: main menu -> apps -> cagehome (does nothing currently)

**Comment by zontreck** [comment]
Could not reproduce. Fixing menus was required
