### ISSUE TITLE
V8.0A2 camera plugin is broken

### ISSUE THREAD

**Issue by tomtenberge** [OpenCollarTeam/OpenCollar#382]
V8.0 A2

expected: a menu for the camera plugin

delivered: no menu

reproduction: try to open the camera menu

**Comment by zontreck** [comment]
when you say camera menu, what is the menu path?

**Comment by tomtenberge** [comment]
OC_camera

not initiating when prompted to initiate during typical menu scrolling through main menu, into apps menu, then attempting to launch it from apps menu.

path: main menu -> apps -> camera (does nothing currently)

**Comment by zontreck** [comment]
Linking to the relevant app for reference: https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/Apps/oc_camera.lsl

**Comment by zontreck** [comment]
Could not reproduce. Fixing menus was all that was required for the menu to open properly.
