### ISSUE TITLE
V8.0A2 GLOBAL=touchNotify~1 not working

### ISSUE THREAD

**Issue by tomtenberge** [OpenCollarTeam/OpenCollar#383]
the last .settings notecard command in this string is nonfunctional in latest 8.0.0002 alpha.

`AUTH=owner~5fd80a5a-a85d-494b-a471-290c75885950~norun~1
GLOBAL=prefix~eden
GLOBAL=DeviceName~Flutter's Mind
GLOBAL=DeviceType~Heart
GLOBAL=WearerName~Flutter
GLOBAL=safeword~teacup
GLOBAL=channel~0,TRUE
GLOBAL=touchNotify~1`

there is no message when someone touches it.

**Comment by zontreck** [comment]
Implementing touch notify now
