### ISSUE TITLE
V8.0A2 problem with prefix sit command

### ISSUE THREAD

**Issue by tomtenberge** [OpenCollarTeam/OpenCollar#384]
What version of OpenCollar are you using?
latest 8.0.00002 alpha

What behavior did you expect?
LLdialog drop down of sit-able objects within range of the wearer be listed, and clickable.

What behavior did you see instead?
precisely nothing. fuckall to be exact.

What steps does someone need to take to reproduce the problem?
use the command on the channel of the wearers collar: prefix sit

**Comment by zontreck** [comment]
Investigating

**Comment by zontreck** [comment]
Could not reproduce. Will leave ticket open until v8.0 Alpha 3 is released
