### ISSUE TITLE
Blocked Avatars can still Capture

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#385]
This was sent me by Trinkitz inworld.

Blocked Avatars should also be blocked from using Capture.  

An owner blocked Trinkitz on her own collar.  When she touched her collar after being blocked, she got a Capture offer from the collar.  While she was not able to capture herself, it seems likely that the effect of the block is simply to remove the avatar from any access; which would leave them still able to use Capture.  If so, this is an undesireable capture feature amounting to a security issue.

Block the wearer from the collar.
Have them touch the collar with capture enabled.  Do they get a capture opportunity, and what happens if so?
Repeat test and block someone other than the wearer.

In V 7.5 the wearer cannot be blocked from their own collar so this does not arise.
A test on V 7.5 also confirmed that blocked avatars do not get a capture message on touch.

Ancillary:  Do we want wearers to be able to be blocked in V8?

**Comment by zontreck** [comment]
Looking into it

**Comment by zontreck** [comment]
A fix has been implemented. Testing will be required for this fix

**Comment by zontreck** [comment]
Fix did not work properly, or at all. Reopening the ticket and moving back to the working on status
