### ISSUE TITLE
8.0A3: # Folders under RLV is not working

### ISSUE THREAD

**Issue by lilerin2020** [OpenCollarTeam/OpenCollar#387]
What version of OpenCollar are you using?
8.0.0003
What behavior did you expect?
to open and list my #RLV Folders from my inventory
What behavior did you see instead?
closes menu 
What steps does someone need to take to reproduce the problem?
/1 [prefix]menu
click RLV
click # Folders

**Comment by zontreck** [comment]
It does work, have you done any troubleshooting steps?

**Comment by zontreck** [comment]
Hmm, it works by chat command - looks like the state manager is not picking up the menu button though.

**Comment by lilerin2020** [comment]
I have tried to reboot the collar and use the fix menus, after the fix menus I no longer have an RLV menu option before that is was giving a script runtime error on oc_folders script

**Comment by zontreck** [comment]
This was directly related to state manager.
Fixed in alpha 4
