### ISSUE TITLE
UNSIT button in Force Sit Menu not working

### ISSUE THREAD

**Issue by lilerin2020** [OpenCollarTeam/OpenCollar#390]
What version of OpenCollar are you using?
8.0.0005
What behavior did you expect?
To stand up after released from force sit
What behavior did you see instead?
Nothing ( when I used tha chat command to unsit that did work)
What steps does someone need to take to reproduce the problem?
open collar menu
RLV
Force Sit
Choose any place to sit
click [UNSIT] button

**Comment by zontreck** [comment]
Investigating
