### ISSUE TITLE
unable to update OC7.3 or OC7.1 to 8.0A5

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#393]
What version of OpenCollar are you using? 7.1, 7.3

What behavior did you expect? expected updater to install 8.0A5 and copy settings

What behavior did you see instead? Installer hangs at 14% after moving oc_auth. waited 20 minutes three times before deleting the updater and collar to try again

[09:56:40] Tara's Collar: Searching for nearby updater
[09:56:46] Tara's Collar: Update will start shortly. Checking for existing settings
[09:57:07] Tara's Collar: * oc_settings has not yet sent us settings! Retry (Count:2)
[09:57:07] Tara's Collar: * oc_settings has not yet sent us settings! Retry (Count:2)
[09:57:18] Tara's Collar: Got Settings! Starting Update
[09:58:52] Authorizer: Moving oc_auth!

What steps does someone need to take to reproduce the problem?
attempt install of OC 8.0A5 over OC 7.1

**Comment by zontreck** [comment]
Investigating

**Comment by zontreck** [comment]
Related: #374

**Comment by zontreck** [comment]
7.0 -> 8.0 A5 works
note: you do end up with duplicated animations

**Comment by zontreck** [comment]
3.x -> 8.0A5 works
note: no glitches

**Comment by zontreck** [comment]
7.3 -> 8.0A5 works
note: you temporarily end up with duplicate animations. Collar appears to clean them up during the finishing install phase.

**Comment by zontreck** [comment]
Could not reproduce this bug. After changing the updater .name notecard to use the flag: AppInstall instead of the version number, the installation works fine. The appinstall is a separate bug resulting in the deprecated message.
