### ISSUE TITLE
OC8.0 B3 relay won't accept force sit commands when in ask and trust owners is checked

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#394]
What version of OpenCollar are you using? 8.0 Alpha 5

What behavior did you expect? Expected a dialog box to display asking for permission for RLV control if object is not owned by a collar owner OR the relay to act as if in 'auto' mode if the object owner is listed as an owner on the collar.

What behavior did you see instead? When being captured/grabbed by an RLV object AND 'Trust Owners' is checked, the relay acts as though it were off. 

What steps does someone need to take to reproduce the problem? set internal relay to 'ask', enable 'trust owners', then attempt RLV grab/capture from an object

**Comment by zontreck** [comment]
Is this still an issue in Beta 1?

**Comment by zontreck** [comment]
test

**Comment by zontreck** [comment]
test

**Comment by zontreck** [comment]
Is this still an issue in Beta 2? This ticket will be closed once Beta 3 goes out if no response is received.

**Comment by boundtight** [comment]
Yes, this is still an issue even in Beta 3

**Comment by zontreck** [comment]
Okay thank you. I will update ticket status for beta 3 then
