### ISSUE TITLE
OC 8.0A5 no confirmation when wearer is removed from owner list

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#396]
What version of OpenCollar are you using? 8.0A5

What behavior did you expect? When an owner removes the wearer from the owner's list a confirmation should be presented to the wearer so they may stop or accept the action

What behavior did you see instead? No confirmation, wearer was removed from owner's list immediately

What steps does someone need to take to reproduce the problem? Have an owner attempt to remove the wearer from the owner's list in their collar

**Comment by zontreck** [comment]
Verified. Implementing a fix

**Comment by zontreck** [comment]
A fix is now implemented. Verifying that the patch works

**Comment by zontreck** [comment]
Verified. Fix works though not entirely. Reopening

**Comment by zontreck** [comment]
Fix verified
