### ISSUE TITLE
Integrated V 7.5 Relay allows global safeword in Helpless mode

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#399]
Tested the integrated relay with Auto and Helpless Set.

Helpless should both prevent the REFUSE button from showing up in the relay menu, and also disable the global collar safeword from releasing the relay.

It did stop REFUSE but the global safeword still ended the trap.

**Comment by zontreck** [comment]
Not a bug
Aug 27, 2020 12:54:43 PM Silkie Sabra <notifications@github.com>:

**Comment by zontreck** [comment]
This is a feature. Collar safeword should not be limited unless safeword is disabled globally
