### ISSUE TITLE
[Request] oc_settings behavior

### ISSUE THREAD

**Issue by MikuGit** [OpenCollarTeam/OpenCollar#400]
7.1 / latest in the repo

Expecting that when LM_SETTING_REQUEST, LM_SETTING_SAVE or LM_SETTING_DELETE is sent to settings, settings respond with LM_SETTING_RESPONSE or LM_SETTING_EMPTY (though it seems that EMPTY is being replaced with LM_SETTING_RESPONSE with "empty" as a key, which I guess is fine)

Reading the code in the repo, since 7.1 it has started responding with RESPONSE on SAVE, which is good. But DELETE and REQUEST (when no value is found) doesn't work consistently. 
DELETE responds with LM_SETTING_REQUEST, which makes no sense at all.
REQUEST responds with LM_SETTING_RESPONSE with "empty" as a key value. It seemed to me that LM_SETTING_EMPTY was fine as it was, but this is also fine, though it won't be backwards compatible with old plugins. However if this is to be used, LM_SETTING_EMPTY should be deleted entirely as a reference in the script. DELETE and REQUEST without a value present should regardless respond exactly the same way.
Essentially, there would be 3 types of requests, REQUEST, SAVE and DELETE and there would be two types of responses, RESPONSE and EMPTY (or RESPONSE with "empty" key). Other scripts are made to listen for the responses and they send the requests.

I don't know what has happened in the other scripts since 7.1, but I do know that in 7.1, some scripts were detecting settings changes by looking for SAVE and DELETE, that should change. I do recognize that for the changes above to happen, those scripts would have to be updated as well, if they aren't already, or functionality would potentially break.

According to the message of the latest commit on oc_settings, it does seem that a rewrite is happening, so I hope that what is stated above is being considered for the rewrite. Though this may very well already be the plan and I will have wasted my time writing this, but that is also perfectly fine and in that case, just close this.

**Comment by zontreck** [comment]
Empty is being deprecated yes. It is hardly ever used in scripts, and 99% of the time, scripts look for the RESPONSE only, not even for the delete signal. This is also a optimization thing, if a script checks for...
```lsl
if(kID == "empty"){
// do delete/reset variable behavior
}else{
// restore variable from settings
}
```

**Comment by zontreck** [comment]
closing this ticket though due to deprecation of LM_SETTINGS_EMPTY

**Comment by zontreck** [comment]
Another point: Although deprecated does not mean it will be removed from the scripts until 8.0 is fully released. it just has been taken out of being used.

**Comment by MikuGit** [comment]
Well, even if LM_SETTINGS_EMPTY is deprecated, the rest is still valid. So I think that's the wrong reason for closing it.
If on the other hand, the behavior stated is already planned or being scrapped, that's a reason.
LM_SETTINGS_EMPTY is however hardly the main topic of the issue.
