### ISSUE TITLE
oc_folders for V8 needs chat commands plus public access in Configure is not allowing public access

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#401]
The version of oc_folders that is V8 compatible from the git:
A user came in to say that she set public access in the Access menu and in oc_folders configuration and it does not grant public access to oc_folders.

We tested Owner, Trusted, and Public on a stock collar and the collar with the recent oc_folders.  Owner, Trusted work fine on both. Public works on V 7.5 but not on V8.  You can set it in configure but it does not confer actual public access to folders even when public access is set in auth.

Also:  Traditional chat commands &[foldername], &&[foldername], -[foldername] and --[foldername] are not functioning in oc_folders for V8.

**Comment by zontreck** [comment]
roan we discussed the & commands......... those were moved to oc_outfits

**Comment by zontreck** [comment]
it has chat commands though

**Comment by SilkieSabra** [comment]
no, it was + not add that should have been moved to oc_outfits.  + is WEAR, & is ADD. That conforms to the distinction between folders and outfits nicely.

**Comment by zontreck** [comment]
okay
https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/collar/oc_folders.lsl#L182-L187

& and - are commands for folders. Not && and not --.  and i believe it has to be: `prefix & folder`

**Comment by zontreck** [comment]
space is required in this version

**Comment by SilkieSabra** [comment]
so there are now spaces required where before spaces would actually not work

**Comment by zontreck** [comment]
as for public i'll look at it and will fix it so it doesnt need a space anymore, make space optional..

**Comment by SilkieSabra** [comment]
Is there a reason for the spelling change? To conform to the other commands?

**Comment by SilkieSabra** [comment]
OK!

**Comment by zontreck** [comment]
what spelling change?

**Comment by SilkieSabra** [comment]
the space or lack thereof.  I just tested [prefix] & [folder} and got nothing

**Comment by zontreck** [comment]
ok no it was just overlooked. i'll look into this in a day or so

**Comment by SilkieSabra** [comment]
yay ! I caught a bug

**Comment by zontreck** [comment]
fixed public access in folders. This will be in Alpha 9
