### ISSUE TITLE
OC Anim Alpha 6 Couples animation fails to play for wearer.

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#402]
Alpha 6 Dev version of oc_folders running with mostly V 7.5 scripts:  Couples animations fail for the wearer.  
Wearer delivers couples animation request.  Partner accepts.
Animation plays correctly for partner but not for wearer.
Tried with footkiss and hug.
Tried with AO on and off, collar pose on and off, both on and both off.
When both AO and collar pose are off, there is a visible conflict between the couples animation and the system animation, leading to a repeated animation attempt or "shiver".

**Comment by reubenshaffer2** [comment]
this seems to be fixed by the recent updates to oc_anim
