### ISSUE TITLE
OC 8.0A6 - RLV Folder Browser does not appear to accurately display worn/unworn items

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#403]
What version of OpenCollar are you using? 8.0 Alpha 6

What behavior did you expect? Items not currently worn shouldn't show up as a half-filled circle or fully filled square in the RLV folders menus

What behavior did you see instead? Some folders show up as partially or fully worn when they are not, see sample screenshot
https://gyazo.com/c83586b2a839b29c88ceb0bca9a4bc41

What steps does someone need to take to reproduce the problem?
Casually browse through the RLV folders available in the collar

**Comment by zontreck** [comment]
this was resolved
