### ISSUE TITLE
8.0A3-6: Multi-menu dialogs all return wrong result on any page but the first one

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#404]
What version of OpenCollar are you using? 8.0 Alpha 6

What behavior did you expect? Selecting a folder on the second page of a menu should open that folder

What behavior did you see instead? Selecting a folder from the second page opens the corresponding folder of the first page

What steps does someone need to take to reproduce the problem? Browse through the RLV folders of the wearer (where multiple pages are required to display items) and select a folder from a second page...the corresponding entry on the first page will open instead

**Comment by zontreck** [comment]
This is a issue with oc_dialog is not isolated to oc_folders

**Comment by zontreck** [comment]
Narrowed down the problems to lines 201 through 233 of oc_dialog. Will resume troubleshooting this tomorrow

**Comment by zontreck** [comment]
Reopening until can be verified 100% as fixed.
