### ISSUE TITLE
Integrated relay does not recapture on login, when trapped in a rlv zone

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#405]
Integrated Relay in OpenCollar V 7.5:  When logging off in a rlv zone type cage on a timer, on relog there's a message from the trap:  "[Wearer]'s relay refused my commands!"  

This was tested with four different wearers in a cage using CC Genesis cage scripts, and a KHINK slave jar which was the sit target control.  The Sit target recaptured with all restrictions.  
V 7.1 Relay did not result in that message when relogging inside the cage, and all restrictions were enforced on relog. 
 V 7.5 integrated relay did not re-assert the restrictions from the cage on relog, and delivered "relay refused my commands."

Wondering if this has something to do with the single source construction of the relay.

**Comment by SilkieSabra** [comment]
My theory above got shot to hell because now my Khink trap is doing it again too, after I walked into the RLV zone cage yesterday and got "Wearer's relay refused my commands" -- The Khink message is slightly different and engages when first trapped, not on recapture " RLV Safeword Detected"  but Helpless is on, there was no safeword sent to the relay.

**Comment by SilkieSabra** [comment]
Also the Khink trap is ejecting almost immediately, not waiting for a relog.

**Comment by lillith-xue** [comment]
For some reason the relay receives a REBOOT linkmessage that resets the script before or sometimes after the recapture took place. 
Also the recapture takes place way too early. The restrictions are sometimes overridden by oc_rlvsuite.
When moving the Ping-message from on_rez event to RLV_ON, and removing the llResetScript() inside REBOOT it works. But that's probably not the best Solution.

The whole recapture code from the old Relay is still present in oc_rlvsys wich is also being reset before the code can do it's job.

**Comment by lillith-xue** [comment]
Just Tested: This Happens with 7.5 and 8.0 versions

**Comment by zontreck** [comment]
I'm not convinced this is entirely due to the reboot signal but if it is, relay just needs to save the temporary device to settings, and then send pong if on settings load the temp device exists & no device is set in the script. Very important that it check for no active device in the script's memory itself. On release function this token needs to be deleted. Will work on this fix in an hour or two after i eat some breakfast.
