### ISSUE TITLE
8.0a5 Relay Locks the collar, but fails to unlock it after a !release

### ISSUE THREAD

**Issue by lillith-xue** [OpenCollarTeam/OpenCollar#406]
What version of OpenCollar are you using?
8.0a5
What behavior did you expect?
Collar becoming locked when the relay has active restrictions, but unlocks when the relay has no active restrictions left.
What behavior did you see instead?
The Collar is still locked after the Device executed a !release
What steps does someone need to take to reproduce the problem?
- Wear an unlocked Collar
- Become trapped in a device
- Let the device release you
- The Collar is still locked

**Comment by zontreck** [comment]
Test it against Alpha 6 please.

**Comment by zontreck** [comment]
On hold until tested against the latest Alpha
