### ISSUE TITLE
Check boxes do not properly show for all users due to font not being universal

### ISSUE THREAD

**Issue by reubenshaffer2** [OpenCollarTeam/OpenCollar#409]
What version of OpenCollar are you using?
7.5

What behavior did you expect?
Checked and unchecked boxes

What behavior did you see instead?
Empty box (no character?) for all

What steps does someone need to take to reproduce the problem?
Use a collar with the latest OC scripts in a recent version of Firestorm Viewer for Linux

-----------------
However, the steps to reproduce probably depend on several other factors...
This seems to be a character encoding issue, but I am able to see the characters as what appears to be a dithered or solid square here in my browser.  In the viewer, however, they seem to be missing characters or something.  I do not fully understand how multi-byte character encoding, fonts, and everything really all fit together in this puzzle, but I can tell you that reverting to g_lCheckboxes=["☐","☑"] has corrected the problem for me.  This had to be done in a number of scripts in order to correct the issue in the entire collar.

**Comment by reubenshaffer2** [comment]
Further investigation reveals that this is not an issue specifically related to Firestorm/Linux but more localized.  I am uncertain what the cause of the problem is, or how many users could be affected by this.  I may need to do some more research to determine if there is something in particular with my setup causing this to know how many others may be affected.

**Comment by reubenshaffer2** [comment]
Further investigation reveals that this is not an issue specifically related to Firestorm/Linux but more localized.  I am uncertain what the cause of the problem is, or how many users could be affected by this.  I may need to do some more research to determine if there is something in particular with my setup causing this to know how many others may be affected.

**Comment by reubenshaffer2** [comment]
I am unable to find any obvious reasons for the characters not displaying here.  Perhaps someone that understands locales, encodings, and fonts a little bit better can offer some suggestions.  Until we all know the reason behind this, it is difficult to know whether or not this is a real issue with OC.

**Comment by zontreck** [comment]
This is known.

This is also why you can change the checkboxes

Global_checkboxes

Just set the value to a CSV list equalling: unchecked,checked

For example in. Settings note: global=checkboxes~[ ],[X]

**Comment by zontreck** [comment]
Making todo in v8.0

**Comment by zontreck** [comment]
If anyone wants to address this in a PR you can either modify every script.  Or set it to auto populate in oc_settings with a new value. 

Need universal symbols for checkboxes in one of the common fonts that ship with all operating systems. The ones currently used appear to be from a Microsoft only font

**Comment by reubenshaffer2** [comment]
I may be able to do this work.  I need to see if your solution really hits every script's checkboxes or what.  If so, shouldn't there be just a single global default rather than a hard-coded (inconsistent) initialization of g_lCheckboxes in each script?

**Comment by zontreck** [comment]
if it is a new default and you feel like editing every script (which is what i'd do) - then go right ahead.

But yes making a new setting should override it anyhow. Most scripts should be using the global_checkboxes flags.

**Comment by zontreck** [comment]
Fixed in #410
