### ISSUE TITLE
8.0 A7-8 : Weld flag gets mistakenly set

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#415]
Weld flag set in error due to a few things wrong in the code

**Comment by zontreck** [comment]
Fixed in latest commit - Requires verification of fix.. Fix is implemented in the oc_settings script.

**Comment by reubenshaffer2** [comment]
I can verify that when the collar's oc_settings script is updated, it does not weld itself any more.  I cannot verify that it will remove the incorrectly set weld flag from the last alpha.

**Comment by zontreck** [comment]
i was also able to verify this thanks @reubenshaffer2  for also validating this fix. Marking as complete
