### ISSUE TITLE
uuid:menu on channel -1812221819 not recognized

### ISSUE THREAD

**Issue by reubenshaffer2** [OpenCollarTeam/OpenCollar#418]
What version of OpenCollar are you using?
8.0
What behavior did you expect?
open collar main menu
What behavior did you see instead?
ignored
What steps does someone need to take to reproduce the problem?
use 8.0, attach AO, click "Collar Menu"

-----

It seems that a couple different things, including the AO, bring up the collar menu by saying "<avatar_key>:menu" on channel -1812221819 (the relay's channel, I believe).  It doesn't really seem like a relay function aside from it using that channel.

I know that I found this command being used by the AO.  I think I saw it in something else, but I am unsure what it could have been.  Anyway, there is no code in the current collar version to handle this, and therefore a menu is never given.

**Comment by zontreck** [comment]
Deprecated with remote API. The AO will be using a menu in a different way as it will be rewritten as an Addon.
