### ISSUE TITLE
Feature Suggestion: external relay compatibility

### ISSUE THREAD

**Issue by reubenshaffer2** [OpenCollarTeam/OpenCollar#419]
What version of OpenCollar are you using?
8.0

Possibly a duplicate, and probably related to #188.

I think it would be nice if the collar's integrated relay did a check for an external relay and, if found, disables the integrated one.

In addition, it seems that some control of the external relay could still be done using the menu within the collar as it was in previous versions.  It could even be possible, at this point, to disable/detach the external relay and switch the integrated one back on from the menu.

It seems that some user prefer to use the external relay over the integrated ones in the collars, and while the integrated one seems to be a good addition, it seems that this added flexibility would likely be an improvement over other systems.

There are a number of questions that arise from this, however, particularly in regard to how settings would be synchronized between the collar(s) and relay.  I think we would need to reach some consensus on this before anything could be implemented.

Detecting the other relay and then changing behavior of the integrated one is fairly trivial and I do have the code for this already.  There are a number of methods for handling control of the external relay, but some of it depends on the answers to the questions I mentioned.

To clarify, I am not suggesting that we give out an external relay with the collar or eliminate the integrated one.  I am simply suggesting that oc_relay have some compatibility with some external relays if the user prefers to use one of them instead (aside from being able to just disable one of them manually).

**Comment by zontreck** [comment]
Community feedback essentially said: no external relays
