### ISSUE TITLE
Add CONTRIBUTORS file

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#42]
In my branding cleanup I also cleaned out the ASCII art headers in all the files.  I left comments about particular scripts being based on some earlier work.

In place of having a contributor list in each source file, let's simplify and have just one project-wide CONTRIBUTORS file.  We can compile that from the headers in the old version.  We should also instruct new contributors to add their names when they send a pull request.

Note that this is more about recognizing people's contributions than it is about asserting copyrights.  The copyright notices in the files were never legally valid or useful anyway, since they didn't use the names of legal entities.  (See http://info.legalzoom.com/correctly-format-copyright-20057.html.)  A single CONTRIBUTORS file is cleaner, lower maintenance, and more common in the open source world.

**Comment by nirea** [comment]
Though I cringe at the thought of the maintenance burden, I'm hearing a preference from some for contributor lists in the files themselves.    We can bring that back if I'm in the minority (but without ASCII art boxes and cartoons, please).

**Comment by TakatSu1** [comment]
My vote is for the individual contributor file.  Having said that though, there is something to be said for a header on each file stating who did what work.  Yes, I know, you can get that from GIT too, but there may be people who are starting from the scripts in the collar itself rather than from a GIT clone/fork operation.  They may not be "professional" developers who understand or even use outside-the-SL-world tools.

So I'm sort of on the fence about this one.  I can see advantages and disadvantages to both.

**Comment by WendyStarfall** [comment]
The copyright header is to assert the copyright of the authors of the code, and in this case, the authors chose to use the names of their Second Life user accounts. That is in simple terms described on our EULA:

> OpenCollar Six (including but not limited to collar, remote, AO, apps, plugins and selected accessory) is open source software, built by residents of the Second Life® virtual world and published by virtualdisgrace.com. You are free to use, and to distribute copies of OpenCollar Six to your friends. You also are welcome to modify the source code to meet your personal needs and you are allowed to distribute your modified versions under applicable terms.

My copyright is also valid when I choose to use a moniker or nickname, especially when taking the nature of this particular software into account, where some privacy may be preferable.

In the current state of your fork, you have merged 1,214 of my commits.

I'm not speaking for every other author, but I want that my name is noted where it rightfully belongs, and that is in the copyright notice of every program. Each of these programs compile individually.

If you need guidance, you can to take a look at the General Public License, version 2 that all the scripts are licensed under. Link: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html#SEC4

Our original headers stated the revision number, the name of the program, the names of the authors, the GPL copyright notice and the link to the file's directory in our upstream git repository.

**Comment by nirea** [comment]
I understand your position Wendy, but I suspect that the lists in the old files weren't even accurate.  Has everyone who's ever touched any file had their name added to that file?  I don't want to give the impression that we're providing that level of copyright tracking. I've never heard of an open source project doing so.

**Comment by GarvinTwine** [comment]
Serious? This is complete against all this project claims to be about.
First remove contributors from your "official" contributor list.
Next step is removing every single entry of contributions from every single script hiding being "re-branding".

And again nothing but assumptions and suspects here, without any clue about how hard Wendy tried over the years to catch every little contribution and make sure to have their names in the scripts.
Sure there might be one missing but I am sure that more than 95% are covered and if anybody said something up would have been added anyway.
Wendy did this as accurate as possible and extra added et al for those who might have been missed.

I would like everybody to look at one example as the new oc_ao script I made basically from scratch, but fragments of other scripts went into it, too...
https://github.com/VirtualDisgrace/opencollar/commit/5be868da13fc13c061dd39e214e7b366b0c2d917#diff-10cc2f8c6bfca525161272776a8678b9

I am sorry but this is by now nothing more but the attempt to claim everything for oneself and remove any other contributor from scripts located in Second Life and hide them in a list somewhere here.
Trying to get the ones who did the most to be forgotten asap.

I cannot express how low I feel about what is going on here.

**Comment by tonyasouther** [comment]
This changeset is nothing but a determined attempt to remove credit for work that's gone one over the past few years. The fundamental currency of the world of open source programming is credit for contributions. That's why Firestorm references contributors who have long since left the project and in some cases even Second Life.

Get rid of the ASCII art if you wish, but at least leave the individual credits in each file.

**Comment by nirea** [comment]
Given that those who prefer the CONTRIBUTORS file have just a mild preference, while those who prefer individual per-file lists have a very strong preference, I've implemented the former in https://github.com/OpenCollarTeam/OpenCollar/commit/e06c360505fa2c9f40a91bda078a756d902e32b3.  (Following @tonyasouther's suggestion to decouple them from the ASCII art.)
