### ISSUE TITLE
OC 8.0.0 Alpha 8 Updater adds s&p_leashholder without removing S&P_leashholder

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#420]
**What version of OpenCollar are you using?**
OpenCollar 8.0.0 Alpha 8 Updater (updated from OC 7.5)

**What behavior did you expect?**
The removal of S&P_leashholder, after s&p_leashholder was installed

**What behavior did you see instead?**
S&P_leashholder still in Collar, along with the new s&p_leashholder

**What steps does someone need to take to reproduce the problem?**
Wear OpenCollar 7.5, rez OC 8.0.0 Alpha 8 Updater, update collar

**Comment by zontreck** [comment]
Resolved
