### ISSUE TITLE
OC 8.0.0 Alpha 8 Toggle AllowHiding in Settings menu needs to be selected twice

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#421]
**What version of OpenCollar are you using?**
OC 8.0.0 Alpha 8

**What behavior did you expect?**
Button "AllowHiding" in Settings menu is expected to function as a toggle: click once for off, then once for on, and vice versa.

**What behavior did you see instead?**
The button "AllowHiding" in Settings menu needs to be pressed twice before its state switches.

**What steps does someone need to take to reproduce the problem?**
Wear OC 8.0.0 A8, from main menu click Settings, then observe toggle-button "AllowHiding" when selecting and monitor chat responses.

**Comment by zontreck** [comment]
Issue resolved in modification to oc_core in Alpha 9 (I still need to upload the commit)
