### ISSUE TITLE
8.0B0.5: Access List Bug

### ISSUE THREAD

**Issue by devy-null** [OpenCollarTeam/OpenCollar#424]
### What version of OpenCollar are you using?
OpenCollar 8.0.0010

### What behavior did you expect?
Strangers should not be able to print the access list, even when the collar is set to public.

### What behavior did you see instead?
They could when the collar is set to public.

### What steps does someone need to take to reproduce the problem?
Set collar to public, and have someone else print the list.

**Comment by zontreck** [comment]
Thank you. Though this is not a security vulnerability so will receive a lower priority.
