### ISSUE TITLE
8.0B0.5: Access List Add Prompts Bug

### ISSUE THREAD

**Issue by devy-null** [OpenCollarTeam/OpenCollar#425]
### What version of OpenCollar are you using?
OpenCollar 8.0.0010

### What behavior did you expect?
The prompts given when you add someone to Owner or Trusted to display your name

### What behavior did you see instead?
The name shown is the one you tried to add; it says they are trying to add themselves.

### What steps does someone need to take to reproduce the problem?
Have someone add you to the Owner or Trusted list.

**Comment by zontreck** [comment]
Can you give me an example of what is said please and what it should say?

**Comment by devy-null** [comment]
For the on that you are adding, the popup says:

`[your own avatar link]  is trying to add you to an access list, do you agree?`

It should not be the avatar link to the one you added, it should be the wearer of the collar's.

**Comment by zontreck** [comment]
The popup i believe says the link to the person who triggered the add operation.

**Comment by zontreck** [comment]
It is intended it should say, for instance, if i try to add you,
`Tashia Redrose is trying to add you to an access list, do you agree?`

**Comment by devy-null** [comment]
That is what I would expect happens, but it was not my name when I added someone, it was theirs; therein the bug.

**Comment by zontreck** [comment]
Alright i'll check it out, thanks for the report.

**Comment by zontreck** [comment]
Looking into this now

**Comment by zontreck** [comment]
.

**Comment by zontreck** [comment]
.
