### ISSUE TITLE
8.0B0.5: (Settings > Hide) Bug

### ISSUE THREAD

**Issue by devy-null** [OpenCollarTeam/OpenCollar#426]
### What version of OpenCollar are you using?
OpenCollar 8.0.0010

### What behavior did you expect?
Consistent functionality when pressing the hide button as a stranger (public mode).

### What behavior did you see instead?
When you press the "Hide" button in the settings menu, you get the text "Access Denied to themes".
That is fine and dandy and the collar does not change visibility status, but the problem is that button itself is toggled.
Something is odd here.

### What steps does someone need to take to reproduce the problem?
Put the collar to public and have someone else press the "Hide" button in the settings menu.

**Comment by zontreck** [comment]
The hide button is one that i have been considering migrating to a different script. The toggle is stored in one script, and the actual action in another script. (Themes). While oc_core handles the menu aspect.

**Comment by zontreck** [comment]
Verified. With new themes the error no longer displays but the button does still toggle.
