### ISSUE TITLE
8.0B0.5: Access Denied Estetic Bug

### ISSUE THREAD

**Issue by devy-null** [OpenCollarTeam/OpenCollar#427]
### What version of OpenCollar are you using?
OpenCollar 8.0.0010

### What behavior did you expect?
You get an "Access Denied" message and the HUD reappears when you press an button you should not have access to.
And it to work the same way everywhere.

### What behavior did you see instead?
There are two type of problems:

Nothing happens, the HUD stays closed:
- Settings > AllowHiding
- Access > Runaway

Nothing happens, the HUD reopens.
- Settings > Print
- Settings > Load
- Help/About > Update

And maybe other places.

### What steps does someone need to take to reproduce the problem?
Set the collar to public and have a "stranger" click the buttons.

Of course, this does not impact the usage of the collar in any meaningful way, it might just be a bit annoying and lead to a bit confusion. But it would be nice if it got fixed and not forgotten.

**Comment by zontreck** [comment]
What HUD?
There is currently no HUD of any kind for 8.0

**Comment by zontreck** [comment]
My only guess is you are referring to attempting to use the remote (7.5) with (8.0) and that is not compatible. There will be a new remote entirely for 8.0

**Comment by zontreck** [comment]
More information is still required

**Comment by SilkieSabra** [comment]
They might have been using "HUD" to refer to the collar menu

**Comment by zontreck** [comment]
yes perhaps roan. Can you try to reproduce this please?

**Comment by zontreck** [comment]
Verified by assuming HUD means menu. Implementing a fix now.
