### ISSUE TITLE
Leash options "Turn" and "Strict"

### ISSUE THREAD

**Issue by MinesweeperM** [OpenCollarTeam/OpenCollar#429]
What version of OpenCollar are you using?  8.0.0009

What behavior did you expect? 
In "leash - Configure" are two options - "Turn" and "Strict"; expect they must work as checkboxes.

What behavior did you see instead? 
They both always displayed as unchecked. And seems that "Turn" is always on, and "Strict" is always off.
Also, restrictions still not contain "sittp=n"

What steps does someone need to take to reproduce the problem?
Just try to use "Turn" and "Strict" options in "leash - Configure".

**Comment by zontreck** [comment]
I will look into it but those two features are partially also broken in 7.5, so it has been on my todo list
