### ISSUE TITLE
Integrated relay refusing ping pong

### ISSUE THREAD

**Issue by LSunkiller** [OpenCollarTeam/OpenCollar#434]
What version of OpenCollar are you using? 7.5

I contacted Chorazin Allen because I had messages that a cage from him didn't grab my sub upon login.
[13:54:25] Resident is online.
[13:54:29] Cell: Resident returned
[13:54:34] Cell: Resident's relay refused my commands! (ping,76e87214-b117-ea18-5389-724219cc6aaf,!pong,ko)

The reply I got was that the relay doesn't seem to properly handle this protocol:
"The cell's not the problem here, it's the RLV relay your sub is using. Ping/pong is a protocol used with relays to reinstate a session and the relay's rejecting it for some reason. Make sure the relay is not in 'Ask' mode or any other setting that requires manual confirmation. If that doesn't work try a different relay - it could be that the one in use now doesn't support ping/pong properly. "

The relay was set to Auto and trust owner, the cell is on my own land and rezzed in my name.

I get that the integrated relay is a slimmed down version, but is that issue the result of a design choice? or a bug?

**Comment by zontreck** [comment]
This is already fixed.  The fix requires v8
