### ISSUE TITLE
OC8.0 B3 Bell becomes visible when locked

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#446]
What version of OpenCollar are you using? 8.0 Beta 3

What behavior did you expect? When locking the collar the only prims which should change visibility are 'lock' prims

What behavior did you see instead? The bell becomes visible when the collar is locked, requiring the user to go to the bell app and first show, and then hide the bell to make it invisible again

What steps does someone need to take to reproduce the problem? wear collar with 8.0 Beta 3 and a bell. Ensure bell is invisible to start and then lock the collar. The bell is now visible.

For this collar the bell is link number 9/27 and has 'Bell~notexture' as its description. It's name is simply 'Bell'. There are no lock prims to turn visible/invisible with the locking/unlocking of the collar

Issue not present in Beta 2

**Comment by felkami** [comment]
Bug verified to exist in RC2
