### ISSUE TITLE
Feature request: Localization (translation options) in collar

### ISSUE THREAD

**Issue by felkami** [OpenCollarTeam/OpenCollar#449]
Per discussion in world, a system where the displayed language is localized to the language of the user.

One possible structure for this:
When localization is enabled, oc_dialog listens on DIALOG_TRANSLATE instead of DIALOG.
oc_translations listens on DIALOG, translates the text, then broadcasts on DIALOG_TRANSLATE

Blockers:
How much is the real demand for this feature?
What is the feasibility on getting people to translate this?
Can this be made resilient against changes in dialog text when updates are done?

**Comment by Medea-Destiny** [comment]
In theory we could have OC_dialog pass all input to a translation function that looks for a localization notecard file, but this would be slow as hell and we'd have to maintain a translation table and find people willing to do localization. It's a nice idea, but closing this as impractical for now.
