### ISSUE TITLE
collar reseting owners and remote ignoring

### ISSUE THREAD

**Issue by TyrantGnome** [OpenCollarTeam/OpenCollar#454]
What version of OpenCollar are you using? 8.0.0100

What behavior did you expect? ownership reset and no Virtual Disgrace(tm) Owner Remote response

What behavior did you see instead? nothing

What steps does someone need to take to reproduce the problem? i didnt do anything given that it was another persons collar that did this after updating

**Comment by zontreck** [comment]
Virtual Disgrace is not opencollar.

**Comment by zontreck** [comment]
This issue will be closed because a third party product was used which was meant for a different product.
