### ISSUE TITLE
Auto TP & Unwelding option needed

### ISSUE THREAD

**Issue by Nevaehrose1** [OpenCollarTeam/OpenCollar#468]
What version of OpenCollar are you using?
8.0
What behavior did you expect?
Auto TP to work as previous 7.5  and  a way to unweld so able to unlock collar if needed
What behavior did you see instead?
wouldnt auto tp and would like to see an unwelded option or an option to unlock the collar
What steps does someone need to take to reproduce the problem?
Im not sure?

**Comment by zontreck** [comment]
Check rlv settings

**Comment by zontreck** [comment]
Unweld not possible

**Comment by zontreck** [comment]
Will be after release

**Comment by zontreck** [comment]
Why you think there was a consent/ warning

**Comment by zontreck** [comment]
Only thing here possibly a bug is auto tp. Just check the exceptions settings

**Comment by meganlawalert** [comment]
Can we just step back for a moment and consider how silly an 'unweld' feature is?  The entire idea of welding a collar is, at its essence, supposed to be irreversible without destroying the collar.  If you want the collar to be removable without destroying it, don't weld it.

**Comment by zontreck** [comment]
Correct megan. There will be a way though after release but it is irreversible as of this moment

**Comment by zontreck** [comment]
@Nevaehrose1 

Can you tell me if the person offering you a teleport is set on the collar as owner or trusted? Trusted is not auto tp by default

**Comment by SilkieSabra** [comment]
Let us not do user support in the git issues page.

**Comment by zontreck** [comment]
@SilkieSabra not trying to. Trying to find out what this person means about auto tp not working. Did they contact the main group for support earlier?

**Comment by zontreck** [comment]
This issue cannot be reproduced.

Please see the below note for troubleshooting tips. Do not reopen this issue.

<details>
<summary>Troubleshooting</summary>

Auto Teleport is not working
```
1) The person must be set as owner on the wearer's collar
2) Check exceptions: RLV -> RLV Settings -> Exceptions -> Owner -> refuseTP
2a) RefuseTP must be checked
3) Have the owner offer you a teleport
```

Still not working
```
1) The collar does not auto teleport you when you are leashed to the leash holder's location
```

Unweld? How?
```
1) Not possible at this time unless you have scripting knowledge and create a unweld tool. Weld should be used with caution.
```

</details>
