### ISSUE TITLE
Apps disappears on upgrade

### ISSUE THREAD

**Issue by MrGinSL** [OpenCollarTeam/OpenCollar#470]
What version of OpenCollar are you using?
8.0.0200
What behavior did you expect?
To find the pose module that was made by a vendor under apps once it was upgraded from 7.1
What behavior did you see instead?
It is not there at all
What steps does someone need to take to reproduce the problem?
have an app button in 7.1 ... upgrade and its not there.

**Comment by zontreck** [comment]
This is an app specific issue, was the app made by opencollar? If not this ticket will be closed.

**Comment by zontreck** [comment]
See ticket #469 - It is a readme.  I did not see anyone post this issue to the support groups, neither discord, nor inworld in the group chats.
