### ISSUE TITLE
No indication of whom you belong to when logging in

### ISSUE THREAD

**Issue by Seleneriver** [OpenCollarTeam/OpenCollar#472]
What version of OpenCollar are you using?
This was something that occured on the beta version of 8, recently went back to version 7.5
What behavior did you expect?
as usual when logging in with any previous version, once the collar booted it would let folk know, you belong to (username of whom you are collared to) however this was not the case with version 8 and didn't get this notice at all when logging in
What behavior did you see instead?
constant rebooting script and no you belong to a person
What steps does someone need to take to reproduce the problem?

**Comment by zontreck** [comment]
Working on this now
