### ISSUE TITLE
Stack heap collision in oc_api

### ISSUE THREAD

**Issue by Tearsarine** [OpenCollarTeam/OpenCollar#473]
What version of OpenCollar are you using? 8.0.0300

What behavior did you expect? just entered an emote and it sent stack heap collision

What behavior did you see instead? stack heap collision, reset the api

What steps does someone need to take to reproduce the problem? I honestly don't know, just said to report the collision

**Comment by zontreck** [comment]
Second Report of this received today. Looking into it.
