### ISSUE TITLE
Online Owner Checker App should have a confirm function to not spam chat & dialog

### ISSUE THREAD

**Issue by TechTheAwesome** [OpenCollarTeam/OpenCollar#477]
What version of OpenCollar are you using?
8.0.1

What behavior did you expect?
Online Owner Checker App should stop provide notification after -exit-/confirm by the collar owner. 

What behavior did you see instead?
The notification kept being spammed at the user set interval

What steps does someone need to take to reproduce the problem?
Just having the app script active with one owner registered.

Due to me having no lsl scripting experience yet, I'm unable to fix it myself. Perhaps someone would need to implement, or hook up the code to after confirm the notification is received by the collar wearer and put them in a 'exemption list' until detected as 'log-ed out' and removed?

**Comment by zontreck** [comment]
The app only messages the wearer, and is fully able to be controlled by the wearer. No confirm function is needed.

**Comment by zontreck** [comment]
Please next time ask support questions in our inworld group. This page should be used for bugs only, see #469
