### ISSUE TITLE
Collar spams furniture owners in some cases

### ISSUE THREAD

**Issue by SharieCriss** [OpenCollarTeam/OpenCollar#479]
OC Version 8.02

Problem: In some cases, furniture or translators, etc. can issue noise on the collar private channel that appears to be a collar access request to the collar, which can result in the owner of those devices getting spammed with No Access requests. 

Recommendation: Collar should check if the UID is an avatar or regular object and only notify if it was an avatar. 

Considerations: If implemented, users of Owners HUD's would not get notified if the HUD is used for collar access. IMHO, this is an acceptable limitation. The detection logic could go further and check if the requesting UID is an attachment, but there is a point of diminishing returns, it's not worth the code. Cutting down undesirable spam is more important.

**Comment by zontreck** [comment]
It should just filter out objects on the command channel.  Addons uses a very different channel.

**Comment by SharieCriss** [comment]
More info on this, apparently relay requests are hitting this function. Not sure why, but suspecting it has to do with attempting to authenticate devices owned by people authorized on the collar? Somehow it's getting through to the CalcAuth function in the API script (tested by adding a couple debugging statements on that last condition where it prints the No Access...)

**Comment by zontreck** [comment]
The relay checks the level.  I know exactly why it is doing that. Hmm ok.

**Comment by zontreck** [comment]
The auth request just needs to be updated to set the calcauth to not be verbose

**Comment by zontreck** [comment]
Though for objects on /1 or public chat,  those need to be ignored and only avatars listened to

**Comment by SharieCriss** [comment]
Checking avatar size on the last condition to check for avi or object seems like it would be a quick fix.

**Comment by zontreck** [comment]
( FOR STAFF ON DECIDING IF WE NEED 8.0.3 )
The issue here is caused by the relay calculating the auth level because it checks if Trust Owner or Trust Trusted is enabled. If they are it uses the calculated auth level to automatically grant the request. This issue is **VERIFIED**
