### ISSUE TITLE
Test/fix 'make lint' on Windows

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#48]
I just added a Makefile that allows running "make lint" to check the syntax of all LSL files.  It automatically downloads an OS-appropriate version of lslint and then runs it on each source file.  I've tested on OSX and Linux (it will now run in CircleCI each time we commit), but I don't have access to Windows.  If someone would like to get it working there, that would be awesome.

**Comment by nirea** [comment]
I might be the only person using the linter (other than CircleCI), so I'm going to close this.

**Comment by silentwar-resident** [comment]
I think cywin does that not sure… I can add 2nd acct on my windows machine at the internet hub.  Have to access on team viewer tho.
