### ISSUE TITLE
Capture ignores range limit

### ISSUE THREAD

**Issue by SharieCriss** [OpenCollarTeam/OpenCollar#480]
Version 8.02
The capture module ignores the range limit setting.

Capture triggers off CMD_NOACCESS yet the Auth code returns CMD_NOACCESS when out of range. 

This is the same issue as the closed issue #295.

**Comment by zontreck** [comment]
Yes, a unintended side effect of fixing capture in 8.0, clearly forgot to take into account that auth still fires a CMD_NOACCESS when range isnt valid.  I'll need to have capture do a range check if the setting limit range is set.
