### ISSUE TITLE
Open Collar Remote Disconnecting

### ISSUE THREAD

**Issue by Rocki-Horror** [OpenCollarTeam/OpenCollar#482]
What version of OpenCollar are you using?8.0.2 and Remote is 8.0

What behavior did you expect? To stay connected to my sub's collar even in laggy sims. 

What behavior did you see instead? I have to continually reconnect to my sub collar just about anytime I want to use use it.  The old remote was so much better.  The new update created this issue.

What steps does someone need to take to reproduce the problem? Use the remote for a couple of days for sitting, standing, leash and unleashing as you normally would and you will be reconnecting your sub all the time.  Very annoying.

**Comment by zontreck** [comment]
I'm going to be honest this ticket doesn't tell me anything. 

1) saying the old remote was better is not constructive feedback.  We won't be going back to the old remote

2) having to reconnect should not happen,  ensure you are using the latest remote with the latest collar scripts. 

Please grab a new remote from HQ and test.  Additionally see our ticket #469 which details posting guidelines.  This could have been addressed on discord,  group,  or at HQ.
