### ISSUE TITLE
About half of RLV restrictions don't work

### ISSUE THREAD

**Issue by EleniaB** [OpenCollarTeam/OpenCollar#485]
What version of OpenCollar are you using?
8.0.2
What behavior did you expect?
apply restriction e.g. notecard or other
What behavior did you see instead?
No message chat and status button doesn't change
What steps does someone need to take to reproduce the problem?
Tries to set RLV restrictions beyond rank 31 in the g_lRLVList  list line 94 oc_rlvsuite script
![2021-02-19_20-56-30](https://user-images.githubusercontent.com/22458584/108555335-a4a89e00-72f5-11eb-937a-e232e91ab1f5.png)

**Comment by zontreck** [comment]
Hard coding RLV restrictions is beyond the scope of support

Feb 19, 2021 1:03:20 PM EleniaB <notifications@github.com>:

**Comment by zontreck** [comment]
<img src="https://share.zontreck.dev/eoBHdsxUwp.png"/>

Those buttons do work which leads me to believe you are trying to manually set the restrictions in the script itself. This is not supported. Please use .settings or respond to this issue explaining more in detail what you are talking about.
