### ISSUE TITLE
Spaces in an #RLV subfolder name blocks browsing its subfolders

### ISSUE THREAD

**Issue by spflanze** [OpenCollarTeam/OpenCollar#487]
What version of OpenCollar are you using?
OpenCollar 8.0.2000 

What behavior did you expect?
When the collar's menu is navigated to "RLV => #Folders =>  Browse" it is expected to be possible to see all #RLV subfolders that do not begin with the "." character, and are nested 20 deep, or less.

What behavior did you see instead?
If there is a space in a subfolder name, it is not possible to browse its subfolders.

What steps does someone need to take to reproduce the problem?
Put a space in the name between any characters between the first, and the last. Its subfolders cannot be navigated in the collar's menu. It is known this inability is a property of the script, and not the viewer, because other collars have been tested that can navigate into the subfolders of folder names that have spaces.

**Comment by zontreck** [comment]
One space is fine, if you have two spaces for instance <pre>Test Test</pre> will work, but <pre>Test    Test2</pre> won't.

**Comment by zontreck** [comment]
This is not a bug.

**Comment by zontreck** [comment]
I have just verified in the script, that there is nothing in there that appears to be causing this.

**Comment by zontreck** [comment]
This will be closed for now.

We are aware of the issue. However this may not be fixable if there is a reason why this is occurring, be it memory saving, or necessary for dialog functionality. 

The topic is also being locked.
