### ISSUE TITLE
Feature Request for Cuffs

### ISSUE THREAD

**Issue by spflanze** [OpenCollarTeam/OpenCollar#490]
This feature request regards the ankle cuffs:

When feet are chained together, the avatar walking speed should be limited. Ideally there would be three connecting chain lengths. The longest length would limit the avatar to walking speed. A shorter length would limit the avatar to crouch speed. A very short length that would bind the feet closely together would either make the avatar immobile, or make the avatar very slow with an animation overrider that makes the avatar do very short hops.

When the ankles are chained together, and avatar walks, continuous clinking sounds should be heard from the chains. Something like edited versions of these: https://freesound.org/search/?q=chain+clinking .

**Comment by zontreck** [comment]
What cuffs are you referring to? We have cuffs that are in development but are not released yet. Besides no OpenCollar Cuffs have ever done this.

**Comment by spflanze** [comment]
I refer to the cuffs in development. It would be a fun feature for them to have.

**Comment by safra-nitely** [comment]
sounds interesting idea. i am working on re-prioritising animations and this is something may look into at same time

**Comment by Pingout** [comment]
I don't think this is a Cuff Feature. Cuffs use stationary animations, with arms and legs posed in fixed positions.
I think we're looking at here is an Animation Override feature, where this "walking" animation would be part of an automated walking, running, standing routine. Once you have the animations you want to use, you can create a unique notecard for this Animation Set that can be loaded into the AO, producing the desired walk, or crawl, as desired. I would suggest you get the OpenCollar Sub AO and experiment with Animation Sets.
