### ISSUE TITLE
SHOCKER APP

### ISSUE THREAD

**Issue by silentwar-resident** [OpenCollarTeam/OpenCollar#494]
What version of OpenCollar are you using? 8.0.4

What behavior did you expect? 

options to shock a sub. 

What behavior did you see instead?

no response.

What steps does someone need to take to reproduce the problem?

install of shocker and click app , shocker, no response

**Comment by zontreck** [comment]
Is the shocker app the one from this github?

**Comment by silentwar-resident** [comment]
yes

**Comment by zontreck** [comment]
Thank you. I'll verify this when i am able to.

**Comment by RomkaSwallowtail** [comment]
make sure the collar contains  '~shock'  animation

**Comment by silentwar-resident** [comment]
seems you fixed it in 518 after me

**Comment by silentwar-resident** [comment]
canty  find it

**Comment by silentwar-resident** [comment]
aria.. looks like the shocker contributor fixed it  in  https://github.com/OpenCollarTeam/OpenCollar/pull/516 and https://github.com/OpenCollarTeam/OpenCollar/pull/518

**Comment by RomkaSwallowtail** [comment]
#529

**Comment by silentwar-resident** [comment]
thanks will check it

**Comment by silentwar-resident** [comment]
ok tested it and fixed.

thank you.

**Comment by cruelraremaster** [comment]
closing because of "ok tested it and fixed"
