### ISSUE TITLE
Returning the ability to add and remove trusted when owned

### ISSUE THREAD

**Issue by 1Acadia** [OpenCollarTeam/OpenCollar#495]
What version of OpenCollar are you using? 8.04

What behavior did you expect? I am owned and used to be able to add and remove trusted for one time play partners without my very laid back owner's permission.

What behavior did you see instead? It now denies that option when owned and we are supposed to use Capture I guess.

What steps does someone need to take to reproduce the problem? It is a not welcomed change in the scripting, and as such is reproduced every time I try.

**Comment by SilkieSabra** [comment]
This is a good feature to introduce as an option that can be turned on by the owner

**Comment by Medea-Destiny** [comment]
Fix provided in https://github.com/OpenCollarTeam/OpenCollar/tree/Medea-4.1-1
