### ISSUE TITLE
opne collar hud

### ISSUE THREAD

**Issue by XxLovlyLadyWolfXx** [OpenCollarTeam/OpenCollar#497]
What version of OpenCollar are you using? 8.0 2000

What behavior did you expect?  to be able to use the collar hud

What behavior did you see instead? collar hud not working

What steps does someone need to take to reproduce the problem? i dont know

**Comment by zontreck** [comment]
Your remote is probably not one of the v8 remotes. Please come to OpenCollar HQ to grab a new remote. Thank you.
