### ISSUE TITLE
Update all references to the list stride in oc_addons to use a global variable

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#498]
This is mostly a todo item, but any bored scripter can pick this up and contribute. 

There are a bunch of references scattered throughout the script to the list stride count in oc_addons.  For sanity's sake this should be updated to be a global variable such...

```lsl
integer ADDON_LIST_STRIDE = 5;
default{..............}
```

**Comment by nirea** [comment]
Looking at that script, I see one place where the stride length is treated as 5 and a couple others where a 4 is used.  Which should it be?
