### ISSUE TITLE
runawaydisable setting in 8.0.5 should be reversed

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#499]
In OpenCollar 8.0.5, the setting to disable runaway is `auth=runawaydisable~0`.  The logic of all the other settings strings would dictate it should be `auth=runawaydisable~1` , to indicate that yes, runaway is disabled.  
Another thought.. changes like this to settings affect all collars that have settings notecards in them upon update.  We should avoid making changes to user settings wherever possible.  I don't see why the change from `auth=norun~1` to `auth=runawaydisable~0` is critical enough to be worth breaking the setting in any collar that has it in the notecard.

**Comment by zontreck** [comment]
Fixed by more accurately renaming the setting to `auth_runaway`
