### ISSUE TITLE
OC Cuffs chain sags too much

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#505]
What version of OpenCollar are you using? OC Cuffs 8.0 Beta

What behavior did you expect? Snug chain

What behavior did you see instead? Too Much Slack

What steps does someone need to take to reproduce the problem?

**Comment by Pingout** [comment]
Suggesting this change to oc_cuffs.lsl 

SetParticles(integer link, key kID,key kTexture, float fMaxAge, float fGravity){
    
    if(kTexture=="" || kTexture=="def")kTexture="4cde01ac-4279-2742-71e1-47ff81cc3529";
    if(fMaxAge==0)fMaxAge=7.3;
    if(fGravity == -1.111) fGravity = -0.01;
    llLinkParticleSystem(link, [
PSYS_SRC_PATTERN,PSYS_SRC_PATTERN_DROP,
PSYS_PART_START_ALPHA,1,
PSYS_PART_START_SCALE,<0.05, 0.05, 0>,
PSYS_PART_END_SCALE,<0.05,0.05,0>,
PSYS_PART_MAX_AGE,fMaxAge,
PSYS_SRC_BURST_PART_COUNT,1,
PSYS_SRC_ACCEL,<0, 0, -0.01>,

**Comment by nirea** [comment]
Fixed in https://github.com/OpenCollarTeam/OpenCollar/pull/515.
