### ISSUE TITLE
Slightly clearer Cuff  Naming Notecard

### ISSUE THREAD

**Issue by Halstrom-lab** [OpenCollarTeam/OpenCollar#507]
What version of OpenCollar are you using? 8+

What behavior did you expect? N/A

What behavior did you see instead? I found it visually confusing not having the groups for each cuff bunched together.
[OpenCuff Naming Guide.txt](https://github.com/OpenCollarTeam/OpenCollar/files/6168744/OpenCuff.Naming.Guide.txt)

What steps does someone need to take to reproduce the problem? N/A

**Comment by zontreck** [comment]
Please see the cuffs naming guide on github

Mar 18, 2021 10:10:34 PM Halstrom-lab ***@***.***>:

**Comment by Halstrom-lab** [comment]
I also just realised this is ambiguous as to which is the front and back of a wrist cuff. Perhaps Top & Bottom may be more obvious, the Top of the wrist where a watch is worn. Unless there is retro compatibility requirement.
In either case a standard should be set in the naming guide as to which way the wrist is facing for Front, Back, Inner, suspecting it would be with hands flat on the avatars legs.

Right Lower Arm Cuff = rlac
Front Right Lower Arm Cuff = frlac
Back Right Lower Arm Cuff = brlac
Inner Right Lower Arm Cuff = irlac

**Comment by Pingout** [comment]
> I also just realised this is ambiguous as to which is the front and back of a wrist cuff. Perhaps Top & Bottom may be more obvious, the Top of the wrist where a watch is worn. Unless there is retro compatibility requirement.
> In either case a standard should be set in the naming guide as to which way the wrist is facing for Front, Back, Inner, suspecting it would be with hands flat on the avatars legs.
> 
> Right Lower Arm Cuff = rlac
> Front Right Lower Arm Cuff = frlac
> Back Right Lower Arm Cuff = brlac
> Inner Right Lower Arm Cuff = irlac

If we can agree that Inner chain point is obvious, then the other chain points fall into place naturally. As you stand on a pose stand, with (as you suggested) hands flat on the legs, front and back become clear, and then by default the final chain point would be named rlac. The naming is fine the way it is. This naming pattern has been like this since version 1. Using names like  "top" and "bottom" would actually be more confusing.

**Comment by Halstrom-lab** [comment]
Awesome, maybe just add that clarification to the naming guide for confused crazies like me who think weird :)
