### ISSUE TITLE
Add setting to allow wearing more than one collar at once

### ISSUE THREAD

**Issue by xxReyes** [OpenCollarTeam/OpenCollar#51]
What version of OpenCollar are you using?
7.0 beta 3

What behavior did you expect?
Feature Request (not a bug)  - Would like to make the test for other attached collars optional
(change suggested in main group by 'sweetstephy')

**Comment by Athaliah** [comment]
Was this the code in the past, that was put into place because of issues with interference of having multiple relays on a person, and having this code prevented those bugs?

**Comment by nirea** [comment]
I don't know if it was relays, but there are a lot of weird behaviors that could happen with multiple collars on.  I think keeping this option on by default makes sense for the typical user, but I'm open to making it a switchable setting.

**Comment by nirea** [comment]
See #77 for another user who would like this functionality.

**Comment by CorwinDavidson** [comment]
I think my questions on this would be what would be the use cases that would require needing to allow someone to wear more than one collar.  

Is this wanted because people want to have the ability to wear a "play collar" that their owner isn't aware of?
Or is it wanted because people are creating accessory items that are using the full OC core scripts to handle Dialog's, Owners, etc.

I'm not too inclined to facilitate the first option.  If it's the second option, I think another option could be the proper solution.

**Comment by nirea** [comment]
@Celestrea, was your ticket #77 about two actual collars, or always a collar and a non-collar accessory?

Perhaps @NorthGlenwalker has some ideas about the best way to add features to non-collar accessories (a clit ring in this case, I think), since he's been maintaining the cuffs.

**Comment by CorwinDavidson** [comment]
I do have code I never released for CollarDB that provides a bridge between the collar and accessories.  It pretty much makes the accessory an extension of the collar and they can use dialog, auth, and any other core collar functions.

**Comment by nirea** [comment]
We're getting a little out of scope here, but I think that's OK as we're talking about new features.  Here are more things I think we'd want out of such a bridge, if thinking of Celestrea's use case:

- ability to use the bridged attachment as a leash point
- ability to lock the bridged attachment in place with RLV (without messing with folders)
- ability for the attachment to insert a button into the collar's menu (e.g. put a "Cuffs" button into the "Apps" submenu, or maybe a new submenu.  I dunno), and get a message when that button is clicked.

**Comment by Celestrea** [comment]
I was asking more about 2 different collar devices (ie someone wants to wear a special collar for their perm Master but have a play collar for someone else which would have also worked with the issue I was having with the clit rings) HOWEVER, in reading these comments I do think the bridge idea is fantastic! It would alleviate my personal issue with the clit rings as well as allow designers to create a myriad of products from collars, clit rings, nipple rings, nose rings, chastity belts, & cuffs that could all work congruently with the collar while maintaining the core and rlv functionality of the individual accessories. So me personally I have no need to wear two collars though I do know many people who do and have had the issue with one being knocked off so even an accessory collar might alleviate their issues using the bridge idea.

**Comment by ExecuterMagic** [comment]
Love the idea of that bride as well !
On the original question , for me as well it would be helpfull to have the posibility to have 2 OC scripted devices as well , and seen that question many times by users in the groupchat , so there is a demand for it,  so maybee we could make that a feature where the user gets an explicit warning that its not adviced ( but still possible if they realy want to ) , or where one has to add a line to the .setings notecard , so it stays persistant also on updates and such ?

**Comment by zontreck** [comment]
Highlander is the name of the setting that you have to place in the settings notecard to use more than one now. It's been implemented. I'm closing this for now.
