### ISSUE TITLE
Sub AO returning unusual or no messages for missing animations

### ISSUE THREAD

**Issue by Halstrom-lab** [OpenCollarTeam/OpenCollar#511]
What version of OpenCollar are you using? OC8+

What behavior did you expect? I made a cut&paste mistake in the notecard for standing animations and put "Tt_adored st1" instead of "Tt adored st1" for a bunch of animations. In other cases I have seen it come back to me correctly saying something like "animation XXX not found" 

What behavior did you see instead? In this case initially it just didn't play those incorrect animations or any after them and there was no error or message. It wasn't till I removed all the other animations from the list I started getting a script error in the debug window saying something like "animation % not found" (replacing the % with a square ascii box I don't know how to type).
[1Gynoid.txt](https://github.com/OpenCollarTeam/OpenCollar/files/6179112/1Gynoid.txt)

What steps does someone need to take to reproduce the problem? The problem was solved when I fixed my typo, not sure if there is some weirdness associated with the underscore doing something strange.

**Comment by SilkieSabra** [comment]
This would need someone to duplicate the error, it seems like a ZHAO II thing more and an OpenCollar AO thing.
