### ISSUE TITLE
Naked button

### ISSUE THREAD

**Issue by survivaltribes** [OpenCollarTeam/OpenCollar#513]
What version of OpenCollar are you using? 8.0.5000

What behavior did you expect?  click on the naked button  wear the naked .core files

What behavior did you see instead? when i click on the naked button inside an outfit sometimes it doesnt work and i get failed: @getinv:.outfits/naked=42051844 (invalid option) in the chat. Work when i type the /1prefix naked.

**Comment by Medea-Destiny** [comment]
Using the naked button and typing the naked chat prefix activates the same code, there's no difference. Sounds like a viewer/network glitch.
