### ISSUE TITLE
command to output script build numbers

### ISSUE THREAD

**Issue by xxReyes** [OpenCollarTeam/OpenCollar#52]
What version of OpenCollar are you using?
7.0 Beta 3

What behavior did you expect?
Feature Request - Not a bug

It might be helpful for support purposes to have an advanced 'version' command that causes all scripts to report their specific build numbers so we can more easily determine what version of scripts someone is running; I know I've run into a few situations with very odd problems where it turned out that they had somehow added an old version of some random script into a current collar build (or similar scenarios). (this would be a different command from 'version' that reports the generic version number that we're all used to) - If possible it would also be great if that script could also check and report on the properties of the scripts to see if they have been modified.

**Comment by CorwinDavidson** [comment]
The code added to each script to do this would be a bit wasteful for limited resources.   

What could be done would be to write a utility script that records the UUID of each script and as part of the validation of permissions function could read the notecard, or request the info from the web, and validate each script matches the noted UUID.

For security you could even use the UUID of the notecard in the llGetNotecardLine calls and not have the notecard in the collar inventory (its been a while since I tested this).

**Comment by Saraeva** [comment]
What if someone took the code from the GitHub here, and compiled their own scripts, wouldn't it have a different UUID?

**Comment by CorwinDavidson** [comment]
Yes, but then they wouldn't be the "official release" of the OC scripts, which as of right now are already being signed with the "OpenCollar Experiance" in the beta releases.   A third party would and should provide their own script validation / versioning to differentiate from the OC scripts.

**Comment by Saraeva** [comment]
So you're proposing that the "OpenCollar Experience" is to achieve the same goal as Wendy and Otto was to do with OC Ready program, am I correct?

**Comment by CorwinDavidson** [comment]
I have no clue what the OC Ready program was.

The "OpenCollar Experiance" tagging that Nirea is now doing is on par with code signing.  It allows you to inspect the scripts and know that they are in fact Official Open Collar Scripts and have not been tampered with in any way.  

It doesn't prevent you from seeing the source, it doesn't prevent someone from grabbing the source from Github and compiling their own scripts.

The solution I outlined is the SL equivalent of a SHA1 , MD5 or SHA256 fingerprint of a file, and the only way to securely identify unique versions of SL Scripts.  Anything that is code within the scripts themselves either takes up code-space, or can be subverted to report incorrect values, or would just have the wrong information if it was forgotten to update.

**Comment by Saraeva** [comment]
@CorwinDavidson For your reference http://www.opencollar.at/ready.html

**Comment by CorwinDavidson** [comment]
Yeah.. that has nothing to do with the feature xxReyes requested nor the possible solution that I suggested.

The OC Ready program was a way for them to get money from people wanting to put scripts in collars and getting vendors to advertise for them.   Basically it was an update shim script that would wait for a special updater that would then "install" onto the collar.  Which usually would have been them simply adding onto the collar another pre-made core of about 6 or so prims.  Basically a $100L charge for script that rezzed an object and linked it to your Mod/Transfer collar.

**Comment by zontreck** [comment]
I think this could be looked into. And i have an idea for a way that would not waste resources

**Comment by zontreck** [comment]
I've tested a feature which implements two new chat commands. The feature is not accessible through the menus. It allows you to dump a output of debug. And it also lets you query the script versions.  Each individual script would reply its own output. I'm still testing it but it looks like it could be added without impacting performance or memory usage too much.

**Comment by zontreck** [comment]
Implemented in OpenCollar 7.2 RC
<prefix> versions
<prefix> debug - This additionally outputs a significant amount of debug, with version numbers
