### ISSUE TITLE
Cuffs should have a Settings menu 

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#526]
What version of OpenCollar are you using?
OpenCollar 8.0.5 - OC Cuffs 8.0 Beta 
What behavior did you expect?
There should be some way to change some settings such as Theme/Texture, Resize, etc
What behavior did you see instead?
Settings menu is missing 
What steps does someone need to take to reproduce the problem?

**Comment by SilkieSabra** [comment]
Shouldn't this one be closed?

**Comment by Pingout** [comment]
Yes, this can be closed as complete.
