### ISSUE TITLE
Getting "Access Denied because you are out of range" messages from local chat (channel 0) messages that start with "*"

### ISSUE THREAD

**Issue by KellyShergood** [OpenCollarTeam/OpenCollar#527]
What version of OpenCollar are you using? 8.0.5000

What behavior did you expect? No messages

What behavior did you see instead?

Getting spurious "Access Denied because you are out of range" messages from collar.

What steps does someone need to take to reproduce the problem?

1) One person wears an OC with range limits

2) Second person stands 50m away and does a "/shout *test", or a "/shout xxtest" with "xx" being the person's initials.  The person shouting will get a "Access Denied because you are out of range" message from the collar.

The message is also triggered when an object owned by someone else chats a message that begins with a "*".  I was getting these messages by someone wearing an OC and using an object of mine by email in offline chats.

**Comment by toywylie** [comment]
You could just discard all chat coming from objects on channel 0, that would get rid of the most common issue of an object chatting the name of an OC wearer in public:

oc_api:514

if(llGetAgentSize(i)==ZERO_VECTOR)
{
    return;
}

The problem with "out of range" sent to an avatar, even when public is false is a different issue in my opinion.

**Comment by SilkieSabra** [comment]
This makes me wonder whether the Access Denied/Out of Range message to avatars who do not have collar access is worth it, since there may be other instances when avatars shouting, etc would trigger this unintentionally

**Comment by nirea** [comment]
I think a more targeted fix than Toy's suggestion, with lower risk of unintended consequences, would be to just remove the lines sending this message in the CalcAuth function (oc_api.lsl, 129-132).

Yes, that means avatars who are shouting commands but are outside the collar's configured range wouldn't know why it's not responding.  That seems to be a much rarer case than the one where object owners get spammed all the time.
