### ISSUE TITLE
Undress not showing many system layers - Tattoo or Universal or Alpha

### ISSUE THREAD

**Issue by melanuss** [OpenCollarTeam/OpenCollar#528]
What version of OpenCollar are you using? 8.0.5

What behavior did you expect? I expected the blue menu under Apps>Undress>Rm Clothes to show ALL the system layers I was wearing: 
Jacket, Pants, Shoes, Socks, 
Alpha mask, Tattoo, Universal, Physics

What behavior did you see instead? The blue menu only showed Jacket, Pants, Shoes, Socks 

What steps does someone need to take to reproduce the problem?
In SL I wore fresh OpenCollar from OpenCollar Headquarters to test on myself. I was wearing system layers & parts (Skin, Tattoo, Universal Layer, Alpha, Pants, Jacket, Socks, Shoe,  eyes, hair base, Physics) plus items worn on attach points (hair, shoes, shirt, BOM mesh body). There are other system layers I was not wearing and did not test. I am reporting the things I was actually wearing.

**Comment by zontreck** [comment]
Detach should be used for attachments.  Undress only shows the SYSTEM legacy clothing layers that would appear on baked on mesh. Attachments are separate

Mar 30, 2021 11:33:16 PM melanuss ***@***.***>:

**Comment by melanuss** [comment]
Yes, attachments are separate from layers. 

I was testing both Detach and Undress and included the information about the attached items for completeness. I was wearing a mix of things on both system layers and attach points. Detach seems to be working fine and the way it lists items is a big improvement over the old RLV legacy Un/Dress I remember from OpenCollar v3 of some years ago. 

Undress should show ALL the system clothing layers. And that includes things that are not actually BOM baked textures. For example Physics.

**Comment by melanuss** [comment]
I was discussing this with someone and they brought up the point that they are not sure if this is sort of in between a bug report and a feature request :-) 

Either way I took a moment to look up the entire list of New Clothing System Layers types that are in the LL inventory drop down menu. Hopefully this is helpful. They are the following 13 types: Shirt, Pants, Shoes, Socks, Jacket, Skirt, Gloves, Undershirt, Underpants, Alpha Mask, Tattoo, Universal, Physics. 

If it is something that can be detached or unworn I would owners to be able to manually remove it independently of whether of not outfits are properly set up in #RLV or not.

**Comment by zontreck** [comment]
The undress app follows the RLV specification.  The viewer does not tell the script if you are wearing physics.  The script only displays what it is told by the viewer

Apr 2, 2021 4:29:53 PM melanuss ***@***.***>:

**Comment by melanuss** [comment]
The old RLV legacy Un/Dress included ALPHAS. I remember that clearly. If I was only allowed one missing system layer to choose from I would choose alphas as important. 

Tattoo layer and Universal layer would be nice to have but not as important as Alphas. 

I could live without Physics. If we have to leave something off the list I would vote to leave off Physics.

**Comment by zontreck** [comment]
As i said. This is not excluding anything. This gets the list directly from the viewer.

Apr 14, 2021 1:16:54 PM melanuss ***@***.***>:

**Comment by melanuss** [comment]
Respectfully Zontreck, I dont know what you mean by 'This' when you say "This is not excluding anything."

If you are referring to the Undress feature, it is not including at least Alpha mask, Tattoo and Universal. 

I get the same list from the LL viewer as I get from the firestorm viewer. Over in the viewer Inventory window look in the right click drop down menu and select "New Clothes" You should see a list of 13 types of new clothes. Let me relist them here: 
Shirt, Pants, Shoes, Socks, Jacket, Skirt, Gloves, Undershirt, Underpants, Alpha Mask, Tattoo, Universal, Physics. 

It is the same system clothing list as was implemented in the old OC v3 collars and also the old OC v6 collars with Legacy Un/dress plus, of course, the new Universal layer. I remember this distinctly with the old RLV Un/Dress and I took the time to personally verify it again. 

The v8 Undress App is not required so people who are not interested don't have to use it. For those like me, who do want to use it and do need it, it is missing important clothing types.

**Comment by zontreck** [comment]
When i say not excluding, i mean that the script is getting the list directly from the viewer.

Apr 15, 2021 10:06:33 PM melanuss ***@***.***>:

**Comment by melanuss** [comment]
For some reason the script is not getting the full list with all the items.

**Comment by zontreck** [comment]
If so that is a viewer bug.  It wouldn't have anything to do with the script.  A workaround would be to hard code these buttons onto the menu,  but then they will always show up even if not worn.

Apr 15, 2021 11:08:20 PM melanuss ***@***.***>:

**Comment by melanuss** [comment]
I don't think it is a viewer bug because I tested it with OC v3 collars and also the OC v6 collars with Legacy Un/dress and also OC v8.0.5 collar. All the testing was done using the current LL viewer and Firestorm viewer as stated above. 

If it was simply a viewer issue the OC v3 and OC v6 would have failed the tests. 

Maybe the script has a problem in the way it get the list or maybe they are not getting all the proper lists they need.

**Comment by melanuss** [comment]
When I tested it with OC v3 collar (specifically OpenCollar Version 3.970), All the buttons worked as expected: They removed the proper thing they were supposed to remove when clicked. I did notice that the three buttons "Alpha" and "Tattoo" and "Physics" did show up even if not worn. So maybe they were hard coded onto the menu as a workaround. 

When I tested it with OC v6 collar (specifically OC v6.5.0 with Legacy Un/dress v1.3), All the buttons worked as expected: They removed the proper thing they were supposed to remove when clicked. None of them showed up when not worn. This included the three buttons "Alpha" and "Tattoo" and "Physics."

**Comment by zontreck** [comment]
It's a viewer bug related to the specific RLV command being used.

**Comment by melanuss** [comment]
you can still add back the missing buttons as shown in with Legacy Un/dress v1.3 and earlier.

**Comment by SilkieSabra** [comment]
The idea this is a "viewer bug" is just strange.  While compiling scripts to update to 8.1 I saw that in two places (around lines 110 and 310) layers are listed.  @zontreck wrote this script.  In both places, tattoo and alpha are absent, and in one place universal is absent. Inserting the layer names caused them to appear in the menu.

**Comment by Medea-Destiny** [comment]
Actually there ARE viewer issues to consider here. Firstly there are some small differences between how RLV and RLVa handle getoutfits, and secondly there IS a "viewer bug" with RLVa's handling of physics layers. We should also properly take into account future expansions of the layers list. There is also a potentially confusing issue in how RLVa will respond to getoutfits because the RLVaHideLockedLayers debug setting is on by default in FS.

I have a version of the script which should address these issues, adds chat commands, and fixes some other minor things. See #604 - but it needs a bit more testing, particularly on a viewer using Marine's RLV to ensure it's working there as I assume it will.
