### ISSUE TITLE
Public chat is channel 0

### ISSUE THREAD

**Issue by RomkaSwallowtail** [OpenCollarTeam/OpenCollar#534]
the manual on the site https://opencollar.cc/docs/Prefixes,-Chat-Commands-and-Other-Non-Menu-Functions says: 

Public chat is channel 0. You can turn this off so the collar doesn’t listen to chat commands in local chat.

    [prefix] channel 0 : enables the collar to listen to commands in local chat.
    [prefix] channel -1 : disables the collar from listening to commands in local chat.

**but in reality this function does not work! collar always listen local chat.**

**Comment by zontreck** [comment]
This is intentional.  Not a bug

Apr 3, 2021 11:51:28 PM Romka ***@***.***>:

**Comment by RomkaSwallowtail** [comment]
in this case, you need to correct the manual so as not to mislead users

**Comment by zontreck** [comment]
Let the team know.  I'm no longer in the team just telling you that it's been this way since 3.x

Apr 4, 2021 1:59:38 AM Romka ***@***.***>:

**Comment by SilkieSabra** [comment]
Since I write the manual I can test this.  However if it doesn't work there should be a fix because also since 3.x there has to be a way to turn off the collar listening to local chat.

**Comment by RomkaSwallowtail** [comment]
@SilkieSabra it doesn't work, you can make sure.
if you like, I have ideas how to fix this without increasing the script code too much

**Comment by SilkieSabra** [comment]
OpenCollar V8.1 uses the negative channel to close channel 0
