### ISSUE TITLE
DoLeash function forces an impulse whenever leash is grabbed, even if already within the maximum configured leash distance

### ISSUE THREAD

**Issue by BaneDarrow** [OpenCollarTeam/OpenCollar#536]
In src/collar/oc_leash.lsl line 336 currently:

```
    if (g_vPos != ZERO_VECTOR) {
        llMoveToTarget(g_vPos, 0.7);
    }
```

DoLeash function forces an impulse whenever leash is grabbed, even if already within the maximum configured leash distance. As such, repeated leash/unleash causes the target to get yanked closer and closer. This is frustrating if just picking up and dropping the leash while everyone is sat around and content with their positions.

Probably that code can just be removed and let normal distance constraining do it's thing. Or at least it shouldn't be ZERO_VECTOR and should be the leash range configured.

If you *want* to Yank there's already a button for that. Or maybe making this driven by a YankOnLeash setting that can be turned off if this is desired behavior for some reason.

Have confirmed removing the above code fixes the behavior, and if leashing when out of range you already get pulled into range by the rest of the codebase.

**Comment by BaneDarrow** [comment]
Created PR: https://github.com/OpenCollarTeam/OpenCollar/pull/537

**Comment by nirea** [comment]
Will be included in the 2021 Q2 feature release.
