### ISSUE TITLE
Allow wearer to be added as secondary owner

### ISSUE THREAD

**Issue by xxReyes** [OpenCollarTeam/OpenCollar#54]
What version of OpenCollar are you using?
7.0 Beta 3

What behavior did you expect?

Currently it is not possible for the person wearing the collar to be added as a secondary owner - they are either an 'owner' (500) or 'wearer' (503) - wearer falls behind "public access" and "group" owners in the permissions hiearchy and there are many cases where owners might want the sub to be able to override restrictions placed by random people but NOT give them the authority to override the owners restrictions.

**Comment by nirea** [comment]
What level of access do they have if OwnSelf is enabled?

**Comment by xxReyes** [comment]
Own Self gives full owner - '500' access

**Comment by CorwinDavidson** [comment]
This is prevented here:  (Line 424 specifically) https://github.com/OpenCollarTeam/OpenCollar/blob/97842f9da81776a3702f98ba471ca15ec85076b3/src/collar/oc_auth.lsl#L421-L431

changing that line to:
```
if (iNum!=CMD_OWNER) {
```
will allow the owner to set anyone, including the wearer to the "Trusted" aka Secondary Owner role

**Comment by AdmiralTails** [comment]
By default, the wearer is able to modify the trusted list at any time, so simply changing that line would give the wearer the ability to add themselves to the trusted list freely, without an owner having to do so.

Adding another mode similar to ownself might be a better option, both so that it can be something that only the owner can set, and so that, like ownself, it can bypass checking the list for the wearer.

**Comment by nirea** [comment]
Slut's original description convinces me that this is a good feature to
have.

I'm not too worried about the privilege escalation issue of a sub always
being able to add his/herself to the trusted list.  They can always run
away too.  Or they could add a friend to 'trusted' and have them do stuff.
As long as owners are notified when people are added to trusted, then that
seems like a sufficient check.  Are there situations when an owner really
wouldn't want it though?

If "ownself" is going to be its own setting, I like the consistency of
having "trustself" work the same way.  It's a bigger implementation task
though.

**Comment by CorwinDavidson** [comment]
@admiralTails the current implementation of "ownself" adds the wearer to the owner list so it doesn't bypass the list checking system.

@nirea As I'm currently working on the oc_auth system to use PRIM_MEDIA I can implement the "trustself" option into that work as well..  

The options to do this would be to implement it the same way the current system does which would add the wearer to the trusted list.  

Or revamp the system to just be a trinary value flag.  "standard", "trustself" or "ownself" the flag would be checked in the Auth function to provide the correct permission.

**Comment by nirea** [comment]
I like the trinary idea.  Seems simpler than worrying about possible conflicts between ownself and trustself.

**Comment by zontreck** [comment]
@nirea seeing as this hasn't been resolved. Can we look into doing away with ownself and just doing it through the relevant add dialogs? We can still prompt wearer upon attempted removal of Auth privs.

**Comment by zontreck** [comment]
Looking into how to make this work
