### ISSUE TITLE
Trusted can unlock collar that was locked by owner

### ISSUE THREAD

**Issue by 1Acadia** [OpenCollarTeam/OpenCollar#556]
Version 8.0.5

I expected my collar, when locked by my owner, to not be unlocked by a Trusted person
I had my owner lock it, and my alt who is on the Trusted list was able to unlock it, but then unable to re-lock.  I expected my owner's permissions to be greater than a trusted and trusted not able to unlock.
To re-create the issue, have your collar locked by your owner and then have someone on the trusted list try to unlock.  We verifed the issue with another person and the same thing happened.

**Comment by mistressohm** [comment]
Is this not Working As Intended?  Perhaps I'm thinking of a different scenario, but Trusted persons are kind of like backup Owners, able to do some things but not all.    

If your collar is locked and you have need to unlock it (and cannot unlock it yourself), you need your Owner.  But, if there is someone Trusted on the collar, they can help get you out of whatever predicament you're in... however, only your Owner can lock your collar again once this happens.  This is to keep subs from 'cheating' on their collar - their Owner will find out that the collar was unlocked ere long.   

However, there is also a possibility that the collar is like a safe - if the Owner has locked it, only the Owner can unlock.  If a Trusted locks your collar, then any Trusted can unlock, along with the Owner.  In this case, yes, the permissions are not correct.

I am intentionally staying away from Safeword/Runaway scenarios - the one is more for undoing RLV restrictions and getting back to normal without unlocking the collar, and the other is for getting out of a bad D/s situation permanently, erasing all ownership and reverting the collar to 'out of the box'.

**Comment by SilkieSabra** [comment]
This is not how the collar should work, Trusted has never been able to unlock a collar if an owner has locked it.

**Comment by Pingout** [comment]
This issue can be closed. The fix has been included in the next quarterly release. Thank you.

**Comment by 1Acadia** [comment]
Thank you, Ping
