### ISSUE TITLE
"Access Denied to browsing #RLV" spam from removing wearer access

### ISSUE THREAD

**Issue by nulshift** [OpenCollarTeam/OpenCollar#560]
**What version of OpenCollar are you using?**
8.0.5000
**What behavior did you expect?**
The error to appear once, then send me back to the previous menu.
**What behavior did you see instead?**
The error appeared, sent me back to the previous menu. Every time any menu option is clicked, the error repeats itself in the chat, and a new copy of the [Folders] menu pops up overtop the current menu
**What steps does someone need to take to reproduce the problem?**
Not entirely sure, but I'll just list everything I did.
1. I first added myself as owner to the collar.
2. Then I added another owner to the collar.
3. I later removed myself as owner from the collar, but did not like that I was able to access the locking and unlocking features of the RLV folders.
4. The owner added me back as an owner on the collar.
5. I disabled the "Wearer" checkbox in the [Folders] configure menu.
6. I removed myself as owner again.
7. Then clicking on browse, configure, or clear locks, all produce this repeating error, up until someone with proper access navigates the menus.

**Comment by SilkieSabra** [comment]
This is expected because you are no longer owner on the collar so when you click on an owner only function you get an Access Denied message

**Comment by nulshift** [comment]
The bug I'm reporting is not that I'm no longer able to access the menu. The bug is that when I accidentally try, the error starts repeating itself in OTHER menus, and brings up clones of the RLV menu over whatever I'm trying to access.

**Comment by nulshift** [comment]
@SilkieSabra A gif demonstrating the issue. Hopefully that clears up what I'm reporting here.
https://cdn.discordapp.com/attachments/238914176066650114/858780663653990420/it_is_a_bug.gif

**Comment by Medea-Destiny** [comment]
Reopening for now. oc_folders is not sufficiently filtering commands sent to the usercommand() function and generating superfluous checks for folder level auth on commands that are nothing to do with the folders script. 

This overlaps with and may be entirely the same as #581 - I have a fix already in testing. 

Really there's insufficient filtering of link messages throughout the collar which generates far too many extraneous function hits throughout the collar, but that's a major refactoring task.

**Comment by Medea-Destiny** [comment]
Fixed in 8.1
