### ISSUE TITLE
Access not allowed for adding or removing owners, trusted, or blocking even with my owner wanting to give me permission to do so.

### ISSUE THREAD

**Issue by EliseBun** [OpenCollarTeam/OpenCollar#562]
What version of OpenCollar are you using?
8..5000
What behavior did you expect?
To have it so I, the wearer, am able to add trusted, and block others without any problems
What behavior did you see instead?
Each time I try to remove or add someone to owner, trusted, and block, it will give me" **RE** Simone Heart Collar v1.0: Access Denied to adding a person" or "**RE** Simone Heart Collar v1.0: Access Denied to adding a person" and I am not sure how to toggle it or give me access even with my owner wanting to have that available for me.
What steps does someone need to take to reproduce the problem?
First I download the new 8.0 patch on the collar and immediately my owner did the weld function. After so, I trying to add someone in trusted and I have no permission is to do so. I asked my owner to fix it so I can have access but even she could have not figure out how to do it, and also that her collar is also experiencing the same thing.

**Comment by SilkieSabra** [comment]
The way to fix this is to add the wearer to the owner list.  It is expected behavior that only owners can change the access settings.  I do see room for a feature that allows owners to set a preference so that wearers can add trusted or set group without being able to change the owner access.

**Comment by Medea-Destiny** [comment]
Fix provided in https://github.com/OpenCollarTeam/OpenCollar/tree/Medea-4.1-1
