### ISSUE TITLE
some old content not removed when updating from 3.937 with 7.0beta5

### ISSUE THREAD

**Issue by xxReyes** [OpenCollarTeam/OpenCollar#57]
What version of OpenCollar are you using?
updating from 3.937 to 7.0 beta 5

the following old content was not removed during the update 

"OpenCuffs - _slave - 1.335" 
"Tranquility"
"~version" 
"Grabby Post"
"OpenCollar RLV Relay Help"

**Comment by nirea** [comment]
Should be addressed by https://github.com/OpenCollarTeam/OpenCollar/commit/a5797214073d50ad562c36be96f6f4c42d168bda.
