### ISSUE TITLE
Hide ~ folder names in Folder listings

### ISSUE THREAD

**Issue by deserted1** [OpenCollarTeam/OpenCollar#570]
What version of OpenCollar are you using?
8.0.5
What behavior did you expect?
The awesome that is.
What behavior did you see instead?
The awesome that is.
What steps does someone need to take to reproduce the problem?
Wear anything by dhb that requires an autohide then look in #RLV then list your #Folders using the collar.

I am asking for a way to hide ~ folders just as we do with . folders in the listings.  Maybe as an option? as it seems some creators like using ~ folders for their temporary names and wont allow you to move them into .folder names.

Thank you~  <- Get it

**Comment by SilkieSabra** [comment]
a ~[folder] is rlv standard string for a folder that can be given directly to RLV.  I agree I wish there was a way to autohide these, otherwise to keep your RLV folders trimmed you need to delete them until the next time the trap comes up and gives them to you all over again.  If the folder goes into .folders, it can't be seen by the RLV search the trap uses and so you will end up with multiple folders.

**Comment by deserted1** [comment]
> a ~[folder] is rlv standard string for a folder that can be given directly to RLV. I agree I wish there was a way to autohide these, otherwise to keep your RLV folders trimmed you need to delete them until the next time the trap comes up and gives them to you all over again. If the folder goes into .folders, it can't be seen by the RLV search the trap uses and so you will end up with multiple folders.

Silkie, I am not asking to move them into the . folders, I am asking if we can specify a way to filter then from the Folders menu inside the collar. There is no reason for an end user to see all those if they choose not to.  Why not parse the foldername and if it begins with a ~ dont show it in the llDialog?  (this can be an option if some choose to see them)

**Comment by Medea-Destiny** [comment]
Optional filtering of folders starting with ~ in https://github.com/OpenCollarTeam/OpenCollar/tree/Medea-4.1-1

**Comment by deserted1** [comment]
Thank you Madea!
