### ISSUE TITLE
Access List is open to the public

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#573]
What version of OpenCollar are you using? 8.0.5

What behavior did you expect?  Access List should only be available to Owner and Wearer

What behavior did you see instead? Access List is unrestricted, anyone  can see it

What steps does someone need to take to reproduce the problem? Menu, Access, Access List

We should be able to add: if((iAuth == CMD_OWNER || iAuth == CMD_WEARER ) between line 549 and 550 in oc_core
We need the most recent version of oc_core as there are other PR's waiting for the oc_core script

**Comment by SilkieSabra** [comment]
This is fixed for V 8.1
