### ISSUE TITLE
Shock feature

### ISSUE THREAD

**Issue by SavieSIlverfall** [OpenCollarTeam/OpenCollar#576]
Could we have a plugin for this? :3 

I was redirected to ask it here for 8.0.5

I couldnt find a preset for forms on that btw.

**Comment by SilkieSabra** [comment]
Is this the app you want? https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/Apps/oc_shocker.lsl

**Comment by SavieSIlverfall** [comment]
Yes, That works :3
