### ISSUE TITLE
When Folders > Configure is set Trusted access is off, Trusted gets Access Denied to entire collar

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#581]
We tested this with 8.0.5 and 8.1 RC3.

V 8.0.5
Imp Trollop, wearer, Amanda Darkheart, owner, Roan, Trusted.  When Owner Configured Folders to remove Trusted access (public was also removed but we did not test public access); A Trusted could not Browse RLV Folders and got "Access Denied to Browse #RLV" which is inaccurate since it's only Folders that should be Access Denied.  Then when the menu was refreshed once, Trusted began to get that message on opening the collar menu.  Collar Access still worked as expected.

V 8.1 RC3
Same as V 8.0.5 except now when Trusted opens the collar menu, the Folders menu also pops up and Access Denied to Folders is sent.  Trusted then cannot access Browse, as expected; but also cannot access any other submenu in the collar because the front menu disappears when touched.  This happened three times.  The fourth time, the wearer got the popup when Trusted opened the collar menu.  Did the whole round a second time, and Trusted got Access Denied when attempting to Browse Folders.  Pressed Back  from there and the Folders menu reappeared.  Pressed Ignore, went back to main menu, Wearer started getting Access Denied messages.

**Comment by Trinkitz** [comment]
Using the fix script, and version 8.1 RC-3 collar, when I remove Trusted access to folders, Trusted sees this message: "Access Denied to browsing #RLV" when they click on the collar, and gets these two menus from that single click: https://gyazo.com/712800ada76161ea24c31ab3ed7cd68e

If I give Trusted access again, all is fine. Hope this helps.

**Comment by Pingout** [comment]
> Using the fix script, and version 8.1 RC-3 collar, when I remove Trusted access to folders, Trusted sees this message: "Access Denied to browsing #RLV" when they click on the collar, and gets these two menus from that single click: https://gyazo.com/712800ada76161ea24c31ab3ed7cd68e
> 
> If I give Trusted access again, all is fine. Hope this helps.

Are you saying Trusted sees this message right away, or do they see it when they try to access the denied area?

**Comment by Trinkitz** [comment]
I clarified in the previous comment. When Trusted access is removed, Trusted sees two menus and receives that message when they click the collar.

**Comment by SilkieSabra** [comment]
Tested this in V 8.1 and the original problem persists.  Tested an inworld test fix for this.  When Trusted access to Folders is turned off in the Configure menu, Trusted gets the Folders menu as well as the main menu on touching the collar, pluss the message "[11:20] OpenCollar: Access Denied to browsing #RLV.  The Folders menu continues to pop up and deliver that message when pressing any menu in the collar after that.

**Comment by SilkieSabra** [comment]
Now testing with the correct "experimental fix" script.  Works according to Specs.  When Trusted is denied access in Folders > Configuration, Trusted can get the menu, go to Folders, press Browse and then gets the Access Denied message as expected.  Thanks Medea !

**Comment by Medea-Destiny** [comment]
okay so I MAY have accidentally mislabelled a script and sent Roan the unfixed script labelled as the fixed script, sorry Roan and thanks for the confirmation the correct version which actually has the fix in does indeed fix. :D Fix will be implemented in 8.1.

**Comment by nirea** [comment]
8.1 is going out this weekend.  To make the release, the fix for this needs to be submitted in a clean pull request for just this issue (not a bunch of other bug fixes in the same PR).  That will help us do some quick targeted testing and have confidence we're not introducing new problems.
