### ISSUE TITLE
Strict Sit not cleanly released when sitting, and conflicts with STAND restriction.

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#582]
Version 8.1RC3

Scenario:
1. Strict sit is ON, and the wearer is forced to sit.
- Strict sit issues a sit restriction only when forcing a sit. Thus whether the sit restriction is normally on or off, but after being force-sat, the restriction is set. All good.
2. The strict sit option is switched off while the wearer is still seated, and subsequent force sit will not activate the sit restriction.
 

Observation: Switching off strict sit does not deactivate the sit restriction. Thus, despite Strict Sit being switched off, the collar wearer is still unable to stand up. What is more, clicking the UNSIT button will now no longer unsit the avatar. To get around this, the collar user must either switch the STAND restriction off by navigating to RLV/Restrictions/Movement, or switch Strict Sit back on before clicking the UNSIT button.

Scenario 2:
1. Collar user switches on SIT restriction in RLV/Restrictions/Movement
2. Collar user switches on STRICT SIT and force sits collar wearar
3.  Collar user uses UNSIT to make wearer stand

Observation: SIT is no longer restricted in RLV/Restrictions/Movement

Options:

1. We could simply replace the STRICT SIT option with a shortcut to the stand restriction button. Easy and avoids conflict, but removes the core functionality of STRICT SIT that it only restricts standing for forced sits.
2. We could handle the sit restriction for STRICT SIT locally, independent of the Restrictions settings. Easy and avoids conflicts, but UNSIT will still not work if there's a separate sit restriction 
3. We could read the restrictions mask setting in the RLVextension script, and store a value for the current STAND restriction so that the Force Sit menu can warn the user if a STAND restriction is set in the Restrictions menu. Easyish, avoids conflicts and removes confusion.
4.  We could make the UNSIT option temporarily override the STAND restriction by coding a temporary release function in the RLVsuite script that clears a STAND exception if existing, issues the @unsit command, then restores the sit restriction if existing. A bit more complicated and RLVsuite is a bit tight on memory space, and also raises questions of expectations. Should the UNSIT button work if sit is restricted?
5. Something else?

Discuss.

**Comment by Medea-Destiny** [comment]
Update. I have  RLVextension sniffing the linked messages to store the current value of the stand restriction. Right now all that I'm  using that for is a notification in the force sit menu prompt.

Where to go from here remains a question. In itself this isn't a fix, it's basically step one so I have it working. The Strict Sit function will set the restriction on force sitting anyway, so as it stands it can't be used to store the prior state. 

There are various ways around this. For example rather than setting the restriction through the settings script, the RLVextension script could issue its own stand restriction for sit strict, independently of the setting in restrictions. Then when Strict Sit is switched off, that restriction can be removed and the current restrictions as set in the restrictions menu restored.

Alternatively the RLVextensions script can store the current restriction state before it issues a stand restriction due to Strict Sit, and then restore that prior state if set when Strict Sit is removed. This would be my favoured approach, though it will result in the odd edge case where someone sets a restriction, then sets strict sit, then forces a sit, then goes back to restrictions and removes the restriction while the Strict Sit restriction is in place, then switches off  Strict Sit - in this case the restriction will be turned back on, as that was the prior restriction before the Sit Strict restriction was put in place.

We also have the option of allowing the UNSIT button to override any stand restrictions.

What's the way to go with this? How should this work for the users?

**Comment by SilkieSabra** [comment]
There's something i don't understand in your first post.  When you say "The strict sit option is switched off while the wearer is still seated, and subsequent force sit will not activate the sit restriction." does that mean you did that in the menu, or it happens automatically somehow?

**Comment by Medea-Destiny** [comment]
When Strict Sit is switched on, a stand restriction is activated only when the force sit menu is used to force sit the wearer. Without Strict Sit, no stand restriction is added on a forced sit. 

The way this is set to work currently, if you force sit someone while the Strict Sit option is on, the stand restriction is applied and they are sat. When you then click the UNSIT button, the stand restriction is removed and they are forced to stand. All good.

However, switching off the stand restriction when UNSIT is used only happens when Strict Sit is active. Switching Strict Sit off does not itself remove the stand restriction. Thus if you force sit someone with Strict Sit activated and _then_ deactivate the Strict Sit button, the UNSIT button will now fail silently. This is because sitting someone with the Strict Sit active causes the restrictions script to apply a stand restriction, but switching Strict Sit off will not remove the stand restriction.

**Comment by SilkieSabra** [comment]
The sole purpose of Strict Sit is to call unsit=n whenever force sit (sit:<UUID>=force) is called.  It should therefore call unsit=y when unsit=force is called.  It should not leave unsit=n in place after the force sit event has ended.  Would it be possible to send unsit=y whenever Strict Sit is turned off, whether or not the wearer is currently sitting on an object ?  If not, then leave it and we'll cover it in the documentation.

**Comment by Trinkitz** [comment]
Disclaimer: I struggle with scripting once we move too far past "Hello Avatar", but, maybe I can offer something to help. During my tests with this (8.1 RC-3) unsit does fail when strict sit is unchecked after being force-sat. If I check strict sit again, I can once again unsit myself. The main time I could see this happening is when someone is trying to escape - and unchecks "strict sit" thinking that will help them stand up. My thinking on this is more or less in line with Roan's.
