### ISSUE TITLE
Possible BUG in 8.1 RC-3 : Runaway Disable action

### ISSUE THREAD

**Issue by Trinkitz** [OpenCollarTeam/OpenCollar#585]
What version of OpenCollar are you using? 8.1  RC-3

What behavior did you expect? When an owner attempts to disable Runway, the wearer is supposed to be offered the opportunity to accept or decline this action.

What behavior did you see instead? No option was given. Runaway was disabled with no notification to the wearer.

What steps does someone need to take to reproduce the problem? Wearer who is not a named owner names an owner on the collar, that owner attempts to disable Runaway. Wearer should receive a notification and opportunity to accept or decline.

**Comment by Medea-Destiny** [comment]
This is not a bug per se as there is no code currently in the collar to request for confirmation of this action. 

Personally I _strongly_ believe that this is wrong and that owners should NOT be able to disallow runaway without the wearer's consent. At the very least there should be a notification to the wearer when this is done, but I really think we do need that accept or decline offer. I can add this easily enough, but let's get some consensus on this first before I go ahead.

**Comment by SilkieSabra** [comment]
Yes, there should be consent to disable runaway by menu, although there has always been a backdoor to do it via Settings and now that there is a Settings terminal, a knowledgeable operator might be able to use that.  In any case, a menu option to disable runaway is relatively new and should return a dialog to the wearer.

**Comment by Trinkitz** [comment]
From the Guide on Runaway. This is what led me to conclude that it IS supposed to happen: "Disable will block the wearer’s ability to run away on this collar. This action can be initiated by the wearer by cannot be reversed by the wearer. Only an owner can reverse it. If the owner presses Disable in the Runaway menu, the wearer gets a dialog box to accept or decline."  - also, my memory told me that earlier versions had offered this. Thanks!

**Comment by Medea-Destiny** [comment]
Confirmation dialog it shall be.
