### ISSUE TITLE
Possible Bug in 8.1 RC-3: Dazzle not working properly.

### ISSUE THREAD

**Issue by Trinkitz** [OpenCollarTeam/OpenCollar#586]
What version of OpenCollar are you using? 8.1 RC-3

What behavior did you expect? Dazzle is a macro which is supposed to blur the wearer's camera view. Guide says: " uses RLV to enforce the debug setting “RenderResolutionDivisor” and create a blurred vision of the environment on the viewer screen. "

What behavior did you see instead? Screen does not change. I am using Firestorm viewer. https://gyazo.com/47d3dbd341e105b5c54883c2a51f6339 

What steps does someone need to take to reproduce the problem? I experience this in any attempt to enforce the macro "Dazzle" . RLV - macros .

**Comment by Medea-Destiny** [comment]
Confirmed, binary value is incorrect and is setting @camunlock restriction instead. Thanks for the bug report, fix will be in 8.1
