### ISSUE TITLE
FOLDERS menu should indicate locked status of folders.

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#587]
8.0 divides folder functionality into separate oc_folders and oc_folders_locks scripts. This division was to reduce the common problem of stack heap errors in the folder script. The downside of this separation is that the folders script does not know which folders are locked. The user may attempt to attach a folder and find it fails silently, because the folder is in fact locked. 

I believe this is a fairly big downside (and have heard user comments to the same effect), but this can't simply be reverted because previously folders was crashing a LOT for people and the current division significantly reduces the memory overhead.  The folders script has to fetch and manipulate a long list of folders under the current path, and in the case of some users this list can be huge. 

The oc_states script monitors other scripts to check they are running and restarts them if they've stopped. I have added a line in this functionality in my branch targeting 8.1 that will identify if it is the folders script specifically that has stopped, and in this case warn the wearer that the likely cause is #RLV organization, suggesting they divide their #RLV folder with more subcategories and look for ~folders that are no longer needed and can be deleted.

However in the longer term I think it would be worth refactoring so that the locks are available to the folders script, and lock status can be displayed in the locks menu. The increased overhead will mean the #folders script is more likely to suffer stack heap collisions from oversized #RLV folders. However this could be ameliorated with some streamlining, possibly moving the folders access code into another script instead, for example, and with the warning as detailed in the above para I think we could tolerate a little more crashing for people with problematic organization of their #RLV folder.

**Comment by SilkieSabra** [comment]
Has this been fixed?

**Comment by Medea-Destiny** [comment]
No but it will be in the updated clothing system. We can close it for now.
