### ISSUE TITLE
Collar Chainpoint test spawns a leash

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#597]
What version of OpenCollar are you using? OpenCollar 8.0.5 (any 8.x collar)

What behavior did you expect? I set up 4 chain points in the collar, using the LG/LM system and including the OCC chainpoint names. I expected to see 4 chains when tested

What behavior did you see instead? The collar spawns a leash from the leashpoint named prim, in the direction of the chaining target. This would probably not be a big deal, except that this leash does not despawn when the user unsits the device. There is no "Unleash" option in the collar's Leash menu. The user must attach the leash to an object or a person to get a Unleash option in the menu

What steps does someone need to take to reproduce the problem? Add 4 chainpoints to the collar, and step into a device that calls for a chain to the fcollar aka collarfrontloop
![Fourpoint Issue](https://user-images.githubusercontent.com/6071164/125091755-b15c4180-e09e-11eb-9860-215246d0937f.png)

**Comment by Pingout** [comment]
In the script oc_particles, Line # 120 - 125 identify the four possible collar chain points and their LockGuard and Lockmeister equivalents.
Further on the script uses a findlinkedprims() state to direct a leash to a specific linked prim. Line # 158 to 161 appear to combine any front-facing prims into "fcollar"
Then line # 170 - 172 points these front-facing prims to LINK_ROOT
Commenting out these lines (158-161, and 170-172) will turn off the leash that appears in this test, but I still don't know what harmful side effects might result from this change

**Comment by Medea-Destiny** [comment]
Commenting out these lines will result in no leashpoint being defined for a standard leashpoint prim - looks like it would break standard leashing if the collar doesn't have an fcollar prim defined. 

I'm not very familiar with the leash/particle stuff having not really looked at in since 3.x, but taking a quick look at the findlinkedprims() function I can see a number of situational issues that will need addressing. For now though, can you try commenting out line 159 (  g_lLeashPrims += ["fcollar", i]; ) and see if that resolves this specific issue for you?

**Comment by Pingout** [comment]
> Commenting out these lines will result in no leashpoint being defined for a standard leashpoint prim - looks like it would break standard leashing if the collar doesn't have an fcollar prim defined.
> 
> I'm not very familiar with the leash/particle stuff having not really looked at in since 3.x, but taking a quick look at the findlinkedprims() function I can see a number of situational issues that will need addressing. For now though, can you try commenting out line 159 ( g_lLeashPrims += ["fcollar", i]; ) and see if that resolves this specific issue for you?

This comment of line 159 was not successful, however I made a discovery that makes this issue null. 
I analyzed the leash, and the test device for the collar chain points, both of them appeared to have the collar as the spawn point of the leash/chain.
We know a chainpoint can be the END of multiple chains, but can only spawn one at a time, so by this reasoning if the collar leashprim and the lockguard chain point are the same prim, that prim can only spawn one set of particles, either the leash or the chain but not both. So I deleted the leashprim, and renamed the Collar Front loop, calling it "leashprim"
It looks like we got lucky, it tries to spawn both, but the lockguard chain is dominant. We tested it on a few bdsm devices. The collarfrontloop chain works good, and the leash also works fine when the subject is not restrained.
