### ISSUE TITLE
Latest 8.1 scripts allowing a second OC collar to be worn

### ISSUE THREAD

**Issue by Trinkitz** [OpenCollarTeam/OpenCollar#598]
What version of OpenCollar are you using? 8.1 RC-3 (latest updates)

What behavior did you expect? Second OC collar should be detached

What behavior did you see instead? Second OC collar was allowed as an add-on:  [08:13] Ping Designs: Addon connected successfully: OpenCollar

What steps does someone need to take to reproduce the problem? Wear a collar with current 8.1 scripts, and then add a second collar, also with current 8.1 scripts.

**Comment by Medea-Destiny** [comment]
This was covered in one of the fixes I have already provided. Trinkitz, try again with the update oc_api and oc_core scripts from the features branch and you should see that you get the extra collar removed as per usual.

**Comment by Medea-Destiny** [comment]
My apologies, a critical fix got reverted during one of the revisions. #603 will restore that fix.
