### ISSUE TITLE
oc_meshthemes should implement hide/show/stealth

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#61]
The new oc_meshthemes script simplifies our theme support (for single-prim mesh collars, specifically).  But since it replaces oc_themes, it should also implement the hide/show/stealth functionality from oc_themes.

**Comment by nirea** [comment]
Implemented in 094315db7c4e635fb8d35dd765c46699ac2ed620

**Comment by silentwar-resident** [comment]
What about some of us still using prim collars?

**Comment by nirea** [comment]
The oc_themes script is still present and supported for those collars.
