### ISSUE TITLE
Leash target conflict when leasher has both collar and leashholder

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#610]
Reported by several people in world. 

Please report your experiences if you have seen this problem, particularly if you know that both the leashee and leasher's collars are up to date, and into about what leash handle was being used.

**Comment by Trinkitz** [comment]
We have tried to duplicate this issue, without success. We did have one "maybe" moment, when the leash jumped from my leash holder to my collar, but we ran out of time to try to duplicate it. We have tried several different leash holders, some VERY old, with no luck in getting the leash to attach anywhere but the holder, even when both are wearing collars.

**Comment by Medea-Destiny** [comment]
No further information or reliable duplication has been found, so this issue is being closed pending further general work on leash.
