### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#62]
May we add back in bookmarks, and delete the scripted-in Temple and Sidekick default bookmarks, and do we need to add a default bookmark or can it go out with that blank?

**Comment by nirea** [comment]
I'm fine with having it blank by default, so long as it doesn't break the script.

Would like to get more opinions on whether this should be in the default distribution or something spares/.

Maybe a good thing to ask about if we put together a survey.

**Comment by SilkieSabra** [comment]
There are very many collars out there that have a bookmarks script with the Temple and Sidekick bookmarks scripted in; so either the updater should overwrite that with our own bookmarks script, or delete the existing one

**Comment by JAY1976** [comment]
I've just been manually deleting the oc_bookmarks script when updating with the betas, it doesn't seem to do any damage to the collar itself, just a little burden that I have to keep an eye out for when updating :)

**Comment by nirea** [comment]
oc_bookmarks is included in yesterday's 7.0 release.
