### ISSUE TITLE
Remote not remaining connected

### ISSUE THREAD

**Issue by Psypher-Overdrive** [OpenCollarTeam/OpenCollar#620]
What version of OpenCollar are you using?
8.0.5

What behavior did you expect?
The old remote, I believe 7.0, would remain connected to the last collar it was used on. I would think this would be a much better option than having to continuously reconnect, especially for those of us that do not have more than one collar. nor wish to have more . 

What behavior did you see instead?
Having to continuously reconnect the remote to the collar.

What steps does someone need to take to reproduce the problem?
Use the newer remote

I mean there are options here... could default it to last collar used with the option to switch to another collar. Could also offer 2 remotes one for single use and one for multiple. Or just an option upon loading the remote for the first time for single collar use or multiple collar. Please consider this, as it is really bothersome to constantly have to reconnect the remote, when one has no desire of owning multiple collars.

**Comment by SilkieSabra** [comment]
One has to connect the remote, a two-click process (click the star button and select the name) on relog, or when the wearer moves to a different region.
