### ISSUE TITLE
Open Collar Remote 6.6.0 No Mod Script

### ISSUE THREAD

**Issue by taylorpaine** [OpenCollarTeam/OpenCollar#63]
What version of OpenCollar are you using?  OC 7.0beta8

What behavior did you expect? n/a

What behavior did you see instead? n/a

What steps does someone need to take to reproduce the problem? n/a

** There is a no mod script in the remote 6.6.0 named "vd_remote_accessory".  No idea why it is there or what it does.  I did delete it from the contents and the remotes appears to still be working just fine with the OC 7.0beta8.  It might be worth checking into, if possible.

**Comment by nirea** [comment]
I'm going to add a "Remote" label to this.  When we do a clean release of the remote, this will be part of it.
