### ISSUE TITLE
Cuffs Restrictions don't release

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#630]
In OpenCollar Addon Cuffs V1, we set restrictions for each pose with the line PoseRestrictions:[restriction]=[value].  The restrictions were not individually tested for V 1.0.  It now turns out that the line will set the restriction, but the restriction does not clear when the pose is changed or stopped, until after a relog.

So, if each pose has a set of restrictions, and you change poses, the new restrictions are added and the restrictions from the former pose are retained.  If you stop the pose, the restrictions are still enforced.  Relogging clears it.

**Comment by Pingout** [comment]
See PR #662 for the possible fix
