### ISSUE TITLE
Feature Request : Bookmarks app

### ISSUE THREAD

**Issue by FrankkParisi** [OpenCollarTeam/OpenCollar#646]
What version of OpenCollar are you using?
8.1

What behavior did you expect?
Was expecting that my sub (collar wearer but not on owner list / self owner) would not be able to add or remove bookmarks 

What behavior did you see instead?
wearer can add and/or delete bookmarks even if collar locked, rlv on etc etc

Would be great to have bookmarks app enhanced so that only owner can add and delete bookmarks (maybe even only owner can see them!))

**Comment by FrankkParisi** [comment]
Having looked at this further, i can now see how use of .bookmarks nc enables perm bookmarks which collar wearer (if not owner) cant remove from the collar/app menu which is good.

**Comment by Medea-Destiny** [comment]
@FrankkParisi does this resolve your issue? Shall I close it now?
