### ISSUE TITLE
Feature Request : OC Remote to enable connection to collar wearers across sims

### ISSUE THREAD

**Issue by FrankkParisi** [OpenCollarTeam/OpenCollar#647]
What version of OpenCollar are you using?
8.1

The OC remote is great - It reminds me of some of the functionality from the old days of icontrol.
It would be amazing if the icontrols feature of being able to control collar wearer **across sims** (i.e the OC menu) could be part of OC 
e.g. be able to pose collar wearer wherever they are even if in a completely different sim to you
e.g. be able to send them to a bookmark even if they are currently in a different sim to you 
etc etc

Thanks

**Comment by Medea-Destiny** [comment]
This cannot be done without using an external server.

To communicate with an object in a different sim, the collar needs to know the UUID of the object, which changes each time it's rezzed, or if we use HTTP it would need the URL of the collar, which would have to change on every teleport. Therefore to manage this the collar would have to send its current UUID/URL to a known, stable, non-changing server to inform it of its current address, and that same server would be queried by the HUD to get the current collar address. 

Running an external server for all collars is not something that's currently in the plans for OC. However I'll leave this issue open for now as there is scope for third party servers running via an app, or for us to provide simple in-world servers that people can leave rezzed in-world for their own collar, and that's worth a discussion.

**Comment by SilkieSabra** [comment]
I think it would be great to provide a kit for people to set up their own inworld servers.

**Comment by FrankkParisi** [comment]
Thanks for responses. I like the idea of the inworld server !! Might be a good way to test this out and see if popular
