### ISSUE TITLE
RLV menu work & exceptions refactoring - oc_rlvsys, oc_rlvsuite and oc_rlvextension modifications

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#649]
1. The RLV menus are a bit confusing and not all that logically arranged.
2.  The exception system could do with an efficiency overhaul, particularly at boot time. As per 8.1 the collar will issue potentially hundreds of duplicate or unset RLV commands at boot time, which isn't a good thing.
3. We could really use a system to allow restrictions to be temporarily overriden to avoid conflicts between scripts, for example when using the UNSIT button in the force sit menu when a sit restriction is in place.

This work will involve significant revision to oc_rlvsys, oc_rlvsuite and oc_rlvextension. **This work is now mostly complete**. If anyone has some changes they intend to make to any of these scripts, I urge you to contact me first.

Scope of the work:
1. Refactoring: I'm reworking a bunch of internal stuff to improve efficiency, particularly with RLV exceptions. A number of bug-fixes are included in this.
2. Menu changes:The current layout of menus in RLV is a touch confusing. We have an RLV settings menu that has the exceptions options as a sub menu in it, which is contrary to where it has traditionally been, and has caused some issues with people trying to find things. Also in that menu are the settings to control camera restrictions, muffling and blur. It makes more sense to have these as a submenu of Restrictions, as they impact the settings in restrictions. Therefore I am reinstituting the Exceptions menu as a submenu of RLV, and moving the restrictions settings to the [MANAGE] submenu of the RLV/Restrictions menu
3. Menu clarity: A number of these menus are not that clear, and do not explain what function they perform. I am adding explanatory text to clarify as much as possible, particularly explaining what the MACRO restrictions actually are and how to use them.
4. A link-message command to allow restrictions to be temporarily overriden. This command is in the form llMessageLinked(LINK_THIS,RLV_COMMAND_OVERRIDE,commands_to_send,restrictions_to_lift); commands_to_send and restrictions_to_lift are CSV strings. When a command using this protocol is received, oc_rlvsys will check if any restrictions in restrictions_to_lift are currently in place, and lift them if so. It will then issue commands_to_send with the =force parameter, and then reinstitute any lifted restrictions. The purpose of this is to allow scripts to temporarily lift restrictions for the sake of one-shot commands. For example, owners will now be able to use the UNSIT button in the Force Sit menu, even if an unsit restriction is currently in place.
5. STRICT SIT handling will be changed to avoid conflicts with restrictions. See #582.

NEXT STEPS: 
I am currently finishing up work on the Extensions refactoring and logic testing, and considering the best way to handle the strict sit issue. After this is all done and passed my initial testing I will be providing a bundle of scripts to testers to play with. The two things testers will be asked to look at and comment on here are firstly that everything's working as intended, and secondly that the menu changes are something everyone agrees with.

**Comment by Pingout** [comment]
This looks great, Medea. Let me know when you have something ready for the testing team, we'll jump right on it!

**Comment by Medea-Destiny** [comment]
This work is now in testing.

Roan has questioned the menu layout I have gone for, which is closer to the 7.4/7.5 structure by having "macros" as the first port of call when you select Restrictions, and the detailed restrictions as a submenu of them. She has pointed out that some people had expressed happiness that in 8.0/8.1 we have detailed restrictions at the top level of RLV, and obviously we need to consider these changes in the light of that, and if this is really want people will want.

I would counter that as the detailed restrictions had been entirely missing in versions 4.0 through 7.3, the issue here is more that most people didn't even  _know_ we're returned them to OC. My proposed layout requires only one more click to get to them, and in contrast to the 8.0/8.1 menu structure respects the standard UI paradigm of having detailed controls below simple controls rather than parallel to them, and maintains a much more logical structure. Conversely I have heard people complaining that the restrictions menu they've been used to since 4.0 is missing - of course it isn't, it just got renamed Macros, and we've never really explained what macros are. 

I have created  a UI flow diagram comparing the current and proposed layouts [here](https://i.imgur.com/mnAElqI.png) and urge people to take a look to understand better what is being proposed.

**Comment by nirea** [comment]
Thank you sooooooo much for attention to these things.  Your numbered list breaking it into three topics makes sense.  Could we make those three separate issues and separate PRs?  It can get really hard to discuss and review and test so many things at once.

Ideally the menu changes would be one thing and the refactoring would be another and the temp override feature would be another.

I'm 95% sure we want the refactoring work.

I'm about 65% sure we want the menu revamp.

I'm about 40% sure we want the temporary override feature.  I worry that it might be more complexity than it's worth.  To answer that question I'd want to see the code for it in its own PR, and compare that against community feedback.

**Comment by Medea-Destiny** [comment]
The temporary override code is as follows:
```
else if(iNum == RLV_CMD_OVERRIDE){
                //New feature! RLV_CMD_OVERRIDE is designed to allow one-shot (force) commands to override current restrictions. This is done by sending the behavior(s) to lift as a comma separate list as kID and the commands to send as a comma separated list as sMsg. EXAMPLE: llMessageLinked(LINK_THIS,RLV_CMD_OVERRIDE,"unsit",(key)"unsit") will lift the current unsit restriction if present, issue an @unsit=force, then restore the unsit restriction if it was previously present. These commands should ONLY be sent if the issuer has OWNER auth.
                list lOverrides=llParseString2List((string)kID,[","],[]);
                integer iLen=llGetListLength(lOverrides);
                while(iLen--) {
                    if(llListFindList(g_lBaked,llList2List(lOverrides,iLen,iLen))==-1)    {
                           lOverrides=llDeleteSubList(lOverrides,iLen,iLen);
                           }
                    else llOwnerSay("@"+llList2String(lOverrides,iLen)+"=y");
                }
                list lCommands=llParseString2List(sStr,[","],[]);
                llSleep(0.5); //give a moment for restrictions to be released)
                iLen=llGetListLength(lCommands);          
                while(iLen--){
                    llOwnerSay("@"+llList2String(lCommands,iLen)+"=force");
                    llSleep(0.1);
                }
                llSleep(0.5); //Give time for commands to be issued before restoring restrictions
                iLen=llGetListLength(lOverrides);
                while(iLen--){
                    llOwnerSay("@"+llList2String(lOverrides,iLen)+"=n");
                }
            }
        }
```


It's  already used as part of these changes to allow the  [unsit] button to work for a collar owner even if a rrestrictions is in place.


There are other situations where it can be used for a similar effect - owner tries to strip the wearer when dress restrictions are in place, for example. I don't think complexity is an issue,  with it in place it's just something that can be used or not.  It seems illogical to me that a collar owner should be restricted in what they can do by restrictions that are supposed to restrict the actions of the wearer, not owners, and this removes the need for an owner to unset restrictions, do what they intend, and then reset them again.
