### ISSUE TITLE
cuff points collar release code.

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#650]
What version of OpenCollar are you using? 
V8.1.0000

What behavior did you expect?
when released from something that connects a chain to the back left and right leash points for it to remove said chain

What behavior did you see instead?
the chain is still there even after the item was drezed and a relog

What steps does someone need to take to reproduce the problem?
ping's leash point tester, and maybe any other rlv item that takes those points 
on the collar.

**Comment by Pingout** [comment]
Superceeded by https://github.com/OpenCollarTeam/OpenCollar/pull/966
