### ISSUE TITLE
Provide easy ways to cycle worn subfolders.

### ISSUE THREAD

**Issue by SatomiAhn** [OpenCollarTeam/OpenCollar#67]
Say you are working at dressing yourself (or your sub), and you are wondering what pair of shoes you will be wearing.

Currently, if you want to do this with OC (but it is hardly better using the viewer inventory GUI), you need to browse into your Shoes folder, then select a subfolder to wear, click on the button for wearing it, then, after deciding these are definitely not the shoes you want, click the button to unwear them, then go back to the Shoes folder, then go into the next shoes subfolders, and so on.

This is rather lengthy and unpractical.

I actually suggest 2 features to help with this:
- add a command/button next to "wear" and "replace", that will not only attach the target folder to the avatar, but also detach all sibling folders (i.e. all folders that are at the same level, in our example: all other pairs of shoes). This should also be lifted to a new chat command for the search-and-wear framework.
- in folders containing several wearable subfolders, when exactly one of them is worn, add 2 buttons: "cycle next" and "cycle previous". The effect would be to detach the currently worn subfolder and attach the next (or previous) one (in alphabetical order). Chat commands should also be added, such as "wearnext >Shoes" (if ">Shoes" is the folder where all the shoes are kept) and "wearprevious >Shoes".

**Comment by SilkieSabra** [comment]
This  seems to have been adopted in a slightly different way by oc_outfits.
