### ISSUE TITLE
RLV restrictions don't persist after re-attaching collar

### ISSUE THREAD

**Issue by AliciaBeele** [OpenCollarTeam/OpenCollar#671]
I wrote a plugin for OC which sets some restrictions using:

`llMessageLinked(LINK_THIS,RLV_CMD,sRestriction+"=n","ABRestrict");`

Now with version 7.x these restrictions were reapplied after reattaching the collar AFAIK.
with the current version, this does not seem to be the case. When i reattach the collar, they are not applied.
It would be great if OC would reapply the restrictions.

Snippet from my plugin:

```
...
list restrictions = ["startim","sendim","showinv","setoverlay"];
...
AddRestriction(string sRestriction){
     llMessageLinked(LINK_THIS,RLV_CMD,sRestriction+"=n","ABRestrict");
}
...
for(i =0;i< llGetListLength(restrictions);i++){
          AddRestriction(llList2String(restrictions,i));    
}
...
```

**Comment by Medea-Destiny** [comment]
Plugins are supposed to resend required restrictions when receiving the RLV_REFRESH signal (integer RLV_REFRESH = 6001;) -- add a check for this link message, and resend the required restrictions when the message is received. 

Please let us know if this resolves your issue.
