### ISSUE TITLE
OC built-in relay doesn't restore restrictions after release

### ISSUE THREAD

**Issue by HappyDee** [OpenCollarTeam/OpenCollar#679]
What version of OpenCollar are you using? 8.1

What behavior did you expect? 

the following owner-set restrictions were in place (applied through menu and working as expected)

-------- startim
-------- recvim
-------- sendim

After entering a cage which applied similar restrictions, and the cage timer expiring, the same restrictions would be in place.

What behavior did you see instead?

The restrictions were not restored by the collar after the device using the relay released the user. Group chats and IM's were no longer restricted. This was verified using the "RLV/List restrictions" drop-down on the Kokua viewer.

Logging off, waiting a few minutes, and logging back on, the owner-set restrictions were again in place.

What steps does someone need to take to reproduce the problem?

Set an RLV restriction in the collar
Use a device which applies the same restriction through the OC relay
When the device using the relay releases control, the owner-set restrictions will no longer be in place.
Logging off and logging back on will restore the restrictions.

**Comment by tayaphidoux** [comment]
i have noticed this to its a result of just forwarding the clear all restriction command rather than intercepting it and being smart about clearing restrictions.

**Comment by tayaphidoux** [comment]
or once clear all is called you trigger the collar to reapply its restrictions less work with this option.

**Comment by HappyDee** [comment]
> or once clear all is called you trigger the collar to reapply its restrictions less work with this option.

Thanks! Other than a re-log, is there a way for a locked wearer to trigger that reapplying?

**Comment by tayaphidoux** [comment]
for me a teleport usualy does it

**Comment by SilkieSabra** [comment]
This is corrected with 8.2.3 I believe
