### ISSUE TITLE
Scripted Prims named "Object"

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#68]
While editing the Settings page for the User Guide I noted that the OpenCollar 7.0 does not have dedicated names for the child prims containing the scripts.

I'm not sure how the listen events work more efficiently without dedicated prim names or link numbers but that's not for me to worry about.  But it certainly would be much easier to explain how to add animations and save settings if these prims, which many users have to find, had names.

**Comment by nirea** [comment]
I just changed this in the default collar.  Still need to do it in the
childprims rezzed when updating a 3.x collar.

**Comment by nirea** [comment]
OK, I've updated the prims in the updaters now too.
