### ISSUE TITLE
IDEA: Modulated start-up

### ISSUE THREAD

**Issue by nightshade231** [OpenCollarTeam/OpenCollar#691]
In a converstation in the main OpenCollar group, I had mentioned either starting scripts up in Modules, or syncing the scripts into stages of importance.

Here's some pros of modules:-
• Modulating scripts to start at rez can also be used to turn off select modules to save memory and script time usage
• Booting each module can be paralleled, or individual, and allows stuck scripts to be restarted independently, instead of resetting every script in the object.

Some of the cons of modulating are:-
• Scripts in the module can hold up the entire module should one spontaneously crash/fail to run.
• Can temporarily impact the sim due to the varying CPU peak for the given scripts in the module.
... And more.

Syncing the scripts done by "Priority grouping" is a little harder, however they can:-
• Allow higher priority scripts to boot first
• Uses less peak CPU times at boot

Some cons of syncing with priority are:-
• Should a script be missing/stuck in the priority chain, the script after may not load and fail. 
• Doesn't easily allow memory savings by turning lower priority scripts off.

As of current, I have no examples of how this can be done, as I am fairly new still to the scripting scene. If someone can whip an example of both ideas, that'd be great!

**Comment by SilkieSabra** [comment]
Improved startup time in 8.2.3 makes this good suggestion obsolete.
