### ISSUE TITLE
OC Cuffs: Make the cuffs hideable

### ISSUE THREAD

**Issue by mvolli** [OpenCollarTeam/OpenCollar#692]
What version of OpenCollar are you using?
OC Addon Cuffs V2.0 Full Release

What behavior did you expect?
A show/hide button

The oc_cuffs script already has a 'ToggleAlpha' function in it. (Line 406).
Add a button to use it to the Addons Menu

**Comment by DonovanQuinn** [comment]
Would love to have a show/hide button on the cuffs!

**Comment by cruelraremaster** [comment]
#692 and #900 are related, although not identical. But maybe if one is implemented, then the other issue can be closed too.

**Comment by SilkieSabra** [comment]
There's no necessity for show/hide on the cuffs.  If they are locked in a pose it would be very strange for them to be hidden.  If they are not locked on, take them off.
