### ISSUE TITLE
Unsit Button in Remote not working to Unsit in V 8.2

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#703]
The OpenCollar Remote has a separate button for Unsit.  This button is not unsitting an avatar in V 8.2.  It does unsit in V 8.1.
Perhaps the rewrite to the Force Sit broke this function for the Remote?

Work around would be to use the Sit button instead of Unsit, which opens the Force Sit menu where you can there push Unsit.
It might be easier to restore function to the Unsit button than to remove it from the Remote though?

**Comment by SilkieSabra** [comment]
Also [prefix] unsit is not working but the collar unsit button does work.

**Comment by VioletVoxel** [comment]
Just went looking for support for this in group chat, prefix unsit doesn't work, independent of whether the person sat by themselves, was force sat, or whether strict sitting is on or off. I use these as core features in gestures bound to buttons(!)

**Comment by Medea-Destiny** [comment]
A change to chat filtering flow in the usercommand function of RLVextension. Fix in testing.

**Comment by VioletVoxel** [comment]
Thaaaanks!
