### ISSUE TITLE
Issue with OC cuffs add-on staying connected in third party collar & cuffs V.8.2 update

### ISSUE THREAD

**Issue by Kemsyormega** [OpenCollarTeam/OpenCollar#706]
What version of OpenCollar are you using? 8.2

What behavior did you expect? my cuffs to stay connected to my collar.......

What behavior did you see instead? Lost connection to collar - resetting **or** Addon:  has been removed because it has not been seen for 5 minutes or more.

What steps does someone need to take to reproduce the problem? all I did was update my collar. It's been crap ever since. I tried resetting the scripts. I tried doing a fresh update. I also tried dropping fresh scripts into the cuffs. I had no issue with previous versions of OC with my collar and cuffs. This is for both the ankle cuffs and the wrist/arm cuffs. I complained multiple times in the group chat and was told it was the sim I was on, even though I stated it happens no matter where I go.  OC advice one time was to stand at the bottom of the ocean. Little to no customer service.

**Comment by Pingout** [comment]
Hi Kemsyormega, I'm sorry to hear you are still having trouble with this. The "stand at the bottom of the ocean" suggestion was a test to see if lag was the real issue. I suggested you go to a protected Linden Labs sim (no lag) and try the cuffs there. As I recall you said they work fine on a no-lag sim. You also indicated you lived on a Mainland sim, which are typically much slower than stand alone sims. Unfortunately there is very little we can do about lag other than having you remove any unnecessary scripted items. 
When we were working on the 8.2 Update, a primary concern was speeding up the time it takes for the collar to start. It seems like, although this reduced start time has helped hundreds of users, in your case the sim lag combined with reduced start time has generated this disconnecting situation.
We may be able to address these disconnects in the next version, and until them you may want to roll back to the 8.1 version, accepting the longer start time as a way to avoid disconnects.
