### ISSUE TITLE
Teleport Function for Collar Owner

### ISSUE THREAD

**Issue by FunViking** [OpenCollarTeam/OpenCollar#715]
What version of OpenCollar are you using? 8.2.1000

What behavior did you expect? To be able to teleport to same location as my sub with a single click when I force teleport my sub. 

What behavior did you see instead? Unable to teleport to same location as my sub after I force teleport, without having to wait until sub arrives at location and sends me teleport request.  There was a function on the peanut 9 collar that popped up after I force teleported my sub which asked me if I wanted to teleport to same location.  A popup menu or HUD came up as I sent my sub and all I had to do was click yes or no.  We would arrive at the location at about the same time. This function was very beneficial when I would take her shopping or exploring.  

What steps does someone need to take to reproduce the problem? There is no problem I am just making suggestion for improvement.

**Comment by Medea-Destiny** [comment]
The easiest way to do this is have the bookmarks app send the SLURL in chat to the person ordering a teleport. This would be a clickable map link in chat. I can add this easily for the next release

We could add a function to the remote that allows landmarks to be dropped into the remote to trigger simultaneous teleports where the user of the remote has RLV active, or if we reintroduce extended interface channel functionality (which I am in favour of) it would be pretty trivial to make a teleport hud that did this.

**Comment by FunViking** [comment]
Results of the testing so far are as follows. The teleport information came up in my nearby and I clicked on it to teleport but then I got this message, you can only teleport 6 times in a minute.  Wait one minute and try again.   I waited over a minute and got the same message again.  collar is sending me somewhere different than where I force tp sub Serena (128,128,13) but it sent me to [20:57:31] Goannas Billabong, Serena (128, 128, 1): the collar is sending her to the correct tp location every time,but sending me to different places second time I went to Tropical (59,220,25) but I sent her to Tropical Lodge/170.000000/94.000000/27.000000.  The instructions you sent with the new script worked just as you had it on the notecard.

**Comment by cruelraremaster** [comment]
Seems to be fixed with above PR
