### ISSUE TITLE
Force TP exception resetting

### ISSUE THREAD

**Issue by elizaveta-markova** [OpenCollarTeam/OpenCollar#719]
What version of OpenCollar are you using?
8.2.1

What behavior did you expect?
As Owner I would like _not_ to Force TP. I unchecked the box Force TP under Exceptions.

What behavior did you see instead?
After relog Force TP is again active and the exception box is checked again.

What steps does someone need to take to reproduce the problem?
RLV Exceptions/Owner/Force TP(uncheck)
relog

**Comment by Medea-Destiny** [comment]
same as issue #740
