### ISSUE TITLE
Owner exceptionnotsaving in 8.2

### ISSUE THREAD

**Issue by MaXX-Troell** [OpenCollarTeam/OpenCollar#720]
What version of OpenCollar are you using? 8.2

What behavior did you expect? that the exceptions to save

What behavior did you see instead? they reset to stock

What steps does someone need to take to reproduce the problem? the slave bought a oc septumring off the mp, we updated it via the recomended way when I went to the owner exceptions in the rlv box i was able to create the exception but as soon as she relogs the exceptions are not saved

**Comment by Medea-Destiny** [comment]
same as issue #740
