### ISSUE TITLE
Plugin Agreement

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#73]
It might encourage good scripters and content creators to build better plugins and peripherals for OpenCollar if we had a clearly spelled out plugin agreement under what conditions plugins would require the same license.. for instance if the only "opencollar derived" code they contain is the listener / handshake to the collar, the plugin script itself can be no mod; and they are allowed to sell their creations.  These are two concerns many scripters i talk to have that i think could be clarified.  I recently looked at Marine Kelley's extensive plugin agreement.. ours need not be so elaborate but it's worth comparing them.

**Comment by nirea** [comment]
It's a good idea.  In addition to the message map constants, most plugins would probably also want to include a copy of the Dialog function.

I'd also want to ask plugin authors to *not* prefix their scripts with oc_.  They can use their own prefix, or another naming pattern entirely.

**Comment by nirea** [comment]
I'm not sure I'd call this an "agreement" though.  It's not like authors have to agree to the terms before they're legally allowed to write a plugin.  This could just be a paragraph about being a good citizen inside a larger "Writing Plugins" guide.

**Comment by zontreck** [comment]
Sounds like a good idea to me to have a plugin agreement.

**Comment by agesly** [comment]
It is good to remind that the plugin template is released under public domain, that explicitly says you can use it for any purpose as long as you don't use code from other parts of OC together with it.

**Comment by SilkieSabra** [comment]
There is a draft plugin agreement [here ](https://github.com/OpenCollarTeam/opencollarteam.github.io/blob/master/docs/Plugin-Guide.md)

I never linked to it because didn't have a final ok for publication after Aria produced the template.

**Comment by zontreck** [comment]
@SilkieSabra That's more of a plugin guide than a agreement.  An agreement would specify dos and don'ts to prevent breaking the core scripts or user experience. And as @nirea said above, and as it is stated in the plugin guide you have there, it would also specify to not use the oc_ prefix.

**Comment by SilkieSabra** [comment]
At any rate I hope something you can use is already there. The three key features we are discussing include the list of do's and don'ts, the permissions and licenses, as well as the "technical" part nirea wrote which is too brief for me to be able to see whether she meant it as a guide or an agreement/ set of requirements.  My reason for putting my oar in, in the first place, was to make sure creators had a clear go-ahead to make closed source plugins for OpenCollar and stay within the license--which Aria accomplished by making the plugin template public domain; yet there are creators who are not using that template. An agreement is a good idea.

**Comment by zontreck** [comment]
Yea. The template was specifically set as public domain so that plugins can infact be closed source if the author of the plugin wants it to be that way.  An agreement would be slightly different from a license though as it would take the legalese and make it human readable. And in some cases an agreement extends past a license by saying that we wouldn't allow for naming plugins certain ways, or for example since this is actually in the RR agreement: not to use touch events, or email events as it can mess up other internals. Our scripts don't utilize the email event, so there's really no need to restrict that in ours.  I'll talk to you inworld tomorrow @SilkieSabra and we can come up with a draft for the agreement.
