### ISSUE TITLE
Move auth check to oc_com and get rid of LMs for requesting auth

### ISSUE THREAD

**Issue by SatomiAhn** [OpenCollarTeam/OpenCollar#74]
In a comment I posted on issue #70, I pointed the fact that if auth data was stored in prim media properties, then auth data could be obtained directly by any script without using link messages. Thus current system for requesting and obtaining auth tokens would become a useless and wasteful complication.

Thus I propose we remove this system (that is emitters and handlers of CMD_ZERO and AUTH_REQUEST LMs) and move the Auth() function from oc_auth to the almost only client of the auth system: oc_com.

I said "almost only", because oc_sys and oc_capture also use it, and oc_auth uses the Auth() directly. Fortunately it can easily be fixed.
- oc_sys uses CMD_ZERO for "menuto", but the handler for this command can be moved to oc_com since it uses no local data
- oc_capture has a touch_start event handler which triggers a CMD_ZERO for authing this touch. The same feature can be achieved by listening to CMD_EVERYONE "menu" messages (it's even better, since it will also react to menu requests issued by chat).
- oc_auth uses Auth() for answering CMD_ZERO messages (of course), but also for auth'ing its own commands (for auth configuration). The later uses can be refactored so that oc_auth works in a more standard way, using the auth token it received along with the command, from either oc_com or oc_dialog.

Benefits:
- less LMs are exchanged
- a leaner message map
- oc_auth becomes dead simple and has even more room for storing owners

Disadvantage:
- oc_com becomes bigger. It should be checked whether it retains enough free memory.

**Comment by nirea** [comment]
Love it.

**Comment by CorwinDavidson** [comment]
Here's a fun little function you might enjoy...
```
integer OWNER_LIST = 1;
integer TRUST_LIST = 2;
integer BLOCK_LIST = 3;

integer hasAuth(integer iList, string kID)
{
    return ~llSubStringIndex((string)llGetLinkMedia(LINK_AUTH,iList,[PRIM_MEDIA_HOME_URL]) + "," + (string)llGetLinkMedia(LINK_AUTH,iList,[PRIM_MEDIA_WHITELIST]), kID);
}
```
Where iList is:
1 - Owner
2 - Trusted
3 - Blocked

Probably need something for Group and TempOwner as well

**Comment by nirea** [comment]
I've been thinking about which prim we should use for this.  I think it should be one of the hidden child prims that is required to be present in current collar versions.  I see that @CorwinDavidson's example is using LINK_AUTH, and that makes sense.

One question though: Are we guaranteed to have enough faces?  If face numbering starts at 0, then the example requires at least 4 faces on the prim.  A sphere might only have 1.

Some collar designs have a few little LED-style prims that light up when the scripts inside do certain things.  If LINK_AUTH is commonly used as one of those LED prims, then we should check that it has enough sides in those designs.

**Comment by nirea** [comment]
By contrast, in designs where LINK_AUTH is invisible, we could reshape it in oc_update_shim however we want.

**Comment by CorwinDavidson** [comment]
A hollow sphere has 4 sides

**Comment by SatomiAhn** [comment]
Now we should beware the moment LL actually decides to check whether valid URLs are entered in PRIM_MEDIA. I bet [this will never happen](https://xkcd.com/1172/) though.

**Comment by nirea** [comment]
I just skimmed the in-progress implementation on Corwin's branch.

I see that there's a 35 person limit.  Should we perhaps just check the string length being saved instead?  It would be less arbitrary that way.

If possible, I'd like to stage the changes here into two phases: 1) replace the storage of these lists with the PRIM_MEDIA solution, and then separately replace CMD_* messages with a hasAuth function in every script that needs it.

I'm wondering if we should use a fourth face that just stores a bit field for things like ownself.

**Comment by CorwinDavidson** [comment]
I was actually thinking of a JSON key/value array on a fourth face (face 0) for the bit fields and any short items like the tempOwner and groupOwner.

{ "ktempOwner" : "01234567-89ab-cdef-0123-456789abcdef", "kGroupKey" : "01234567-89ab-cdef-0123-456789abcdef", "isOpenAccess":"1", "isGroupEnabled":"0","isLimitRange":"1" }

then you can use llJsonGetValue and llJsonSetValue for those item.

I've also considered changing the stored owner list as a JSON array:

{ "owner" : [ "01234567-89ab-cdef-0123-456789abcdef","01234567-89ab-cdef-0123-456789abcdef"] }
etc.

And eliminating the conversions to lists as you can search for keys using llSubStringIndex and can remove items using the strReplace function below:

string strReplace(string str, string search, string replace) {
    return llDumpList2String(llParseStringKeepNulls((str = "") + str, [search], []), replace);
}

**Comment by nirea** [comment]
JSON wastes a bunch of space though, with all its quotes and curly braces.

**Comment by nirea** [comment]
But I like the idea of not having to cast to a list.  That would save a bunch of memory.

I'm sticking names on tickets that are actively being worked on.  @CorwinDavidson should I stick your name on this one?

**Comment by CorwinDavidson** [comment]
Yes you can

**Comment by CorwinDavidson** [comment]
Just finished added the JSON string conversion and rebased to master to account for any fixes that were done while I was working on it.

**Comment by CorwinDavidson** [comment]
As a note on list capacity...   using JSON Strings with PRIM_MEDIA the theoretical maximum is 52 keys per list with 8 bytes left free.  I will be making one more change to this to use the JSON array index 0 of each list to store the list length allowing us to remove the few remaining List conversions used in oc_auth.   Specifically in RemPersonMenu, SayOwners and UserCommand .

The other change required is to fix the oc_settings to store owner / trust / block directly into the PRIM_MEDIA instead of passing that via Link Messages

**Comment by CorwinDavidson** [comment]
* oc_auth has no list conversions for owner, trust or block any longer. 
* oc_settings now passes auth_lists straight to the PRIM_MEDIA

TODO:
* oc_settings needs to read from PRIM_MEDIA to generate output for "Notecard Backup"
* oc_relay needs to be changed to use PRIM_MEDIA auth lists.

**Comment by SilkieSabra** [comment]
Out of date, no idea what was incorporated in what is now oc_core or oc_api
