### ISSUE TITLE
Exceptions won't stay set.

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#740]
I'm using OpenCollar 8.2.1.

When I set exceptions for owners, when I relog, these settings get reset to the default. I have tried a settings notecard, it still happens.

Here is the content of that settings notecard in case it helps at all. And yes, it is properly named.

settings=nocomma~1
global=checkboxes~▢,▣
global=hide~0
global=allowhide~1
capture=status~8
label=show~1
label=text~Surssin
auth=owner~264f2419-2dd4-41f0-b4af-c0bf7221720a,8265cc41-7885-4bda-9480-9b86ae30a4f4,f732ce14-9477-4b6d-9372-ab833606940c,c58e9945-5312-4fec-9882-69eb806bf6e6,133b53e4-bd60-45e7-ad2d-28705144ec6d,88f69280-39fb-4c8a-982c-64ccffea9e0c,9337fc07-89d6-4dbd-97d
auth+owner~f-aff449ccf726,b41eb408-1370-4b68-948a-5325a125c933,e9eb8034-19c7-478d-8e1f-57fc6bc17007
auth=trust~c6c9274c-92c4-45eb-98c5-1e1fe5442442,20e30cab-71a5-48f0-ad7b-6d02f5192404,eb101ff2-064b-437d-bf43-b205774f1270,fb2dbc58-e4e9-4478-99dd-965808aab4dc,7ed42295-c5ab-4f24-9157-a7f06d805f12,a630c909-3180-4540-8aa4-d9ce5b3e32b6,75b797a3-14ab-4870-8e6
auth+trust~7-144dc5d151f5,1f6b54c6-2455-42e7-a055-73c744a75d43,87241433-2300-48e2-8505-07c053dd760d
auth=limitrange~0
auth=wearertrust~1
leash=turn~1
leash=leashlength~3
leash=strict~1,500
particle=ctexture~Chain
particle=particlemode~Classic
particle=color~<0.000000, 0.501960, 1.000000>
particle=gravity~-1.1
particle=size~<0.13,0.13,1>
bell=show~1
bell=on~0
bell=vol~10
bell=sound~7
titler=offset~6
titler=title~R29vZGVzdCBCb3kh
titler=color~<0.00000, 1.00000, 0.00000>
titler=show~1
rlvsuite=masks~0,0
rlvsuite=macros~Talk^514^0^TP^62914560^3145728^Stand/Sit^0^786432^Dress^0^30^Touch^0^23808^Inventory^805308416^224^Map/Info^94208^0
rlvext=mincamdist~1.000000
rlvext=maxcamdist~2.000000
rlvext=bluramount~5
rlvext=muffle~0
rlvext=owner~79
rlvext=trusted~79
rlvext=strict~0
rlvsys=on~1
shocker=sound~Default
folders=accessflags~15
occuffs=synclock~0
occuffs=locked~1
occuffs=cmdlevel~500
occuffs=armspose~Crossed Back 2
occuffs=legspose~Chainonly
relay=mode~0
relay=wearer~1
relay=helpless~0
outfits=accessflags~25
coupleanim=timeout~120.000000
bookmarks=ali ground floor~Vallory(215,212,23)
bookmarks=room cage~Nocht(168,91,30)
bookmarks=main cage~Stuttgart(81,195,22)
bookmarks=pony stall~Tall Tails Meadow(116,134,26)

**Comment by Cellysnow** [comment]
I have the same issue, i used the  OC_collarizer script and the OC8.2.1 updater to add functionality to an old collar. It works well, but when i try to turn the exception for "force TP" off, it rests on a relog.   

ive updated again thinking i did a mistake the first time, but it still happens

**Comment by Medea-Destiny** [comment]
Same as issue #720

**Comment by Medea-Destiny** [comment]
problem is trigged by a setAllExes function sending the settings save command when triggered by RLV_On... before settings are fully sent. I have a fix that seems to work fine.

**Comment by Pingout** [comment]
> problem is trigged by a setAllExes function sending the settings save command when triggered by RLV_On... before settings are fully sent. I have a fix that seems to work fine.

Will you need the testing team, @Medea-Destiny

**Comment by tayaphidoux** [comment]
this seems to also be tied to the rlv relay allowing devices to reset restrictions the owner sets untill relog or teleport, the other times it just gets lost no idea why.

**Comment by KristenMynx** [comment]
@Medea-Destiny is your fix in a patch or pr?   I'd like to test it.   The current 2022-q1-features branch still has this problem.
