### ISSUE TITLE
Unwelder intermittently fails to deliver a dialog box to unweld

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#750]
People come to the HQ all the time to unweld a collar.  Often they click on it several times before reading the text that tells them how to do it.  For some reason, about 40 % of the time the unwelder fails to respond either with a text with the info or a dialog to unweld.  After observing it for a while, it's hard to tell without systematic tests if this is due to random sim server conditions (such as http throttling that also affects the vendors) or if it is that the unwelder stops responding after so many clicks, or what.

**Comment by Medea-Destiny** [comment]
To clarify, is this happening AFTER the unwelder has been connected to the collar?

**Comment by Pingout** [comment]
After multiple tests using a couple of different collar users, we were unable to reproduce this problem. The unwelder worked every time. We even tried multiple rapid clicks on the unwelder object in an effort to force an error. 
I wonder if the users of the unwelder are expecting a blue dialog menu that they can click an "UNWELD" button, or they have in fact successfully unwelded the collar and don't realize it, and so continue their attempts

**Comment by StormedStormy** [comment]
Hello all i can confirm that the unwelder dose indeed work after a bit of testing, however i did find out that it is not so much the unwelder script itself it is the addon script that is was causing the problem if there was one in the first place. but otherwise it works just fine

**Comment by jotasprout** [comment]
What file would one edit to change the instructions that appear in local chat and make a pull request?

**Comment by jotasprout** [comment]
> What file would one edit to change the instructions that appear in local chat and make a pull request?

I'm willing to start as soon as I hear back.

**Comment by SilkieSabra** [comment]
This is not a place to chat about issues other than the one originally posted, Try joining our [discord ](https://discord.gg/yU2kpmsP)channel.  https://discord.gg/yU2kpmsP .  If you are asking about the unwelder instructions, it's [here]( https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_unwelder.lsl) .

**Comment by SilkieSabra** [comment]
Since we can't reproduce this issue, it's intermittent, and inworld help is not always able to check whether someone has unchecked the other buttons in Settings > AddOns, I'm closing the issue.

**Comment by jotasprout** [comment]
I changed the wording but now the Issue is closed. When I tried to push my new code to the Q1 branch, I got this:
https://gyazo.com/086c52823f89fbbc3d33fc2d635c8351

**Comment by SilkieSabra** [comment]
Did you make a pull request? The pr should not be tied to the issue, it's starting a new thing.
