### ISSUE TITLE
Missing Unsit Chat Command

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#761]
There should be a chat command to unsit.  Either it wasn't updated/changed to unsit  or it got lost.  There used to be a standnow chat command.  Tried that and also stand.  Neither worked.  Have not tried to locate it in the script but it's not functioning in at least two collars tested.

**Comment by Medea-Destiny** [comment]
Duplicate of #703 -- fix is already merged.
