### ISSUE TITLE
Strict leash disables touch

### ISSUE THREAD

**Issue by Erick-Gonzales** [OpenCollarTeam/OpenCollar#762]
What version of OpenCollar are you using?
8.2

What behavior did you expect?
Strict leashing to prevent TP/ Unable to move further away from leasher or anchor point

What behavior did you see instead?
Besides the expected behavior, touch is disabled (in the restrictions menu, touch remains allowed).

What steps does someone need to take to reproduce the problem?
Leash -> Config -> Enable strict (touch will be disabled through RLV as well, but NOT in the restrictions menu)

**Comment by mistressohm** [comment]
This is as designed (altho the restrictions menu should show it).

Disallowing far touch means that the leashed cannot 'sit' on anything out
of reach to move away from their owner.

**Comment by Erick-Gonzales** [comment]
I can understand FAR touch, but it disallows touch.
If she's standing next to furniture, she can't sit on it. Or touch an item
she's standing right next to.

**Comment by jotasprout** [comment]
I've looked at the code and don't see anything that would cause this. I don't know enough about RLV to know how loosely or tightly coupled it is with OC. Is it possible it is disabled only in RLV and not in the collar? I'm inferring that from the original comment.

**Comment by SilkieSabra** [comment]
As of this date, tested on two avatars, strict does not disable touch.
