### ISSUE TITLE
I needed help. Now I see I need a new brand.

### ISSUE THREAD

**Issue by JoiMarieAmore** [OpenCollarTeam/OpenCollar#764]
JoiMarie Amore — Today at 8:27 PM
You make customer service for the temple IMPOSSIBLE.  I'm going to use a different collar- I can't reach ANYONE for he;lp.
Eva Ryan — Today at 8:28 PM
I'm sorry, I'm no longer associated with No.9 collars or the Temple of the Collar. Thank you.
JoiMarie Amore — Today at 8:30 PM
Great- No one is reachable from that place or this group No response and I cannot write in group to ask questions. The fact is, OC and the group here are not the only collars. I think xxxxx xxxxxxxx is trying to kill their business.    I am going to Nove Collars only because  can reach someone from there who can help. 😦
*Nova Collars
At least someone from that team is approachable
Eva Ryan — Today at 8:31 PM
Sure. Go ahead.

**Comment by Pingout** [comment]
Hi JoiMarie,
First let me say how sad we at OpenCollar are to see the problem you are having. But please understand: The Temple, and the No.9 collars are NOT OpenCollar. They broke off as a separate CLOSED collar system over 5 years ago. We are not, and can not be responsible for their product or their customer service. We are just as unhappy about the bad name they are giving OpenCollar as you are. Please come back to the one, the only, the original OpenCollar, you will be glad you did.
https://opencollar.cc/2017/11/21/what-the-opencollar-name-stands-for.html

**Comment by JoiMarieAmore** [comment]
Omigosh, Pingout I didn't realize any of this.
I was so frustrated with The Temple. I reached out several times and was ignored, and somehow I got information that I had to go to Discord for their customer service. So I did, then I was told I needed to sign up to be in their group before posting, so I did that, but still could not post in their forum. So I tried to IM WS and some others through their Discord IDs and was simply ignored. ... I have renewed faith in OC now that I know you are not affiliated with her. I still have a pixie collar I love that I did not purchase from the Temple, Thank you for this information. Much appreciated!

**Comment by SilkieSabra** [comment]
Joi, have a look at your pixie collar, in Help/About.  The current version of OpenCollar is V 8.2.1.  Join the OpenCollar group at secondlife:///app/group/45d71cc1-17fc-8ee4-8799-7164ee264811/about (inworld slurl) for instructions on how to update or convert it to the current OC scripts.  If it's modifiable you can do it !

**Comment by JoiMarieAmore** [comment]
OK Silkie, Thank you.
