### ISSUE TITLE
Custom exceptions (done badly) can cause odd IM distance modifiers

### ISSUE THREAD

**Issue by DeaEnyo** [OpenCollarTeam/OpenCollar#772]
What version of OpenCollar are you using? 8.2.1

What behavior did you expect? Adding a custom exception and checking any of the IM boxes adds that exception.

What behavior did you see instead? Due to sloppy copying of an avatar's UUID from their profile, I missed the last character. Upon activating the IM exceptions I was subject to a modifier limiting the minimum IM distance. (from 25m up to 8845178m across several malformed UUIDs)

What steps does someone need to take to reproduce the problem? Be bad at copying an UUID into a custom exception, apply IM exceptions, watch the Modifiers tab of RLVa.

PLEASE do a sanity/idiot/length check on each key pasted into the avatar UUID entry dialog.  There is no indication that anything is wrong and it took me several hours of dopey fiddling to track down the issue.

**Comment by mistressohm** [comment]
I would actually recommend that a user lookup be performed on any UUID
submitted.   One doesn't have to save the data returned, just know that the
lookup was successful.

Not only does it rule out 'malformed' data (since the lookup would fail)
but also ensure that owners / trusted / blocked persons actually exist
within SL.  This means that you're not using script memory to store data
that is invalid or obsolete.

There's also the issue of 'ghost' owners - if you've a locked collar, do
not 'own' yourself, and your Owner deletes their SL account, what happens?

**Comment by DeaEnyo** [comment]
That would be an excellent solution to many of the rare but serious problems that could occur. 
I know at least one person who had lost their Owner to a ban and was forced to cheat out of their collar.
(I should explain HOW I messed up a simple action so badly: Instead of 'copying URL' from the resident's profile and deleting the "secondlife:///app/agent/" and "/about" parts, I simply dragged mouse cursor over the Key field to select it all, then copied. It turns out that some characters take up more space than others, so while it works on some keys, such as mine, it will miss the last one on others. A Firestorm/viewer UI issue, essentially. )

**Comment by mistressohm** [comment]
Yah I prefer using the Key field myself, but I'm also a big fan of
triple-clicking (which should highlight the whole thing) or CTRL-A (which
"selects all"). Then either right click and copy or CTRL-C.

Sanity checks are never 'wasted code'.

**Comment by KristenMynx** [comment]
I did some extensive testing with Firestorm.   Malformed UUIDs in exceptions are not accepted by firestorm.  They are ignored (altho if you have rlv debugging on, you'll see the rejection message).  Properly formed UUIDs are accepted of course (either group or avatar).  But there is no (supported) way a script can know if a given UUID might or might not be a valid group UUID.

I'll create a PR to do some sanity checking.   I'll just check if it is a properly formed UUID.  No sense sending RLV garbage.

 However checking if it is a uuid, that corresponds to a valid person or a valid group, is problematic.   There is a supported way to check for a user (llRequestAgentData), but there is no supported way to check if a UUID is a valid group. (there is a way to use the unsupported world api, but I can't imagine that will be available in coming years).

**Comment by Medea-Destiny** [comment]
Kristen's fix is in testing in 8.22 beta
