### ISSUE TITLE
Auto teleporting not working

### ISSUE THREAD

**Issue by ClaireBare** [OpenCollarTeam/OpenCollar#773]
What version of OpenCollar are you using?  OpenCollar 8.2.1000

What behavior did you expect? That when I tp my pet he comes whether at keys or not

What behavior did you see instead?  he has to be at the keys.

What steps does someone need to take to reproduce the problem?
No one else seems to have the problem 
I have checked - his RLV is on
the area where I teleporting from has scripts on
I have checked under RLV and Exceptions like told in world group and the auto tp is ticked.  
If I untick it close the window down and then open and retick it works once but not again

**Comment by tayaphidoux** [comment]
i have experienced this and have not figured out exactly what causes it beyond relay devices, the other times it seems to be lost due to lag often times when teleporting or a slow login.

**Comment by ClaireBare** [comment]
> i have experienced this and have not figured out exactly what causes it beyond relay devices, the other times it seems to be lost due to lag often times when teleporting or a slow login.

I am not sure at all what causes it, like I said, if I go into Exceptions, untick it, close it down open it up again and re-tick it, it will work one time and then I have to do it again, fortunately he is at keys most of the times but sometimes not

**Comment by Medea-Destiny** [comment]
"whether at keys or not" -- @ClaireBare could you check to see if this is happening _specifically_ when he is AFK?

**Comment by ClaireBare** [comment]
> "whether at keys or not" -- @ClaireBare could you check to see if this is happening _specifically_ when he is AFK?

It used to happen only when he was AFK but I know that is from his viewer being minimized, it happens all the time now, he has to physically click the tp request, so if he happens to step away from the computer for 5 mins I cannot tp him (if say the sim resets and I want to tp him away, I cant)

**Comment by tayaphidoux** [comment]
> "whether at keys or not" -- @ClaireBare could you check to see if this is happening _specifically_ when he is AFK?

this happens to me often even when i am not afk and it only really started becoming common after sl's move to cloud, there is also issues going on with people being shown as offline in users profiles when they are online and vise versa, its an sl bug and could be related if afk affected it in the past.

**Comment by ClaireBare** [comment]
this happens to me often even when i am not afk and it only really started becoming common after sl's move to cloud, there is also issues going on with people being shown as offline in users profiles when they are online and vise versa, its an sl bug and could be related if afk affected it in the past.

Glad to know I am not the only one, have you found a solution or work around Taya?

**Comment by tayaphidoux** [comment]
> this happens to me often even when i am not afk and it only really started becoming common after sl's move to cloud, there is also issues going on with people being shown as offline in users profiles when they are online and vise versa, its an sl bug and could be related if afk affected it in the past.
> 
> Glad to know I am not the only one, have you found a solution or work around Taya?

unfortunately like i said i have not however as it seems it would happen in the past related to afk i do think its possible what ever is making it difficult to tell when people are actually online could be a cause.
