### ISSUE TITLE
mouse look cross sim/teleport

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#778]
What version of OpenCollar are you using? 
8.2.1000

What behavior did you expect?
to stay in mouse look 

What behavior did you see instead?
the viewer canceled mouse look on teleport and the mouse got stuck free

What steps does someone need to take to reproduce the problem?
set mouse look restriction i.e. camdistmax:0

i have this fixed on my own custom add-ons with a simple if region changed set unset then reset cam distance.

**Comment by Medea-Destiny** [comment]
Unable to reproduce in Firestorm -- which viewers do this? It should be reported as a viewer bug.
@tayaphidoux or anyone else who can reproduce this issue, can you please also try out for other values of maxcamdist, and also mincamdist?

**Comment by tayaphidoux** [comment]
as i mentioned it happens on viewers that by default force you out of mouse look when you teleport, the one i know for sure does it is singularity i can test others but i do remember having this issue before on firestorm.

**Comment by tayaphidoux** [comment]
just checked fire storm it does do it but it don't actually force mouse when max distance is 0 look to begin with you can still toggle between mouse look and not in mouse look

**Comment by tayaphidoux** [comment]
it does not break in kokua.

**Comment by tayaphidoux** [comment]
@Medea-Destiny  you are welcome to come up with a different solution if you think that re en stating the camera distance when ever the sim changes is to much, and have taken my solution cross sim carting before and teleporting around multiple shops with my owner.

**Comment by tayaphidoux** [comment]
catznip don't actually have a linux client yet, and light speed i don't trust, coolvlviewer does not accept my password its a bug that used to affect the official viewer, and since the official viewer don't have rlv by default there is no reason to test it, i can only test viewers with linux support.

**Comment by tayaphidoux** [comment]
@Medea-Destiny 
    "Mouselook"     , 7 , "camdistmax:0"                            // 61  31 <- part of oc_rlvsuit.lsl that refrences mouse look.

below also part of oc_rlvsuit.lsl its function is to set mouselook aka (@camdistmax:0)
```
else if ((sCommand == "setcam_avdistmax" || sCommand == "setcam_avdistmin") && g_bForceMouselook) {
        sCommand = "camdistmax:0";
    } else if (sCommand == "camdistmax:0"){
        if (bEnable) g_bForceMouselook = TRUE;
        else g_bForceMouselook = FALSE;
```
my solution which calls the code above to toggle mouse look and resolve this bug.
```
    changed(integer change){
        if(change && CHANGED_REGION){
            if( g_bForceMouselook == TRUE){
                FormatCommand("camdistmax:0",FALSE);
                FormatCommand("camdistmax:0",TRUE);
            }
        }
    }
```

**Comment by tayaphidoux** [comment]
ignore this "[tayaphidoux](https://github.com/tayaphidoux) added a commit to tayaphidoux/OpenCollar that referenced this issue 9 days ago
@tayaphidoux
[Update oc_outfits.lsl](https://github.com/tayaphidoux/OpenCollar/commit/b77aa0a49cc02b37cf9e70eaaf66d37b15e55ca1)
[b77aa0a](https://github.com/tayaphidoux/OpenCollar/commit/b77aa0a49cc02b37cf9e70eaaf66d37b15e55ca1)

llSubStringIndex(sMsg,"RLVa") == -1 is a good idea but it don't actually work well in the puppy talker system i made ~llSubStringIndx(sMsg, "RLVa") returns true and works well every time so i can confirm this change should work and could fix the swapping bug in issue https://github.com/OpenCollarTeam/OpenCollar/issues/778, also we should be using @versionnew instead of @Version that's only still allowed for code that didn't and won't be updated prior to the SL Rules change." - thats a different issue
