### ISSUE TITLE
oc_outfits has changing paths for outfits under #RLV

### ISSUE THREAD

**Issue by AlexNumberFour** [OpenCollarTeam/OpenCollar#779]
What version of OpenCollar are you using? 8.2.1000

What behavior did you expect? 

I expected to be able to set up my outfits under #RLV/.outfits 

What behavior did you see instead?

Sometimes oc_outfits  changes it's mind and I have to rename #RLV/.outfits to #RLV/outfits for it to see my outfits. The dialog window simply doesn't show my outfits so they can be selected otherwise. 

I've had to change back and forth between #RLV/.outfits and #RLV/outfits several times now.

What steps does someone need to take to reproduce the problem?

1.  I have not found a way to reliably reproduce the problem other than to just use it regularly. 

As best I can tell, looking at the code, 

// from: oc_outfits

// looks like this has a problem setting g_iRLVa sometimes ... 
// however, I have no idea what is sending these messages -- that's up to someone with more knowledge than I have to figure out.
    listen(integer iChan, string sName, key kID, string sMsg)
    {
        if(llSubStringIndex(sMsg, "RLVa")==-1){
            g_iRLVa=FALSE;
        }else g_iRLVa=TRUE;
    }

// this causes the code to return the wrong value sometimes based on g_iRLVa
string GetOutfitSystem(integer iCorePath){
    if(g_iRLVa){
        if(iCorePath)return ".outfits/.core";
        else return ".outfits";
    }else{
        if(iCorePath)return "outfits/core";
        else return "outfits";
    }
}

I've attached a copy of the oc_collar file that is in my collar

[oc_collar.txt](https://github.com/OpenCollarTeam/OpenCollar/files/8644252/oc_collar.txt)

**Comment by tayaphidoux** [comment]
it should be using ~outfits instead of .just plain outfits

**Comment by AlexNumberFour** [comment]
I'm using the latest version of 64 bit firestorm, 6.5.3.65658. It's the only viewer I use for SL. 

> @versionnew=0
versionnew: RestrainedLove viewer v3.4.3 (RLVa 2.4.2)

I always have RLV enabled.

**Comment by tayaphidoux** [comment]
given that info it should only do .outfits and .outfits/.core seems the code needs to be checked out its possible some one changed somthing or its just not coded flexible enough

**Comment by tayaphidoux** [comment]
it checks the rlv version here 

lines 348-350 as of this post

 listen(integer iChan, string sName, key kID, string sMsg)
    {
        if(llSubStringIndex(sMsg, "RLVa")==-1){
            g_iRLVa=FALSE;
        }else g_iRLVa=TRUE;
    }

and lines 315-333 set the folder paths 

string GetOutfitSystem(integer iCorePath){
    if(g_iRLVa){
        if(iCorePath)return ".outfits/.core";
        else return ".outfits";
    }else{
        if(iCorePath)return "outfits/core";
        else return "outfits";
    }
}

string GetFolderName(integer iCore){
    if(g_iRLVa){
        if(iCore)return ".core";
        else return ".outfits";
    }else{
        if(iCore)return "core";
        else return "outfits";
    }
}
i don't see why it would be swaping for you

**Comment by AlexNumberFour** [comment]
Maybe the viewer doesn't always identify RLVa correctly, at least using that check.

**Comment by tayaphidoux** [comment]
do you script in secondlife? if so you might know that llSubStringIndex returns a number if the string provided exists in the test string if it does not exist it return -1, so unless your viewer is not handing out the string correctly the code should be working correctly.

https://wiki.secondlife.com/wiki/LlSubStringIndex

**Comment by AlexNumberFour** [comment]
I am actually a scripter. 

I've modified my copy of oc_outfits as follows to provide more feedback when it detects RLVa messages from the viewer:

(starting at line 339)

    listen(integer iChan, string sName, key kID, string sMsg)
    {
        if(llSubStringIndex(sMsg, "RLVa")==-1)
        {
            llOwnerSay( "\n**********************\n\n\nFailed to detect RLVa. Messages received was: " + sMsg + "\n\n\n**********************");
            g_iRLVa=FALSE;
        }
        else 
        {
            llOwnerSay( "Detected RLVa with message: " + sMsg );
            g_iRLVa=TRUE;
        }
    }

**Comment by tayaphidoux** [comment]
that's a good step to figuring out why your case is going on.

**Comment by AlexNumberFour** [comment]
This issue just happened to my friend Eleven. I was working with him over Team Viewer to sort out another issue. About two hours earlier, I had modified his oc_outfits, to add the same debug messages as I have in my collar's oc_outfits: 

 listen(integer iChan, string sName, key kID, string sMsg)
    {
        if(llSubStringIndex(sMsg, "RLVa")==-1)
        {
            llOwnerSay( "\n**********************\n\n\nFailed to detect RLVa. Message received was: " + sMsg + "\n\n\n**********************");
            g_iRLVa=FALSE;
        }
        else 
        {
            llOwnerSay( "Detected RLVa with message: " + sMsg );
            g_iRLVa=TRUE;
        }
    }

He had just logged out and logged back in because he was having issues setting a det. this lock in the folder browser and we had RLV debug messages were turned on.

Here's what his local chat looked like at login (I've removed some stuff that's not relevant or might be considered personal, such as UUIDs and lists of friends that were online):


[11:53:49] CLBlue-Necklace(arrowheaded)-Jake:  executes: @clear
[11:53:49] CLBlue-Necklace(arrowheaded)-Jake: Collar is preparing to startup, please be patient.
[11:53:49] CLBlue-Necklace(arrowheaded)-Jake:  executes: @version=999988

[11:53:50] CLBlue-Necklace(arrowheaded)-Jake: Collar ready. Startup complete
[11:53:50] CLBlue-Necklace(arrowheaded)-Jake: You are owned by: << information removed as it's not relevant >> 
[11:53:52] OpenCollar Remote: oc_remote_menus ready with 46578 bytes free
[11:53:53] OpenCollar Remote: Ready
[11:53:53] OpenCollar Remote: Ready
[11:53:54] CLBlue-Necklace(arrowheaded)-Jake:  executes: @detach=n

[11:53:59] CLBlue-Necklace(arrowheaded)-Jake:  executes: @versionnew=293847
[11:53:59] It's NOT ALL Mine! Complete Body Cum for Men:  executes: @versionnum=540798540
[11:53:59] It's NOT ALL Mine! Complete Body Cum for Men: [Private Message]
RLV Version: 3040300
[11:53:59] It's NOT ALL Mine! Complete Body Cum for Men:  executes: @detach=y (unset)
[11:53:59] CLBlue-Necklace(arrowheaded)-Jake:  executes: @setgroup=y (unset)
[11:53:59] CLBlue-Necklace(arrowheaded)-Jake:  executes: @detach=n (duplicate)
[11:53:59] CLBlue-Necklace(arrowheaded)-Jake:  executes: @sendim:<< information removed as it's not relevant>>=add, recvim:<< information removed as it's not relevant>>=add, recvchat:<< information removed as it's not relevant >>=add,recvemote:<< information removed as it's not relevant >>=add,tplure:<< information removed as it's not relevant >>=add,accepttp:<< information removed as it's not relevant >>=add,startim:<< information removed as it's not relevant >>=add
[11:53:59] CLBlue-Necklace(arrowheaded)-Jake:  executes: @sendim:<< information removed as it's not relevant>>=add,recvim:<< information removed as it's not relevant >>=add,recvchat:<< information removed as it's not relevant >>=add,recvemote:<< information removed as it's not relevant >>=add,tplure:<< information removed as it's not relevant >>=add,accepttp:<< information removed as it's not relevant >>=add,startim:<< information removed as it's not relevant >>=add
[11:54:01] CLBlue-Necklace(arrowheaded)-Jake:  executes: @detachthis:/stuff/cock cage/rusty=n
[11:54:04] CLBlue-Necklace(arrowheaded)-Jake: RLV ready!
[11:56:28] OpenCollar Remote: Attempting to connect...
[11:56:28] CLBlue-Necklace(arrowheaded)-Jake: Addon connected successfully: OC_Remote
[11:56:28] OpenCollar Remote: Connected!
[11:56:42] CLBlue-Necklace(arrowheaded)-Jake: Addon: OC_Remote has been removed because it has not been seen for 5 minutes or more.
[11:56:42] CLBlue-Necklace(arrowheaded)-Jake: Addon: 1652122589 has been removed because it has not been seen for 5 minutes or more.

At this point I noticed that NEITHER of the debug messages that I added above were present in the local chat output, so we checked his outfits dialog. The gyazo (also attached as a picture).

https://gyazo.com/d930388f51f293119ace03449ce7110c 

This shows that oc_outfits dialog is looking for #RLV/outfits and his #RLV directory which before his relog was working with his #RLV/.outfits folder. 

![d930388f51f293119ace03449ce7110c](https://user-images.githubusercontent.com/105090343/167482073-4bf6d0f1-f278-4a9f-99de-0d3c2f985be3.png)

**Comment by tayaphidoux** [comment]
looks like rlv is disabled or they have the debug open

**Comment by tayaphidoux** [comment]
[11:53:49] CLBlue-Necklace(arrowheaded)-Jake: executes: @Version=9999 might have to look into this but that should be correct 
and the script modification you are showing does not have a message on confirmation i don't see a message for the error showing up

**Comment by AlexNumberFour** [comment]
Right. 

I purposely covered both cases with llOwnerSay() calls and NEITHER one showed up -- RLV was enabled the entire time and you can see where other RLV calls were working. There were no script errors.

**Comment by tayaphidoux** [comment]
i was about to look into the listen to see if it is listening properly, but i had to help my youngest brother set up his new computer and build it.

**Comment by tayaphidoux** [comment]
try setting the llownersay("@version=999988") to @versionnew

**Comment by tayaphidoux** [comment]
> Right.
> 
> I purposely covered both cases with llOwnerSay() calls and NEITHER one showed up -- RLV was enabled the entire time and you can see where other RLV calls were working. There were no script errors.

yea my bad i looked again and seen that you are correct, i am theorizing it may be using legacy @version instead of @versionnew

**Comment by tayaphidoux** [comment]
made a simple test script so it should not matter which version is used
[10:02:31 PM]  Object: Message recived
RestrainedLife viewer v2.9.0 (RLVa 2.1.0)
[10:02:31 PM]  Object: Message recived
RestrainedLove viewer v2.9.0 (RLVa 2.1.0)

**Comment by tayaphidoux** [comment]
> This suggests that for whatever reason, Firestorm did NOT pass a message to oc_outfits and g_iRLVa was using the default (uninitialized?) value of zero. To me, this suggests g_iRLVa should be initialized to a value of -1 to indicate that it has not been set via a message from the viewer yet, thus you could explicitly check for this condition, but you know this code better than I do.

you are not wrong i didn't write this specific script but i am trying to help and i asked if you knew lsl code well enough i was not trying to imply that i knew better than you cause at this point i am just as cluless as you are i am just trying to get as much information as i can to see if i can even help.

**Comment by AlexNumberFour** [comment]
My friend Eleven has consistent issues with this, so he has become my guinea pig. 

My proposed code above had some issues, such as he would get the "failed to detect" messages even when it clearly initialized correctly. Also that did not account for the fact that a viewer without RLV enabled will NOT respond to RLV commands, thus the default value for g_iRLVa should be FALSE.

**Comment by tayaphidoux** [comment]
i have proposed the fix https://github.com/OpenCollarTeam/OpenCollar/pull/781 if you could test that change to the listen command it would help.

**Comment by cruelraremaster** [comment]
a fix got merged, I am closing this issue
