### ISSUE TITLE
New Feature: Cuff Resizer

### ISSUE THREAD

**Issue by KristenMynx** [OpenCollarTeam/OpenCollar#784]
I've created a cuff resizer script, which can be optionally included in a cuff.  It requires a few minimal changes to oc_cuff to integrate/check presence.    

It is based on oc_resizer.  I usually like to include a menu driven resizer in the cuffs I make.

The question is do you want to include this as a base feature.

I'll do a pull request if it is something that's wanted.

**Comment by Pingout** [comment]
This is another great idea, it's something people have been asking for. I'd love to see what you have come up with.

**Comment by KristenMynx** [comment]
Created pull request #788

**Comment by KristenMynx** [comment]
PR #788 merged, so closing
