### ISSUE TITLE
New Feature: Cuff Themes

### ISSUE THREAD

**Issue by KristenMynx** [OpenCollarTeam/OpenCollar#785]
I've created a cuff theme script, which can be optionally included in a cuff.  It eavesdrops on the addon chat channel to watch for theme change requests from the main oc_theme script in the collar.   No changes are needed, except its presence in the cuffs.

It is based on oc_themes.

The question is do you want to include this as a base feature.

I'll do a pull request if it is something that's wanted.

**Comment by Pingout** [comment]
I would like to see the script, if you could post it here. The themes and the cuffs are very near and dear to me :)
I would assume for the themes to work on the cuffs, the Link Number and Face Number needs to be identical between collar and cuff. Omnia made a cuff and collar texture change hud, which has been included in the latest beta version of the cuffs, which required a re-linking of the collar to make the link numbers identical. We could generate a handful of themes for the Beta OpenCollar Addon cuffs, and try out your cuff theme script in the "official" set.
Thanks for this new feature idea!

**Comment by KristenMynx** [comment]
Added pull request #787

No the prim/faces  don't have to match at all.   The design of this requires the cuffs to have their own theme notecards.  Those notecards must have the same name as the corresponding collar theme, but the target faces/links etc need not be the same.   Also themes which do not apply to a cuff (bell colors for example) don't need to exist in the cuff, and are silently ignored.

I can give you a copy of my collar and cuffs in-world which make extensive use of themes, where the cuff and collar stay in sync.

**Comment by KristenMynx** [comment]
PR 787 merged so closing issue
