### ISSUE TITLE
Include oc_undress in OPTIONAL bundle in installer

### ISSUE THREAD

**Issue by IsabeauConnaught** [OpenCollarTeam/OpenCollar#79]
What version of OpenCollar are you using? 7.0

in RLV un/dress menu is shown link to VD web site

https://gyazo.com/f32347fa581fdb0dfbc3c9f3746e6753

**Comment by nirea** [comment]
Thank you for your report!

RLV un/dress isn't included in the 7.0 updater, so I'm guessing you're still running the pre-7.0 version.

The current development version has added support for updating optional scripts like this though.  See https://github.com/OpenCollarTeam/OpenCollar/issues/71.  So you could either wait for that, or paste in the current contents from https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_undress.lsl.

**Comment by IsabeauConnaught** [comment]
that would be that this link is remnant, my collar was bought as 6.4. thanks

**Comment by zontreck** [comment]
Including our oc_undress in the optional installer bundle. This will go out with Alpha 3
