### ISSUE TITLE
Stack Heep Error

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#801]
A few times now when I log in, I get this message after my collar has a stack heep error.

[16:20] Surssin's Collar: oc_rlvextension has been reset. If the script stack heaped, please file a bug report on our github.

Roan asked that I list my owners. As of this writing, I have 9 owners and 12 trusted, but only one custom exception option for one of those trusted. Owners can force TP me, trusted cannot. The one custom exception list has all of the exceptions owners do.

**Comment by ManoloUnplugged** [comment]
Trust has all the exceptions owners do except for @accepttp, it looks like
that script is running out of memory because of too many owners, trusts

**Comment by Surssin** [comment]
Removed one owner and two trusted, and the custom exception. We'll see if it stack heeps again.

**Comment by tayaphidoux** [comment]
@Surssin ManoloUnplugged is right that reducing the exceptions for trusted could help.

**Comment by Surssin** [comment]
Well, at least so far, it seems to be stable. I think we can call it closed now, so I'm going to go ahead and do so.
