### ISSUE TITLE
RLV Restriction disables Auto TP

### ISSUE THREAD

**Issue by Scarlett-Jayy** [OpenCollarTeam/OpenCollar#802]
What version of OpenCollar are you using? 8.2.1000 (Latest)

What behavior did you expect? Expected a Working Auto TP after being captured in a Object with restriction and then be released then get a Auto TP.

What behavior did you see instead? After being Captured onto a Object with restrictions and then released after then be sent a TP. The Collar does not Auto TP to Owner. It sends a request TP instead. This is a Bug i noticed on V8.2.1, ,  the older version 8.1 does NOT have this problem at all. This problem is only on the latest version.

What steps does someone need to take to reproduce the problem?  The Wearer needs to be capture into a RLV ristricted Object with all Restrictions active. "No Radar, No IM, etc" . . Then the wearer must be released from the RLV Restricted Object like normal use with out removing the restrictions on the RLV Object. Once the Wearer has been released from the RLV Object, The Owner of the Wearer will send the Wearer a TP (In this case a Auto TP is active and it should Auto TP with out prompting to accept the TP or Cancel) at this moment. The Auto TP should take affect with out the wearer getting the option to Accept or Decline. This problem does not effect the older version at all. All of these steps followed on the older version works exactly like it should. . The Latest version doesnt work this way. and should be fixed.

**Comment by tayaphidoux** [comment]
this is related to https://github.com/OpenCollarTeam/OpenCollar/pull/794 and is being worked on.

**Comment by SilkieSabra** [comment]
Fixed in 8.2.3
