### ISSUE TITLE
I just noticed a problem in the oc_cuff_resizer

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#818]
What version of OpenCollar are you using? oc_cuff_resizer

The "Back" button does not work properly.  The script uses the UPMENU variable, similar to oc_resizer script on the collar. It could be that the UPMENU routine used in the collar is not apropriate for the cuffs.

What steps does someone need to take to reproduce the problem? Set up cuffs using the 2022 Q1 Features branch scripts (the most current version)

Attn: KristenMynx

**Comment by KristenMynx** [comment]
@Pingout fixed in PR #821
