### ISSUE TITLE
infinite loop in oc_api.lsl

### ISSUE THREAD

**Issue by pfifo** [OpenCollarTeam/OpenCollar#819]
I was just browsing the source code to answer a few questions for a friend, and noticed a bug.
As rare as it may be, if someone's UUID ends with '000000' this code will become an infinite loop
(oc_api.lsl Line 459)

// make the API Channel be per user
while(g_iInterfaceChannel==0){
  g_iInterfaceChannel = (integer)("0x" + llGetSubString(g_kWearer,30,-1));
  if (g_iInterfaceChannel > 0) g_iInterfaceChannel = -g_iInterfaceChannel;
}

**Comment by pfifo** [comment]
Maybe try this, to ensure the channel is never 0...
g_iInterfaceChannel = (integer)("0xf" + llGetSubString(g_kWearer,31,-1));

**Comment by pfifo** [comment]
Ok, here is a version that preserve existing functionality

`integer getNonZeroChannelFromUUID(string kID) {
    kID = (string)llParseString2List(kID, ["-"], []);
    llOwnerSay(kID);
    integer iChannel = 0;
    integer i = 0;
    while(iChannel == 0 && i <= 26) {
        string sTestString = llGetSubString(kID, 26 - i, -1 - i);
        llOwnerSay("Try #" + ((string)i) + ") " + sTestString);
        iChannel = (integer)("0x" + sTestString);
        if(iChannel > 0) {
            iChannel = -iChannel;
        }
        if(iChannel < 0) {
            return iChannel;
        }
        i++;
    }
    llOwnerSay("using default channel");
    return -87654321;
}
integer getApiChannel(string kID) {
    kID = (string)llParseString2List(kID, ["-"], []);
    integer iChannel = 0;
    integer i = 0;
    while(iChannel == 0 && i <= 26) {
        iChannel = (integer)("0x" + llGetSubString(kID, 26 - i, -1 - i));
        if(iChannel > 0) {
            iChannel = -iChannel;
        }
        if(iChannel < 0) {
            return iChannel;
        }
        i++;
    }
    return -87654321;
}
default
{
    state_entry()
    {
        getNonZeroChannelFromUUID(llGetOwner());
        getNonZeroChannelFromUUID("9b5fe5a9-af85-de4c-bb95-382b9a7ba902");
        getNonZeroChannelFromUUID("9b5fe5a9-af85-de4c-bb95-382b9a000000");
        getNonZeroChannelFromUUID("9b5fe5a9-af85-de4c-bb95-000000000000");
        getNonZeroChannelFromUUID("90000000-0000-4a00-0000-000000000000");
        getNonZeroChannelFromUUID("90000000-0000-0000-0000-000000000000");
        getNonZeroChannelFromUUID("00000000-0000-0000-0000-000000000000");
        llOwnerSay("Your API channel is: " + ((string)getApiChannel(llGetOwner())));
    }
}
`

**Comment by pfifo** [comment]
Ok here is a version that preserves existing functionality, with a test case, and a production version.
[getApiChannel](https://gist.github.com/pfifo/5b75f2c6ecca6eb3c685856bad40ee3a)

**Comment by Medea-Destiny** [comment]
fix in testing seems good.

**Comment by SilkieSabra** [comment]
If an issue is fixed the outcome should be a pull request.  Who's going to do the pr?
