### ISSUE TITLE
help wanted:  status on Gag scripts?

### ISSUE THREAD

**Issue by Athaliah** [OpenCollarTeam/OpenCollar#82]
There was a question in the group earlier about if there was an OpenCollar gag  or gag scripts in the odds and ends.    
There is memories of once having a gag that we offered, as well as there being OpenGag, in a notecard by Betsy Hastings a long time ago.  Suggestions, any help with what we had?    

What ever we do figure out, it would need to be fully checked out and see if its still hanging in our odds and ends, and tested to see if it would work in conjunction with the current collar.

Anyone interested?

**Comment by NorthGlenwalker** [comment]
I wrote an add-on for the cuffs, that will work ok with the collar as well for a gag and a blindfold attachments. There are based on the free DH blindfold and gag, which I believe are fully Open Source.
There is also the garbler script, but I have never seen or heard of any OpenGag in any old parts I have which date back to 3.6.
