### ISSUE TITLE
Capture app not listing capture message when not set to risky. Can't check who captured you anywhere.

### ISSUE THREAD

**Issue by FiachranRafe** [OpenCollarTeam/OpenCollar#833]
What version of OpenCollar are you using?

8.2.1

Issue:

- A chat message when clicking yes when capture is enabled would be handy as confirmation that you're actually captured as feedback (similar to the message you get when capture is set to risky: "[11:45] OpenCollar: You have been captured by ròan (Silkie Sabra) ! If you need to free yourself, you can always use your safeword 'RED'. Also by saying your prefix capture"
- The name of the capturer being visible somewhere in the OpenCollar menu since theaccess list isn't available. (So under the capture app)
- Capture info on/off command not working (not sure if not working, or just not reporting anything to chat, documentation may need to be updated)
- capture command is a toggle (not clear in documentation and a bit unclear in the message when capture is set to risky)

**Comment by SilkieSabra** [comment]
Fixed
