### ISSUE TITLE
problems with the oc_label script

### ISSUE THREAD

**Issue by serinea-askold** [OpenCollarTeam/OpenCollar#84]
[oc_label_SERINEA.txt](https://github.com/OpenCollarTeam/OpenCollar/files/1595886/oc_label_SERINEA.txt)
What version of OpenCollar are you using?
base coller version 7.0
oc_label version "¹⋅⁶" (taken direct from the script source)

What behavior did you expect?
I expected the label cylinders to be set showing specific letters correcponding to the label i set in the app.

What behavior did you see instead?
Of the 10 "Label~#" cylinders, Label~1 to Label~9 were made fully transparend, Label~10 appeared untouched.

What steps does someone need to take to reproduce the problem?
How I worked on this issue was by the following:
I was looking in to how to create a "collar" that had the basic functionality, but also things like a lock that showed, and "working" LED and label for an application I have in mind, and wanted to know the what I would require in objects needed for it.

I started out by linking 8 spheres together, then dropped the oc_collarizer script in, with an OpenCollar 7.0 updater nearby.

After the update completeed, I created a second string of balls, this time with 11 spheres, and one with FloatText in the decsription, one with Bell in the description, and one called Lock, to these 11 sphere's I added 10 cylinders, called respectively Label~1 to Label~10. I linked all 21 prims together, and manually copied the OpenCollar scripts into specific spheres, checking labelas as i went.

Once I had done that, I dropped the oc_collarizer script into the root prim, and it picked up the additional label cylinders, and installed the oc_label script.

I then proceeded to test the results, and saw immediately that the label wasn't working as intended.
As it was specifialy the label that wasn't working as i expected, I opened the oc_label script, making a copy in my inventory, and started looking through it, following the program code and moving around little llOwnerSay() breadcrumbs i would put in.

I tracked down that there are a couple of issues with the oc_label script, and put in work arounds to my version after unchecking the "use experience" option.

Problems found in the code of oc_label:
1. During the running of the script, when it builds a list of Label~ prims, there is an issue that resilts in the g_lLabelLinks[0] always retaining a value of "0" therefore ending up pointing badly to the root of the object (i think) rather than to one of the label prims. in my example this list would always end up populated like [0,11,12,13,14,15,16,17,18,19,20].
2. The issue above meant that when SetOffsets(key font) is called, the first thing it does is check the LinkID stored in g_lLabelLinks[0]. This returns a value of 0, which in this case points to a sphere, so it is not able to choose relevant offsets, and returns null or incorrect values.
3. during the SetLabel() function, again due to the g_lLabelLinks[0] error in 1. above, the call to RenderString() gets called on prim 0, then up till the last but one label prim, resulting in incorrect setting of the label.

I have attached a copy of the oc_label script as oc_label_SERINEA.txt

 that I have got working as I expect it to, it includes 2 code changes that are functionaly significant and work around this issue:

ORIGINAL
276.	            RenderString(llList2Integer(g_lLabelLinks, iCharPosition), llGetSubString(sText, iCharPosition, iCharPosition));

CHANGED
276.	            RenderString(llList2Integer(g_lLabelLinks, iCharPosition + 1), llGetSubString(sText, iCharPosition, iCharPosition));

ORIGINAL
283.	    integer link = llList2Integer(g_lLabelLinks, 0);

CHANGED
283.	    integer link = llList2Integer(g_lLabelLinks, 1);

**Comment by nirea** [comment]
@xxReyes, you were looking at label when we were beta testing 7.0.  Is this related to the issues you discussed then?

**Comment by xxReyes** [comment]
That is not what I was seeing; What I mentioned was related to the positioning of the text on the prim faces and can be addressed by setting path cut the prim to (begin)0.3750 and (end)0.6250.

I was testing with 14 label prims and did not observe the symptoms she's mentioning, Note however that the prims all show as transparent normally as the label font texture is mostly alpha with the exception of the characters that are displayed (which is done with a texture offset of a single texture applied to all of the prims). - If you want the label prims to have a background you'd need to have a textured prim behind the label prims. I just ran some checks on my collar tester and all 14 of the label prims got the texture map applied as expected.

**Comment by serinea-askold** [comment]
I have just had a chance to revisit this, and i have found the problem, it turns out there was an off by one error, but not where i thought it was

my "label" prims were "Label~1" through to "Label~10" (i think that the markdown formatting of github changed some of my text to show as strike through) and when the oc_label script was processing there's a line in the LabelsCount() function that does the following:

g_lLabelLinks = llListReplaceList(g_lLabelLinks,[iLink],iLabel,iLabel);

The iLabel in the above line is the number after the tilde character on the label prim, and as my count started at 1, my first label prim was referencing the second element of the g_lLabelLinks[] list.

Adjusting my prim names to read "Label~0" through to "Label~9" corrected the behaviour.

Thus, not an error exactly, perhaps a note in the construction guide (if there is one) to the effect that label names need to start from 0.

**Comment by nirea** [comment]
Good find!
