### ISSUE TITLE
Wearer set to Trusted Access is still denied access to Runaway in 8.2.2 beta

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#843]
We tested the 8.2.2 Beta for the fix for certain Access settings available to Wearer but not to Trusted.  In 8.2.1 and possibly earlier versions, when the Wearer is set to Trusted level access they  lose the ability to operate Access List and Runaway, since those are not available at Trusted level.

8.2.2 should fix that.  Access List is fixed.  Wearer set to Trusted can see the Access List.  However Runaway is still denied to a Wearer who is also Trusted on the collar.

**Comment by Medea-Destiny** [comment]
This should be fixed now, contact me in world for testing
