### ISSUE TITLE
Owned Wearer Not Self Owned should not have the ability to change the Exceptions List.

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#844]
While testing the 8.2.2 Beta we noted that an owned wearer can uncheck the Force TP exception.  We did not test the other exceptions.  This should not be the case.  Exceptions should be Owner only, otherwise a wearer has an easy way to prevent an owner from using the Force TP.  I don't know when it snuck in.

**Comment by Medea-Destiny** [comment]
This should be fixed now, contact me in world for testing.

**Comment by jotasprout** [comment]
I will. I'm available.

**Comment by SilkieSabra** [comment]
Can you move it to a pr for testing? That way we will not have to test it twice before merge.
