### ISSUE TITLE
Double Relay menu

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#845]
in the 8.2.2 beta, when using a chat command or the menu button to open the Relay menu, you get two menus.  Contents of the collar were checked for duplicates and there is only one copy of oc_relay in the collar.  Duplicated by Bunny, Trinkitz and Omnia.

**Comment by Medea-Destiny** [comment]
In the first beta for 8.22010 the oc_resizer script accidentally got a copy of the oc_relay script pasted into it, so there are in fact two copies of oc_relay (and none of oc_resizer!).

**Comment by Medea-Destiny** [comment]
Roan has already done a new updater with the oc_resizer script fixed.
