### ISSUE TITLE
Adding Wearer to Trusted breaks WearerTrust

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#849]
8.2.2 Beta collar.  Adding Wearer to Trusted should not break WearerTrust functionality.  

When WearerTrust is checked, Wearer can add and Remove trusted.

When Wearer has WearerTrust checked and is also added to the Trusted list, wearer can no longer add and remove Trusted.

**Comment by Medea-Destiny** [comment]
Fix already in my beta fixes, doing the PR now(ish).

**Comment by Etaski** [comment]
Similar, likely related issue: Wearer is mentioned as "trusted" in settings NC, and can no longer use "hide" and "show", gets "Access Denied" response. Removing wearer from "trusted" entry in NC solved it.
