### ISSUE TITLE
Access to Lock Core in Outfits

### ISSUE THREAD

**Issue by NikkiLacrima** [OpenCollarTeam/OpenCollar#855]
What version of OpenCollar are you using? 8.2.1

Avatars without owner access rights should not be able to change  the Lock Core settings under outfits ?

This protects items in .core like mesh body and heads from ill willed or clumsy removals by captors that are unknown and not granted owner rights, or from the public when public setting is used.

**Comment by SilkieSabra** [comment]
If the wearer cannot lock or unlock core, they can't edit their core folder or take off anything in it they are currently wearing. I think this one should be a wearer convenience.

**Comment by SilkieSabra** [comment]
Testing to see if you mean that anyone but owner and wearer does have access to core

**Comment by tayaphidoux** [comment]
@SilkieSabra  they are saying they have their collar in public access mode and think that any one using the collar with "public" access should not be able to change (~).outfits/(~).core causing avatars to break when using (~).core as base for the avatar.

**Comment by Medea-Destiny** [comment]
Yes, looks to me like this should be corrected so that owner and wearer can lock/unlock core, but nobody else can. Anyone disagree?

**Comment by pfifo** [comment]
I think it would be even more useful to have a notecard in the collar containing a list of directories that should be restricted as mentioned, along with the ability to completely hide some as well. The first thing that comes to mind is the ability to hide folders for things like 'bare' game and what not.

**Comment by tayaphidoux** [comment]
@pfifo that might be a solution to an idea i have had about having separate folders for things and keeping them separate with the ~ hide function would not be to hard to add to oc_folders aside from the note card reader eating up more memory and then adding a modular menu thank you

**Comment by NikkiLacrima** [comment]
The issue is the locking and unlocking of the .core folder, locking from rlv detach and not about browsing

**Comment by tayaphidoux** [comment]
@NikkiLacrima  thank you for that i will look into it the fix should be the same for that section
