### ISSUE TITLE
Detach chat command fails

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#875]
8.2.2 and older

chat message {prefix} detach fails due to incorrect filtering of usercommand() function. Only accepts "{prefix} menu Detach" (with capital letter) at the moment

**Comment by JoyAcker** [comment]
What threw me is that it fails silently with no error message.
Is that a general issue may be - no "invalid command" error msg?

**Comment by SilkieSabra** [comment]
This will be bundled with other features in a future update.
