### ISSUE TITLE
Suggestoin: Apps / Outfits should display outfit list right away, like bookmarks

### ISSUE THREAD

**Issue by JoyAcker** [OpenCollarTeam/OpenCollar#878]
What version of OpenCollar are you using? 8.2.1 / 8.2.2

What behavior did you expect? n/a

What behavior did you see instead?  n/a

What steps does someone need to take to reproduce the problem?  n/a

A minor saving to have one less click; but I think it would be useful improvement especially when using chat command    /1 yz outfits

**Comment by SilkieSabra** [comment]
No room on the outfits front page to mix actual outfit folders in with other config options.
