### ISSUE TITLE
Suggestion: Aliases for clothes

### ISSUE THREAD

**Issue by JoyAcker** [OpenCollarTeam/OpenCollar#879]
What version of OpenCollar are you using? 8.2.1 / 8.2.2

What behavior did you expect? n/a

What behavior did you see instead? n/a

What steps does someone need to take to reproduce the problem? n/a

Many clothes are no mod with long names and the important part at the end; more visual clutter again in menu display, and long commands to by typed accurately if using commands.

**Comment by Medea-Destiny** [comment]
I have a project in the works to try to clarify the detach menu display some (and allow for much simpler chat commands), but scripting name substitutions isn't reasonable. Large substitution lists (and they would grow HUGE for many people) would increasingly slow down scripts and take up a ton of memory. Scaling would be a nightmare (we'd have to have memory scripts to store the substitutions and tell people to add more memory scripts to their collars as needed). Ultimately the best answer for this problem isn't something OC can fix -- getting creators to stop making things no mod unnecessarily.

**Comment by JoyAcker** [comment]
You've thought this through more than I have!  I think I know the problem,
but not the solution!
What about wildcards?  Or maybe thats just another way of looking at what
your trying to do (I think you talked about categorising clothing).
