### ISSUE TITLE
Ability that the collar tells in public that it was touched by foreigner

### ISSUE THREAD

**Issue by Torvis-of-Gor** [OpenCollarTeam/OpenCollar#88]
What version of OpenCollar are you using?
OC7dev2

What behavior did you expect?

Like many other objects in SL which people are wearing the collar should be able to tell in open chat. a lot of objects to that. the OC should be able to tell that is was touched by a foreigner. and  what it tells should be configurable. here is a sample how the Dari's Haus Collars does that: " .... runs their finger along SLAVENAME's collar. Her/His Owners might not appreciate such overt familiarity."

this feature should be able to be disabled for those who might consider that as spam or does not wish that for other reasons. the function for that already exists, a collar can notify the slave that her/his collar was touched by a foreigner. it simlply needs to be expanded to the public or not. this should also be configurable.

**Comment by lord9** [comment]
This should be part of a plugin, not core.

**Comment by Athaliah** [comment]
This seems to be similar to issue # 69, where there is a feature request to notify the owner of the collar when someone touches a collar that they do not own.     

Is this what you were requesting in your feature request as well as wishing for local chat message to go with it, or just to add the local area message by itself?

**Comment by SatomiAhn** [comment]
I don't believe this should just be a matter of preference for the wearer (or their owner), as implied spam concerns anybody who can hear it.

For another reason, I don't like this much. Auto-emoters are already bad in general (as opposed to real RP), but even worse are automatic emotes describing actions that were never intended by their alleged perpetrator!
When somebody clicks a foreigner's attachment, it is most of the time either accidental or just mere exploration. If they wanted to emote some action, they would just do it... no need to click anything.
If the clicker attempts something forbidden, let the scripts inform them and be done, no need to yell it at everybody around.

Also I would like to ask a few questions to those who wants this feature: why do you think it is a good idea? What purpose is it supposed to achieve? Is it for punishing people who were foolhardy enough to try accessing your collar?

**Comment by Torvis-of-Gor** [comment]
@Athalia: as i tried to describe above, this is should be a option to set a message to local chat or nor
@SatomiAhn: Yes, i think this is a good idea cause everbody can see that there is someone trying to take control about other avatars, there is no other reason (based on my experience) that someone touches a collar and tries out what he can do with the menu. I know, he can do nothing but he is trying this is enough to make it public. 

and if you fear spam, i think that is no spam, more a warning to others. spam is for example the Mama Hud with really spams around in open chat every 5 Minutes or so. and there tons of objects in SL who are doing similar, think about this free penis :)

**Comment by ExecuterMagic** [comment]
I think that it should be included to issue # 69 as another option/feature to the reporting possibility to the wearer and / or set owners , with maybee the posibility to set a own mesage that the person clicking gets , but totaly not over mainchat but as personal message that only the person clicking gets , since i am with satomi there , it beeing in local chat  is nothing but unneeded spam that asks for drama , be it against the person clicking the collar , or against the collar wearer for having that spammy item trough bystanders or place owners .

**Comment by SatomiAhn** [comment]
@Torvis-of-Gor: if control access implemented by script efficiently prevents any mischief, what need is there to warn all people around of an imaginary danger?

As for the chatty free penis example, I hope OpenCollar is above that sort of junk.

**Comment by CorwinDavidson** [comment]
I'm going to side with @SatomiAhn on this one.  There are exactly 2 people who should possibly be notified when someone without authorization is attempting to use someone's collar, and only one of those for sure:

1. The wearer of the Collar
2. The {Primary} owner(s) of the Collar if they wish to be notified.

**Comment by mailani19** [comment]
I'm going to go ahead and agree with SatomiAhn as well.  There's no need to publicly humiliate someone for clicking on your collar.

**Comment by zontreck** [comment]
A plugin can be easily developed using the template script in spares. A touch event just needs to be added along with the llSay. It is a part of core to notify wearer. It just doesn't do it publicly
