### ISSUE TITLE
Some pose do not reverse the animation when pressed stop

### ISSUE THREAD

**Issue by Misca1234** [OpenCollarTeam/OpenCollar#891]
What version of OpenCollar are you using?
Latest, target avi have AO switched off

What behaviour did you expect?
After an avatar have been placed in a pose, like shy/kneel/submitt/table and when pressing stop 
the animation of getting down into the pose should be reversed up to standing.

What behaviour did you see instead?
After placing an avatar in a pose, like shy and then press button stop, the avatar Swoosh up directly to standing
Note that some animation works as expected, such as tower and rise

What steps does someone need to take to reproduce the problem?
Choose a pose, like  table
See the animation of the avatar gets down in table
Press stop
The avatar swish up to standing

**Comment by Pingout** [comment]
This is how the pose was made. Most of what we think of as "collar animations" are simple static poses. The avatar seems to abruptly go into and out of the pose, what you see as swish up. To correct this you would need to make and upload new poses.

**Comment by Misca1234** [comment]
But the animations are per default loaded into the collar. It is difficult to load them via the remote UI if you do not have direct access to the collar. Which in many cases is not possible. The "easiest" way should be if the already existing animations are updated.

**Comment by SilkieSabra** [comment]
We can't "update" an existing animation because the only way to do that is to make a new animation.
