### ISSUE TITLE
The "#" prefix wildcard is not working in 8.2.3 

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#897]
What version of OpenCollar are you using? Collar 8.2.3

What behavior did you expect? There are two global prefixes. * issues commands to everyone in range with the required level of access, and # issues commands to everyone in range with the required level of access except yourself. (Cut and Paste from the User Guide)

What behavior did you see instead? The # symbol is not working, and does nothing. The * symbol works as advertised.

What steps does someone need to take to reproduce the problem? When close to someone you have collar access to, try the # wildcard in a chat command.

**Comment by Medea-Destiny** [comment]
Looks like another thing that got lost in the 8.x API transition.

**Comment by Medea-Destiny** [comment]
fix in #1016
