### ISSUE TITLE
Cuffs HIDE Feature Request

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#900]
Would it be possible to change the OpenCollar Cuff script to listen for a HIDE/UNHIDE message from the collar, so that when a collar is hidden/unhidden, the cuffs will also hide/unhide. It will probably require some changes to the cuff object itself, probably adding the ~nohide flag to the hidden parts of the cuffs (ie. chain points)
There have been a couple of requests for this feature in OpenCollar Chat recently, and also this item was always on the Cuffs wishlist, along with Resizer and Themes which were included in the most recent version.

**Comment by SilkieSabra** [comment]
I would like to hear under what conditions you would want to hide the cuffs instead of taking them off.  If they are locked on they are usually locked in a pose and one would not want to be locked in that animation without visible cuffs to explain it.

**Comment by cruelraremaster** [comment]
#692 and #900 are related, although not identical. But maybe if one is implemented, then the other issue can be closed too.

**Comment by SilkieSabra** [comment]
See my comment at #692
