### ISSUE TITLE
"Lock Core" doesn't work for the wearer on an owned collar

### ISSUE THREAD

**Issue by AlexRayden-SL** [OpenCollarTeam/OpenCollar#902]
**What version of OpenCollar are you using?**
8.2.30000

**What behavior did you expect?**
As wearer, to be able to change the "Lock Core" option into the "Apps/Outfits" section

**What behavior did you see instead?**
When i try to change it, the menu just close without any message (neither error nor access denied), and the "Lock core" has no change. Only the owner can change it.

**What steps does someone need to take to reproduce the problem?**
Use a collar owned by someone else then the wearer and lock it. Go into "Apps/Outfits" and try to change the "Lock core" option.

**Comment by SilkieSabra** [comment]
I duplicated this.  It seems to me we had a discussion whether the wearer should have access to lock core and said they should be able to do this since its main purpose is to prevent traps and Detach from removing the wrong body part.

**Comment by SilkieSabra** [comment]
I have tested this further and it is in fact a bug.  When Wearer is checked in Outfits > Configure, they should be able to lock and unlock the core folder.  I get Access Denied to Configuration settings, and even though Wearer is checked in Configure, I get a silent fail when i try to lock the core folder in the menu.

**Comment by Evilgertie** [comment]
I have the same issue.  I'm not an owner on my collar and my owner can toggle the Lock Core button but the menu disappears when I try.
