### ISSUE TITLE
Suggestion: Emergency Recovery

### ISSUE THREAD

**Issue by eksynn** [OpenCollarTeam/OpenCollar#904]
What version of OpenCollar are you using?
823000

What behavior did you expect?
.core isn't locking even if I lock it. i'm my own owner.
when it IS locked, it won't unlock through the collar - you need to release it from the viewer (and that doesn't always work)

What behavior did you see instead?
the opposite of those behaviours

What steps does someone need to take to reproduce the problem?
as this is a suggestion, I don't believe this is applicable.
the suggestion is, please add an emergency recovery button and command, where you press the dialogue button and a specific folder (set by the user?) in the RLV setup would be worn, with your body and usual attachments in case a random trap removes literally every attachment you have. it's so annoying hunting everything down after everything gets unworn.

i understand the .core mechanic exists, but it doesn't currently reliably works. plus, the feature would KEEP items from being unworn, but there's nothing to MAKE SURE that if you do lose all of your attachments, you can put it all back on without the hassle of searching for everything again. this could be an addition to the .outfits feature and it could work side by side.

**Comment by SilkieSabra** [comment]
See issue #902

**Comment by SilkieSabra** [comment]
I think most of this is solved by the fix to lock core in oc_outfits in the 8.3 features branch.

**Comment by eksynn** [comment]
they were different features altogether - lock core keeps attachments from being removed, emergency recovery would allow the user to re-attach a specific RLV folder in case of everything getting removed, to save time

if that makes sense

unless i misunderstood how lock core works xD
