### ISSUE TITLE
message when login in: you are owned by.... is missing

### ISSUE THREAD

**Issue by JuliaC15** [OpenCollarTeam/OpenCollar#906]
What version of OpenCollar are you using?

What behavior did you expect?

What behavior did you see instead?

What steps does someone need to take to reproduce the problem?

**Comment by SilkieSabra** [comment]
I believe this user meant to report that when starting up, there used to be a message saying your owner's name in chat.  It went missing at some point in V8.   Who would like it back?

**Comment by Pyhrn** [comment]
+1 from me for having it back

**Comment by Trinkitz** [comment]
The message can be restored by running an update, even if that update is the same version as the one on the collar. The message will vanish again the next time the collar restarts, though.

**Comment by Pyhrn** [comment]
I did some digging in the scripts. The message is handled by oc_api (in line 623) and the changelog for 8.2.3 about oc_api says  `Changes: Only reset script when needed, not on each reboot`.  
I suspect that is the reason why the messages appears only after a reboot/update, not on every restart.

**Comment by Medea-Destiny** [comment]
Fixed in 8.3
