### ISSUE TITLE
oc_outfits does not keep ~outfits/~core attached (8.2.3)

### ISSUE THREAD

**Issue by clairem-sl** [OpenCollarTeam/OpenCollar#910]
## What version of OpenCollar are you using?

8.2.3000

And I am using **Kokua**, so I'm on an RLV viewer rather than RLVa.

## What behavior did you expect?

When I use Apps > Outfits > Browse > (Outfit name) > Wear, I expect the contents of `~outfits/~core` to stay attached.

## What behavior did you see instead?

Only items in `~outfits/(Outfit name)` gets attached, the collar actively removes what it can remove from `~outfits/~core` (some items in `~outfits/~core` are locked via RLV).

This happens even after I relog after I updated.

## What steps does someone need to take to reproduce the problem?

Maybe this:

1. Use Kokua
2. Set up `#RLV/~outfits/~core`
3. Set up `#RLV/~outfits/Other` containing different things from `~core`
4. Use Apps>Outfits>Browse>Other>Wear

**Comment by SilkieSabra** [comment]
The tilde is an alternative for users of RLV rather than RLVa.  That was in the Release Notes for 8.2.3.

**Comment by clairem-sl** [comment]
> The tilde is an alternative for users of RLV rather than RLVa. That was in the Release Notes for 8.2.3.

^^ This exactly.

Also if I choose "BrowseCore", OC said that it was browsing `~outfits/~core`, so I decided I move things in there, rather than `outfits/core`. I _did_ notice that the folder is recognized by OC: If I turn on "LockCore", I can no longer rename/delete the `~core` directory under `~outfits` (the menu item is disabled). Something that does not happen if I name it `core` or `.core`.

But somewhere along the way, when `oc_outfits` try to detach things, it somehow ignores `~outfits/~core`.

**Comment by tayaphidoux** [comment]
it could be we need to check some where deeper in the code for sub folder locks, usually when a top folder is locked all related sub folders are locked to so this is interesting, i put in the change for RLV form outfits/core to ~outfits/~core because it hid outfits and core from "# folders", and to my first tries did lock the folder however i guess i missed that it didn't lock the items or sub folders, though i thought when i tried it i was unable to remove any thing in ~core or ~outfits respectively when it was locked. i did notice a bug with it however where ~core is visible some where where it should not have been.

**Comment by tayaphidoux** [comment]
> I'm curious why you are using the tilde character? In general the “~” Tilde symbols indicate items that were sent to your #RLV folder from a scripted device. You can use “Forbid Give to #RLV” in your RLVa drop down to keep this from occurring. The Complete User Guide https://opencollar.cc/docs/Outfits suggests using the dot character. In the first paragraph it suggests an alternative for the non-RLVa viewer "To use Outfits with Restrained Love Viewer, follow the instructions below, except when spelling the Outfits and Core folders in your inventory, eliminate the period in front of the name: outfts and core in place of .outfits and .core. Unfortunately this means your Outfits folders will also appear in the Folders menu."

the guide is not quite up to date with the changes that were made.

**Comment by tayaphidoux** [comment]
i belive i have located the issue at https://github.com/OpenCollarTeam/OpenCollar/blob/0818419fd1b4b2569ea910dba519bc9ad1451bf9/src/Apps/oc_outfits.lsl#L268

need to change "" to "~".

**Comment by tayaphidoux** [comment]
please feel free to try out #940 and see if it solves your issue.
