### ISSUE TITLE
Suggestion: Move code for hiding collar from oc_theme

### ISSUE THREAD

**Issue by SurniM** [OpenCollarTeam/OpenCollar#925]
What version of OpenCollar are you using? 8.2.3

What behavior did you expect? uninstalling the oc_theme script from a collar that does not need it and still be able to use the hide collar feature

What behavior did you see instead? uninstalling the oc_theme script from a collar disables the hiding a collar feature.

What steps does someone need to take to reproduce the problem? *points up*

**Comment by SilkieSabra** [comment]
This is already in the works for the next version
