### ISSUE TITLE
problem with folder browser

### ISSUE THREAD

**Issue by paintpeeler** [OpenCollarTeam/OpenCollar#926]
What version of OpenCollar are you using?
8.2.3000

when using the rlv folder browser...there seems to be an issue with sections that take more than one page... let me show you an example.. in a collar worn by my sub I see this when I browse her restraints folder

[Folder Browser]

Legend:
▢ = Nothing in the folder is worn, or any subfolders
▣ = All items in either this folder or its subfolder are worn
◑ = Some items are worn in this folder, or its subfolders

Currently browsing path: ◑ /Restraints

0 ▢ RR Elegance()
1 ◑ RR Vixen Leather
2 ▢ RR Siren Ropes()
3 ▢ RR Serious Shackles()
4 ▣ Kemono StraitJacket
5 ▢ RR Armbinder()
6 ▢ DHB Armbinder
followed by the buttons...

if I check a folder that has more stuff in it. I see this...
[Folder Browser]

Legend:
▢ = Nothing in the folder is worn, or any subfolders
▣ = All items in either this folder or its subfolder are worn
◑ = Some items are worn in this folder, or its subfolders

Currently browsing path: ◑ /clothing

Page 1/2
followed by the buttons...

no list of the folders contained within

**Comment by NikkiLacrima** [comment]
The list of folder names is only displayed if some name is to long to fit in the button, more than 18 characters

**Comment by SilkieSabra** [comment]
thanks for the explanation, @NikkiLacrima , I was not sure what the question was.
