### ISSUE TITLE
Collar get unhidden after TP

### ISSUE THREAD

**Issue by RaulinWolfwood** [OpenCollarTeam/OpenCollar#928]
What version of OpenCollar are you using?
 8.2.3

What behavior did you expect? 
if i hide my collar it stays hidden

What behavior did you see instead? 
after tp either to a busy sim or a empty sim at various moments it get unhidden

What steps does someone need to take to reproduce the problem?
i honestly don't know. my collar bugged before so maybe its just my bug after this other wise i have no clue

**Comment by RaulinWolfwood** [comment]
i unpacked the collar again but the same thing happened as soon i tp from a sim to an other it reaappered

**Comment by SilkieSabra** [comment]
Can you tell us who made your collar? It might be a build problem of some kind.  See if you can duplicate this on our stock collar.

**Comment by Pingout** [comment]
I tried this on a collar that was recently updated to 8.2.3 and I had no problem. I tried teleporting to 10 different sims, each with various levels of "busy" but I could not reproduce the problem.  If we could meet at the OpenCollar Headquarters, i might be able to diagnose the problem with the collar rez'd on the floor.

**Comment by RaulinWolfwood** [comment]
sorry i just only saw your message earlier, so i appologize for the replay... [Renegade] Kali Collar creator is ღ Լєxι ƲєƖνєт ღ (alexandra0666)

**Comment by Medea-Destiny** [comment]
Cannot reproduce. Could be an issue with a 3rd party inclusion, but not an Open Collar issue.
