### ISSUE TITLE
"Stray" preset configuration error

### ISSUE THREAD

**Issue by JimmyKM** [OpenCollarTeam/OpenCollar#929]
OpenCollar version 8.2.3
Stray presets are: Landmark, TP Location, TP Local, Sit Down
This allows the sub to tp to her camera location using firestorm's "tp2cam" chat command.

To prevent this, I had to change the preset to: Landmark, TP Location, TP Local, Sit TP

This should be easily seen and reproduced.  Behavior has been verified in the SL OpenCollar support group.

**Comment by Medea-Destiny** [comment]
Fixed in #947
