### ISSUE TITLE
OpenCollar Help Notecard includes obsolete [prefix] version command line

### ISSUE THREAD

**Issue by Margarita1480** [OpenCollarTeam/OpenCollar#934]
What version of OpenCollar are you using? 8.2.300

What behavior did you expect? any output

What behavior did you see instead? no output

What steps does someone need to take to reproduce the problem? [prefix] verify

document states:

----------
Settings:
----------

    settings

    print settings
    load url [url]

    fix
    verify     <-- does not produce output

    hide / show

**Comment by SilkieSabra** [comment]
The help notecard needs updating.

**Comment by mistressohm** [comment]
Is this an issue where the 'verify' function was removed, but the help
notecard was not updated?  If so, then simply delete the 'verify' line from
the help printout.

Or does the 'verify' function need to be checked?  It would -seem- to be
useful, to be able to test-parse the settings and report on any lines with
bad punctuation, strings too long, or other issues that would prevent them
from taking effect.

But if it's no longer in the OC code, then no mention need be made about it.

**Comment by Medea-Destiny** [comment]
Notecard rewritten for 8.3
