### ISSUE TITLE
group auth not being cleared by runaway?

### ISSUE THREAD

**Issue by Medea-Destiny** [OpenCollarTeam/OpenCollar#935]
Reported to me in world by Clody (gynger81). Have not yet investigated, putting this here to remind me to. Anyone else observed this behaviour?

**Comment by Pingout** [comment]
Trinkitz and I tested this a couple of times, and yes..... Group Access is not cleared by Runaway command.  However the runaway command makes the wearer own themselves, and they can simple uncheck the Group Access box themselves.

**Comment by SilkieSabra** [comment]
Minor issue but I think for consistency it should be corrected.  All access should be cleared by runaway.
