### ISSUE TITLE
Bug: RLV Folders - 'add' with subfolder argument does not work

### ISSUE THREAD

**Issue by JoyAcker** [OpenCollarTeam/OpenCollar#936]
What version of OpenCollar are you using?  8.2.3000

What behavior did you expect?    
/1 xx && folder/subfolder   to add the contents in and below subfolder.
Actual result:
Error:  "Nothing matching that term was found in #RLV!"  is reported.

(/1 xx & folder/subfolder  doesnt work either.   /1 xx && folder   works fine)

/1 xx -- folder/subfolder   DOES work as expected , removing contents in and below subfolder

The particular relevance of this is that it forces all outfits (that are to be available to scripts for adding / removing using & or -) need to be at the top level under #RLV, cluttering up the directory, rather that grouped into #RLV/Outfits , say  (a parallel to .outfits for the Outfits app)

I suspect this is an OC issue (as opposed to RLC) as Im aware of at least one game (JasX BARE) that uses this kind of functionality with outfits all grouped under #RLV/JasX  folder.

**Comment by SilkieSabra** [comment]
Not a bug.  Outfits works this way because it was initially designed not to have subfolders, and the path folder/subfolder was added to the chat command as an afterthought.  In Folders, you simply type the destination folder straight in and don't need to designate the path to it through a forest of subfolders.  Suppose you have a folder named gags, and in that folder you have subfolders named ringgag and ballgag.  [prefix] & ringgag is all you need to add the ringgag.

**Comment by JoyAcker** [comment]
Ahah. 

I now have a different bug (!) - doing it the way you describe works fine on one test outfit (& subfolders) but not on another.  Ill do some more testing to pinpoint cause - on the face of the two outfits are very similar, and the subfolder names are the same

**Comment by JoyAcker** [comment]
Thx.

I’m guessing that having identical sets of subfolders in each outfit folder
is deprecated?  I’m certainly seeing inconsistent behaviour.    (Move one
folder away from RLV and an outfit that wasn’t working now does).

I’m getting the strangest feeling I’m trying to do something the wrong way.
   When I get in world I’ll drop you a nc with a sort of functional spec of
what I’m trying to do.

I can see some advantages of what I think the current Folders approach is
trying to do.  (Eg brevity!). But the ambiguity is perhaps a problem.
Does Folders keep track of a “current folder”?  I’m sensing that maybe not.

**Comment by SilkieSabra** [comment]
Please start a new issue if you have a different problem than the one we closed.

**Comment by JoyAcker** [comment]
Yes of course I will.   I think its all boiling down to "all bets are off
with OC RLV/Folders if there are non-unique subfolders"
I going to re-read the documentation to see where I missed that caveat.
Some of the anomalous behaviours Im seeing when there are multiple uses of
a subfolder name include

   - && does not add all items, some are omitted
   - an outfit is added and then immediately removed

**Comment by SilkieSabra** [comment]
This is true for any rlv search.  It can't know what folder you meant when there are two identical folder names.

**Comment by JoyAcker** [comment]
One of the things I’m not clear on is how much of the OC functionality is
raw RLV vs some “wrapper” code around it. The constraint of unique
subfolder names for example, is that imposed by RLV or by OC.    I’m still
working my way through the RLV docs.    NC explaining what I’m trying to do
is nearly done.
