### ISSUE TITLE
won't stay locked

### ISSUE THREAD

**Issue by jessicamiggle** [OpenCollarTeam/OpenCollar#937]
What version of OpenCollar are you using? premium

What behavior did you expect? to work

What behavior did you see instead? don't lock

What steps does someone need to take to reproduce the problem? I don't know.
I activate TPE and add my owner. Owner locks collar, I unlock it simply by clicking unlock. then I deactivate TPE by un-checking box. which I assumed once set can only be unset by an owner.

**Comment by SilkieSabra** [comment]
What is "TPE" ?

**Comment by jessicamiggle** [comment]
TPE Is a feature that makes runaway impossible the collar was expensive and it broke. oh well seems everything breaks at some point.

**Comment by SilkieSabra** [comment]
It sounds like the collar you are wearing is not OpenCollar.  Please ask the maker of the collar for help.

**Comment by cruelraremaster** [comment]
@SilkieSabra I agree and ticket should get closed
