### ISSUE TITLE
Feature: Force Sit range is hardcoded to 20 meters. This would be a valuable setting if changed from Literal.

### ISSUE THREAD

**Issue by Margarita1480** [OpenCollarTeam/OpenCollar#939]
What version of OpenCollar are you using?8.2.300

What behavior did you expect? Ability to configure Force Sit scan range

What behavior did you see instead? It is hardcoded in rlvextenstions, line 201

What steps does someone need to take to reproduce the problem? Use force sit in an area where desired items are more than 20 meters away

code snippet that obscures the llSensor distance value of 20:
   llMessageLinked(LINK_SET, DIALOG_SENSOR, (string)kID +"|"+sPrompt+"|0|``"+(string)(SCRIPTED|PASSIVE)+"`20`"+(string)PI+"`"+llDumpList2String(lUtilityButtons,"`")+"|"+llDumpList2String(lChoices,"`")+"|" + (string)iAuth, kMenuID);

**Comment by cruelraremaster** [comment]
Hello @Margarita1480 ,
nice idea - nevertheless I don't understand the use-case for do a force sit for more than 20m away.
It is kind unrealistic anyways. Can't you leash/yank the wearer closer to the desired place and then force sit?

**Comment by SilkieSabra** [comment]
In my opinion there are other better ways to send someone more than 20m away, including bookmarks, experience teleports etc. into the area of the furniture where you could then have a collision grab set up.

**Comment by Margarita1480** [comment]
I think this is being misinterpreted.

The idea is there might be a group at a given location. The main character might wish to Sit attendees from a distance over 20m. The Setting for Limit Range could be augmented with an Extend Range for something like this. The current situation is that avatars cannot "see" a SitTarget farther than 20m from the avatar even if it is next to the person issuing the Sit command.

The range to extend is NOT the command range, but the sensor range for the Sit.

**Comment by Medea-Destiny** [comment]
The 20m scan range is pretty much an arbitrary choice. However the scan will only pick up the nearest 16 objects to the collar, so someone would have to be in a pretty empty location to find the sit target they actually want at significantly larger differences. Bringing the collar wearer closer seems like the more sensible approach here.

**Comment by Margarita1480** [comment]
I am in the minority here in seeing the value so I will one-off the sensor code for my purposes.  Feel free to close this as a noise item without value to the general community. I imagine the more experienced members of the group have spaces where many sit-targets exist and I have seen those spaces. Having the option to tune for the spaces you use would be nice, but not a general need for others. I do appreciate the feedback.
