### ISSUE TITLE
oc_safezone works not correct

### ISSUE THREAD

**Issue by KarinKorpov** [OpenCollarTeam/OpenCollar#95]
In OC 7.0 works the oc_safezone not longer correct anymore with the option "public". The option public is vanished of the settings in oc_safezone.

**Comment by nirea** [comment]
Weird.  We haven't made any substantive changes to that script (just header
comments and cleaning up unused/shadowed variables identified by lslint).

Do you have another collar that shows the behavior you expect?

**Comment by KarinKorpov** [comment]
No, i don't have... Sadly. I have tried with version 3.9xx and [six] collars. In version 3.9xx comes the safezone even not in the Apps (Addons) 

But could this option make in the new "SafeZone" zone? 
Deny with closed for public and Allow is open for public.

**Comment by CorwinDavidson** [comment]
This script was never updated to keep up with the changes in link messages nor the changes in auth setting messages.  Update should fix these issues.

**Comment by KarinKorpov** [comment]
Problem is solved thanks to the update. This can be close
