### ISSUE TITLE
Crippled Public mode

### ISSUE THREAD

**Issue by emmi-1564** [OpenCollarTeam/OpenCollar#952]
What version of OpenCollar are you using? 
8.2.3

What behavior did you expect? 
- Public mode used to be just that, the collar was set to allow anyone to control the collar, allowing the user to control the restictions and even locking/unlockign the collar.

What behavior did you see instead?
- Public is now just public leashing it appears, perhaps there are other things it does as well, I don't know.  if you are going to change the major functionality, move the public button under leash configuration and set it there, this would make more sense if thats all its going to do.
-  I enjoy the risk of exposing my collar to the public, addionally , if I were owned, why shouldn't my owner be able to make that disision as well. This was the functionality of the collar for a very long time.

What steps does someone need to take to reproduce the problem?
- Turn on public mode. The behavior has been radically changed.

**Comment by Medea-Destiny** [comment]
Locking/unlocking has never been a capability of public access. It does look like the change to 8.x from 7.x  back in 2020 lost public access to the restrictions submenu. Is there anything else you've observed that has changed?

**Comment by emmi-1564** [comment]
I recall locking and unlocking, except if owned. Even if that capibiity was left out, adding back the original capibilities of restrictions woudl be what I'd want.

**Comment by SilkieSabra** [comment]
There was one edition of capture, to my unreliable memory, that allowed a captor to unlock a collar.  That was a mistake and was corrected in a later version.  I would like to see a config for restrictions include options to set access, like several other menus.

**Comment by Pingout** [comment]
We did some testing with older collars just to help us wrap our brains around the evolution of this issue. We tested three collars: The current version 8.3.2, then we tested a version 6 collar and a couple of version 3.
We found a wide variety on what Public access was allowed or not allowed to do in the collar.
Version 8 allows Public access to Apps, which includes as many items as the collar wearer wants. Public can turn Label and Title, Undress, Detach, Outfits, etc... along with Public access to animations and poses. Public has insufficient authority to access add-ons menu, Lock/Unlock, Access menu and Restrictions/Exemptions
Version 6 collar allowed Public to use Restrictions and Apps but No capture access, no ability to use the access menu or Lock/Unlock.
Older versions had many variations (version 3.x). Some allowed full access to public, even allowing a Public to use +Owner and -Owner. So if Public can make themselves Owner they can literally do everything. Some later Version 3 collars (3.9x) did not allow Public to Add and Remove owner, and does not allow Public access to Restrictions but does allow Public access to Exceptions, along with the Apps, Leash and Animations
We also discovered in our testing that there were many unofficial collars still in inventory. Collars that were modified to trap the wearer, and some auto-locking collars. It's best, of course, to make sure you get your collar from a reputable source.

**Comment by SilkieSabra** [comment]
out of curiosity, which version 3 collar allowed public to add owners?

**Comment by emmi-1564** [comment]
thats not a option I'm requesting

**Comment by SilkieSabra** [comment]
what option are you requesting?

**Comment by emmi-1564** [comment]
I don't knwo where all the documentation is, bu there seems to be missing a spec sheet. What should public do. What should a owner be able to do, what should a trusted be able to do. then there is something to test and verify against.

**Comment by SilkieSabra** [comment]
you're correct about that missing spec sheet.

**Comment by emmi-1564** [comment]
sorry if I just screwed soemthing up, but I 'm not the best with this chat system. My request was to have public mode be able to add/remove restrictions.

**Comment by emmi-1564** [comment]
> I don't knwo where all the documentation is, bu there seems to be missing a spec sheet. What should public do. What should a owner be able to do, what should a trusted be able to do. then there is something to test and verify against.

Alos, any deviations from the spec woudl be visible to all.

**Comment by SilkieSabra** [comment]
the only specs we have are in the user manual and partly because the access to various options is so changeable it is not included consistently in the manual.  If you see a spot where there should be a note about the access to a particular feature in that manual page. you could really help by making a pull request to that page here:  https://github.com/OpenCollarTeam/opencollarteam.github.io/tree/master/docs .  I think that many pages now have a config where you can fine tune the access to that feature, but restrictions doesn't have that and probably should have it.
