### ISSUE TITLE
oc_badwords does not trigger after transfer

### ISSUE THREAD

**Issue by Phuk-SLAM** [OpenCollarTeam/OpenCollar#953]
What version of OpenCollar are you using?
8.2.3

What behavior did you expect?
Badwords triggers, as expected.

What behavior did you see instead?
Badwords works for the initial owner/creator of the collar. When transferred to another person, the punishment will not trigger, although the next owner can set up the app with trigger words, penance, anim, sound etc, the actual punishment silently fails.

What steps does someone need to take to reproduce the problem?
Add oc_badwords to a collar and transfer it to another user.

SOLUTION FOUND:
oc_badwords does not reset on owner change. When adding

if(iChange & CHANGED_OWNER)  llResetScript(); 

to the changed event, the issue is resolved.

**Comment by Phuk-SLAM** [comment]
modified script attached
[oc_badwords_transfer-fix.txt](https://github.com/OpenCollarTeam/OpenCollar/files/11446789/oc_badwords_transfer-fix.txt)

**Comment by Medea-Destiny** [comment]
Thanks Phuk! Don't worry about the PR, I'll sort that out for you. You'll get the credit though!
