### ISSUE TITLE
Under Kokua Viewer, ~core folder becomes detached

### ISSUE THREAD

**Issue by tenshilove** [OpenCollarTeam/OpenCollar#961]
What version of OpenCollar are you using?
8.2.3
What behavior did you expect?
a locked ~core folder whilst using Kokua viewer
What behavior did you see instead?
the ~core folder fails to lock and becomes detached. Trued updated oc_outfits, to no avail.
What steps does someone need to take to reproduce the problem?
* use the RLV API instead of RLVa

**Comment by tayaphidoux** [comment]
can you see if that script fixes it as it was accidentally deleted 5 days ago or have you already tried it

**Comment by tenshilove** [comment]
tried the new version, still same outcome

**Comment by tayaphidoux** [comment]
you re opened this , we have done extensive work to get this updated i just fixed a minor bug when i uploaded the version that worked when i tested it in kokua, if its still doing it could you describe your issue more clear, for me the ~core does not detach and becomes locked when changing outfits also using core lock locks it so i can't edit/detach items in ~core

**Comment by tenshilove** [comment]
I'll have to check on that, is there an updated script that i can download to test?

**Comment by tayaphidoux** [comment]
@tenshilove https://github.com/OpenCollarTeam/OpenCollar/blob/8.3_Features-branch/src/Apps/oc_outfits.lsl - it has been merged with the next update for now you can get it here.

**Comment by SilkieSabra** [comment]
Thanks Phidoux, and thanks tenshilove for sticking with this, closing it now.  Fix merged to the 8.3 branch.
