### ISSUE TITLE
showstopper: safeword can not be changed by wearer if owned

### ISSUE THREAD

**Issue by tenshilove** [OpenCollarTeam/OpenCollar#964]
What version of OpenCollar are you using? 8.2.3

What behavior did you expect? I can change my safeword even when owned, which was possible to do in previous versions

What behavior did you see instead? If owned I am unable to change my safeword and I get no output (access denied, etc.)

This is not an issue to be taken lightly. Warers **must** be able to change their safewords **at all times**

**Comment by SilkieSabra** [comment]
This has been a standard feature for several years.  The current safeword is printed in the Help/About menu of the collar.  Being unable to change the safeword, or restore the safeword if the owner disables it, is part of the experience for many users.  Those who do not like that degree of loss of control can be added to the owner list on the collar.  Changing the safeword works for owners.
That said, there should be an Access Denied message there.

**Comment by tenshilove** [comment]
Understood; i propose that trust owners should be able to change it or enable it as well; it's an additional safeguard in case a sub is abandoned with a welded collar and, for instance, the sub is set as trust owner

**Comment by cruelraremaster** [comment]
> sub is abandoned with a welded collar

That's a much wider issue triggerin and including problems beyond only changing the safeword.
I am with @SilkieSabra here and would say the current behaviour is not a bug but a feature and not to be changed.

**Comment by Medea-Destiny** [comment]
@tenshilove "wearers must be able to change their safewords at all times" -< Can you explain this statement? As Roan says it's printed in the help/about menu so there's no issue of forgetting or anything like that, so what's the issue here?
