### ISSUE TITLE
Bookmarks Access.. chat command works on public access even while "access denied" message sent

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#98]
Bookmarks works with an older chat command that was written for force teleports using landmarks inserted into the collar or remote.  This 

Bookmarks and force teleport should be available only to Trusted and Owners.  I tested this using both the OpenCollar 7 dev Remote and the collar.  The fault i found is that people on public access can still use the bookmarks to send people with either the chat command or the menu button; even though they get the Access Denied message.

When i used the remote, I was able to teleport the wearer to the destination in the remote only when i had Trusted access on the collar, and not on public access.  This is correct--even though the bookmark is not in the collar, it's in the remote and i had Trusted access on the collar.  I next added the bookmark directly to the sub's collar and tested the chat command [prefix] tp [bookmark name].   

The chat command is keyed to the collar bookmarks and not the remote (If you have a bookmark in the remote and not in the collar, the chat command does nothing).  Using the chat command, I tested Trusted Access and Public Access.  I was able to teleport the wearer to her bookmark destination on Trusted Access.  This is expected behavior. 

However, when i used the same chat command on public access, with the bookmark in the collar and not in the remote, I got the message Access Denied twice from the collar:  [09:39] OpenCollar: Access denied.
[09:39] OpenCollar: Access denied.  And was still able to send the sub to the destination.  

Last, i got another user to send the wearer to the destination using the buttons.  Again got the Acess Denied message and again the bookmark worked regardless.  

It may be debatable whether bookmarks should be available on public access.  I think not, due mainly to the opportunities for griefing.  Nevertheless, it should either be available; or not available; not available while getting "Access Denied" message.

To reproduce:  Set the collar to public access, add bookmark.  Have someone nearby use the chat command [prefix] tp [bookmarkname]; or use the same menu button function.

**Comment by CorwinDavidson** [comment]
When the collar is put on Open Access everyone not on an auth list gains the CMD_GROUP permission.  The UserCommand function in the oc_bookmarks script was checking the permission but not actually stopping anything for almost all cases.  

I consolidated the check into one call at the beginning of the function with a hard return after the No Access is sent.

**Comment by nirea** [comment]
Thanks @CorwinDavidson!
