### ISSUE TITLE
problem with folder browser

### ISSUE THREAD

**Issue by paintpeeler** [OpenCollarTeam/OpenCollar#984]
What version of OpenCollar are you using?
8.2.3000

when using the rlv folder browser...there seems to be an issue with SECTIONS THAT TAKE MORE THAN ONE PAGE... let me show you an example.. in a collar worn by my sub I see this when I browse her restraints folder

[Folder Browser]

Legend:
▢ = Nothing in the folder is worn, or any subfolders
▣ = All items in either this folder or its subfolder are worn
◑ = Some items are worn in this folder, or its subfolders

Currently browsing path: ◑ /Restraints

0 ▢ RR Elegance()
1 ◑ RR Vixen Leather
2 ▢ RR Siren Ropes()
3 ▢ RR Serious Shackles()
4 ▣ Kemono StraitJacket
5 ▢ RR Armbinder()
6 ▢ DHB Armbinder
7 simple folder names....followed by the buttons...

if I check a folder that has more stuff in it (like more than 9 folders). I see this...
[Folder Browser]

Legend:
▢ = Nothing in the folder is worn, or any subfolders
▣ = All items in either this folder or its subfolder are worn
◑ = Some items are worn in this folder, or its subfolders

Currently browsing path: ◑ /clothing

Page 1/2
followed by the buttons...

no list of the folders contained within

this IS fixable I have corrected the problem myself.

**Comment by paintpeeler** [comment]
it is because it is a more than one page listing that it ceases printing the expanded descriptions.

**Comment by NikkiLacrima** [comment]
If none of the folder names is more than 18 characters, then the expanded descriptions are not printed.
You can test this by adding an empty folder with a very long name (more than 18 characters) to the folder with more than 9 subfolders.

**Comment by paintpeeler** [comment]
▣ Kemono StraitJacket is more then 18 characters and it prints.
I'm telling you the problem is if it's multi-page. If it's multi-page is does not post the long descriptions and if it is just ONE page it does.

**Comment by paintpeeler** [comment]
never mind. the latest version doesn't do this anymore. its been fixed. I apologize.
