### ISSUE TITLE
Stand Alone Addon Proposal

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#988]
THIS IS A PROPOSAL NOT A REQUEST, NOT AN ISSUE.
https://opencollar.cc/docs/Development-Life-Cycle
```
Feature Decisions

Someone’s got to decide what we’ll include in OpenCollar. The founders (Athaliah Opus and Nirea Mercury) have final decision-making power there, but most features don’t start with them. Most often, someone in the community has an idea, they propose it (either in chat or even better, as a pull request), and if there’s consensus that it’s something we want in the collar, it gets added.

That consensus is the hard part. There are a lot of competing concerns at play:

    Is this the kind of feature that we want in OpenCollar?
    Will this feature be used by most users, or just a small subset?
    How much does this new feature complicate OpenCollar? Is the additional functionality worth that additional complexity?
    Is this going to be a surprising change to how existing collar users expect things to work?
    Who’s going to do the work to add this?

If you want to propose a new feature for OpenCollar, there are a couple things you can do to improve your odds of success:

    Communicate clearly, in durable written form. If it’s a small feature, then a paragraph or two in a Github issue might be all you need. If it’s a big feature, or especially if it’s a complicated architectural change, then you might need to create a separate document or diagrams to make it easy to understand.
    Seek feedback. Discuss your proposal with the project leaders and be prepared with answers to the questions above. The OpenCollar Discord server is the best place for this. Consider gathering feedback from the larger community, such as through group chats or a poll.
```

(edit note: added this because i think some people are confused of why this is in issue.)

i Closed the previous pr because of https://github.com/OpenCollarTeam/OpenCollar/pull/960#issuecomment-1704392375 this will clear up the pr and allow me to discuss this template with others as i work to incorporate what users might be interested in.

```
define "stand alone":
Intended, designed, or able to be used or to function alone or separately : not connected to or requiring connection to something else in order to be used or to function.
https://www.merriam-webster.com/dictionary/stand-alone
```
Rssentially the add-on would function without the collar connection but could be connected to the collar, like the pending AO.

```
define "template":
1.  A gauge, pattern, or mold (such as a thin plate or board) used as a guide to the form of a piece being made
2.  Something that establishes or serves as a pattern
https://www.merriam-webster.com/dictionary/template
```

the current version in that closed pr is functional but there has been an expressed desire for it to 1:1 compatible with oc_plugin template so that you could drop in oc_plugins and core files to help create templates, it will take time and more work than i have put in at the moment, the stand alone add-on template started out as a template for a stand alone add-on.

The idea at first was to just do lock/unlock which could be dropped in for harnesses and other items to make them lockable, it still serves this function with oc_standalone_addon and oc_addon_menu, but currently has a custom api to create plugins for it
that could load their own menu buttons into the main menu as well as relay information between the collar and said plugin.

The objective is to make something that can allow new creators to drop and use, while giving something to more advanced creators to build from/modify/improve on, i feel that moving to a more 1:1 collar plugin stand alone platform may actually do this so to comply with https://opencollar.cc/docs/Development-Life-Cycle i am closing the pr and moving to issues as mentioned in this guide.

Please feel free to ask me for script updates, or get them from https://github.com/tayaphidoux/OpenCollar-Alpha/tree/8.3_Features-branch -  i will try to keep it up to date with the changes in feature branch as i make changes.

Do interact with me here not the closed pr going forward, the template name may end up changing due to the 1:1 nature desired i am thinking oc_standalone_addon_core and oc_standalone_addon_menu for the main scripts, auth is a plugin for managing users list, as is buttonloader they are examples of the current api as well as a way to test the menu input feature.

**Comment by tayaphidoux** [comment]
ok i have just uploaded a start on a 1:1 oc_plugin compatible standalone addon system.
there is issues with long button names in some of the current apps like leash but it generates a button.
llDialog: button labels must be 24 or fewer characters long

**Comment by Pingout** [comment]
I grabbed the three scripts and compiled them in SL. I dropped them into an object to see what would happen. I was able to get a |=====Main=====| menu with a choice to Lock. The lock works good.

I tried dropping the Badwords App into the object, and was not able to get a menu for Badwords
I tried dropping in the leash script, with no effect
Any other collar app dropped in to the object doesn't do anything
Am I missing something?

It might help if there was an outline of what steps to follow to make the Standalone System work

**Comment by tayaphidoux** [comment]
yea there were some issues with official oc_plugins i am working on making it work at the time of this post i have it mostly working and the script count is going to change as well as the script names i had to do alot of work, some of it was taking the states and dialog scripts from oc_dialog and oc_state then modifying them to exactly what i needed, they have little documentation so i have to trial and error it, oc_states is really hard to understand what its doing and what part of it only controls script states, in the addon i  don't need to wait for memory to be loaded since i am using linkset data and core manages settings memory.

**Comment by Pingout** [comment]
Where do I find oc_plugin? I don't see that script in the github

**Comment by tayaphidoux** [comment]
@Pingout https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_plugin_template.lsl

**Comment by SilkieSabra** [comment]
We have at least one item that already does this, the AO.  There are others like it.  I thought the existing Addon Template was intended to connect separately scripted items that can work alone to the collar. I really don't need to see a dictionary definition of stand-alone or template, thank you.  Is this an improvement on the existing addon template, or is it going beyond that and becoming a template for how to actually create the scripted item you want to connect?

**Comment by Yosty7B3** [comment]
> We have at least one item that already does this, the AO. There are others like it. I thought the existing Addon Template was intended to connect separately scripted items that can work alone to the collar. I really don't need to see a dictionary definition of stand-alone or template, thank you. Is this an improvement on the existing addon template, or is it going beyond that and becoming a template for how to actually create the scripted item you want to connect?

If @tayaphidoux is implementing my suggestions it would be more then a template for scripters. Is could be used by non-scripters to have a functional addon by dropping in scripts they need and very little editing needed (addon name sill have to be edited at least. 

Personally I think that's the right approach because currently there are many attachments that just used old opencollar scripts while they should be using addon scripts. But since a lot of mesh/attachment creators won't know know to code or don't want to put that much work into it they aren't making use of the addon connection yet.

**Comment by Pingout** [comment]
We made a lot of progress in the past 24 hours. The Alpha 2.5 version is working pretty well. 
Following @tayaphidoux directions, I placed the 3 'main' script of _core, _dialog, and _states into a piercing ring. I added the _addon script to make the connection to the Collar
I then added oc_leash and oc_particle scripts to the piercing
![image](https://github.com/OpenCollarTeam/OpenCollar/assets/6071164/09c73391-e632-4092-9b07-a7b4c062a97a)
I was able to use the Lock and Admin Menu and I was able to connect to the Collar Addons menu.
Working back through the Collar, I was able to get the Leash menu through the Collar Addon Menu. I was able to Grab, Unleash, Yank, and Follow using the leash Menu. I was also able to get the Configure menu.
I encountered a couple of minor problems. As Taya said the scanner was not working so I was unable to make the leash go to an Anchor or Pass. I also got a Stack/Heap error while configuring the Leash
So far so good!

**Comment by tayaphidoux** [comment]
i may need a copy of 2.5 some how when doing 2.6 an older version of some of the scripts got in the mix and broke some things, i am also going to have to take a look at my wardrobe script its way to spammy.

**Comment by tayaphidoux** [comment]
updates uploaded for 2.9 that separate the settings and chat commands to prevent collision with collar plugins

**Comment by zontreck** [comment]
The existing addon template is a template, intended for scripters to be able to use as a starting guide. I intentionally wrote it as minimal as possible to be on par with the plugin template, except it provides the necessary components for interfacing with the addon API.

https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_addon_template.lsl

**Comment by tayaphidoux** [comment]
@zontreck thanks for the info, however this proposed idea is a tool that would allow creators to drop and run plugins as addons/stand alone gear, it should make it easier for people using full oc core scripts to create items that are compatible but don't require the collar, dunno if you have ever used any of these items, the oc bridle i used in version 6 was done this way and i had to make the plugin script compatible with newer versions of the collar, now my bridle is an addon that functions even when it don't have a connection to the collar, i am using this as i develop it, it also has a leash that works independently of the collar, so it does what you intended for the api just expands it to make it easier for the less script capable creators.

**Comment by zontreck** [comment]
I see. You are asking for a tool then, not a template. I created that exact thing when I created the addon system as a testing tool. I just never pushed it to the repo. I'll send it as a pull request, since it is already created. Might take me a minute to do so though. The way it worked was it was an addon bridge. You dropped that addon script into the attachment, it pulled the description as the addon name, and any plugins inside the addon were then able to function as you would expect.

**Comment by tayaphidoux** [comment]
@zontreck  this issue is a proposal to add this to the project i have already been working on it its not a request but a proposal check the github link i posted in the main section to the repository with the updates on it, i moved it here so that i was not making things more difficult for ping there is also a discussion section on it.

**Comment by zontreck** [comment]
Have a look at least, no point reinventing the wheel, when this is something i already created. If it doesn't solve the issue, can close PR. At least by the description you gave above, this fits that. See #997

**Comment by tayaphidoux** [comment]
@zontreck this is not a replacement for your template, and your template did not do this you can't just drop in an oc_plugin script on your template and have it work as an addon, nor does your template work stand alone without the collar being present, your addon just accepts information from the collar i had to filter the information out other wise a leash call for collar would also get a leash from the addon which is not the intended effect.

also many have asked for an addon leash or at the very least the ability to drop in oc_leash into an addon to create one for things like bridles and fashion collars, this covers that request, and more.

**Comment by Medea-Destiny** [comment]
This whole discussion is not adding a whole lot of clarity, and there's a lot of terminology being thrown back and forth which isn't entirely consistent and adding to the confusion. Right from the start, this issue calls for a "Stand-alone add-on", and that's a contradiction in terms from the get go. 

Can we step back a bit and start this discussion over? I think we could do with a solid "use case" presentation here. I may be misunderstanding what is being presented, but if I'm right the idea here is to provide not a template but rather a set of core scripts that could be used in an RLV attachment to provide basic menu & auth functionality, as an alternative to dumping the entirety of the OC scripts into the attachment, as unfortunately some creators have been prone to do in the past?

If my understanding of this is correct, then while that's certainly a worthy concept, I don't really understand why this is being connected to the add-on system. The concept of the add-on system, and the add-on template, is to provide all this functionality to an attachment directly from the worn collar. Creators who are currently dumping the entire OC script set into an attachment for that functionality OUGHT to be using the add-on system instead. That's what it's for. If however the creator doesn't want to use the add-on system and rather wants something stand-alone, then yes having a simple core for people to use that's based on but not dependant on the OC script set makes sense, and this could avoid the conflicts that can arise from having two collar cores worn.

On this basis... and please do correct me if I've got this wrong... then I would suggest that the best way to handle this would be to  divorce this from the add-on system, because it seems to me that what is being suggested is an alternative to using add-ons rather than complementary to it, and will at best create a lot of redundancy and at worst conflicts of its own. A small core of OC-derived scripts that offer their own auth and a basic dialog system is something I can certainly see having their place and could be a valuable offering. However I'd suggest that this is somewhat outside of the scope of the OC core project _simply because it's a stand-alone_, and on that basis should probably be in its own separate repository (as we have for the AO and Remote) rather than as a part of the collar repository.

Thoughts and comments?

**Comment by mistressohm** [comment]
I think that you're on the right track with this, Medea.  An* addon *should
rely on the collar for most of the heavy lifting, and only supply poses or
other functions based on the collar's auth.  This should slim down the
script loads considerably for things like cuffs or lockable toys.

A *standalone* "mini collar" would be appropriate for something that may
not need ALL of the collar's functions.  The main issue I'd see is
conflicts between OC attachments that are both trying to do the same thing
with the same commands.  So a 'standalone' should only be used when no
other OC collar/implant is attached (simple or full).

Possible use case:  Furniture or devices that attach props - such a 'prop'
collar would detach itself either when no longer seated OR no longer in the
region, or after a set amount of time.  During that time, it would provide
OC functions to a dominant (say for kidnap or prison play).  You wouldn't
want to lock on a full OC system for scene-based roleplay, so a
stripped-down version with a limited lifespan would be more appropriate.

**Comment by tayaphidoux** [comment]
@Medea-Destiny 
Not all every one wants a system that is sole reliant on having the open collar, in fact the chances of being locked and the add-on failing to connect are greater in this situation, being stand alone is a fall back function and a feature for those who may want a product that was made for open collar but not the collar itself.

Secondly to be able to drop in oc_plugins you need to separate the communications from the collar and the plugin to only what is needed other wise if you have two copies of said script one in the collar and one in an add-on it will conflict as you said.

Thirdly relying on boot up commands from the collar through the add-on bridge alone is unreliable you need a boot manager like you would have in the collar for oc_plugin scripts to even function.

As for conflicts for example i have a bridle system i placed oc_leash and oc_particle in the bridle with the appropriate prim to draw the leash form like you would the collar, i have done a lot of work to make sure that when you say prefixleash you don't get to menus instead to get the leash from the bridle you have to do prefixbridle leash while still accepting *leash.

there are benefits to having a system that can work in stand alone but still connect and share information like owner list,
the down side its a little heavy yes and a script that translates oc_plugin to oc_addon in order to make it easier for some developers to create products that use oc_addon instead of dropping in oc_collar core and making an oc_plugin for that is
going to be a bit bulkier than a from scratch built to connect system, which not every one is going to have the skills or 
expertise to do right away.

@mistressohm 
connect add-on then lock add-on lag on login add-on fails to connect, no menu no commands you are stuck until either the collar figures out the add-on exists or you re-log.

as for conflict with the collar that's where most of the bulk comes from making it so it does not conflict with the collar.

**Comment by tayaphidoux** [comment]
no one has to use this system it was an idea to make oc_plugin scripts work as add-ons, and at the same time make it easier for developers who are learning to code create for the collar by lowering the bar of entry within reach, which helps to grow the development side of add-ons and its adoption as well as increases the product base supporting the collar which increases interest and community supporting it, and sharing praise of the work that was put into it to their friends.

you never know one of the developers of add-ons using a system like this could eventually solve other issues with the core system in the future, rather than be turned away because of the complexity and daunting entry into creating for the collar.

**Comment by tayaphidoux** [comment]
@Medea-Destiny  it stopped being just a template a while back when features where asked to just make it something that  you could drop an oc_plugin script into.

**Comment by tayaphidoux** [comment]
@Medea-Destiny @mistressohm 
https://github.com/OpenCollarTeam/OpenCollar/pull/997/files#diff-d6cafe93d669cc6ec9d44b96c124662dd31b6f5054b847bf59ae1335f2c88222 created by @zontreck  does exactly what  you want however it will have collisions if the same plugin exists in the collar and add-on at  the same time, there is no filtering in this script to force the plugin to respond to prefixaddon sub-command instead of prefixsubcommand, it is the lighter alternative you seem to be thinking of.

**Comment by Medea-Destiny** [comment]
@tayaphidoux Lowering the barrier of entry to creating add-ons is certainly a very good idea, but it looks like a large part of what you're working towards here actually circumvents the add-on system. There shouldn't be a question of collisions between plugins existing in the add-on and the collar, because the whole point of add-ons is to provide collar services via the attachment interface.  My concern is that what you're proposing here appears to be both an alternative to the add-ons system and using the add-ons system at the same time. If an attachment is using the add-ons system, why would it need to have auth and menu functions, or plugin compatibility? And if we want those as a stand-alone, why would it have add-on compatibility?

**Comment by tayaphidoux** [comment]
@Medea-Destiny  you aren't thinking from a newbie developer stand point or the perspective of a developer that don't want to have to create two products just to support open collar add-on, you are thinking exclusively as an open collar dev and if you can't step out of that mind set and put your self in some one else's shoes then i can't help you understand why some thing as simple as a stand alone system that can connect as an add-on is useful.

As for collisions i.e two items doing the same thing zonetrek has a nice plugin that does the add-on system like how you are describing it except it just passes oc_plugins to apps menu via the add-on system, which can create collisions, I am saying my system avoids such collisions by being a little beefier and being able to "stand alone".

It solves several issues with the idea of being able to drop oc_plugin script in along side an add-on link script to create an add-on with features that have already been created like the leash for example, or in ping's tests the bad-words system, devs don't have to create two whole products to support open collar while still allowing non oc users to use the same item, that's a reason for stand alone

**Comment by tayaphidoux** [comment]
my owner has decided its time i stop working on oc projects so i am closing this take care.
