### ISSUE TITLE
Script run-time error Stack-Heap Collision in oc_dialog

### ISSUE THREAD

**Issue by eksynn** [OpenCollarTeam/OpenCollar#993]
What version of OpenCollar are you using?
8.2.3

What behavior did you expect?
friend of mine's collar is giving a stack-heap collision error whenever I try to use the [prefix] detach command (same when going through the menu). the expected behaviour is to open the detach dialogue
edit: it works when she tries the command

What behavior did you see instead?
Neural Access Node [script:oc_dialog] Script run-time error
Stack-Heap Collision

What steps does someone need to take to reproduce the problem?
as it seems to be working on mine, I can't promise it can even be duplicated. her display name is in Japanese, but so is mine, so I really can't tell why it wouldn't work
I gave her a copy of my collar to test it out, but it still does this
we've tried rebooting, relogging, resetting, and reattaching, but nothing works

my friend's inworld username is "竜女  (Naomi Takeda)"

**Comment by eksynn** [comment]
to be clear, the neural access node is actually the collar in the form of a brainchip

**Comment by tayaphidoux** [comment]
has the scripts been modified from what is available on github, were they manualy loaded by the one who created the brainchip, i have been experementing with oc collar scripts without the oc_experience flag to see if the stack heap i saw would affect the avarge user so far i have not come across it, but the stack heap i seen was from modified oc_dialog.

**Comment by NikkiLacrima** [comment]
A possible cause of memory issues (Stack-Heap Collision) when using detach is by wearing lots of attachments, clothes and other items, so try to use sparse outfit and see if the problem remains.

**Comment by SilkieSabra** [comment]
Also wearing attachments with very long names will do this

**Comment by Medea-Destiny** [comment]
Either issues addressed or known issues with dialog memory footprint  which will be addressed in future, probably pending script engine improvements LL are working on (LUA).
