### ISSUE TITLE
Newest update now giving error when clicking detach menu.

### ISSUE THREAD

**Issue by SnowWolfWicked** [OpenCollarTeam/OpenCollar#995]
What version of OpenCollar are you using? 8.2.3000

What behavior did you expect? Deatch menu to come up

What behavior did you see instead? Crashes with error [20:16] DIRTY PRINCESS- hazardous Princess Open Collar RLV [script:oc_dialog] Script run-time error
[20:16] Stack-Heap Collision

What steps does someone need to take to reproduce the problem? Does it with multiple different collars all at same version. Older versions work fine. After resetting collar can generally open menu once then after that it crashes again.

**Comment by Pingout** [comment]
Can you let us know what OpenCollar Version you upgraded from? Than might make a difference. But in general the Stack-Heap error is an out of memory message. There are either too many attachments, or the attachment names are too long.
Once we get Linkset Data (LSD) working, this particular "Long attachment name" issue should go away.

Again, please let us know the version you are upgrading from.

**Comment by SnowWolfWicked** [comment]
8.1 but that is hardly the issue. Also no having to many attachments is far from issue either as I have tried it on multiple avi's and multiple collars and every single collar that is 8.2.3 has this issue where as none of the other versions do. Even being naked with nothing but body head and skin with 8.2.3 collar still has the issue.

**Comment by NikkiLacrima** [comment]
I try to reproduce this issue with a collar directly from the 8.2.3 distribution, have not been able to reproduce that behaviour for a normally complex outfit. 

Can you try with a collar from th OC distribution ?

**Comment by SilkieSabra** [comment]
@SnowWolfWicked the older version could indeed be an issue.  Please update the collar and see if the problem recurs.

**Comment by SnowWolfWicked** [comment]
@SilkieSabra You obviously didn't read the entire thread as I clearly stated that 8.1 works and 8.2.3 doesn't. @NikkiLacrima Yes i'll give that a try and see if it works coming directly with 8.2.3

**Comment by SnowWolfWicked** [comment]
@NikkiLacrima Yes 8.2.3 works fine when bought from OC. Also think I narrowed issue down and resolved it on my end. Got collars redelivered with a 7.0 version updated it to 8.2.3 and seems to work just fine right now. So issue seems to be when update from 8.1 to 8.2.3 that something is going wrong but working now so all good.
