### ISSUE TITLE
There is NO master list of ALL Commands. Why not in Remote and Collar for easy use/access?

### ISSUE THREAD

**Issue by DrWebX** [OpenCollarTeam/OpenCollar#996]
What version of OpenCollar are you using? 8

What behavior did you expect? Be able to see, cut and paste commands available to me.

What behavior did you see instead? There is no help, no list, no commands inside the collar or remote.

What steps does someone need to take to reproduce the problem? Try to find commands online with Google. What a shame!

**Comment by SilkieSabra** [comment]
the "List of All Commands" is the Holy Grail of OpenCollar documentation.  The list changes with every update.  The list will not fit in collar or remote menus.  Except possibly as a chat dump.  The most commonly used commands are available on the manual page for each menu, and also on the separate page, for Prefixes, Chat Commands, and other non-menu functions, if they do not correspond to a menu button.  Wish List:  Someone to go through every script in the collar, find the existing chat commands, list them on a github wiki page, and also flag the ones that could be there but aren't.  Are you up to this task, @DrWebX ?

**Comment by DrWebX** [comment]
No, not something I can do. Appreciate your help....

**Comment by Trix7125** [comment]
We could use tool like Doxygen to automate generate documentation. Down is GPT4 response how todo it.

`File Extensions for Custom Documentation:
Doxygen treats certain file extensions as additional documentation files. To include custom file extensions, follow these steps:
Edit your Doxygen configuration file (usually named Doxyfile).
Locate the FILE_PATTERNS setting in the configuration file.
Add the desired file extension (e.g., .lsl) to the list of patterns. For example:
FILE_PATTERNS = *.cpp *.h *.txt *.lsl

[This tells Doxygen to consider files with the .lsl extension as part of the documentation](https://stackoverflow.com/questions/4216285/doxygen-how-to-document-files-with-non-standard-extension-ini)[1](https://stackoverflow.com/questions/4216285/doxygen-how-to-document-files-with-non-standard-extension-ini)[2](https://www.doxygen.nl/manual/config.html).
Commenting in LSL Files:
In your LSL files, use comment blocks that Doxygen recognizes. Doxygen expects two lines of either the following formats:
/// or //! for starting a Doxygen-aware comment block.
[It also accepts multi-line comment blocks using /** and /*!](https://stackoverflow.com/questions/4216285/doxygen-how-to-document-files-with-non-standard-extension-ini)[1](https://stackoverflow.com/questions/4216285/doxygen-how-to-document-files-with-non-standard-extension-ini).
Example Comment in an LSL File:
For instance, in your LSL file (my-script.lsl), you can add comments like this:
//! @file my-script.lsl
//! This script does something amazing.
//! ...`

**Comment by DrWebX** [comment]
Thank you, very useful.. it empowers the chat line commands for easier use
in various settings and environments.
Wonderful to add to the core knowledge...

Thanks,
Michael aka DrWeb


*Michael*| E-mail: ***@***.***|Facebook: Facebook
<https://www.facebook.com/michael.mcculley.drweb>| Blog: (DrWeb's Domain
<https://drwebdomain.blog/>)

**Comment by Medea-Destiny** [comment]
OpenCollar_help notecard inside collar now updated with *almost* every chat command from 8.3
