### ISSUE TITLE
oc_particles vs LockGuard furnature.

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#998]
What version of OpenCollar are you using?
Opencollar 8.2.3000

What behavior did you expect?
lock guard chains to disconnect when standing up from furniture

What behavior did you see instead?
lock guard chains stay connected when standing up.

What steps does someone need to take to reproduce the problem?
sit on furniture that makes of lockguard frontcollarloop then stand up

cause of the problem:

https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/collar/oc_particle.lsl
lines 751 to 761
```
                // check that we are within leash length
                integer point = llList2Integer(llGetObjectDetails(kLGTarget, [OBJECT_ATTACHED_POINT]),0);
                if(point != 0 && g_iLeashedToAvatar){
                    // this is likely a leash holder
                    jump ovLG;
                }
                if(llVecDist(llGetPos(), (vector)llList2String(llGetObjectDetails(kLGTarget, [OBJECT_POS]),0)) > g_iLeashLength){
                    return;
                }

                @ovLG;
```
breaks unlink call and probably others, i have it on good authority there are no lock guard based leash holders so there is no point in this code, and i only found one project in marketplace but it is unclear what it does and the creator is no longer in sl.

https://marketplace.secondlife.com/p/Bijoux-by-Salacity-Dancing-Girl-Bangle-Bracelets-FatPack/12666815

lock guard was meant as furniture chains not leashes so it has no yank or position lock down function which further points to the fact looking for a leash holder is pointless in this section.

(edit)
tested in my bridle using the standalone/addon system i created to drop in oc_plugin style scripts and removing that section of code fixed the lock guard bug.

**Comment by Pingout** [comment]
Ref https://github.com/OpenCollarTeam/OpenCollar/issues/965
Ref https://github.com/OpenCollarTeam/OpenCollar/issues/650
Ref https://github.com/OpenCollarTeam/OpenCollar/pull/974

I thought this issue was fixed by the above PR, which has been merged into Features Branch.

Or is this an entirely new issue?

Taya did you try this with https://github.com/OpenCollarTeam/OpenCollar/blob/8.3_Features-branch/src/collar/oc_particle.lsl

**Comment by tayaphidoux** [comment]
yep looks like you have two different scripts fixing the problem and more i didn't seem them after figuring out my self what the cause was, this can be closed since its already been solved in updates.
